### ISSUE TITLE
Status Bar has no Background

### ISSUE THREAD

**Issue by dmsw0303** [laurencedawson/sync-for-reddit#1]
When scrolling down status bar background disappears entirely but leaves elements

**Comment by laurencedawson** [comment]
This is actually the intended behaviour. Still in play though.

**Comment by dmsw0303** [comment]
I think the functionality should just hide the icons as well then.

Basically just default to immersive mode?

**Comment by dmsw0303** [comment]
also this behavior isn't seen in comments. it leaves the status bar background

**Comment by laurencedawson** [comment]
As mentioned on discord, only the main page has any md2 redesigned
elements. More to come elsewhere.

**Comment by laurencedawson** [comment]
Added for alpha 17.
