### ISSUE TITLE
BUG: Strike-through text appearing in spaces between words

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#100]
https://imgur.com/a/BMsmjqs

**Comment by laurencedawson** [comment]
Any way to reproduce this?

**Comment by RecklessDwark** [comment]
The self-text in this post does it for me

https://www.reddit.com/r/redditsync/comments/gt53yk/_/

**Comment by laurencedawson** [comment]
Actually happens on the normal website too!
