### ISSUE TITLE
[BUG] Sometimes the comment navigation bar doesn't finish its animation

### ISSUE THREAD

**Issue by superluig164** [laurencedawson/sync-for-reddit#1004]
**Describe the bug**
Sometimes, when opening a post, the comment navigation bar doesn't finish its animation.  It still works fine, but it ends up being small, or the arrows are off center, or any various point in between.

**To Reproduce**
Open posts until it happens.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/13702255/161848702-48a2f2aa-4fd1-4fc2-8ca5-130d33cb8f0c.png)

**Smartphone**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 12
 - Version: 22.4.4

**Comment by laurencedawson** [comment]
Fixed for the next release.
