### ISSUE TITLE
[BUG] Unable to open Youtube links in-app

### ISSUE THREAD

**Issue by Rahlun** [laurencedawson/sync-for-reddit#1005]
**Describe the bug**

Unable to open Youtube links in-app. Previously able to do this. Now I can only open. YouTube links by going to settings and un-checking the open in-app option which means all youtube links direct to the separate YouTube app. Error received when attempting to access YouTube link in-app: You must have the YouTube app to support this function. Then I am directed to Google play to download the separate YouTube app. I have the YouTube app and it is up to date. I can watch videos through the YouTube app when they link from the sync app. Unable to watch the YouTube videos inside the sync app. 

**To Reproduce**
1. Go to Settings '
2. Ensure YouTube is selected to open in sync app
3. Attempt to open YouTube link either from post or comments

**Expected behavior**

Should open YouTube type interface inside the sync app instead of directing to outside app. 

**Screenshots**

NA

**Smartphone (please complete the following information):**
 - Device: [SAMSUNG S20]
 - OS: [Androibd version 12]
 - Browser [Reddit Sync app]
 - Version [22. Update rolled out to me 4/5/22]

**Additional context**

**Comment by laurencedawson** [comment]
Can you post the exact version of sync you're on please

**Comment by Rahlun** [comment]
Issue seems to be fixed today. Thank you.
