### ISSUE TITLE
[BUG] 'Submit Photo' buttons are not themed.

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-reddit#1010]
**Describe the bug**
When submitting a photo, the buttons to choose a photo are not themed.

**To Reproduce**
1. Go to any subreddit
2. Click on submit
3. Select photo

**Expected behavior**
The buttons should look like the proper Material 3 buttons.

**Screenshots**
![Screenshot_20220406-160603.png](https://user-images.githubusercontent.com/28932047/162061883-212585bd-f793-4edd-9c8c-c355dbf31957.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12.1 April 2022
 - Browser: Firefox
 - Version: 22.3.28

**Comment by laurencedawson** [comment]
Ew gross.

Fixed for the next release.
