### ISSUE TITLE
Highlight comment usernames with random (identifiable) colours.

### ISSUE THREAD

**Issue by superluig164** [laurencedawson/sync-for-reddit#1012]
Highlight comment usernames with random colours, but that stay the same for the same user.  This way it's easy to identify a conversation between the same person without reading the usernames.  This could also be done with a small dot.  Highlighting the root comment OP with an icon could also be an extension of this suggestion, especially in WP subs or AskReddit style subs.

**Comment by laurencedawson** [comment]
You can "paint" users in ultra. No plans to expand on this further.
