### ISSUE TITLE
[BUG] Numbered lists with a blank line or text between items not numbered correctly

### ISSUE THREAD

**Issue by jso8910** [laurencedawson/sync-for-reddit#1014]
Essentially, if I were to type this text:
```
1. Something
hello
2. Something
```
It would render as and I would see
```
1. Something
hello
1. Something
```
Obviously that isn't what I want. What should happen is that the correct numbers are preserved.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 12L, March Security Update
 - Browser: Chrome
 - Version: 22, whatever the version is on the free beta

**Comment by laurencedawson** [comment]
Unfortunately this isn't the correct markdown implementation. Sync is just parsing what it gets and those are two seperate lists in the html.

**Comment by jso8910** [comment]
That doesn't make any sense, though. If I explicitly type "2."  I should
get "2. even if it means it will no longer be a markdown list but a
plaintext "2. ". That is the behavior on every single other Reddit app and
most word processors.

**Comment by laurencedawson** [comment]
I'm rendering html that's returned by reddit
