### ISSUE TITLE
[BUG] [VISUAL] Arrow Indicator next to profile dropdown

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1015]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/txt9r6

**Steps to reproduce:**

- Open the apps sidebar, and navigate to the top of it (if not already there)
- Open the Profile dropdown (up voted, saved, etc)
- The arrow next to the Profile string points up, as it should
- Tap on one of the options.
- Back out of the page, and open up the app sidebar
- The Profile dropdown is closed, but the arrow still points up.

**Device information**
```
Sync version: v22.4.5    
Sync flavor: free    
Removed ads: true    

View type: Slides    
Push enabled: false    

Device: nairo    
Model: motorola moto g 5G plus    
Android: 11
```

**Comment by laurencedawson** [comment]
https://github.com/laurencedawson/sync-for-reddit/issues/993

Duplicate.
