### ISSUE TITLE
[REQUEST] Distinction between post and comments in notifications

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1016]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/txxuti/_/

**Is your feature request related to a problem? Please describe.**
Tapping a comment from a user's profile will sometimes not jump to the comment. That *really* needs to be distinguished better. The title being italicized only indicates to me that's the title vs comment, but not actionable differences. When different things within an object do two different things, they're generally identified as being different. 

**Describe the solution you'd like**
Red/green buttons, bolded font, etc. This is really counterintuitive and I'm a software developer and do stuff like this!

**Additional context**
[Video](https://v.redd.it/yd1j9hkugzr81/DASHPlaylist.mpd?a=1651919507%2CNzM0MGE2ZTFmMTdiOGU4NjQ0YTNkZjA3YWUyN2NkNTRhZTY0NDlhOTVmN2IzMWY2MjU1MGU5NGRjNmQwYzFkNw%3D%3D&amp;v=1&amp;f=sd)

**Comment by laurencedawson** [comment]
Disagree on this one. Its been the same way for 10 years and I think after one click its obvious.
