### ISSUE TITLE
[REQUEST] Could you consider adding an option to have a confirmation dialog before sending messages?

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1017]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/txy0fq/_/

**Is your feature request related to a problem? Please describe.**
I keep accidentally sending half-finished messages to people 😬

**Comment by laurencedawson** [comment]
The button is top right, no plans to add an extra confirmation.
