### ISSUE TITLE
[BUG] Sync app lags when the lovoo ad is shown

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1018]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/txy8b3

**Describe the bug**
I noticed that any time an lovoo app is shown the whole app gets very laggy to the point it's pretty much unusable. Reacts to touch gestures very delayed etc.

It's very obvious that it's the lovoo ad, when I'm on the frontpage scrolling with a different ad everything is fine and as soon as I click a post and the new ad happens to be lovoo app extremely laggy again.

If I leave the post again (using return button on phone) it's instantly fine again as soon as lovoo ad is gone.

If lovoo ad is on frontage I have lags there too.

**Scenario**
- On frontpage, ad is not lovoo, everything fine
- Click post, if ad is lovoo -> lags
- Leave post to frontpage -> if ad not lovoo anymore no lags

**Device Info**
```
Device: OnePlus 7
OS: OxygenOS 11.0.5.1 (Android 11)
Location: Germany (since apps are localized) 
Sync version: v19.0.17 
Sync flavor: free
```

**Comment by laurencedawson** [comment]
This has since been removed.
