### ISSUE TITLE
[Enhancement] Changing colors for light mode switch toggles to match Android 12

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#1019]
Minor enhancement regarding switch toggles. Switching colors from light on dark to dark on light matches Android 12's native theming for switch toggles.

Comparison:  
![Android 12 switches](https://user-images.githubusercontent.com/75273570/162200430-e4c59c36-c088-4285-bc1e-f7797889f894.png)

![Sync for reddit switches](https://user-images.githubusercontent.com/75273570/162200548-38324142-f4e5-4db8-9733-ab7ca2e5a73b.png)

Dark mode looks fine as it is.

**Comment by laurencedawson** [comment]
Fixed for the next release.
