### ISSUE TITLE
[REQUEST] Enhanced search indexing

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1020]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ty2lhn

**Is your feature request related to a problem? Please describe.**
I haven't been able to figure out how to search for subreddits in the beta, and I mean more than the suggested ones. I can only search for posts apparently.

Am I missing something or is it simply not possible?

I know how to search and I can see the subreddits that match what I've typed so far. What I'm looking for is a search that shows subreddits if the context matches even if the name doesn't. Sometimes searching only by exact name isn't quite enough if I don't know the subreddit name.

Boost (app) has this, so does the official Reddit app and website. I can't say about non-beta Sync as I haven't used it in a while.

For example, here I searched for "cat" and this is what Reddit offers in return (I suggest you open in browser): https://www.reddit.com/search?q=cat&type=sr

I don't know what kind of algorithm they use. One more example would be: if I wanted to find the subreddit for the game franchise Project Cars, Sync wouldn't suggest it to me with "project cars" since its r/pcars. With the Reddit or Boost app I can just search for "project cars" and see what subreddits they (or Reddit) found for it.

**Comment by kiksu89** [comment]
Original Reddit poster here:
I downloaded the non-Pro version (normally a Pro user) to see if the stable version has a subreddit search and sure enough it does.

It's available under the three dots > Search... > Search subreddits.

So the functionality has been there before, but is missing in the v22 beta.

**Comment by kieraneglin** [comment]
Second this. Here are my steps to reproduce (v22.4.6, free w/ in-app upgrade):

- click explore button
- enter a valid subreddit name that doesn't appear in the automatic suggestion list
- click "open subreddit <name>"
- instead of being brought to that subreddit, it looks like I'm brought to a Reddit search with the name of the subreddit being the search term

**Comment by kieraneglin** [comment]
I never realize that my issue isn't the same as the original posters. I'll open a new one

**Comment by bohrabhijeet** [comment]
> Second this. Here are my steps to reproduce (v22.4.6, free w/ in-app upgrade):
> 
> * click explore button
> * enter a valid subreddit name that doesn't appear in the automatic suggestion list
> * click "open subreddit "
> * instead of being brought to that subreddit, it looks like I'm brought to a Reddit search with the name of the subreddit being the search term

This has been fixed in the latest v22.4.11 release.

**Comment by laurencedawson** [comment]
Expanded searching has been added.
