### ISSUE TITLE
[ENHANCEMENT] Improve album counter's visibility

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1021]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ty0eno

**Request**
Currently it is literally impossible to see the number at the bottom left of an album when it is on a white background.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/795
