### ISSUE TITLE
Automatically open keyboard when explore is tapped 

### ISSUE THREAD

**Issue by DanGLES3** [laurencedawson/sync-for-reddit#1023]
**Is your feature request related to a problem? Please describe.**

It's somewhat frustrating having to reach for the search button when navigating with one hand

**Describe the solution you'd like**

An option to automatically display the keyboard when explore is tapped would be great

**Describe alternatives you've considered**

Alternatively having an option to move the search bar at the bottom would work as well, tho it might not be aesthetically pleasing

**Additional context**

**Comment by bohrabhijeet** [comment]
Long-pressing the Explore button triggers the keyboard, if that helps.

**Comment by DanGLES3** [comment]
> Long-pressing the Explore button triggers the keyboard, if that helps.

Wasn't aware of that, that does it then
