### ISSUE TITLE
[BUG] The up arrow on page divider scrolls all the way to the top regardless of the page number

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1024]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tyjidf

**Describe the bug**
When clicking the down arrow on page dividers it only scrolls to the next page, but the up arrow behaves like clicking the home icon on the bottom bar (including the "restore position" toast). Not sure if this is intended but it's a bit unintuitive.

**To Reproduce**
1. Scroll until the page divider
2. Tap on the ^ arrow

**Expected behavior**
Should scroll to the previous page instead

**Comment by laurencedawson** [comment]
Intended.
