### ISSUE TITLE
[Enhancement] Spelling error in summary

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1025]
Under Settings > Reddit web preferences > Don't show thumbnails next to links, the text should be ...and _affects_...

**Screenshot**

![Screenshot_20220408-153107~2.jpg](https://user-images.githubusercontent.com/34155181/162414658-69fa277c-ce8c-44d2-9494-7e53f325eb07.jpg)

**Comment by laurencedawson** [comment]
Fixed
