### ISSUE TITLE
[REQUEST] Blur NSFW media

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1027]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tz32fj

Hello. Big fan of Sync, very thankful for all the work, by far the best client available.

**Is your feature request related to a problem? Please describe.**
I know this was asked a few years ago, but I feel strongly that this is a useful feature that is found on other Reddit clients, and I was surprised to find it was unavailable in Sync. 

Historically, low end devices didn't handle blurring very well, but today even low end devices don't suffer from it. My Pixel 6 Pro should easily handle it, my old LG G4 from 2015 can still handle it too. I feel it would be a great optional addition, as the solid red is quite jarring. Also, blurring helps me guess what kind of NSFW content it is (e.g. nudity) so I know if it really is something I don't want to open or not.

**Describe the solution you'd like**
I believe SDK 31's RenderEffect API provides a highly performant solution, although would be limited to Android 12+. With that said, more traditional methods would work fine (I think Blurry is still a thing).

Thanks again!

**Comment by laurencedawson** [comment]
No plans to ever add blur I'm afraid as I don't think this would sit well on Google Play.

Going to play this one safe.
