### ISSUE TITLE
[REQUEST] Change the Backup sharesheet

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1030]
**Is your feature request related to a problem? Please describe.**
Current implementation shows a sharesheet that lets you choose a default app

**Describe the solution you'd like**
Change it to the one shown while sharing a post outside of Sync

**Additional context**
![Screenshot_20220408_215139.jpg](https://user-images.githubusercontent.com/34155181/162482726-f488c041-5250-4bc1-83e4-1123398659c0.jpg)

**Comment by laurencedawson** [comment]
Done.
