### ISSUE TITLE
YouTube videos that don't support external viewing time out instead of displaying message.

### ISSUE THREAD

**Issue by RlyRlyBigMan** [laurencedawson/sync-for-reddit#1032]
Apparently some videos require you to visit the YouTube channel to watch instead of in your app. I've seen this numerous times for videos published by the official NFL YouTube channel.  Before recently changing your video engine, Reddit Sync would display a message to the user to open in browser instead. Now it just shows the loading swirly endlessly until you just give up and cancel the request.

Ideally the app would notify me of the requirement to go to YouTube and then provide a button to launch to the browser, but a quick message that I need to do that would still be better than me just waiting 5 seconds and realizing what's wrong on my own.

A sample reddit post with such a video link is posted below.

https://www.reddit.com/r/nfl/comments/tz1ox3

I am using Sync Dev version v22.4.6 on a Google Pixel 4 XL.

I love your app, thanks for all of your hard work!

**Comment by laurencedawson** [comment]
After checking it seems like the error callback isn't being fired by the YouTube in-app player.

Sadly not much I can do here.
