### ISSUE TITLE
[BUG] Default link handlers are disabled after each update

### ISSUE THREAD

**Issue by Sagarg125** [laurencedawson/sync-for-reddit#1034]
**Describe the bug**

After the recent v22 updates, I have noticed that I am unable to open Reddit links without re-enabling the "Supported web addresses" in Android Settings for the app. Once I do, they get reverted after a new update to the app. 

**To Reproduce**
1. Go to Android Settings>Apps>Sync>Set as default>Supported web addresses
2. Enable any links you need
3. Update the Sync app
4. Try (and fail) to open a supported Reddit address
6. Repeat step 1
7. Notice that all previously enabled web addresses are now disabled again

**Expected behavior**

After an app update, the enabled links in "Supported web addresses" should be maintained. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 12
 - Browser Firefox Beta
 - Version Sync v22.4.8

**Additional context**

**Comment by laurencedawson** [comment]
On the Sync FAQ. Unfortunately a restriction we're dealing with at the moment:

https://www.reddit.com/r/redditsync/comments/tk02dp/v22_faq/i45dwam/
