### ISSUE TITLE
[Tablet?] Search Debounce

### ISSUE THREAD

**Issue by snah-dev** [laurencedawson/sync-for-reddit#1035]
**Is your feature request related to a problem? Please describe.**
I use a tab s8 with keyboard accessory so when I type "tech" it shows subreddits such as "television", "tea" unrelated to "tech".

Example below.

https://user-images.githubusercontent.com/58427306/162551223-232f1cf4-ce8a-44c6-86f3-486ebaf8835b.mp4

**Describe the solution you'd like**
Debounce for a few milliseconds like 250ms.

**Comment by laurencedawson** [comment]
Did this get fixed by accident?
