### ISSUE TITLE
[BUG] Text doesn't instantly update in search suggestions when theme is switched manually

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1040]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tzm2bt

**Description**
When switching from light mode to dark mode, or vise versa, text should change brightness in order to maintain contrast. I found a scenario in which that does not happen until you close out of the screen and come back.

**Scenario (steps to reproduce)**
- Open the app settings
- Search for "dark mode"
- Select the result
- Change the mode to the opposite (screenshot demonstrates changing from light mode to dark mode)
- Go back to the search results

**Result(s)**
You will observe the search results text did not update its color.

**Device Info**
```
Device Model: Pixel 6 Pro

Android Version: 12

sync version 22.4.8 free (beta version)
```

**Screenshot**
https://i.imgur.com/12dZnwL.png

**Comment by laurencedawson** [comment]
Duplicate. 

https://github.com/laurencedawson/sync-for-reddit/issues/940

**Comment by laurencedawson** [comment]
Actually might be different after all. Re-opening.

**Comment by laurencedawson** [comment]
Fixed for the next release.
