### ISSUE TITLE
[BUG] Not opening subreddit you aren't subscribed to in search and double quotation marks

### ISSUE THREAD

**Issue by JordanCollinsNZ** [laurencedawson/sync-for-reddit#1041]
**Describe the bug**
Love the new version by the way!

When searching for a subreddit that you aren't subscribed to, it is within two sets of quotation marks instead of one.
When you select it, it seems to search instead of opening the subreddit.

**To Reproduce**

1. Use Explore menu to search for a subreddit you aren't subscribed to
2. Select the open subreddit option

https://i.imgur.com/KdmWV9E.png

**Expected behavior**
Should be taken to that subreddit but instead you are taken to a search for that text https://i.imgur.com/WYpTvk4.png

**Smartphone (please complete the following information):**
- Sync version: v22.4.6
- Sync flavor: pro
- View type: List
- Push enabled: false
- Device: crosshatch
- Model: Google Pixel 3 XL
- Android: 12

**Comment by laurencedawson** [comment]
Fixed for the next release.
