### ISSUE TITLE
[BUG] it's possible to end up in a state where you can't leave a comment

### ISSUE THREAD

**Issue by twig** [laurencedawson/sync-for-reddit#1043]
**Describe the bug**
title

**To Reproduce**
https://www.reddit.com/r/redditsync/comments/u0ep81

**Expected behavior**
Button to leave comment is accessible 

**Screenshots**
https://imgur.com/a/U3H9BaQ

**Smartphone (please complete the following information):**
 - Device: Samsung s10e
 - OS: android 9
 - Version 22

**Additional context**

**Comment by laurencedawson** [comment]
As the reply is available from the overflow I'm going to mark this one as wontfix.
