### ISSUE TITLE
[BUG] Performance issues with ads

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#1044]

**Comment by laurencedawson** [comment]
Discussion:

https://www.reddit.com/r/redditsync/comments/tzn5xu/general_performance_issues_with_the_redesign/

**Comment by laurencedawson** [comment]
Would you mind trying the beta to see if the issues are resolved for you?
Thanks

**Comment by laurencedawson** [comment]
Added another fix for this in todays releases.

v22.4.16 &  v19.0.19

**Comment by laurencedawson** [comment]
@eyalzek how is it for you now?

**Comment by eyalzek** [comment]
Hey @laurencedawson, sorry for the late reply. It seems to be working better so far! Thanks!

**Comment by laurencedawson** [comment]
Fixed.
