### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by kvl19** [laurencedawson/sync-for-reddit#1046]
**Is your feature request related to a problem? Please describe.**
I would like to request a text to speech feature.

**Describe the solution you'd like**
Adding a button next to a post that will read the content of the post out loud.

**Describe alternatives you've considered**
An alternative would be using Android's native text to speech feature but that's not very intuitive and hard to use.

**Comment by bohrabhijeet** [comment]
This was added with the new Ultra feature set.

**Comment by laurencedawson** [comment]
Actually this was added for everyone not just ultra.
