### ISSUE TITLE
[BUG] Comments sort issue

### ISSUE THREAD

**Issue by PerLycke** [laurencedawson/sync-for-reddit#1048]
**Describe the bug**
Comments aren't sorted the way you expect. If you select "Suggested" as the default comments sort and "Top" is the suggested one, it sorts by new.

"Best" doesn't seem to work at all, selecting this manually and it sorts by new.

**To Reproduce**
1. Go to r/soccer
2. Open a post and select "Best" as comments sort.
3. See bug, comments are sorted by new.

OR

1. Select "Suggested" as default comments sort
2. Go to r/soccer
3. Open a post. Confirm "top" is the suggested sort
4. Comments aren't sorted by top, they are sorted by new.

**Expected behavior**
Comments should be sorted as expected

**Screenshots**
![Screenshot_20220410-214842_Sync Pro.jpg](https://user-images.githubusercontent.com/8590720/162680447-f6c5fe99-08fc-49c3-b6e0-8c932cfd7186.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10+
 - OS: OneUI 4.1
 - Version 22.4.6

**Comment by laurencedawson** [comment]
Unable to reproduce this.

**Comment by PerLycke** [comment]
@laurencedawson so if you select "best" comments sort on https://www.reddit.com/r/redditsync/comments/u2az1e/_/ and compare it with official Reddit app or website with "best" sorting, you get the same result? Really weird issue if it only affects me / some 🤔

**Comment by laurencedawson** [comment]
Think I figured this out.

If scores are hidden there could be a discrepancy on how the results are ordered!
