### ISSUE TITLE
[SUGGESTION] Update strings

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1049]
I've noticed a few irrelevant strings in Settings. Listing them below:

- `Settings > Images` » `Settings > Media`
- `Image cache duration` and `Manually clear the image cache` » `Media cache duration` and `Manually clear the media cache` respectively`
- `Use complimentary colors` » `Use complementary colors`

**Comment by laurencedawson** [comment]
Done.
