### ISSUE TITLE
[SUGGESTION] For onboarding

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1050]
- https://www.reddit.com/r/redditsync/comments/u1bdkq/_/i4bfokc

- https://www.reddit.com/r/redditsync/comments/u1bdkq/_/i4cvyup

- https://www.reddit.com/r/redditsync/comments/u1bdkq/_/i4cl15t

**Comment by laurencedawson** [comment]
Closing as I won't be adding these. Thanks for raising them though.
