### ISSUE TITLE
[VISUAL] Deeplink settings icon stretches on adding text after it

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1052]
![Screenshot_20220412-0729312.jpg](https://user-images.githubusercontent.com/34155181/162925405-d900a0b9-a1df-4163-a1bd-02849fcb08f4.jpg)

**Comment by bohrabhijeet** [comment]
Fixed in v22.4.12

**Comment by laurencedawson** [comment]
woohoo
