### ISSUE TITLE
[BUG] Sync crashes on tapping View Type preview

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1054]
**Describe the bug**
Sync crashes every time the preview is tapped

**To Reproduce**

- Go to Settings > View Type
- Disable media preview
- Tap the preview
- Sync crashes

**Expected behavior**
Nothing should happen

**Device information**
```
    Sync version: v22.4.12    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 11
```

**Additional context**
Stacktrace: https://pastebin.com/civqFK3A

**Comment by laurencedawson** [comment]
Fixed for the next release.
