### ISSUE TITLE
[BUG] Links inside spoilers cannot be interacted with when unhidden

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1055]
**Describe the bug**
If a link is inside spoilers, the link will show as plaintext when unhidden and cannot be tapped to open. 

**To Reproduce**
1. Go to https://www.reddit.com/r/goodanimemes/comments/u1y4cn/_/i4ggigl
2. Click on spoiler text to unhide 

**Expected behavior**
The link in the unhidden spoiler should be active.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox
 - Version: v22.4.11

**Additional context**
The link _can_ still be tapped but only if you can manage to guess its location within the original hidden text.

**Comment by laurencedawson** [comment]
Fixed for the next release.
