### ISSUE TITLE
Dark Mode Spash Screen

### ISSUE THREAD

**Issue by JEnduriumK** [laurencedawson/sync-for-reddit#1056]
**Is your feature request related to a problem? Please describe.**
I'm pretty sure a past version had a dark-mode splash screen that is now missing, so... if you consider something being missing a problem, sure?

Otherwise, only the problem of the searing white blinding light during 'the dark times'.

**Describe the solution you'd like**
A AMOLED-black splash screen.

**Describe alternatives you've considered**
Closing my eyes for two seconds when launching the app?

**Additional context**
Pretty sure this was in a prior version?

**Comment by laurencedawson** [comment]
Added for the next release.
