### ISSUE TITLE
[BUG] Comment Navigation Bar becomes unresponsive after incomplete animation 

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1059]
https://www.reddit.com/r/redditsync/comments/u2az1e/_/i4kotlv

**Comment by bohrabhijeet** [comment]
Similar instance:
https://www.reddit.com/r/redditsync/comments/u31pp1/_/i4mge0n

**Comment by laurencedawson** [comment]
Fixed for the next release.
