### ISSUE TITLE
V22.4.12 Restore Purchase works initially, then fails later

### ISSUE THREAD

**Issue by blindaim** [laurencedawson/sync-for-reddit#1060]
I opened Sync to the new beta update today and it offered to restore purchase in one of the screens then said "Ads Removed". I locked the phone for a bit while I had been in middle of a comment. When I returned, it sent me to Google Play store despite no ads on the screen. I hit back out of that then had ads. I exited and force stopped the app and opened again with no ads. When I came back just now, had ads. I just now attempted to restore purchase again.

Sync v22.4.12 Don't remember if it is pro, but I had purchased to remove ads years ago, so think it was an upgraded Free
Model: Samsung SM-G781V (Galaxy S20 FE 5G UW)
Android software version: 12

**Comment by laurencedawson** [comment]
I've since added a fix for this.
