### ISSUE TITLE
Padding for comment navigation chip/buttons/pills

### ISSUE THREAD

**Issue by arkon** [laurencedawson/sync-for-reddit#1061]
**Is your feature request related to a problem? Please describe.**
When browsing a post's comments, the nav buttons at the bottom (with the arrow buttons) are very close to the bottom of the view. On taller screens, it may be difficult to reach.

**Describe the solution you'd like**
Padding options, i.e. additional padding between the bottom edge of the screen and where the buttons are positioned.

**Describe alternatives you've considered**
I could change how I hold my phone?

**Additional context**
N/A

**Comment by bohrabhijeet** [comment]
Similar reports, https://www.reddit.com/r/redditsync/comments/ukwsfw

**Comment by laurencedawson** [comment]
This has since been fixed.
