### ISSUE TITLE
[bug] list view youtu.be type indicator

### ISSUE THREAD

**Issue by co5mo** [laurencedawson/sync-for-reddit#1062]
hi

list view type indicator for domain youtu.be is picture not video

thanks

**Comment by bohrabhijeet** [comment]
This is a duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/1062

**Comment by bohrabhijeet** [comment]
This is a duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/1029
