### ISSUE TITLE
Awarder and Awardee Karma

### ISSUE THREAD

**Issue by cococoot** [laurencedawson/sync-for-reddit#1064]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Add awarder and awardee karma to existing pop up from bottom displaying link and comment karma. 

**Describe alternatives you've considered**
None

**Additional context**
Nope

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/771
