### ISSUE TITLE
Change the look of the comment arrows

### ISSUE THREAD

**Issue by cococoot** [laurencedawson/sync-for-reddit#1065]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
See image attached. 

**Describe alternatives you've considered**
None. 

**Additional context**
I'm not an artist. Just showing you what I think. Put this on Discord today and had favorable comments. 

![Polish_20220414_160802340.jpg](https://user-images.githubusercontent.com/61015333/163488687-8874f6f4-be0d-485d-b37a-d6678d7b6ce7.jpg)

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/763
