### ISSUE TITLE
Add a button to retrieve removed and deleted comment

### ISSUE THREAD

**Issue by Jnss98b** [laurencedawson/sync-for-reddit#1066]
Infinity for reddit has such feature using reveddit and that's just the fallback. I'm not sure what their main implementation uses

https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/591/commits/318a95985a9006b1d2075af92a223a76b1331bb7

**Comment by laurencedawson** [comment]
This is against reddits terms and conditions.
