### ISSUE TITLE
[BUG] Certain videos don't play when opened but play when previewed

### ISSUE THREAD

**Issue by Jnss98b** [laurencedawson/sync-for-reddit#1068]
**Describe the bug**
Some imgur videos won't play and give "UNKNOWN ERROR(17)" if you open them but will play normally if you preview them

**To Reproduce**
1. Find a comment with an imgur video the particular video that caused me error is [this video](https://i.imgur.com/hWbFqis.jpg)  [from here](https://www.reddit.com/r/gaming/comments/u3ny8k/_/i4rx05e) 
2. Tap on it instead of tap and hold
3. See error

**Screenshots**

https://user-images.githubusercontent.com/24306400/163509403-fb5c16e7-f35e-484e-846b-c248d06512ec.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 12
 - Version Dev v22.3.28

**Comment by laurencedawson** [comment]
Fixed for the next release.
