### ISSUE TITLE
Add support for v.redd.it previews on subreddits that do not support previews

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#1073]
e.g. anime_irl does not generate the previews needed by default.

However we can perhaps make one ourself from the ```media``` information as it contains height + width
.

Otherwise we can look to somehow override this setting even for the logged out account.

**Comment by geominorai** [comment]
Images marked as spoiler in that sub are also unable to generate previews in the feed.

See also related issue #1053

**Comment by laurencedawson** [comment]
Done.
