### ISSUE TITLE
[BUG] Opening Reddit video player Link crashes the app

### ISSUE THREAD

**Issue by Metalbird1997** [laurencedawson/sync-for-reddit#1084]
https://www.reddit.com/r/teslamotors/comments/u61hfc

Pressing on the first link in this post freezes the app or restarts it.

Device information

Sync version: v22.4.16    
Sync flavor: free    
Removed ads: true    

View type: Slides    
Push enabled: false    

Device: crownlte    
Model: samsung SM-N960F    
Android: 10

**Comment by JEnduriumK** [comment]
Possible similar issue when clicking the last link in this post?

https://www.reddit.com/r/SS13/comments/ufamjw/rtx_on_tau_ceti_station/

The link is: https://reddit.com/link/ufamjw/video/4rn6x2hswnw81/player

My app didn't crash immediately. But I did click on the link about a dozen times, and it would freeze for about eight seconds each time I'd try to hit the Back button. Phone is now a bit unstable, and likely needs a reboot. Fairly unresponsive, can't task switch away to swipe away Sync, etc.

**Comment by Metalbird1997** [comment]
Yeah, I've changed the link handling for reddit links in android and it seems it is stuck in a loop, and if the link handling is set to always use Sync it would crash. See here https://youtube.com/watch/RRXosujNiIM

**Comment by laurencedawson** [comment]
Fixed for the next release.
