### ISSUE TITLE
[BUG] Media is visible behind the expanded toolbar with autoplay enabled and autohiding disabled

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1090]
**Description**
Media preview is visible behind the toolbar with expanded toolbar enabled, autohiding disabled and autoplay enabled.

****Scenario** (steps to reproduce)**
1. Enable Autoplay
2. Enable Expanded toolbar
3. Disable Autohiding toolbar

**Result(s)**
Media plays behind the toolbar with the chips visible

**Expected behavior**
Toolbar should stay opaque

**Device information**
```
    Sync version: v22.4.20    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 11
```

**Additional context**
https://user-images.githubusercontent.com/34155181/163998818-7a8db220-81ec-489c-917f-bb76d35a0a87.mp4

**Comment by laurencedawson** [comment]
Fixed for the next release.
