### ISSUE TITLE
Request: Add the ability to update the default sorting of a subreddit from that subreddit

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#1093]
Currently the only place to Override Sort is to open the Explore menu, scroll down to the subreddit in the list, tap the 3-dot menu, Update Sort

It would be nice to have it here:

https://i.imgur.com/eADzt5Y.png

Or here instead:

https://i.imgur.com/4kPDVMt.png

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by thereddestdog** [comment]
Thanks! Where did you add it?

**Comment by laurencedawson** [comment]
Where you suggested 👍🏻

**Comment by thereddestdog** [comment]
Ah I see it now, but it's so buried 😭

Sorry, I thought more like "Set Default" under Comments here:

https://i.imgur.com/2RwKq41.png
