### ISSUE TITLE
[BUG] NSFW results do not appear when searching for subreddits

### ISSUE THREAD

**Issue by rsmyst** [laurencedawson/sync-for-reddit#1097]
**Describe the bug**
As indicated, NSFW subreddits just don't seem to appear in app when searching for them. I have NSFW search enabled in account prefs and it works in other reddit clients.

**To Reproduce**
1. Open app
2. Search for any NSFW subreddit

**Expected behavior**
The result pops up as expected.

**Screenshots**
https://i.imgur.com/jBXcCFA.jpg

**Smartphone (please complete the following information):**
 - Device: Galaxy S9+
 - OS: Android 10
 - Browser Brave
 - Version 22.4

**Additional context**
The nsfw results work perfectly fine in other apps...

**Comment by laurencedawson** [comment]
So just to double check, are you logged in?

**Comment by rsmyst** [comment]
> So just to double check, are you logged in?

Can confirm that search doesn't show nsfw results regardless of whether i'm logged in or not. tried in both cases. same result.

**Comment by laurencedawson** [comment]
Make sure you have NSFW posts enabled in the settings.

Settings > uncheck "Hide NSFW posts"

Make sure you have the reddit preference set:

Settings > Reddit web preferences > NSFW search

Failing that try on a VPN as your ISP might be restricting you.

**Comment by laurencedawson** [comment]
Unable to reproduce.
