### ISSUE TITLE
[BUG] Low image resolution in full height card previews

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1098]
**Describe the bug**
Previews for images and videos in full height cards have resolutions too low for their size.

**To Reproduce**
1. Enable full-height cards
2. Open a sub with vertical videos like [r/WatchPeopleDieInside](https://www.reddit.com/r/WatchPeopleDieInside/)
3. Scroll down to the video
4. Watch the crisp thumbnail image suddenly turn into a pixelated video reminiscent of the days of dial-up modems.

**Expected behavior**
Resolution of preview vertical images and videos for full-height cards should not differ significantly from the original media.

**Screenshots**

https://user-images.githubusercontent.com/13911156/164333131-16589fa1-8d85-4bd2-b706-aeec6d84a2d9.mp4

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.20-23

**Additional context**
Vertical images are also affected by this -- not only video!

**Comment by laurencedawson** [comment]
This has been fixed for the next release.

Great report btw, video was *chefs kiss

**Comment by geominorai** [comment]
Unfortunately, images are still affected as of v22.4.23-18 (1522):

![Reddit Apps Comparison - Full height image previews](https://user-images.githubusercontent.com/13911156/164966807-60401654-68d5-4fa3-9cad-3662a462fdbf.jpg)
