### ISSUE TITLE
[BUG] Disabling Autohide Toolbar setting causes missing text in toolbar

### ISSUE THREAD

**Issue by anonymous-user** [laurencedawson/sync-for-reddit#1099]
**Describe the bug**

Disabling the Autohide Toolbar setting causes the subreddit name and sorting to be hidden from the toolbar

**To Reproduce**

1. Go to Settings -> General -> disable Autohide Toolbar
2. Go back to the front page or any subreddit
3. Look at the toolbar. The name and sorting will be invisible.

**Expected behavior**

The name and sorting should not disappear.

**Screenshots**

With Autohide Toobar enabled:

![Screenshot_20220419-212637](https://user-images.githubusercontent.com/4295854/164356915-b5830793-b08a-4a8e-b1e9-8db692b31251.png)

Versus disabled:

![Screenshot_20220419-212648](https://user-images.githubusercontent.com/4295854/164356918-d4e9d7ea-f942-46c8-81e7-310f2d552dcd.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android 12
 - Browser: Firefox
 - Version: v22.4.20

**Comment by laurencedawson** [comment]
Fixed for the next release.
