### ISSUE TITLE
Searching through saved posts (in offline mode too)

### ISSUE THREAD

**Issue by hungrypippo** [laurencedawson/sync-for-reddit#1103]
As simple as it sounds. 

Cache my saved posts in my device storage, obviosuly give me a warning that it will use some storage. 

And with the help of this, i can browse saved posts with comments, pictures,videos when offline. 

Also having an option enabled where in i can toggle to just save the posts or save the imaged and videos too.

A simple version of this exists in Joey for reddit. Even that version has been majorly helpful for me personally quite a few times.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/460

Closing as theres no API.
