### ISSUE TITLE
[BUG] [Tablet] Autohide FAB disabled but still hides the FAB on comments panel

### ISSUE THREAD

**Issue by snah-dev** [laurencedawson/sync-for-reddit#1107]
**Describe the bug**
The FAB on the comments panel in tablet mode still autohides when autohide FAB is disabled.

**To Reproduce**
1. Disable Autohide FAB
2. Enable Tablet mode
3. Open a post
4. Scroll the comments

**Expected behavior**
FAB should not autohide.

**Tablet (please complete the following information):**
 - Device: Samsung Tab S8
 - OS: Android 12

**Comment by laurencedawson** [comment]
You adjust the post + comment fabs independently of each other:

Settings > Comment options > autohide fab
