### ISSUE TITLE
[REQUEST] OneUI notification pop-up (not Android's heads-up) should show more context

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1109]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/u7lt9e

**Screenshot**
![8FIu0zn~2.png](https://user-images.githubusercontent.com/34155181/164487308-2822db8a-3190-4a1d-9d61-51b603b27373.png)

**Comment by laurencedawson** [comment]
OneUI restriction. boo
