### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cococoot** [laurencedawson/sync-for-reddit#1110]
**Describe the bug**
App just started crashing all of a sudden

I try to post an image and crash. I try to go to a subreddit and crash. Never experienced this before. 

I writing this from another app. 

Any help appreciated. Thank you.

**To Reproduce**
See above

**Expected behavior**
NA

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+ 5G
 - OS: Android 12 OneUI 4.0
 - Browser is Chrome
 - Version Latest Dev beta. Downloaded this morning. 

**Additional context**
NA

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers
