### ISSUE TITLE
[BUG] Switching between subreddits in Card view, not returning to the very top post

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#1112]
https://photos.app.goo.gl/gNSJXyfPZyya53LA9

Can not replicate with Slides. No difference if I have Extended Toolbar enabled or not, or if Full Height Images are enabled or not

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by thereddestdog** [comment]
Hey @laurencedawson I found this same bug when switching between sorting on a sub (Hot/New/Rising, etc). I would think when changing Sorting you would always want to return to the top-most post like on Desktop

**Comment by thereddestdog** [comment]
> This has been fixed no?

You fixed it for when switching between subreddits. I happened to find it when switching sorting in any subreddit

**Comment by laurencedawson** [comment]
Re-opened.

**Comment by laurencedawson** [comment]
This has since been fixed.
