### ISSUE TITLE
[BUG] Immediate Crash/Close On Attempted Launch

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1115]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/u8fhe9/_/

**Description:**
When launching the app, the native biometrics authentication process launches as normal. Once authenticated, it looks like Sync tries to launch but immediately closes. I have performed full system reboot and issue remains.

**Scenario (steps to reproduce):**

- Click on app launcher icon on phone screen

- Authenticate with native biometrics (I cannot disable this in current state to try without)

**Result(s):**
Sync For Reddit seems to initially begin to launch, but immediately closes back down to app launcher icon.

**Device Info:**
```
Device Model: Samsung Galaxy S9+ SM-G965U

Android Version: Android Q (10) Build QP1A.190711.020.G965USQU9FUL1

Sync version: Sync Dev v22.4.20
```

**Logcat:**
https://pastebin.com/zvUL8Byq

**Comment by thereddestdog** [comment]
Update to 21-22 and see

**Comment by SPQRBob** [comment]
I was the original reporter of this issue in the subreddit.  Clearing the app's cache and data removed the biometric 2FA settings.  

I was then able to successfully launch Sync, reattach my account, and use the app's functionality as expected.  I have not re-enabled the biometric 2FA feature at this time, but am willing to do so for further debugging as needed.

**Comment by laurencedawson** [comment]
Thanks for the update

**Comment by laurencedawson** [comment]
Linking:

https://github.com/laurencedawson/sync-for-reddit/issues/1058

**Comment by laurencedawson** [comment]
Closing, stale.
