### ISSUE TITLE
[BUG] Site preview images are low quality and not full height

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1121]
**Describe the bug**
Site preview images show a cropped and highly compressed image even for full height cards.

**To Reproduce**
1. Go to a sub with posts linking websites with thumbnails like [r/anime](https://www.reddit.com/r/anime) (e.g. explore domain crunchyroll.com)
2. Observe horribly compressed and cropped thumbnails

**Expected behavior**
Thumbnail images should be original quality as provided by the site, and displayed without cropping when in full-height cards mode.

**Screenshots**

![Reddit Apps Site Thumbnail Comparison](https://user-images.githubusercontent.com/13911156/164882404-9ce674b0-0536-452a-9915-6ff05a03d91d.png)

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.22-22

**Additional context**
It looks like Sync is using the low resolution thumbnail image Reddit provides and also uses in their app, but is intended to be a tiny thumbnail off to the side instead of full-height, so stretching it out larger makes the compression artifacts much more obvious.

**Comment by laurencedawson** [comment]
This was an edge case where the source preview was low quality and reddit provided a smaller version still.

Fixed for the next release.
