### ISSUE TITLE
[BUG] Focusing the search field while being anonymous causes a CRASH

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#1124]
**Describe the bug**
If you open the explore bottomsheet and clicking the search field, the app will crash

**To Reproduce**
1. Be anywhere on reddit
2. Click on explore
3. Click the search box
4. App crashes

**Expected behavior**
App should be able to highlight the field without crashing

**Smartphone (please complete the following information):**
 - Device: Galaxy A51 4G (a51nsxx)
 - OS: Android 11, OneUI 3.1 Jan Patch
 - Browser: Samsung Internet (16.2.5.4)
 - Version: Sync Dev 22.4.22-22 (INTERNAL)

**Comment by laurencedawson** [comment]
Think I've got this fixed for the next release.
