### ISSUE TITLE
[BUG] App crash when adding quote via editor toolbar in submit text post

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#1128]
**Describe the bug**
The app crashes when adding quote via editor toolbar in submit text post

**To Reproduce**
1. Open Submit > Text  
2. Select quote icon on the editor toolbar

**Expected behavior**
Tapping quote icon should add `>` in the selftext editor

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A32 4G
 - OS: Android 11
 - Version: 22.4.23

**Comment by laurencedawson** [comment]
Fixed for the next release.
