### ISSUE TITLE
SUGGESTION/REQUEST: Resume autoplayed content in the media viewer from where the user left off

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#113]
Is it possible such that when you're viewing a post's video being autoplayed while scrolling, that if you click on the video that the video continues to play from where it was in the autoplay view?

So, you're viewing a 10s autoplayed GIF in your feed (you haven't clicked the content on the post yet); it plays for 6s; you click the post content; the GIF is now open in the media player at the timestamp of 6s and not at the start.

**Comment by devanshupipalia** [comment]
Please LJ this!

**Comment by laurencedawson** [comment]
Added for the next release.
