### ISSUE TITLE
[BUG] Long press on spoiler text treats it like a link

### ISSUE THREAD

**Issue by lime-red** [laurencedawson/sync-for-reddit#1131]
**Describe the bug**
A long press on spoiler text in comments treats it like a link, and shows link options. A short tap on the spoiler text behaves as expected.  This only happens on comments, doesn't happen if the spoiler is in selftext. 

**To Reproduce**
1. Find a spoiler text in comments.
2. Long press on the spoiler text
3. See link options in error

**Expected behavior**
I would expect either the same action as a short tap, or the collapse action.

**Screenshots**
![Screenshot_20220423-224705_Sync Pro](https://user-images.githubusercontent.com/8443840/164895367-ffb333b8-bb99-4c38-b292-5e58f27851a8.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S20FE
 - OS: Android 12
 - Sync
 - Version 22.4.20

**Additional context**
Link to example: 
https://www.reddit.com/r/combinedgifs/comments/u9elnq/_/i5s0lpz

**Comment by laurencedawson** [comment]
Fixed for the next release.
