### ISSUE TITLE
Apply "easing" to all animations

### ISSUE THREAD

**Issue by OptimisticSean** [laurencedawson/sync-for-reddit#1132]
**Is your feature request related to a problem? Please describe.**
Currently, all animations in the app seems to have liitle or no "easing" at all. According to the [Material Design guidelines](https://material.io/design/motion/speed.html#duration), easing should be applied to animations to make them feels smoother and less jarring.

**Describe the solution you'd like**
Apply suitable animation curves to all animations in the app according to the Material Design guidelines.

**Describe alternatives you've considered**
An switch to turn on or off easing for animations would probably be better, since some people might dislike such effects.

**Additional context**
None

**Comment by laurencedawson** [comment]
Which specifically? Most animations have the material animation interpolator already.

**Comment by OptimisticSean** [comment]
For me, it's mainly the comment transition, collapsing and navigation animations. Those three feel like they end abruptly. The fly-out and fly-in animations of the bottom dialogs feel really smooth, though.

I think the reason it feels like that for me is probably because I just switched from Relay, which seems to has a slower animation speed overall compared to Sync. Perhaps I just need some time to get used to it.

**Comment by laurencedawson** [comment]
Ensured all post + comment animations now use FastOutSlowInInterpolator.
