### ISSUE TITLE
[BUG] Media previews not loading when opening posts and comments

### ISSUE THREAD

**Issue by lottevanilla** [laurencedawson/sync-for-reddit#1133]
**Describe the bug**
Media previews of any kind (URL thumbnails, images, video thumbnails, etc.) are not showing up when opening a post even if those are showing up when browsing through subreddits, the frontpage and other instances. The issue persists even when changing from smaller cards to slides or other types of views.

**To Reproduce**
1. Open the app
2. Browse through any kind of list of posts
3. Select a post with any kind of thumbnail
4. Thumbnail doesn't show up

**Expected behavior**
The media preview should load without any issue.

**Screenshots**
![Screenshot_20220423-152832_Sync Pro.png](https://user-images.githubusercontent.com/104275952/164943495-0ec8b220-ec82-42ee-86c9-2d521283c41e.png) ![Screenshot_20220423-152838_Sync Pro.png](https://user-images.githubusercontent.com/104275952/164943498-476eaa21-aa58-4661-8d22-c18402f4e13d.png) ![Screenshot_20220423-152847_Sync Pro.png](https://user-images.githubusercontent.com/104275952/164943500-6575c111-fdc0-4ab4-bc4e-7df5aee70f98.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO X3 NFC
 - OS: Android 12
 - Browser: Samsung Internet 16.2.5.4
 - Version: 22.4.23

**Comment by laurencedawson** [comment]
Fixed for the next release.
