### ISSUE TITLE
[BUG] Swipe distance causes missed inputs

### ISSUE THREAD

**Issue by Liz-chan** [laurencedawson/sync-for-reddit#1134]
**Describe the bug**
When you want to upvote a post or comment, the distance needed to trigger the swipe action is further than it was in V20, causing the action to not register and then having to go back and swipe again to actually upvote. An easy fix would be shortening the distance that you have to travel to trigger the swipe action, and a more elegant fix would be adding a setting where you could change the distance for the 3 individual swipe actions.

**To Reproduce**
1. Try to upvote a post/comment by swiping.
2. It doesn't work because your finger didn't go far enough.

**Expected behavior**
1. The post/comment should be upvoted

**Screenshots**
V20: 
<img src="https://user-images.githubusercontent.com/18467466/164946861-61cef874-c8e3-4361-bb55-e07a38a29565.png" width="400">
V22:
<img src="https://user-images.githubusercontent.com/18467466/164946865-9a7c05f0-c87e-4d1c-946c-cb137f280d75.png" width="400">

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro 5G McLaren
 - OS: OxygenOS 10
 - Browser: Samsung Internet
 - Version: 22

**Additional context**
I know this isn't technically a bug but it isn't really a feature request either.

**Comment by laurencedawson** [comment]
This has since been fixed.
