### ISSUE TITLE
[BUG] YouTube preview images are low quality 

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1137]
**Describe the bug**
YouTube video preview images have significant compression artifacts.

**To Reproduce**
1. Go any sub with YouTube video links
2. Observe horribly compressed thumbnail

**Expected behavior**
Video previews should higher resolution like image previews.

**Screenshots**

![Reddit Apps Comparison - YouTube thumbnails](https://user-images.githubusercontent.com/13911156/164965654-e9a2fe41-dbc8-46ec-b023-6704b9c0a37d.jpg)

Note: There are compression artifacts in the thumbnails of other apps in this example but the one Sync uses is comparably worse.  See the left part of the image with the cursive writing.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.23-18 (1522)

**Additional context**
YouTube video thumbnails are available in a variety of sizes, see [this gist](https://gist.github.com/a1ip/be4514c1fd392a8c13b05e082c4da363) for examples.

Choosing a suitable thumbnail resolution would be a performance and data usage trade-off.

This bug is similar to issue #1121.

**Comment by laurencedawson** [comment]
Switched to a higher quality version.
