### ISSUE TITLE
[BUG] Tapping on text after a link opens the link

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1138]
**Describe the bug**
The text (up to 6 or 7 characters) after a link is treated as a part of the link

**To Reproduce**
- Tap on the text after a link
- It opens the link

**Expected behavior**
The link shouldn't be opened

**Video**
https://media.discordapp.net/attachments/799399306775887926/967707360925732864/22-04-24-14-11-33.mp4

**Device information**
```
    Sync version: v22.4.23-18    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: true    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 11
```

**Additional context**
If the link is in the end of the sentence, it functions normally

**Comment by laurencedawson** [comment]
Android issue I'm afraid.
