### ISSUE TITLE
[BUG] A blank space after the search query results in Error: 400

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1139]
**Describe the bug**
While searching for a username or subreddit, if it consists of a space in the end, the search result throws an _Error: 400_

**To Reproduce**
- Tap on Explore
- Search for the username or subreddit
- Add space after the search query
- See error

**Expected behavior**
Blank space should be disregarded

**Screenshots**
- Sync
![Screenshot_20220424-143112.jpg](https://user-images.githubusercontent.com/34155181/164968783-fcc4bceb-0af6-4f93-888c-02d8c85cf3fc.jpg)

- Reddit official client
![Screenshot_20220424-143119.jpg](https://user-images.githubusercontent.com/34155181/164968792-534af036-b753-4d35-800b-e39faf80c3fb.jpg)

**Device information**
```
Sync version: v22.4.23-18
Sync flavor: pro    

View type: Slides
Push enabled: true    

Device: OnePlus7
Model: OnePlus GM1901
Android: 11
```

**Additional context**
N/A

**Comment by laurencedawson** [comment]
Fixed.
