### ISSUE TITLE
SUGGESTION/REQUEST: Improvements to go-to Subreddit feature

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#114]
I'm referring to the view you see when you click the subreddit name at the top:

![Screenshot (Jun 4, 2020 2_54_25 PM)](https://user-images.githubusercontent.com/2940826/83799255-8883a480-a673-11ea-8d95-389757a46a2f.png)

- When entering this view, by default I think the text should be automatically highlighted so I don't have to delete the text first
- If you enter this view while looking at a multireddit, you can no longer use it to go to an individual subreddit; maybe a radio button or something in this view to allow you to choose whether you want to go-to an individual subreddit or a multireddit.
- It should strip out special characters from the input like spaces and other characters that couldn't be in a subreddit name

**Comment by devanshupipalia** [comment]
Good suggestions

**Comment by laurencedawson** [comment]
Added the first two for the next release.

I'll have a think about the third.

**Comment by Nxt3** [comment]
Thank you! Appreciate your hard work 🙂

**Comment by laurencedawson** [comment]
Added some chips for the next release to switch between the different types

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/106373743-8691f280-6374-11eb-92a0-5843b815a8d3.png)
