### ISSUE TITLE
[REQUEST] Unread messages indicator beside Inbox in the drawer

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1145]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ub3tya

**Comment by humanplayer2** [comment]
OP of comment here. Thank you for moving it here. Original text read:

_I don't use the boot om panel for anything but being reminded of unread notifications.

Could the same counter perhaps be added as an option of the drawer's inbox?_

**Comment by bohrabhijeet** [comment]
> boot om

I had a hard time figuring out you actually meant _bottom_.

**Comment by humanplayer2** [comment]
Thanks, that was embarrassing.. I've edited.

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/958
