### ISSUE TITLE
[ENHANCEMENT] Placeholder when refreshing

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1152]
**Something similar to this:**
![Screenshot_20220427-003604~2.jpg](https://user-images.githubusercontent.com/34155181/165376312-0021b3b8-fbf7-4d75-952e-67bbcac06bf0.jpg)

**Comment by laurencedawson** [comment]
Not planning to add this as sync supports way too many view types for it to be feasible.
