### ISSUE TITLE
[BUG] Autoplaying this video darkens the screen

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1153]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ucjb3o

**Steps to reproduce:**
Go to the [r/virtualreality](https://reddit.com/r/virtualreality) subreddit and scroll past [this video](https://www.reddit.com/r/virtualreality/comments/uc3gfq), the whole screen turns dark red. It cannot be captured with screen recording however.

**Comment by laurencedawson** [comment]
The video has a color profile which is being used when playing. Not a sync issue.
