### ISSUE TITLE
New icon in Icon Selector for Android 11 and below

### ISSUE THREAD

**Issue by abhy-kumar** [laurencedawson/sync-for-reddit#1157]
The current new icon has only been made available to Android 12, an option to select it directly would be appreciated.

**Comment by Jnss98b** [comment]
Idt there's a new icon on Android 12, unless you meant smth else?

![Screenshot_20220430-163801_Sync Dev](https://user-images.githubusercontent.com/24306400/166121888-cd0b41c2-328b-4e18-8047-f091fdb97a6c.png)


**Device information**

    Sync version: v22.4.30    
    Sync flavor: dev    

    Device: redfin    
    Model: Google Pixel 5    
    Android: 12

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/773
