### ISSUE TITLE
BUG : Subs list when viewed from a multi (by selecting manage) shows incorrect subs when compared to reddit.com

### ISSUE THREAD

**Issue by devanshux** [laurencedawson/sync-for-reddit#116]
here is my multis sub list

![Annotation 2020-06-05 003828](https://user-images.githubusercontent.com/26577124/83800948-e7720980-a6c5-11ea-89cf-46d00e6974f6.png)

and here is my multis sub list in sync
![Screenshot_20200605-004042](https://user-images.githubusercontent.com/26577124/83800995-fbb60680-a6c5-11ea-91d4-6a060d1359a5.jpg)

The feed of the multi picks and shows all the contents of all the subs perfectly fine. it just incorrectly display those sub in the list when hit manage in a multi

**Comment by laurencedawson** [comment]
This has since been fixed.

**Comment by devanshux** [comment]
Yes it has can confirm
