### ISSUE TITLE
[BUG] Missing comment dividers

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1161]
**Describe the bug**
Comment dividers do not show regardless of theme.

**To Reproduce**
1. Toggle on via `Settings > Comments > Comment dividers`
2. Open any thread with many comments
3. Observe lack of dividers

**Expected behavior**
Comment dividers should work on all themes and appear similar to how it was on v19:

<img src="https://cdn.discordapp.com/attachments/685907856351821824/968958540742008902/Screenshot_20220427-123438_Sync.png" width="200"> <img src="https://cdn.discordapp.com/attachments/685907856351821824/968959210484293713/Screenshot_20220427-123752_Sync.png" width="200">

**Screenshots**

<img src="https://cdn.discordapp.com/attachments/685907856351821824/968837950001545226/Screenshot_20220427-043411_Sync_Dev.png" width="200"> <img src="https://cdn.discordapp.com/attachments/685907856351821824/968837950219640902/Screenshot_20220427-043433_Sync_Dev.png" width="200"> <img src="https://cdn.discordapp.com/attachments/685907856351821824/968837950504833024/Screenshot_20220427-043503_Sync_Dev.png" width="200">

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.27-17:37 (1545)

**Additional context**
See related feature request #844.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/790
