### ISSUE TITLE
[BUG] Search in subreddit with a "#"

### ISSUE THREAD

**Issue by Yurof** [laurencedawson/sync-for-reddit#1171]
**Describe the bug**
If  I search in a subreddit with a '#' in my query it became a global search

**To Reproduce**
1. Go to a subreddit
2. Click on search panel
3. type a query with a #
4. click on search *name of the subreddit*

**Expected behavior**
You get a subreddit search result

**Screenshots**
<img src= https://user-images.githubusercontent.com/48862755/166104344-912c7df5-5178-40a7-ae59-d627087f751e.png width="400">
<img src= https://user-images.githubusercontent.com/48862755/166104346-6d22b586-a2fd-4a4a-9914-4253d6b78024.png width="400">

**Smartphone :**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 12
 - Browser : Samsung Internet
 - Version: v22.4.28 (1549)

**Comment by laurencedawson** [comment]
Good spot. Fixed for the next release.
