### ISSUE TITLE
Inline tables option

### ISSUE THREAD

**Issue by Code027** [laurencedawson/sync-for-reddit#1173]
**Is your feature request related to a problem? Please describe.**
Currently the only way to view tables is through a bottomsheet.

**Describe the solution you'd like**
An option or toggle to view tables as inline in comments in settings.

**Describe alternatives you've considered**
Some users may prefer to still have it as it is to reduce scrolling so perhaps a collapsable **View table** but in a way that would stay inline instead of a bottomsheet.

**Additional context**
\-

**Comment by laurencedawson** [comment]
No plans to add these in comments.

Used to be this way and it's not ideal.

Thanks for the suggestion though.
