### ISSUE TITLE
[BUG] Clicking existing search text does not focus the search field

### ISSUE THREAD

**Issue by snah-dev** [laurencedawson/sync-for-reddit#1174]
**Describe the bug**
I have entered a search text "Test" but when I click the "Test" search header text it doesn't focus the search field.

**To Reproduce**
1. Search "Test"
2. Click the search header text "Test"
3. It will display the Explore popup but not focus the search field.

**Expected behavior**
The search field should be focused.

**Comment by thereddestdog** [comment]
You now have to long press to edit the search keywords

**Comment by hanschua** [comment]
> You now have to long press to edit the search keywords

I know the long press but if I want the Explore to popup then I would have clicked the Explore button instead of the search header.

**Comment by snah-dev** [comment]
> You now have to long press to edit the search keywords

I know the long press to edit but if I wanted the Explore popup then I would have clicked the Explore button instead of the search header.

**Comment by laurencedawson** [comment]
Long clicking the search term will do this.

Or click "options"
