### ISSUE TITLE
[BUG] Error saving media if subfolder is deleted

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1177]
**Describe the bug**
If an image subfolder previously used to download images is deleted, the app fails to download the image once before recreating the subfolder on manual retry.

**To Reproduce**
1. Enable `Media > Download to subfolders` in settings
2. Open a sub with image posts
3. Download an image
4. Delete the image subfolder with a file browser app
5. Attempt to download an image from the same sub
6. See error message

**Expected behavior**
The app should silently recreate the folder and proceed with the download.

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/166181651-d0cbd55e-760b-4d14-96f3-44218cde6dcf.png" width=400 />

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.30 (1552)

**Additional context**
Boost and Infinity also support downloading to subfolders and handle the folder recreations silently.

**Comment by laurencedawson** [comment]
Hitting retry downloads the image again.

This is expected behaviour.

**Comment by laurencedawson** [comment]
I've updated the message here.

**Comment by geominorai** [comment]
This is not very intuitive for interface design.

Since there is normally a download success notification, this error will get buried and ignored with the rest of them. Users who download multiple images in the same sub would not realize until too late why one of the images they tried to download never got downloaded, and will have a hard time figuring out which one was missing and go hunt it back down.

Plus, users who archive their downloads should already know they removed the subfolders purposely and need not be nagged about it each time.

**Comment by laurencedawson** [comment]
I'll keep this open as its discussed.

**Comment by Ralim** [comment]
If this could be opted out of in settings would be great.
This behaviour is not what I would expect at all from the description given in the settings.
For now I've reverted out of the beta and backed up the app version until this can be opted out of.

My use case is that my phone downloads are automatically cleaned up, after 24 hours they are pulled off to external storage.
I now generally have to click retry every time and it's a lot of extra friction; and super easy to miss. If found if I miss them for too long they sometimes give "media unavailable" so I have no idea of knowing what failed (or good luck finding it again).

If this is the way it's going to be forever I'll have to figure out a way to keep empty folders around but hopefully can keep the app here back for a while 😁

**Comment by agret** [comment]
Thanks for tagging the issue in my duplicate, I'm having the same bug on my phone which is also Android 10. Why is the app saying that the folder no longer exists and making us click on retry? It should auto retry to create the deleted folder and only if that attempt fails display this prompt for action.

**Comment by agret** [comment]
Whenever you try to save reddit/imgur video the retry prompt won't come up until the video download background completes. Since these servers are trash for videos it's often 2-3 mins later you get the prompt for the 10second video you pressed save on, when you click retry it gives an error that the media was not found.

**Comment by laurencedawson** [comment]
What content are you viewing that doesn't stay up for more than 3 minutes?

**Comment by agret** [comment]
The content still exists, just if you get this retry prompt on saving a video it always says the media doesn't exist (after the download has completed in the background).  If you go back and find the original post then press download it will save no problem.

**Comment by laurencedawson** [comment]
The error notification has a retry button

**Comment by agret** [comment]
It does have a retry but every time you press retry it brings it up again instantly (Error saving media - media not available). You have to dismiss the error notification, go back to the original post and press download again for it to succeed.

**Comment by agret** [comment]
![Screenshot_20220528-192243](https://user-images.githubusercontent.com/568523/170819367-a4d26f93-4f3f-49cf-bd3e-ae9e8de9209e.jpg)

![Screenshot_20220528-192259](https://user-images.githubusercontent.com/568523/170819370-9dc855ba-5b4a-4086-8baa-93e87364b91e.jpg)

**Comment by laurencedawson** [comment]
Changed the behavior of this for the next release.
