### ISSUE TITLE
[BUG] Media subfolders recreated indefinitely when each app is installed or app data is reset

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1178]
**Describe the bug**
When the app is first installed, reinstalled, different version of the app are installed (e.g. public, pro, dev), or app data is reset, any media download subfolders that already exist will be ignored and a new one will be recreated with an incrementing number in the suffix.

**To Reproduce**
Steps to reproduce the behavior to create subfolders indefinitely:
1. Install any one version of the app or reset app data of existing app(s)
2. Enable `Media > Download to subfolders` in settings
3. Open a sub with image posts
4. Download an image
5. Observe newly created subfolder(s)
6. Go to line 1

**Expected behavior**
Existing subfolders should be used if they already exist.

**Screenshots**
<img src="https://user-images.githubusercontent.com/13911156/166184493-a1aef43d-fe43-4007-9276-518292db3c13.png" width=300 />

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.4.30 (1552)

**Additional context**
Users noticing this bug may attempt to merge the contents of the duplicate folder with the previous one and delete the duplicate, but this will instead trigger bug #1177.

The only real workaround when encountering this bug is to move away all subfolders temporarily so that the main download folder is empty.  Then go to every sub and attempt to download any image, and thus triggering bug #1177 as many times as there are subs, then move all the existing subfolders back.

**Comment by PhilippLoewen** [comment]
I have the same problem on my OnePlus 7T with Android 11 and Sync version v22.4.30 (1552).

My folders are a mess as a result.

**Comment by bohrabhijeet** [comment]
Another report:
https://www.reddit.com/r/redditsync/comments/uvqidf

**Comment by laurencedawson** [comment]
Fixed for the next release.
