### ISSUE TITLE
BUG: Black background on navigation bar when pulling card down from recents menu

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#119]
https://streamable.com/2aqckl

Also happens when scrolling between apps
https://streamable.com/upbt3y

**Comment by laurencedawson** [comment]
Pretty sure this is a knock on effect from switching the full screen flags to work with Android R.

Try with Google messages and I bet you get the same thing.

**Comment by RecklessDwark** [comment]
Doesn't happen on Google messages

**Comment by laurencedawson** [comment]
This has since been fixed!
