### ISSUE TITLE
Ultra - Limit number of website previews generated

### ISSUE THREAD

**Issue by Nive9** [laurencedawson/sync-for-reddit#1198]
An option to limit how many previews are shown below comments would be nice to avoid filling up the whole screen when there are multiple links.

It was already requested [here](https://www.reddit.com/r/redditsync/comments/ufhii5/comment/i6xcg6y/), but I'm not sure if it was added to the to-do list or if the reply there was just an auto-reply due to the Ultra sign-up requests.

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/1172
