### ISSUE TITLE
[ENHANCEMENT] Update TTS and ‘Paint user’ icons

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1199]
[Text-to-speech](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

[Paint user](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aformat_paint%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

**Comment by laurencedawson** [comment]
Done.
