### ISSUE TITLE
REQUEST/SUGGESTION: Updated overflow menus within the Subreddits bottom sheet (see notes)

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#120]
(edit: there's a bunch of stuff here. I don't know if it's all easy to do or the best way to do it, but I think these menus can be streamlined nonetheless)

Suggestions for this top-level subreddit overflow menu: https://i.imgur.com/1mGRaDN.png

- Change Sort text to "Change /r/(Subreddit)'s default sort"
- Change View Mode text to "Change /r/(Subreddit)'s default view mode"
- Include "Open in new window" option to be consistent with search result's overflow menu
- Include "View sidebar" option to be consistent with search result's overflow menu
- Maybe include icon for each menu option

Suggestions for "Update Sort" and "Update View Mode" menus: https://i.imgur.com/037941c.png / https://i.imgur.com/tDCC4ZN.png

- Change header of menus to "Change /r/(Subreddit) Sort" and "Change /r/(Subreddit) View Mode"
- Eliminate confirm dialogs (https://i.imgur.com/VONzJyf.png / https://i.imgur.com/5lqQYfo.png) and include "Reset to Default" in both Update Sort and Update View Mode menus
- Make "Top" and "Controversial" sorts collapsible like in the sort picker bottom sheet (https://i.imgur.com/gefcNk5.png)
- Include icon for each Sort option
- When it is a valid option, have "Best" appear at the top of the Sort options list, to be consistent with the sort picker bottom sheet

**Comment by devanshupipalia** [comment]
Agree with all of these!

**Comment by laurencedawson** [comment]
The first level menus have been replaced with drop down menus largely negating the need for the changes.

Admittedly the sort and view sub menus could still do with changing to bottomsheets but as this is a fairly obscure feature I'm going to go ahead and close this issue. Cheers.
