### ISSUE TITLE
Add option to remove AMOLED black theme post dividers

### ISSUE THREAD

**Issue by intrapt** [laurencedawson/sync-for-reddit#1201]
Some people might like them, but the theme looks much cleaner without them

**Comment by amnesia** [comment]
Agreed, I absolutely hate them. I know this is gonna sound stupid, but I almost don't want to use the app anymore. Lines add too much clutter (and look super bad), even on a 120hz screen, if you're a rolling fast(er). I would really appreciate an option to remove them.

**Comment by laurencedawson** [comment]
Added.
