### ISSUE TITLE
[BUG] New comments are highlighted even when option is disabled

### ISSUE THREAD

**Issue by Code027** [laurencedawson/sync-for-reddit#1203]
**Describe the bug**
Loading new comments displays the color highlight without the dot indicator when "Highlight new comments" is disabled.

**To Reproduce**
1. Going to posts with a lot of comments like [this](https://www.reddit.com/r/redditsync/comments/ui4htl/v2254_beta_release/)
2. Scroll down to load more comments (My initial comment count is 75)
3. See error

**Expected behavior**
Comments should not be highlighted when the setting is disabled.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: MIUI 12.5
 - Browser: Brave
 - Version: 22.5.4

**Additional context**
Issue found [from the subreddit.](https://www.reddit.com/r/redditsync/comments/uicmp4/v2254_bug_new_comments_have_highlight_color_even/)

**Comment by laurencedawson** [comment]
Fixed for the next release.
