### ISSUE TITLE
[BUG] Lock-up when clicking on a type of reddit video url

### ISSUE THREAD

**Issue by TheEchoCode** [laurencedawson/sync-for-reddit#1206]
[Post on the subreddit](https://reddit.com/r/redditsync/comments/uivbwr/bug_lockup_when_clicking_on_a_type_of_reddit/?)

**Bug description**

When looking at this [post](https://reddit.com/r/selfhosted/comments/ui6cny/tandoor_recipe_v14_released_shopping_importing/) I clicked a reddit video link which caused the app to start stuttering (low framerate) and the gesture back and back button stopped working. If you try to switch app reddit sync goes to the splash screen and locks up. 

**Scenario**

Example link: https://reddit.com/link/ui6cny/video/yn2oadiukgx81/player

    1. Click on a reddit video link, like this one https://reddit.com/link/ui6cny/video/yn2oadiukgx81/player
    2. Try using slide back and back button
    3. Use app switch button
    4. Reddit sync is now stuck on the splash screen    

**Result(s)**
The app locks up in the splash screen. 

**Device information**

    Sync version: v22.5.4    
    Sync flavor: pro    
    
    View type: Cards    
    Push enabled: false    
    
    Device: G8341    
    Model: Sony G8341    
    Android: 9

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/1084
