### ISSUE TITLE
[BUG] Sync Ultra doesn't show up in settings search results

### ISSUE THREAD

**Issue by rvictorr** [laurencedawson/sync-for-reddit#1211]
**Describe the bug**
While in Settings, when searching for "ultra" or other related keywords, the Sync Ultra section doesn't show up in the search results.

**To Reproduce**
1. Go to app settings
2. Search for "ultra", "sync", "sync ultra"
3. Notice the "Sync Ultra" section doesn't show up in the results

**Expected behavior**
The user should be able to reach the "Sync Ultra" section by searching for it.

**Screenshots**
![Screenshot_20220505-181809](https://user-images.githubusercontent.com/4266327/166956493-d7d27de7-dd97-4369-9a5d-dc85f776fa53.png)
![Screenshot_20220505-181815](https://user-images.githubusercontent.com/4266327/166956497-fa68dbe9-fdb9-4026-837a-cb366a2ff935.png)

**Smartphone (please complete the following information):**
 - Version 22.5.4

**Comment by laurencedawson** [comment]
Fixed for the next release.
