### ISSUE TITLE
[BUG] Draft selector barely legible in dark mode

### ISSUE THREAD

**Issue by Philipp-Codes** [laurencedawson/sync-for-reddit#1216]
**Describe the bug**
The draft selection section in the commenting toolbar is very hard to use in dark mode due to bad contrast of text and background.

**To Reproduce**
1. Enable dark mode
2. Compose a post
3. Exit post without submitting
4. Select save draft in prompt
5. Start composing a new post
6. Select the folder icon in the comments toolbar

**Screenshots**
[https://imgur.com/cvZl3dj](https://imgur.com/a/EqWGtB1)

**Smartphone:**
 - Device: OnePlus3T
 - OS: Android 9
 - Sync Version: v22.5.4
 - Sync flavor: pro

**Comment by laurencedawson** [comment]
Fixed for the next release.
