### ISSUE TITLE
[bug] Sync allows 'image share' of websites in peek

### ISSUE THREAD

**Issue by heleos** [laurencedawson/sync-for-reddit#1217]
Peeking a website preview allows you to share the image, but since it's a link to the website, sync fails to share the image.

**Comment by heleos** [comment]
Error message is 'glide failed to grab this image'. Would maybe be useful to swap out image share for post preview share?

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/1166
