### ISSUE TITLE
[BUG] Mute button state lost after app switch

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1222]
**Describe the bug**
When switching between recent apps, returning to Sync while the video player was on will show an incorrect state for the mute button.

**To Reproduce**
1. Enable video `mute when opening` in settings.
2. Open any post with a video
3. Unmute video and play it for a bit
4. Switch to another app
5. Switch back to Sync

**Expected behavior**
The mute button icon should be consistent with the actual audio state after switching back to the app.

For consistency, if the video was unmuted prior to the app switch, it should still be unmuted when switching back.

**Screenshots**

https://media.discordapp.net/attachments/685907856351821824/971880703442714684/Screen_Recording_20220505-140252_Sync_Dev.mp4

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.5.4 (1559)

See also related issue #746.

**Comment by laurencedawson** [comment]
Fixed for the next release.
