### ISSUE TITLE
[BUG] [Feature Regression] Full video does not resume from feed autoplay position

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1223]
**Describe the bug**
Tapping on a video autoplaying in the feed does not resume in the full video player at the same timestamp.

**To Reproduce**
1. Enable autoplay in `Settings > Data Options`
2. Scroll to a video or animated GIF in any sub
3. Watch for a few seconds
4. Tap to open in full video player.

**Expected behavior**
The video should resume playing where it left off in the feed.

**Screenshots**

https://media.discordapp.net/attachments/685907856351821824/970849928945467412/Screen_Recording_20220502-175028_Sync_Dev.mp4

https://media.discordapp.net/attachments/685907856351821824/970851041727897670/Screen_Recording_20220502-175506_Sync_Pro.mp4

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.5.4 (1559)

This is a regression for implemented feature request #113.

**Comment by laurencedawson** [comment]
I'll take a look into this again

**Comment by laurencedawson** [comment]
Turns out it was just busted for cards. Fixed.

**Comment by geominorai** [comment]
It's not clear if this is a regression or an oddity with the video, but the feed's video preview timestamp does not resume when opening https://www.reddit.com/r/anime/comments/10si0d9 on v23.
