### ISSUE TITLE
[BUG] Comment dividers cut through indentation bar

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1225]
**Describe the bug**

Comment dividers currently cut through the vertical indentation bars

**Expected behavior**

Comment dividers should start to the right of the corresponding indentation bar.

**Screenshots**

Current (left) and proposed fix (right)

<img src="https://user-images.githubusercontent.com/13911156/167251006-fd412f39-80b9-4db6-9e4f-f3fde14c4248.png" width=300 /> &nbsp; <img src="https://user-images.githubusercontent.com/13911156/167251009-7b1dee2d-c773-409f-8b6d-3811eb25431b.png" width=300 />

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.5.4 (1559)

**Comment by laurencedawson** [comment]
Fixed for the next release.
