### ISSUE TITLE
[BUG] Sports Mode not working

### ISSUE THREAD

**Issue by TexasTibab** [laurencedawson/sync-for-reddit#1226]
**Describe the bug**
Starting Sports Mode shows only a blank page. 

**To Reproduce**
1. Go to a post. 
2. Click on Start sports mode in the Comment Actions menu. 
3. Blank page

**Expected behavior**
I expected to see the post with auto-refreshing comments. 

**Screenshots**
![Screenshot_20220507-151206_Sync Pro](https://user-images.githubusercontent.com/8116769/167270325-220baf9f-7063-402e-9e24-80c9454b938b.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra 5G
 - OS: Android Version 12
 - Browser: Sync
 - Version v22. 5.4 (1559)

**Additional context**
I reproduced this error in game threads in r/LonghornNation and r/nba

**Comment by laurencedawson** [comment]
This has been fixed for the next build. Cheers.
