### ISSUE TITLE
[BUG]"Subscribe to Ultra" button looks disabled with some themes

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#1246]
**To Reproduce**
Set a theme like purple or grey

**Screenshots**

![Screenshot_20220513-171908_Sync Dev.png](https://user-images.githubusercontent.com/55349349/168277444-9d4bd126-a9ff-482a-b522-83bff9962823.png)

**Additional context**
Maybe blacklist all shades of grey from that button or something?

**Comment by laurencedawson** [comment]
Switched to a brighter tone for the next release.

Thanks for the report!
