### ISSUE TITLE
[BUG]Inconsistency is displaying usernames in the subreddit selector

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#1248]
**Describe the bug**
Following a user shows the username as - "u_ljdawson" in the Following section of the list

Favoriting a user shows the username as - "ljdawson" in the favourites section of the list

**To Reproduce**
1. Favorite u/mark
2. Follow u/david

Check subreddit Selector list 

**Expected behavior**
Should be same both places

![Screenshot_20220513-173328_Sync Dev.png](https://user-images.githubusercontent.com/55349349/168279444-e385c858-7714-4e05-9ae0-2ad1b54084a0.png)

![Screenshot_20220513-173339_Sync Dev.png](https://user-images.githubusercontent.com/55349349/168279457-57698332-4a10-4afc-981d-5510aaeea030.png)

**Comment by laurencedawson** [comment]
Fixed.
