### ISSUE TITLE
[BUG] Inconsistency displaying user profiles in subreddit Selector list

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#1249]
**Describe the bug**
Favouriting a user doesn't display the pfp of the user in the list. Instead it displays the user of the subreddit by the same name

Following a user doesn't display any pfp at all. Just displays "r"

**Comment by laurencedawson** [comment]
Can't reproduce.

**Comment by laurencedawson** [comment]
Fixed.
