### ISSUE TITLE
[Suggestion] Replace comments "Done" Icon with Send

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#125]
Send Icon

https://cdn.discordapp.com/attachments/685907412146061339/718331155585433650/1988.png

Current Icon

https://cdn.discordapp.com/attachments/685907412146061339/718331155337707620/1986.png

**Comment by skff-err** [comment]
it's a small nitpick but i think the icon we have in the app looks weird

**Comment by laurencedawson** [comment]
Added for the next release.
