### ISSUE TITLE
[BUG] "Open in new window" does not work on select devices

### ISSUE THREAD

**Issue by Code027** [laurencedawson/sync-for-reddit#1250]
**Describe the bug**
Opening a new window only redirects to the subreddit and it does not show up in Recents as a separate window.

**To Reproduce**
1. Go to Explore.
2. Click on 3-dot menu then "Open in new window" in any subreddit.
3. Go to recents

**Expected behavior**
Action should open as its own window

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: vivo 1906
 - OS: Funtouch OS 10.5
 - Browser: Brave
 - Version 22.5.4

**Additional context**
As I've only observed the issue in the mentioned device, it could also mean that it's an OS issue which may not be a Sync problem.

**Comment by laurencedawson** [comment]
I've tested on 5 devices and 2 emulators and I'm unable to reproduce this.
