### ISSUE TITLE
[BUG] Toggle account no longer switches to Anonymous Account 

### ISSUE THREAD

**Issue by AlanMW** [laurencedawson/sync-for-reddit#1251]
**Describe the bug**
Tapping "Toggle Account" from the actions tool bar no longer switches to an existing anonymous account like it used to. 

**To Reproduce**
1. Bring up the "more actions window"
2. Press toggle account
3. Get the error message, " You need two accounts to toggle! "

**Expected behavior**
Switch to anonymous account, or switch from anonymous account to signed in account

**Screenshots**
N/a

**Smartphone (please complete the following information):**
 - Device: Galaxy S10 
 - OS: Android 12,
 - Browser: Chrome for Android
 - Version 22.5.13

**Additional context**

**Comment by bohrabhijeet** [comment]
This is an intended behaviour since v22.4.20.
