### ISSUE TITLE
Fixed page numbers

### ISSUE THREAD

**Issue by TexasTibab** [laurencedawson/sync-for-reddit#1252]
**Is your feature request related to a problem? Please describe.**
I try to keep my scrolling limited by page numbers, but as they are I often miss the page breaks and scroll longer than I want to. 

**Describe the solution you'd like**
I would like to have an option allowing users like me to choose to have the page numbers stay at the top of the screen as you scroll so that I can check what page I am on at any time.

**Comment by laurencedawson** [comment]
No plans to add this one I'm afraid.
