### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Amby713** [laurencedawson/sync-for-reddit#1258]
[BUG] Sample title
---
I've noticed this issue for a few months now, not localized to the current build, but about all the builds in at least 6 months.

I'll browse /r/all  and read a few pages. When i share a link/image to external apps and come back, sync shows Frontpage  cause me to lose my place in /r/all. This doesn't happen on just all, but any sub I browse. Also, it's not limited to sharing, but also hitting the home button on my phone to use other apps.

It's very annoying because I constantly lose my place and have to go back and then scroll past everything I already viewed.
I hope this makes sense, if not, lmk and I'll try to better explain it

**Scenario** (steps to reproduce)**
1. Browse a sub and scroll through a few pages
2. Share link on external app

**Result(s)**
Sync goes back to Frontpage leaving the sub I was in causing me to lose my place. 

**Device information**

    Sync version: v22.5.13    
    Sync flavor: pro    
    
    View type: Cards    
    Push enabled: false    
    
    Device: apollo    
    Model: Xiaomi M2007J3SY    
    Android: 11

**Comment by laurencedawson** [comment]
Can't replicate this.

**Comment by laurencedawson** [comment]
Closing (stale issue).
