### ISSUE TITLE
[BUG] "paint user" feature uses case-sensitive match for usernames

### ISSUE THREAD

**Issue by PATXS** [laurencedawson/sync-for-reddit#1263]
**Describe the bug**
if you open a user's profile page by typing their name in, ultra's "paint user" option does not work unless you matched reddit's exact capitalization on their name.

**To Reproduce**
1. try opening the profile for user "LJDawson"
2. click on "paint user" chip and select a color
3. refresh, should see that it did not work
4. try opening the profile for user "ljdawson" instead (leads to the same account). doing it there should work.

**Expected behavior**
the option should paint the target user even if their username case isn't an exact match.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G UW
 - OS: Android 11, OneUI 3.1
 - Browser: Kiwi Browser
 - Version: free v22.5.16

**Comment by laurencedawson** [comment]
Fixed for the next release
