### ISSUE TITLE
[BUG] Text space formatting doesn't match the official client

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1264]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/uohqoy/text_spacing/

**Screenshots:**
<p float="left">
  <img src="https://user-images.githubusercontent.com/34155181/168788592-6a4ae123-9628-42b6-a6a1-98c9cabaf192.jpg" width="241" />
  <img src="https://user-images.githubusercontent.com/34155181/168788599-710fd1f5-dd25-43cb-8271-3672d2d9294d.jpg" width="241" />
</p>

**Comment by laurencedawson** [comment]
Fixed for the next release.
