### ISSUE TITLE
[REQUEST] Larger touch targets

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1267]
**Requested here:** 
https://www.reddit.com/r/redditsync/comments/up32di

> Currently, the click boxes for user profiles and subreddits are extremely small. Same goes for the comment button, the 3-dot menu and most other elements.
> My accuracy is not amazing and it would be nice if these elements were easier to click.

**Comment by laurencedawson** [comment]
These are 48dp the recommended size by Google.
