### ISSUE TITLE
[BUG] Visual glitches when use with split screen

### ISSUE THREAD

**Issue by Jnss98b** [laurencedawson/sync-for-reddit#1270]
**Describe the bug**
System bars are opaque when sync is used in split screen mode with another app. In addition to that, the status bar also turns white with status icons stay white

**To Reproduce**
1. Open the app
2. Initiate split screen with any other app
3. To best see the bug, rotate the screen to landscape. The bug also does show up in portrait orientation with the status bar when the app is on top or with the gesture bar when the app is at the bottom

**Expected behavior**
System bars should behave normally like when the app is used outside of split screen

**Screenshots**
_Disregard the black bar on the left side. My device has a punch hole cutout and since sync doesn't have notch support in landscape, it's letterboxed like that._

Sync in split screen:
![Screenshot_20220517-064704](https://user-images.githubusercontent.com/24306400/168804103-6fd9f8af-7681-4325-b2bc-a2313d9f0c0c.png)

Sync without split screen:
![Screenshot_20220517-065439](https://user-images.githubusercontent.com/24306400/168805171-790f926d-55c6-436c-a2e8-98969d08d66a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12.1/12L May 2022 patch
 - Version Dev v22.5.13

**Comment by laurencedawson** [comment]
Fixed for the next release.
