### ISSUE TITLE
[BUG]  Left drawer doesn't work if app is opened in split screen.

### ISSUE THREAD

**Issue by Hyperfrost1** [laurencedawson/sync-for-reddit#1273]
[BUG] Left panel doesn't work if app is opened in split screen.

Left panel doesn't work if app is opened in split screen. Sample description body

Scenario (steps to reproduce)** 
1. Have an app open (any app works) 
2. Open Sync in split screen. (In my case I opened from edge panel) 
3. Try to use the left sliding panel (not sure what the name is)

Result(s) Left panel doesn't respond to touches.

https://youtu.be/ZOkxIDp3cZI Video of bug in action.

Device information

Sync version: v22.5.17    
Sync flavor: free    
Removed ads: true    

View type: Slides    
Push enabled: true    

Device: q2q    
Model: samsung SM-F926B    
Android: 12

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/588
