### ISSUE TITLE
[BUG] Video crashes Sync app on Android 13 Beta 2, works fine in Firefox

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1275]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/uq663i

**Comment by bohrabhijeet** [comment]
Another one:
https://www.reddit.com/r/redditsync/comments/v4nqi5

**Comment by laurencedawson** [comment]
This has since been fixed.
