### ISSUE TITLE
Open in browser option in username bottom sheet produces error

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#1281]
**Describe the bug**
Upon long pressing the username, we are presented with three options. Of those three, the open in browser option causes an error. 

**To Reproduce**
1. Long press user name
2. Click open in browser
3. Hmmmmmm

**Expected behavior**
It should _open in browser_

**Screenshots**
![Screenshot_2022-05-19-00-07-37-396_com.laurencedawson.reddit_sync.dev.jpg](https://user-images.githubusercontent.com/3417276/169120330-94e99a65-946c-4bf1-87bd-3309fbd1f667.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10s
 - OS: A11
 - Browser: chrome
 - Version: v22 dev internal

**Comment by laurencedawson** [comment]
Fixed for the next release.
