### ISSUE TITLE
[BUG] Experimental discord style drawer collapses abruptly in landscape mode.

### ISSUE THREAD

**Issue by Fizwizjiz** [laurencedawson/sync-for-reddit#1282]
**Describe the bug**
With Experimental discord style drawer enabled, the drawer menu abruptly collapses when trying to access the 3 dot menu of each subreddit when the app is in landscape mode.

**To Reproduce**
1. Enable Experimental discord style drawer
2. Turn device/app to landscape mode
3. In the drawer, scroll down to a listed subreddit and try to open a 3-dot menu on the right side of the subreddit

**Expected behavior**
It should open the menu instead of collapsing the whole drawer

**Screenshots**
Video of the occurance: https://i.imgur.com/G3cHXzT.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 -  OS: Android 12 

    - Build Number: SP2A.220505.002
    - Android Security Update May 5 2022
    - Google Play System Update May 1 2022

 - Browser: Kiwi Browser
 - Version: 101.0.4951.40

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/588
