### ISSUE TITLE
[BUG] The app is suddenly crashing since the last update

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1284]
https://www.reddit.com/r/redditsync/comments/usrjxb

> I'm using the app as usual and boom, it crashes. No idea why it happens, i can't replicate it voluntarily but it happens quite often.

> **Device information**
> Sync version: v22.5.18    
> Sync flavor: free    
> Removed ads: false    
> View type: Slides    
> Push enabled: false    
> Device: cannong    
> Model: Xiaomi M2007J22G    
> Android: 11

**Comment by laurencedawson** [comment]
Fixed.
