### ISSUE TITLE
[Enhancement] Error subfolder doesn't exist when saving images after offloading my saved pics

### ISSUE THREAD

**Issue by agret** [laurencedawson/sync-for-reddit#1293]
**Is your feature request related to a problem? Please describe.**
I like to save my images in a somewhat organized fashion by enabling the "create subfolder for each subreddit" feature which works great. Since my phone has limited storage every month or two I'll connect it to my PC and move the entire reddit_sync saved images folder to my PC which has TBs of storage space.

After moving the reddit_sync folder to my computer, going back to the app and trying to save an image brings up an error that says "error subfolder doesn't exist anymore" and it has a button prompt to retry creating the folder. Why does this happen? Please just make sync automatically attempt recreating the folder and only raise this error if it fails after the first try.

**Comment by bohrabhijeet** [comment]
> and move the entire reddit_sync saved images folder to my PC 

Are you copying them? If not, I suggest you copy the contents instead of moving (cutting & pasting) them.

Due to Android's new storage access implementation, Sync can't access the entire internal storage so it fails to read the folder name and prompts you to create a new one.

**Comment by agret** [comment]
I'm moving them not copying, I do it from inside the reddit_sync folder so it still has full access to create them otherwise pressing retry wouldn't work. It doesn't bring up an OS prompt, just a Sync prompt so it could be handled transparently in the background.

Copying them from the phone wouldn't clear up my phone storage as all the files will still be there. I go into Pictures then reddit_sync then do CTRL+A and move to my PC which deletes all the subfolders. Sync can recreate them if it wanted to but it just brings up a prompt, my suggestion is to first just have sync try to create it rather than auto assuming there is a problem with the file access and if it fails only then raise the prompt.

**Comment by bohrabhijeet** [comment]
Let's say you create a folder within _/Internal storage/Pictures/reddit_sync_ when you download media for the first time, and grant access to it. 

Sync will have access to **only** the _reddit\_sync_ folder. Once you delete the said folder's existence, Sync can't do anything but prompt you to create a new folder. 

The storage access is not being handled by Sync, but Android so automatically creating a new folder wouldn't be possible, because again, Sync can't access the internal storage.

**Comment by bohrabhijeet** [comment]
Also, this is an on-going discussion on https://github.com/laurencedawson/sync-for-reddit/issues/1178 

Closing this ticket

**Comment by agret** [comment]
`Once you delete the said folder's existence, Sync can't do anything but prompt you to create a new folder.`

On my phone it brings up the prompt saying that it no longer exists so it can't save the media, if I just press retry on that prompt that displays it will do create the folder and then save. Maybe something has changed on future Android versions, I'm on Android 10 so might need a version check in this function.

Seems that linked issue is unrelated

**Comment by geominorai** [comment]
See the ongoing discussion in issue #1177.
