### ISSUE TITLE
[REQUEST] Would it be possible to ‘Disable Inbox Replies’ on comments by default as an option?

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1297]
https://www.reddit.com/r/redditsync/comments/utcdyh

> Hello, I was wondering if it would be possible to have an option to Disable Inbox Replies by default on submitted comments.

> I'm one of those who dislike having my inbox be filled with replies to comments I've made. While I know we can disable Inbox Replies after a comment submission, I was wondering if we could have an option to Disable it by default.

**Comment by laurencedawson** [comment]
No plans to add this.
