### ISSUE TITLE
[BUG] Sync Pro not loading most gifs/images/videos

### ISSUE THREAD

**Issue by MPritsch** [laurencedawson/sync-for-reddit#1304]
**Describe the bug**
Sync the last 2 updates Sync Pro has a difficult time loading gifs/images/videos. This happens for previews as well as upon clicking the content. It doesn't seem to be restricted to certain pages or subreddits but mostly happens on "all".
This only affects the Pro version. The free version loads the same things flawlessly. After clearing the cache of the app, the previews load again, but won't load the (long hold) preview or the content itself when being clicked.

**To Reproduce**
1. Go to "all"
3. Click on any/a few video/gif post
4. Wait for it to load and see "Error: This request has timed out"

**Expected behavior**
Previews and content of gifs/images/videos should load properly in the Pro version of sync, just like the free version.

**Screenshots**

Here is the error, when a preview or video can't be loaded:
![Error: This request has timed out](https://user-images.githubusercontent.com/15358778/169696050-4ebea28b-280e-41aa-8010-dbe849c03f7d.jpg)
Note that the same post loaded fine in the free version. I'll spare the screenshot of that.

Here is how the page looks like when most post previews can't be loaded:
![Preview of gifs/images/videos](https://user-images.githubusercontent.com/15358778/169696081-696e3507-c309-4d20-bd46-ce67b7c63a93.jpg)

Here is the free version loading the same posts fine
![Free version loading fine](https://user-images.githubusercontent.com/15358778/169696095-ee8c9740-4fd7-4088-a737-2569a1f4e9bb.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Oxygen OS 12 (last update of 5. April 2022). Build-Number LE2113_11_C.48
 - Browser: (do you mean WebView for android?) Android System WebView 101.0.4951.61
 - Version of Sync (Free) and Sync Pro: v19.0.21

**Additional context**
This seems to happen to aprox. 80% of my posts. Some load fine, but most won't load at all or take much longer than in the free version. Upon restarting the app and clearing the cache, some of these will load again, but not all. I don't have any bandwidth limiters installed.
Switching between WLAN and Mobile Data doesn't seem to affect anything.

**Comment by laurencedawson** [comment]
V19 is about to be replaced with v22 which should fix this issue.

If you'd like to try it now you can hop in the beta:

- [Pro beta signup](https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync.pro)

- [Free beta signup](https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync)
