### ISSUE TITLE
[REQUEST] "No more posts were loaded" Auto refresh

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1307]
https://www.reddit.com/r/redditsync/comments/uukv61

> Hey guys, every so often I get a message when scrolling at the bottom that says "no more posts were loaded" or something to that effect. I have to tap retry in the banner for it to load any new posts and to resume scrolling. Is there an option for it to just auto do it? Thanks!

**Comment by laurencedawson** [comment]
IMO this is not something that should be automatic.
