### ISSUE TITLE
[REQUEST] Inline link previews should show the link, not the text, when referencing a hyperlink

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1308]
https://www.reddit.com/r/redditsync/comments/uumgup

> Noticed that comment link previews in some instances show just the text of hyperlinks, which kinda defeats the purpose. Here's an example:
>
> https://www.reddit.com/r/AskReddit/comments/uub8e9/_/i9emxrl
> 
![image](https://user-images.githubusercontent.com/34155181/169824765-73f05c16-9af3-458c-a99c-b2a3be69c437.png)

**Comment by laurencedawson** [comment]
Definitely. 

Fixed for the next release.
