### ISSUE TITLE
[BUG] This link opens in a Chrome Custom Tab instead of Sync

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1309]
https://www.reddit.com/r/redditsync/comments/uux23o

> [It shows a mature content warning and opens to a chrome custom tab instead of sync](https://i.imgur.com/pHuRsKg.png)

Link to the comment in question:
https://www.reddit.com/r/19684/comments/uuotwn/comment/i9h2j2a/

**Comment by laurencedawson** [comment]
Fixed.
