### ISSUE TITLE
[REQUEST] An option to delete a comment when viewing your comments (from Profile)

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1311]
https://www.reddit.com/r/redditsync/comments/uvca74/

> without having to open the link for each comment, then clicking '...' > 'Delete comment'
>
> Like kind of on the desktop website, here there are no options to edit comment without opening the comment in the thread

**Comment by laurencedawson** [comment]
Added for the next release.
