### ISSUE TITLE
[BUG] Some YouTube links get by the Content Filters

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#1316]
![Screenshot_20220523-200259](https://user-images.githubusercontent.com/24947579/169924222-271dddf6-dcf6-4cb5-93a2-a5cbac96ec20.png)

![Screenshot_20220523-200301](https://user-images.githubusercontent.com/24947579/169924242-550f098d-fed9-4b7d-aa98-2ac984d1d5c1.png)

**Comment by laurencedawson** [comment]
Fixed.
