### ISSUE TITLE
[ENHANCEMENT] Change search suggestions strings

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1320]
I suggest changing these strings to
```
- Open u/<term>
- Open r/<term>
```

![Screenshot_20220525-194126_Sync_Dev2.png](https://user-images.githubusercontent.com/34155181/170290534-4e577507-15f2-4bcd-a072-2acc888d9c22.png)

**Comment by laurencedawson** [comment]
Done.
