### ISSUE TITLE
[BUG] [ULTRA] Restored comments can't be translated

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1324]
**Describe the bug**  
The translate option is absent in a restored comment's actions

**Steps to Reproduce**  
1. Restore a deleted comment
2. Tap on three dots
3. Translate option is absent

**Expected behavior**  
Translate should be visible

**Video**  
https://user-images.githubusercontent.com/34155181/170522330-d7d91da6-42cb-45d8-8253-3d6822368707.mp4

**Smartphone (please complete the following information):**
```    
    Sync version: v22.5.26    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 12
```

**Link to the comment in question**
https://www.reddit.com/r/MorbidReality/comments/uvlrgy/_/i9nh37o

**Comment by laurencedawson** [comment]
This was actually due to translate not being available on NSFW posts.

I've added a toast to alert the user.
