### ISSUE TITLE
[BUG] [ULTRA] Tapping on an Ultra setting deeplink shows "Ultra is in closed testing..." bottom sheet

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1326]
**Describe the bug**  
Pretty much the title

**Steps to Reproduce**  
1. Copy and paste Tags' Ultra shortcut in comments
2. Tap on it
3. See error

**Expected behavior**  
Sync should open the corresponding setting

**Video**  
![screen-20220527-150131_exported_8595.jpg](https://user-images.githubusercontent.com/34155181/170673492-6d34914e-113c-4fbd-8ac1-839bc3ab9219.jpg)

**Device information**
```
    Sync version: v22.5.26-22:34    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 12
```

**Comment by laurencedawson** [comment]
Fixed.
