### ISSUE TITLE
[BUG] Setting Restore not using other Backups. 

### ISSUE THREAD

**Issue by WesTechNerd** [laurencedawson/sync-for-reddit#1328]
If I backup the settings for the pro app on another device the app from the current device will not recognize the backup. It will only show backups from that current device as available for restore. Transfer fails both ways.

**Steps to Reproduce**  
1. Backup from original device
2. Copy over to new device over cloud
3. Select the folder containing the backup
4. Click on restore, no option to restore unless I run a backup from the same device. 

**Expected behavior**  
It should give you to option to restore from another backup. 

**Screenshots**  
![Screenshot_20220527-114325](https://user-images.githubusercontent.com/7519777/170733506-dc8efd75-813d-4f18-9e0c-58138760795b.png)
![Screenshot_20220527-114359](https://user-images.githubusercontent.com/7519777/170733571-50de3e4f-a32a-404b-ade3-e17d358da932.png)

**Smartphone:**
 - Device: Pixel 5a and Samsung Tab A
 - Android: 11, 12
 - Sync version: 19.0.21
 - Sync variant: pro

**Comment by laurencedawson** [comment]
Rename .json to . txt
