### ISSUE TITLE
[BUG] Gfycat links with text are not embedding or missing domain info

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1329]
**Describe the bug**  

Gfycat links, if used in a link with custom text (e.g. `[Text](https://gfycat.com/horriblesilentincatern)`, will neither embed or show the URL domain in round brackets after it like regular external links.

**Steps to Reproduce**  

1. See comment at https://www.reddit.com/r/space/comments/uxtu9x/_/i9zztzx

**Expected behavior**  

If an image embedding within the comment after the link text is not consistent or doable, then it should either display under the comment as an image link preview (like for Imgur) or show the URL domain in round brackets after the link text like any regular external link.

**Screenshots**  

<img src="https://user-images.githubusercontent.com/13911156/170739308-b04f37d6-75dd-4e88-9fdc-4ddfc53b91e6.png" width=250px />

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.5.27-13:12 (1608)

**Comment by laurencedawson** [comment]
Fixed for the next release.

![gfy](https://user-images.githubusercontent.com/534059/173195182-9724af09-a2b8-43a0-96e2-46d9572283ad.png)
.
