### ISSUE TITLE
Manual Main Monet Theming Subtext does not update after color change

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#1330]
**Describe the bug**  
Under the main theme selector, there is the current colour subtext; this subtext does not update after a change in colour, even though the current colour is different. 

**Steps to Reproduce**  
1. Go to Theme Management 
2. Click on Manual Theming, 
3. Change Main Monet Theme 
4. See subtext unchanged

**Expected behavior**  
The subtext should be updated to the new current colour

**Screenshots**  
https://user-images.githubusercontent.com/3417276/170761454-25b70975-5b4e-40f8-a7bf-f8f52782a91a.mp4

![IMG_20220527_225202.jpg](https://user-images.githubusercontent.com/3417276/170761644-4bfdd3c0-0d7b-42b3-8da5-7cefa56df5f9.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 10S
 - Android: 11
 - Sync version: v22.5.27
 - Sync variant: dev

**Comment by laurencedawson** [comment]
Fixed!
