### ISSUE TITLE
[ENHANCEMENT]  Give Awards

### ISSUE THREAD

**Issue by madscribbler** [laurencedawson/sync-for-reddit#1332]
**Is your feature request related to a problem? Please describe.**  
Cannot give awards.

**Describe the solution you'd like**  
When on a post or reading comments, provide the ability to award the post or comment 

**Describe alternatives you've considered**  
Right now I have to use the desktop client which makes it a bummer every time I find I'm on sync for Reddit because I can't award from my phone

**Additional context**  
I've paid for ultra and would be happy with this being an ultra only feature, I think it adds a lot of value and would be compelling reason for upgrading to ultra.

**Comment by laurencedawson** [comment]
Unfortunately this is outside the scope of sync as it's not something reddit have made available to third party devs.
