### ISSUE TITLE
[BUG] Video does not autoplay when scrolling with a mousewheel

### ISSUE THREAD

**Issue by amasover** [laurencedawson/sync-for-reddit#1333]
**Describe the bug**  
I have a bluetooth mouse connected, and videos do not autoplay when I scroll down with the mouse wheel. But if I scroll down with the touchscreen, instead of with the mouse, I can see that the autoplay works correctly.

**Steps to Reproduce**  
1. Connect a mouse
2. Scroll down with the mousewheel and see if videos play or not

**Smartphone (please complete the following information):**
 - Device: Pixel 5a
 - Android: 12.1
 - Sync version: v22.5.28
 - Sync variant: free with ads removed

**Comment by laurencedawson** [comment]
Fixed for the next release.
