### ISSUE TITLE
[BUG] code blocks not formatted correctly 

### ISSUE THREAD

**Issue by kzshantonu** [laurencedawson/sync-for-reddit#1336]
Expected to look like [this](https://user-images.githubusercontent.com/7745374/170897343-975eee76-dc27-42b5-bfe1-dd7d009ea925.jpg) but looks like [this](https://user-images.githubusercontent.com/7745374/170897393-e62c25dd-d4e7-4b87-8e4d-0260ecc500aa.jpg) instead

**Comment by laurencedawson** [comment]
Do you have a link to the post?

**Comment by laurencedawson** [comment]
[OK found the post in question](https://www.reddit.com/r/selfhosted/comments/v0avy7/some_quick_aliases_to_save_you_some_time/) and it was formatted incorrectly.

Formatted correctly it will look like this:

![code](https://user-images.githubusercontent.com/534059/173187941-3620580a-9c41-4261-974c-b88bbeaa3ead.png)

However multi line code didn't look great so I've changed that too for the next release.
