### ISSUE TITLE
[BUG] Mute/Unmute button absent from Imgur & Gfycat domains

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1337]
Reported here:
https://www.reddit.com/r/redditsync/comments/uzn6jk/_/iai7ss6
> I was just looking at the new v22 and noticed that the video player doesn't have the volume button like it did in v19 in the feed. you have to tap on the video to open it to hear sound. is there a setting that I'm missing or was it not added?
> 
> I didn't see a setting for it so I'm not sure if it's a bug or not.

**Comment by laurencedawson** [comment]
Reddit previews always acted this way.

Added audio support to Gfycat + Redgifs in the next release:

https://github.com/laurencedawson/sync-for-reddit/issues/827
