### ISSUE TITLE
[BUG] ‘Glide failed to grab this image’ error for files.catbox.moe domain

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1342]
Reported here:
https://www.reddit.com/r/redditsync/comments/v10y8g
> Every time I try to open an image from this site, it says "glide failed to grab this image"
>
> [Example post NSFW](https://www.reddit.com/r/hentaicaptions/comments/o3zg91/_/)

**Comment by laurencedawson** [comment]
Not a sync issue. 

The server is failing when attempting to connect.

**Comment by katherinehackworth** [comment]
It always loads when I open the link in chrome though. Is it possible that there is an incompatibility with the image request from glide?

**Comment by laurencedawson** [comment]
It works if I change the user agent so it's them specifically blocking these kinds requests.

I'd add to the external sites list if I were you

**Comment by laurencedawson** [comment]
Feels a little dodgy to spoof user agent in syncs case

**Comment by katherinehackworth** [comment]
What's the user agent sync self reports?

**Comment by laurencedawson** [comment]
I'm using okhttp so just the default user agent for that.
