### ISSUE TITLE
[ENHANCEMENT] Option to remove submit link button

### ISSUE THREAD

**Issue by Vinhcognito** [laurencedawson/sync-for-reddit#1344]
Most people will never need to submit a link and the submit link button does get in the way sometimes when scrolling.

Please add an option to remove the submit link button.

![IMG_20220531_142600](https://user-images.githubusercontent.com/48443988/171262292-b7c7ef6f-b847-4491-abb6-da051dff0d1a.jpg)

**Comment by laurencedawson** [comment]
Settings > General > Show FAB
