### ISSUE TITLE
[BUG] Hide Read button hides posts from subs you aren't actively looking at

### ISSUE THREAD

**Issue by alexrmay91** [laurencedawson/sync-for-reddit#1345]
**Describe the bug**  
I have the FAB configured to hide all read posts. When clicking this button, it will hide read posts from subreddits/pages that I'm not actively looking at. This behavior is different from the previous V19!

**Steps to Reproduce**  
1. Go to any subreddit
2. Click on some posts to mark them as read
3. Go to any other subreddit
4. Hide read posts
5. Go back to subreddit from step 1, posts previously clicked on are gone

**Expected behavior**  
I expect to only hide posts from the view I'm currently looking at. If I want to hide posts on a specific subreddit (or not), I can do it after I finish browsing and before I switch away. This is the behavior of V19.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android: 12
 - Sync version: v22.5.29-22:36 (1622)
 - Sync variant: Pro

**Comment by laurencedawson** [comment]
Hide read specifically hides ALL that you have read. This was requested during development and was confusing in v19.

Closing as I think this is the correct behaviour.

**Comment by alexrmay91** [comment]
Man that's a bummer. I really dislike the new behavior.
