### ISSUE TITLE
[Bug] Youtube thumbnails not loading in certain subreddit feed, only loads after opening the thread.

### ISSUE THREAD

**Issue by p-patra** [laurencedawson/sync-for-reddit#1347]
**Describe the bug**  
Youtube thumbnails not loading in certain subreddit feed, only loads after opening the thread.

Update: The thumbnails loading while I'm on anonymous mode but not while logged in. 

**Steps to Reproduce**  
1. Go to r/music
2. Look for any Youtube links. You'll see blank thumbnails.
3. Continue to open any post where thumbnail is blank, now it will load the thumbnail. 

**Expected behavior**  
Youtube thumbnails should load as usual. 

**Screenshots**  
![Screenshot_20220601-115136_Sync Pro.png](https://user-images.githubusercontent.com/106650211/171340923-60a3f79e-10d2-438c-93d6-714ffe5b86fc.png)

**Smartphone (please complete the following information):**

 **Device information**
Sync version: v22.5.31-22:32    
Sync flavor: pro    
Ultra user: true    
View type: Slides    
Push enabled: false    
    
Device: r8q    
Model: samsung SM-G781B    
Android: 12

**Comment by laurencedawson** [comment]
Unable to reproduce. I'm pretty sure this is just a network issue your end,.

**Comment by laurencedawson** [comment]
Switched to using Youtube previews directly.
