### ISSUE TITLE
[ENHANCEMENT] Subreddit watch notification should take us to sorted by new page. 

### ISSUE THREAD

**Issue by p-patra** [laurencedawson/sync-for-reddit#1353]
**Is your feature request related to a problem? Please describe.**  

When subreddit watch is enabled for a cetain subreddit upon clicking on notification it takes us to "Hot" or any default page. But it should take us to "New" page.  (Sorted by new upon clicking on notification)

**Describe the solution you'd like**  

App should take us to sorted by new page upon clicking on notification.

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/910
