### ISSUE TITLE
[BUG] Posts are marked as read on reload

### ISSUE THREAD

**Issue by alexrmay91** [laurencedawson/sync-for-reddit#1359]
**Describe the bug**  
Posts get marked as read when reloading a page. Not when clicked on or when they scroll off the screen.

**Steps to Reproduce**  
1. Go to a subreddit/page with no posts marked as read/greyed out
2. Swipe down to reload multiple times
3. Posts will start to be marked as read

**Expected behavior**  
Posts should only be marked as read when viewed in some way or when they are scrolled off the top of the screen.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android: 12
 - Sync version: v22.5.29-22:36 (1622)
 - Sync variant: Pro

**Additional context**  
I frequently use the "hide all" function to manage my browsing. This causes me to hide posts I have not seen yet or skip over posts I think I already saw. Whatever code was used in V19 to handle this worked fine. Combined with issue [#1345](https://github.com/laurencedawson/sync-for-reddit/issues/1345), it makes using the new app very frustrating.

**Comment by alexrmay91** [comment]
[I've recorded an example of this happening here.](imgur.com/a/0hszBGb)

After 6 reloads, 4 out of 7 of the visible posts are marked as read. It's actually worse than this because there are posts below that are also being marked as read, they just can't be seen in the video.

**Comment by laurencedawson** [comment]
If they're shown on screen I think this is the correct behaviour no?

**Comment by alexrmay91** [comment]
I thought the correct behavior (at least how it was in V19 and other reddit apps I've tried) is that the post must scroll off the screen to be marked as read. How it is now seems strange with seemingly random posts being marked on each refresh. I tend to jump around subs and /r/all a lot so it happens to me frequently.

**Comment by laurencedawson** [comment]
Reverted this behavior to match v19.
