### ISSUE TITLE
[BUG] Markdown errors

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1361]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/v36f0s
> Not sure if these are bugs or just changes, but I was browsing my comments and saw these two instances of markdown not displaying how I would expect.
> 
> [One](https://www.reddit.com/r/SubredditDrama/comments/nb3g41/_/gxx6nqz/?context=9) - On both versions of desktop, this comment displays a quote and then a double line quote. But on Sync the second quote is just added to the first line. Is it just that I now have to double space when doing multiple quotes now?
> 
> [Two](https://www.reddit.com/r/help/comments/uzklgo/_/iabih06/?context=9) - I escaped the first spoiler markdown because I was showing someone how to format the spoiler code, but Sync spoilers both things. On both versions of desktop the escaped spoiler isn't hidden. Did the escape notation change, or is it just something about spoilers?
> 
> **Device information**
> 
>     Sync version: v22.06.01-22:40    
>     Sync flavor: pro    
>     
>     Ultra user: false    
>     View type: Cards    
>     Push enabled: false    
>    
>     Device: bramble    
>     Model: Google Pixel 4a (5G)    
>     Android: 12

**Comment by laurencedawson** [comment]
Fixed for the next release.
