### ISSUE TITLE
[BUG] Remember Position option in subreddit selector doesn't work

### ISSUE THREAD

**Issue by ozy6724** [laurencedawson/sync-for-reddit#1364]
The remember position option in the subreddit selector, in the three dot menu from the top right doesn't seem to work. 

It never remembers position and goes back to the top of the subreddit list. 

Sync v22.06.01-22:40

**Comment by kevina1234** [comment]
Same issue. Very frustrating when you're subbed too a lot of different subreddits.

**Comment by laurencedawson** [comment]
Fixed for the next release.
