### ISSUE TITLE
[BUG] Lag in some photo albums

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1367]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/v3nyms
> **Description**
> Lags when swiping pictures in album
> 
> **Scenario**
> 1. For an example, open the pics Album in this post https://www.reddit.com/r/rarepuppers/comments/v2opan?is_gallery=true
> 2. Swipe/change back and forth between the pictures
> 
> **Result(s)**
> Lags when swiping the pictures
> 
> **Device information**
> 
>     Sync version: v22.06.01-22:40    
>     Sync flavor: pro    
>     
>     View type: Cards    
>     Push enabled: false    
>     
>     Device: d2s    
>     Model: samsung SM-N975F    
>     Android: 12
>     Gallery DPI: auto

**Comment by laurencedawson** [comment]
DPI was set to auto. Needs to be 200.
