### ISSUE TITLE
[BUG] Disabling Inbox replies on submitted posts keeps enabling the notification on every tap

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1369]
**Description**
Just the title

**Device information**

    Sync version: v22.06.02-23:48    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 12

**Comment by laurencedawson** [comment]
Huh?
