### ISSUE TITLE
[ENHANCEMENT] Gif support in comments

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#1373]
**Is your feature request related to a problem? Please describe.**  
Just an enhancement 

**Describe the solution you'd like**  
Having a way to add gifs in text fields. Comments and selftext(if that is possible) 

Solution - https://discord.com/channels/684912692485554230/799399306775887926/982624605602709584

**Comment by laurencedawson** [comment]
If you're using GBoard this is already an option. No plans to expand on this further.
