### ISSUE TITLE
[ENHANCEMENT] Disable top navigation 

### ISSUE THREAD

**Issue by incster63** [laurencedawson/sync-for-reddit#1374]
Most of the items in the toolbar are redundant, including the subreddit picker, the sort button, the about button, and the overflow menu. They are unnecessary when using bottom nav, drawer nav, or FAB nav.

The ability to disable these duplicated items would make the interface much cleaner and more modern looking.

**Comment by laurencedawson** [comment]
I think adding the option to change items in the toolbar would be great. But no plans to disable it all together, especially as it hides on scroll.
