### ISSUE TITLE
[ENHANCEMENT] Top sheets to replace bottomsheets

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#1381]
When bottomsheets should be shown at the top of the screen we should try to show a top sheet (similar to Google Chrome).

**Comment by laurencedawson** [comment]
How many times can one ticket get re-assigned lol.

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by katherinehackworth** [comment]
What if we don't like the top sheets tho? It feels less intuitive than the bottom sheets imo
