### ISSUE TITLE
[BUG] Unable to change flair on /r/ApexLegends

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#1387]
[Screen recording found here](https://drive.google.com/file/d/1wRk7pvvED-Jw7YEr4Wdb3Zf2ofkHiN16/view?usp=drivesdk)

 **Device information**

    Sync version: v22.06.03-19:50    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 12

Thank you!

**Comment by laurencedawson** [comment]
Still having this issue? I'm unable to reproduce it. Cheers

**Comment by Nxt3** [comment]
I'm able to change flairs now. Thank you! 😀

**Comment by laurencedawson** [comment]
Perfect cheers
