### ISSUE TITLE
[BUG] Sync not loading media on WiFi

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1389]
**Reported here**:
https://www.reddit.com/r/redditsync/comments/v5tjw4
> * Samsung Galaxy Fold 3
> * Ax6000 Router.
> * WiFi 6
> * Both 2.4 and 5 ghz bands.
> * Reset router/power cycled both router and modem
> * Uninstalled/reinstalled Sync **Pro**.
> * Restarted phone multiple times.
> * Reddit is fun/relay/Boost/etc all load gifs/pics/media just fine on wifi. 
> 
> * EDIT:
>  Changing DNS settings does nothing either. Tried 1.1.1.1 and both of Google's DNS
> 
> I'm at my wits end. It'll load media on mobile data/5g just fine. Refuses to load gifs/videos/thumbnails on wifi.

**Comment by laurencedawson** [comment]
Fixed for the next release.
