### ISSUE TITLE
[BUG] This video stutters and the progress bar "bounces"

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1390]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/v48a19
> https://www.reddit.com/r/TheDepthsBelow/comments/v3u8nu
> 
> The video stutters and the progress bar on this video "bounces" as it plays. This is the first time a video did that and other videos are playing normally
> 
> I have restarted sync and the video still does it
> 
> (First time reporting something here, I think I provided the correct info. Let me know if something is missing)
> 
> 
> This is a clip of the behavior:
> https://imgur.com/a/iN0viyn
> 
> 
> ---
> 
> **Device information**
> 
>     Sync version: v22.06.01-22:40    
>     Sync flavor: pro    
>     
>     View type: List    
>     Push enabled: false    
>     
>     Device: sunfish    
>     Model: Google Pixel 4a    
>     Android: 12

**Comment by laurencedawson** [comment]
Annoyingly the video has been taken down.
