### ISSUE TITLE
[ENHANCEMENT] File size for media

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1393]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/v4d5b6
> The new v22 is out and I'm enjoying it. However there's one little catch. In the old app when I'm opening a large photo or video, there's this indicator at the bottom showing how much the media size is. In the new version however, I don't see the indicator anymore. I find this feature useful due to data saving or not having to wait for the whole video/photo to load so I can skip and read another post.
> 
> Is there any way to restore this? Thank you.

**Comment by laurencedawson** [comment]
Still there if the image hasnt been cached already.
