### ISSUE TITLE
[REQUEST] Paste post URLs in search to open the post

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1395]
https://www.reddit.com/r/redditsync/comments/v54l2c
> V19 app had the open url from the 3dot menu on top right and easily accessible but I can't find it
> 
> I require it because reddit pages in browser sometimes don't show sync as option to open with and I have to manually open with the url

**Comment by laurencedawson** [comment]
Added for the next release.
