### ISSUE TITLE
[BUG] Video crashes when clicking on it

### ISSUE THREAD

**Issue by Mando2077** [laurencedawson/sync-for-reddit#1397]
**Describe the bug**  
App crashes when opening videos like in this post 
https://www.reddit.com/r/marvelstudios/comments/v67bwq

**Steps to Reproduce**  
1. Go to https://www.reddit.com/r/marvelstudios/comments/v67bwq
2. Click on the video

**Expected behavior**  
Video opens and app doesn't crash

**Smartphone (please complete the following information):**
 - Device: pixel 4xl
 - Android: 13
 - Sync version: v22.06.06-22:29
 - Sync variant: dev

**Comment by bohrabhijeet** [comment]
Known issue.
https://github.com/laurencedawson/sync-for-reddit/issues/1275
