### ISSUE TITLE
[ENHANCEMENT] Hide read front page posts on reload

### ISSUE THREAD

**Issue by Mando2077** [laurencedawson/sync-for-reddit#1398]
I've seen a few posts about this on the subreddit but I'd really love the ability to automatically hide posts marked as read on the front page when the front page is refreshed. Right now posts that are read are grayed out. It would be amazing to have sync automatically hide these posts so that on reload, I don't have to scroll through all of them again.

**Comment by laurencedawson** [comment]
https://github.com/laurencedawson/sync-for-reddit/issues/741

Duplicate.
