### ISSUE TITLE
[BUG] Bottom sheet doesn't close after selecting sort method 

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#1403]
The bottom sheet neither gets dismissed nor updates the sorting chip.

Screen recording: https://drive.google.com/file/d/1xA3cEi3BBtO-5NpOecPMBwy2OfjnQzeI/view?usp=drivesdk

 **Device information**

    Sync version: v22.06.07-23:00    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 12

**Comment by bohrabhijeet** [comment]
The sort chip in the bottom sheet doesn't update either:
https://www.reddit.com/r/redditsync/comments/v8yfpl

**Comment by bohrabhijeet** [comment]
This was fixed.
https://github.com/laurencedawson/sync-for-reddit/issues/1428
