### ISSUE TITLE
[BUG] Opening this post (with a very long image embedded in selftext) causes a crash

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1404]
**Reported here:**
https://www.reddit.com/r/redditsync/comments/v76y4n
> **Description**
> For this post only the title is displayed when trying to open it. After some seconds the app closes.
> https://www.reddit.com/r/de/comments/v6s5ch/deutscher_cookiewahnsinn_%C3%BCber_290_partner_mit/ 
> 
> **Scenario (steps to reproduce)**
> 1. Try to open the post in any way ( via the link/ on the subreddit/..)
> 2. Wait
> 
> **Result(s)**
> App closes and when it is manually reopened the start screen is shown
> 
> **Device Info**
> 
> - Device Model - Pixel 5
> - Android Version - 12
> - Sync v22.06.01-22:40 (1630) - pro max
> 
> **Screenshot**
> https://abload.de/img/screenshot_20220607-2b0kmm.png

I can reproduce this.

**Device information**

    Sync version: v22.06.07-23:00    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: true    
    
    Device: OnePlus7    
    Model: OnePlus GM1901    
    Android: 12

Stack trace:
https://katb.in/exodufiqodo

**Comment by laurencedawson** [comment]
Fixed for the next release.
