### ISSUE TITLE
[BUG] Swipe mode cuts off but does not scroll long self-text posts

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1406]
**Describe the bug** 

In swipe mode, long self-text posts are cut off but cannot be scrolled to see more.

**Steps to Reproduce**  
1. Go to a sub with long self-text like https://www.reddit.com/r/ProRevenge/
2. Enable swipe mode from the actions menu

**Expected behavior**  

The self-text post should be scrollable and preferably also displaying a scrollbar.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.06.07-23:00 (22003)

**Comment by laurencedawson** [comment]
Fixed for the next release.
