### ISSUE TITLE
[BUG] Swipe mode fails to load images embeded in self-text posts

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1409]
**Describe the bug** 

In swipe mode, self-text posts that contain embedded images will not show the embedded image or an image preview and tapping to open them in the image viewer shows an error that glide has failed to grab the image.

**Steps to Reproduce**  
1. Go to a sub or profile with self-text posts containing embedded images
2. Enable swipe mode from the actions menu
3. Swipe to an affected post

**Expected behavior**  

Images should appear embedded like it were outside of swipe mode and tapping on one should successfully open the image in the image viewer.

**Screenshots**  

<img src="https://user-images.githubusercontent.com/13911156/172581730-e56265f5-9ef1-4352-b165-a304a43451b2.png" width=400 />

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.06.07-23:00 (22003)

**Additional context**  

Due to the sequential nature of swipe mode, finding an affected post is difficult.  At present, the example from the screenshot above can be found by swiping through the profile at https://www.reddit.com/user/hanr10 after wading through the blank slides caused by bug #1408.

**Comment by laurencedawson** [comment]
This has since been fixed.
