### ISSUE TITLE
[BUG] Swipe mode corrupts GIF image downloads

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#1410]
**Describe the bug** 

GIF images (hosted under the `i.redd.it` domain) downloaded while in swipe mode are saved as a single-frame still image in PNG format but with a GIF file extension.

**Steps to Reproduce**  
1. Go to a sub with GIFs such as https://www.reddit.com/r/animegifs
2. Enable swipe mode from the actions menu
3. Download an image

**Expected behavior**  

The original GIF image should be downloaded, assuming consistency with issue #304, or the MP4 version otherwise.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v22.06.07-23:00 (22003)

**Comment by laurencedawson** [comment]
Fixed for the next release.
