### ISSUE TITLE
[BUG] "Restore comment" option not visible

### ISSUE THREAD

**Issue by StuntHacks** [laurencedawson/sync-for-reddit#1412]
**Describe the bug**  
Even though I am subscribed to Ultra Yearly, the option to restore deleted comments does not appear in the comment menu. All other Ultra features work fine, and resetting and restoring the subscription does nothing.

**Steps to Reproduce**  
1. Subscribe to Ultra
2. Find a deleted comment
3. Open the comment menu
4. Despair

**Expected behavior**  
There should be an option to restore the deleted comment

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android: 12
 - Sync version: v22.06.07-23:00
 - Sync variant: Dev

**Comment by laurencedawson** [comment]
Was this the issue with language? Deleted was showing in German or something...

**Comment by StuntHacks** [comment]
@laurencedawson Oh, yes that could be it. [removed] is [entfernt] and [deleted] is [gelöscht] for me.

**Comment by laurencedawson** [comment]
Gotcha. Fixed.

**Comment by StuntHacks** [comment]
@laurencedawson It worked after the big update yesterday for a bit, now it doesn't work again.

Example comment: https://www.reddit.com/r/Minecraft/comments/ve9srn/so_i_made_a_thing_for_pride_month/icpdx1h/
