### ISSUE TITLE
[BUG] Copy title contains zero-width space at the end

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#1413]
**Describe the bug**  
When chosing the Copy... < Copy title option of a post, the copied text will end with a zero-width space.

**Steps to Reproduce**  
1. Go to a post
2. Click on the three dot menu
3. Select Copy...
4. Select Copy title
5. Paste the title somewhere
6. Move cursor to the end
7. Tap delete on keyboard
8. Nothing visbily happens
9. Tap delete on keyboard again
10. Last character will be deleted as expected

**Expected behavior**  
No zero-width space at the end

**Device information**

    Sync version: v22.06.07-23:00    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7Pro    
    Model: OnePlus GM1913    
    Android: 11

**Comment by laurencedawson** [comment]
Fixed for the next release.
