### ISSUE TITLE
[BUG] Comment swipe in landscape tablet mode doesn't show icons

### ISSUE THREAD

**Issue by Solus** [laurencedawson/sync-for-reddit#1415]
**Describe the bug**  
You can enable swipe actions to use on comments (upvote, downvote, save, etc.). When swiping, the corresponding action's icon should be shown in the "swiped" region (up arrow, down arrow, etc.). 
However, when using Sync on a tablet in landscape mode (i.e., in split view), the action icons aren't showing. Rather, only the background color is visible. 

**Steps to Reproduce**  
1. Enable comment swipe actions ([Settings shortcut: Comment options > Swipe comments for additional options](sync-settings://3-comment_swipe_actions))
2. Enable tablet mode ([Settings shortcut: Tablet > Tablet mode](sync-settings://30-tablet_mode))
3. Open a post, and swipe left on any comment. 

**Expected behavior**  
When swiping on a comment, an icon should be visible to the right of the comment, corresponding to the action that would happen. 

**Screenshots**  
This is how the swipe action currently looks. 
![image](https://user-images.githubusercontent.com/7745354/172779863-2f3a35f2-18f0-4ebf-ac12-1b1f3ef84356.png)

This is how it should look.
![image](https://user-images.githubusercontent.com/7745354/172780126-fb46b809-7d7a-41ab-a0f6-4a4ceaf22681.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S6
 - Android: 12
 - Sync version: v22.06.07-23:00 (22003)
 - Sync variant: pro

**Comment by laurencedawson** [comment]
Fixed for the next release.
