### ISSUE TITLE
[Fix] Post buttons need a bigger radius when tapping

### ISSUE THREAD

**Issue by oathzed** [laurencedawson/sync-for-reddit#142]
![Screenshot_20200605-234850](https://user-images.githubusercontent.com/52545913/83938763-2d91a080-a78c-11ea-9b8c-f5bc470a54f2.png)

These buttons need a bigger radius when tapping, I find myself accidently going into the post rather than upvoting or sharing it cause the radius to press is to small.

**Comment by JacobDB** [comment]
I absolutely agree on this, I've found myself accidentally tapping on the post constantly since I upgraded the app. Love the redesign, but this is incredibly annoying. Just invisibly expanding the tap area to include some space around each button would be a massive improvement.

**Comment by laurencedawson** [comment]
These have since been increased.
