### ISSUE TITLE
[ENHANCEMENT] Options for new version announcement

### ISSUE THREAD

**Issue by mcstafford-git** [laurencedawson/sync-for-reddit#1424]
The rate at which need versions are available seems to outpace Android automatic updates at times. I'm happy to update occasionally, but don't want it to be a daily part of using the app.

Maybe require a notice if the new version is flagged with urgency, or the installed version is several releases behind?

Thanks for a great product.

**Comment by laurencedawson** [comment]
You can disable the popup in the settings.

Things will be calming down a bit so closing this ticket as I don't plan to add additional granularity.
