### ISSUE TITLE
[BUG] Quick actions bottom sheet does not go back down automatically after sort update via contextual chips

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#1428]
**Steps to Reproduce**  
1. Open a sub
2. Open quick actions 
3. Use sort contextual chip to update sort. For example choose top - all time
4. Bottom sheet does not go back down on its own

**Expected behavior**  
Bottomsheet should go down on its own

**Comment by laurencedawson** [comment]
Fixed for the next release.
