### ISSUE TITLE
[Feature Request] Subreddit image icons next to posts

### ISSUE THREAD

**Issue by oathzed** [laurencedawson/sync-for-reddit#143]
![Screenshot_20200606-001433](https://user-images.githubusercontent.com/52545913/83938811-721d3c00-a78c-11ea-98cd-766adc2ffd4a.png)

Can we please get subreddit image icons next to the subreddit name on posts. It's a lot faster to destinguish what subreddit it is.

**Comment by laurencedawson** [comment]
Added in v22
