### ISSUE TITLE
[BUG] Swiping from right to left on drawer itself not closing it 

### ISSUE THREAD

**Issue by AT302** [laurencedawson/sync-for-reddit#1431]
**Describe the bug**  As title says. It only happens inside subreddit 

**Steps to Reproduce**  
1. Go to '...' r/redditsync 
2. Click on open left drawer which shows sub list 
3 swipe from right to left on drawer itself. It's not working 

**Expected behavior**  

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Fixed for the next release.
