### ISSUE TITLE
[ENHANCEMENT] Replace official crusty YouTube library

### ISSUE THREAD

**Issue by Liz-chan** [laurencedawson/sync-for-reddit#1433]
**Is your feature request related to a problem? Please describe.**  
Currently, if you try to play a YouTube video in-app, it just loads for a sec and doesn't do anything. It might be because I use YouTube Vanced, but a lot of people use Vanced, so I'm sure this issue affects more than just me. The official YouTube lib is also crusty and old and full of bugs like LJ said, so I think it'd be better to switch to the new and shiny supported one.

**Describe the solution you'd like**  
I think it'd be good if we could switch to [this lib](https://github.com/PierfrancescoSoffritti/android-youtube-player) since it seems to be more stable, and lets you customize the player to your liking.

**Describe alternatives you've considered**  
I've considered not using the in-app player and just opening links in Vanced instead.

**Additional context**  
Here's a video of the in-app player not working bug:

https://user-images.githubusercontent.com/18467466/173198552-d35f8a06-525e-4416-918e-523f3a06296b.mp4

**Comment by laurencedawson** [comment]
Swapped for the next release!
