### ISSUE TITLE
[ENHANCEMENT] Increase swipe-area for about-menu

### ISSUE THREAD

**Issue by StuntHacks** [laurencedawson/sync-for-reddit#1434]
**Is your feature request related to a problem? Please describe.**  
The current swipe-area to open the about menu easily interferes with system-gestures.

**Describe the solution you'd like**  
Increase the swipe-area in a similar fashion to the normal side-drawer with the discord-style enabled.

**Describe alternatives you've considered**  
Perhaps a hamburger button would suffice, if a larger area would interfere with post swipe-actions?

**Comment by laurencedawson** [comment]
Expanded tooplbar > about

Three dots top right > about

Are also ways to open the sidebar

**Comment by StuntHacks** [comment]
That's true, and those work, but at least on big phones reaching the about button can be a bit of a stretch. And the more actions menu requires an additional click. This is pretty nitpicky, so don't worry too much about it, but opening it via a swipe is naturally the most convenient way of accessing the menu, and would fit in well with the rest of the user experience

**Comment by laurencedawson** [comment]
I tried making the swipe area larger and the main issue was conflicts with the swipe actions.

**Comment by StuntHacks** [comment]
Fair enough, just thought I'd mention it
