### ISSUE TITLE
[BUG] Tapping usernames with hyphen ( - ) will open the default browser instead of Sync

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#1436]
**Describe the bug**  
With "Tap usernames to open" enabled, tapping usernames with hyphens ( - ) in posts and comments will open the default browser instead of opening via Sync.

**Steps to Reproduce**  
1. Enable "Tap usernames to open" in Settings > Link handling
2. Visit a post or comment where usernames have hyphens with them. Example link: https://www.reddit.com/r/MurderedByWords/comments/va1d6f/_/  
3. Tap said usernames with hyphens

**Expected behavior**  
Tapping usernames (whether with hyphens or underscore) should launch in Sync and not in default browser.

**Smartphone**
 - Device: Samsung Galaxy A32 4G
 - Android: 12
 - Sync version: 22.06.12-00:51
 - Sync variant: Internal Dev

**Comment by laurencedawson** [comment]
Fixed for the next release.
