### ISSUE TITLE
[BUG] Black block briefly appears when quickly scrolling sometimes

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1439]
https://www.reddit.com/r/redditsync/comments/va0buw
> Like the title says. Sometimes when I'm scrolling, it seems like the posts don't catch up or something and for a very brief moment the scrolling feed shows a big black block before refreshing to whatever was there in the feed. It's been impossible for me to take a screenshot of as it only happens towards the end of a scrolling motion and always refreshes to the normal feed by the time it stops. I'm on a Samsung S21 Ultra, and have the latest version of sync installed. I'm wondering if it has to do with my high screen refresh rate since i rarely have Internet issues with my phone. Any thoughts?

**Comment by laurencedawson** [comment]
No idea about thisone.

**Comment by feerlessleadr** [comment]
I'm getting the same thing (have had it for a while now across multiple updates over the last month+ on my OnePlus 8t on Android 11 stock) and just assumed it was related to how ads are shown in the non pro version (ie a scrolling ad is placed in the feed), and the black box was just a remnant of that.

**Comment by laurencedawson** [comment]
I think this might have been caused by the secret panel. Reverting.
