### ISSUE TITLE
[BUG] Refresh not working

### ISSUE THREAD

**Issue by ianhandsup** [laurencedawson/sync-for-reddit#1442]
Refresh is not working. When I refresh, the same posts appear. Nothing is new.

1. Go to the main page
2. Pull down to refresh

When I refresh, new posts should appear. 

 - Device: Pixel 6 Pro
 - Android: 12 (SQ3A.220605.009.B1)
 - Sync version: V22.06.10-1 0:35 (22012)
 - Sync variant: Beta/Free

**Comment by laurencedawson** [comment]
Mm not necessarily. There needs to be new content available. Try on all and set the sort to new.
