### ISSUE TITLE
[BUG] Copy Code Block UI gets repeated and faded

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#1454]
[Check out this comment](https://www.reddit.com/r/ProgrammerHumor/comments/vcx34k/im_not_old_i_just_forgot_dot_a_few_times/icgvmkd/)

![Screenshot_20220615-162214.png](https://user-images.githubusercontent.com/2940826/173920270-1c360e9d-e074-4249-8aa5-7b5b36af7b8c.png)

 **Device information**

    Sync version: v22.06.15-20:43    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 12

**Comment by laurencedawson** [comment]
Oooh nice find

**Comment by laurencedawson** [comment]
Fixed for the next release.
