### ISSUE TITLE
[BUG] Sync fails to load from shortcut menu on icon in latest version

### ISSUE THREAD

**Issue by OvermindDL1** [laurencedawson/sync-for-reddit#1457]
**Describe the bug**  
When loading sync directly then it loads fine to the front page, But as of the latest pro version that my phone updated to just a few minutes ago then pressing and holding on the sync icon to bring up my list of subreddit favorites to immediately load into one appears to be broken, It just shows the sync loading screen at that point.

I can still access the subreddit by loading to the front page first to normally and then navigating to the subreddit, it's only via the quick Access pane.

**Steps to Reproduce**  
1. Update to the latest pro version, for me that is currently v22.06.15-20:43.
2. Press and hold on the sync icon on your home screen, You will see the quick access pane showing some favorited subreddits.
3. Tap on one of those favorited subreddits, which before this recent update would launch sync and immediately go to that subreddit.

**Expected behavior**  
As in previous versions I expected it to load into the subreddit chosen.

**Screenshots**  
When I choose one of the quick access pains, this is the only thing I see and it sits on it for at least a few minutes before I gave up:
![Screenshot_20220616-004955](https://user-images.githubusercontent.com/401605/174010451-8653d208-56f9-4bdf-944f-316a641e8913.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6] Pixel 6 Pro
 - Android: [e.g. 12] 12
 - Sync version: [e.g. v22.5.20] v22.06.15-20:43
 - Sync variant: [e.g. pro] Pro

**Additional context**  
No other applications updated.  Someone on the discord also confirms the same issue is happening for them.

**Comment by OvermindDL1** [comment]
Oh, and just to confirm, I have force killed the app and cleared its cache and so forth.

**Comment by fessmm** [comment]
i can reproduce, android 13 beta 3.1 
sync version 22.06.15-20:43

**Comment by laurencedawson** [comment]
Fixed for the next release.
