### ISSUE TITLE
[BUG] [ULTRA] Can no longer restore deleted comments 

### ISSUE THREAD

**Issue by jarquafelmu** [laurencedawson/sync-for-reddit#1468]
**Describe the bug**  
When I first got Sync Ultra, I was able to restore deleted comments, but after the recent update I can no longer do that and I don't see that in the settings. Was that feature removed?

**Steps to Reproduce**  
1. Go to a deleted comment, click on it
2. Click on the menu for it on the right side. The three dots. 
3. Scroll down to find the option to restore the comment 
4. See that the option no longer exists

**Expected behavior**  
I expected to be able to see the option to restore comments. 

**Smartphone (please complete the following information):**

Sync version: v22.06.16-17:33    
    Sync flavor: pro    
    
    Ultra user: true    
    View type: Cards    
    Push enabled: false    
    
    Device: dream2qltesq    
    Model: samsung SM-G955U    
    Android: 9

**Comment by atomfist** [comment]
I am also running into the same issues listed above as an ultra user.

Smartphone (please complete the following information):

Sync version: v22.06.16-17:33
Sync flavor: pro

Ultra user: true    
View type: Cards    
Push enabled: false    
  
Model: Google Pixel 4XL   
Android: 12

**Comment by jarquafelmu** [comment]
This has been resolved
