### ISSUE TITLE
[ENHANCEMENT] Refresh button in Top Bar

### ISSUE THREAD

**Issue by mikeleus** [laurencedawson/sync-for-reddit#1476]
Please bring back the Refresh button up top, it was super helpful and fast to refresh any sub
![Screenshot_20220617-012336](https://user-images.githubusercontent.com/77749535/174407640-343c6a49-4d75-47dc-af49-1d5dbcafcec7.png)

**Comment by bohrabhijeet** [comment]
You can now long-press the header to refresh.
