### ISSUE TITLE
[ENHANCEMENT] A Picture-in-Picture mode would be a nice addition to the app.

### ISSUE THREAD

**Issue by daviduzondu** [laurencedawson/sync-for-reddit#1485]
**Describe the solution you'd like**  
It would be nice if you could scroll through the feed or comments section while a video is playing in PiP mode.

**Describe alternatives you've considered**  
There are no alternative solutions considered since a video currently takes up the entire screen.

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/419
