### ISSUE TITLE
[ENHANCEMENT] Restore removed or deleted post

### ISSUE THREAD

**Issue by Racle** [laurencedawson/sync-for-reddit#1494]
**Is your feature request related to a problem? Please describe.**  
Few times I've opened text post (preview had text), but when I open it it, sync refreshes post and I only see that it has been removed or deleted.  Would be nice to restore that original post.
Ex. while browsing I see text on preview window. But when I open post, sync refreshes post and doesn't show original text anymore in the post or in the preview window. Instead it will show `[removed]` or `[deleted]` text.

**Describe the solution you'd like**  
Restore post same way you restore comments currently.

**Describe alternatives you've considered**  
Use cached version of post instead of showing `[removed]` or `[deleted]` text when sync loads post again.

**Comment by bohrabhijeet** [comment]
Duplicate.
https://github.com/laurencedawson/sync-for-reddit/issues/1429
