### ISSUE TITLE
[BUG] Inline images in selftext don't show in Sync

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1539]
**Reported here**:
https://www.reddit.com/r/redditsync/comments/vznogx
> Looks like it's just a text post, but it should have an image displayed with it. I am able to see the image in browser and/or in another client.
> 
> https://www.reddit.com/r/sousvide/comments/vz2dvg
> 
> **Device information**
> 
>     Sync version: v22.06.17-16:57    
>     Sync flavor: pro    
>     
>     Ultra user: false    
>     View type: Cards    
>     Push enabled: false    
>     
>     Device: raven    
>     Model: Google Pixel 6 Pro    
>     Android: 12

Comment by u/tumultuousness:
> > I think I know the issue - Reddit recently announced that [they will allow text on all image post options](https://www.reddit.com/r/modnews/comments/vj4evp/text_now_available_on_all_post_types/). So it seems like sync is only reading the text with the image, not also showing the image.
> >
> > I saw [this post](https://www.reddit.com/r/RedditLaqueristas/comments/w05ae0/amazed_at_the_difference_even_a_cheap_base_coat/) and saw only text and thought back to this sub to post another example, when I remembered that Reddit was adding the option. The funny thing is when I first saw this post with the different examples, I was on desktop so I could see the image so I didn't think much of it, but now I can see, on the old design with RES turned on, that only the image shows, none of the text shows. Without RES, the old design does show both text and image.
> >
> > Anyways, my Sync info too:
> >
> > **Device information**
> >
> >     Sync version: v22.06.10-10:35    
> >     Sync flavor: pro    
> >    
> >     Ultra user: false    
> >     View type: Cards    
> >     Push enabled: false    
> >    
> >     Device: bramble    
> >     Model: Google Pixel 4a (5G)    
> >     Android: 12

**Comment by bigbill25** [comment]
Similar post that has a video that doesn't show in Sync:

https://www.reddit.com/r/VWiD4Owners/comments/w0mkdk/_/

**Comment by bohrabhijeet** [comment]
Fixed in v22.8.1.
