### ISSUE TITLE
BUG: Gyfycat downloads are low quality

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#155]

**Comment by Keagel** [comment]
Example:
https://old.reddit.com/r/babyelephantgifs/comments/gw1fwl/since_gfycat_is_down_and_there_are_no_new_posts/

Downloading this with Sync shows this URL:
https://thumbs.gfycat.com/UnhappyMaleBrocketdeer-mobile.mp4

The highest quality available is this one:
https://giant.gfycat.com/UnhappyMaleBrocketdeer.webm

**Comment by laurencedawson** [comment]
Fixed for the next release.
