### ISSUE TITLE
[ENHANCEMENT] Options for labeling and sorting Saved Posts

### ISSUE THREAD

**Issue by reMaster17** [laurencedawson/sync-for-reddit#1552]
I'd like options to label and sort my saved posts. The best design would be to be free in creating different labels for the saved posts amd have the subs of the subs of the saved posts as automatic labels. You should be able to sort by those labels in the saved posts category. 
For example I have saved a lot of posts regarding pixelart from different subs and want to label them with one label called "Pixelart" and all the posts about vr related stuff "VR Stuff". After that I would be able to sort by the labels I'm looking for.

**Comment by felimenta970** [comment]
I believe that's a Reddit Gold feature already

**Comment by reMaster17** [comment]
I'm not familiar with gold. Couldn't find any infos on that when searching for reddit premium festures. Maybe someone can confirm it?
Would that be a dealbreaker for a feature request?

**Comment by bohrabhijeet** [comment]
> I'm not familiar with gold. Couldn't find any infos on that when searching for reddit premium festures. Maybe someone can confirm it?
> Would that be a dealbreaker for a feature request?

Reddit Premium (or Gold) supports this, and so does Sync. You can categorize saved posts with it. (Long pressing the save icon will show you the toast)
