### ISSUE TITLE
[BUG] Image not showing

### ISSUE THREAD

**Issue by PerLycke** [laurencedawson/sync-for-reddit#1554]
**Describe the bug**  
Image not showing for this post: https://www.reddit.com/r/sweden/comments/w9arrl/_/

**Steps to Reproduce**  
1. Go to https://www.reddit.com/r/sweden/comments/w9arrl/_/

**Expected behavior**  
Image should show.

**Screenshots**  
![Screenshot_20220727-185942_Sync Pro.jpg](https://user-images.githubusercontent.com/8590720/181306196-51504ffc-09a8-40eb-9031-3620103bc72b.jpg)
![Screenshot_20220727-190225_Chrome.jpg](https://user-images.githubusercontent.com/8590720/181306693-f0b3ada0-0383-414d-8e05-5a46bf501cfd.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - Android: 12
 - Sync version: v22.06.17
 - Sync variant: pro

**Comment by laurencedawson** [comment]
Thanks for closing!
