### ISSUE TITLE
[BUG] Older-style spoilers do not work

### ISSUE THREAD

**Issue by AlexVasiluta** [laurencedawson/sync-for-reddit#1557]
**Describe the bug**  
I was watching the Mr. Robot old discussion threads and noticed they were using an old type of spoilers. Unfortunately, tapping the spoiler will not actually reveal it. I think this is a bug

**Steps to Reproduce**  
1. Go to https://www.reddit.com/r/MrRobot/comments/77bs7l or https://www.reddit.com/r/MrRobot/comments/77bs7l/mr_robot_3x02_eps31_undogz_postepisode_discussion/domywkf/
2. Tap on the spoiler preceded by `SPOILER: `
4. It will not be revealed

**Expected behavior**  
The spoiler should be revealed

**Screenshots**  
N/A

**Smartphone (please complete the following information):**
    Sync version: v22.06.17-16:57    
    Sync flavor: pro    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: r9q    
    Model: samsung SM-G990B    
    Android: 12

**Comment by bohrabhijeet** [comment]
Duplicate. 
https://github.com/laurencedawson/sync-for-reddit/issues/1490
