### ISSUE TITLE
[BUG] The "Other discussions" button takes up 3 lines

### ISSUE THREAD

**Issue by FaviFake** [laurencedawson/sync-for-reddit#1596]
**Describe the bug**  
The "Other discussions" button takes up 3 lines

**Steps to Reproduce**  
1. Go to a post
2. Click on the three dots in the top right - corner 
3. See error

**Expected behavior**  
I expected the button to use 2 lines, not three

**Screenshots**  
![Screenshot_20220818-133745_Sync.png](https://user-images.githubusercontent.com/86537048/185386304-2b0e31f3-d7bc-4801-8dd1-273b1862d6b2.png)

**Comment by laurencedawson** [comment]
Fixed for the next release.
