### ISSUE TITLE
SUGGESTION/REQUEST - Long-pressing new Sync icon in bottom nav executes default action

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#161]
I think it would be really cool to have the ability to set one of the 6 options in the Sync button popup as the default for long-pressing the button. Can set it in app settings, or by long-pressing one of the 6 options while popup is open.

**Comment by skff-err** [comment]
I'd love to be able to hold the buttom to hide read posts

**Comment by laurencedawson** [comment]
Long pressing in the latest version will now fully expand the menu.

**Comment by laurencedawson** [comment]
Boom done
