### ISSUE TITLE
BUG: Post title is too close to the classic card border

### ISSUE THREAD

**Issue by themajorhavoc** [laurencedawson/sync-for-reddit#164]
The title text is too close to the top border of the card. I've noticed this happens only with posts having image/gif/video

![Screenshot_20200607-161726_1](https://user-images.githubusercontent.com/66555628/83967874-dbaf5e80-a8e2-11ea-9df4-6cf8c1f95e42.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release.
