### ISSUE TITLE
BUG: Image previews doesn't load initially.

### ISSUE THREAD

**Issue by themajorhavoc** [laurencedawson/sync-for-reddit#165]
This behavior is very random. Even after viewing the full image, still the same. Sometimes it loads but very slow.

![Screenshot_20200606-144612_1](https://user-images.githubusercontent.com/66555628/83967970-4b254e00-a8e3-11ea-958b-28a955f18b7c.jpg)

**Comment by laurencedawson** [comment]
These images here are loaded separately. If they time out or fail they don't try to re-download.

Closing for now.
