### ISSUE TITLE
[BUG] Restoring comments functionality has been broken for a while

### ISSUE THREAD

**Issue by blackandwhitetux** [laurencedawson/sync-for-reddit#1657]
**Describe the bug**  
Find a deleted comment, tap and select restore comment, feature doesn't seem to work on any of the comments I tested. 

**Device information**

    Sync version: v22.08.01-13:26    
    Sync flavor: dev    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: RMX2001L1    
    Model: realme RMX2001    
    Android: 11

**Expected behavior**  
At least some comments are restored.

**Additional context**  
I searched for this bug report carefully but I didn't see it logged already. If this is a duplication of any existing issue I'd be happy to close it.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers

**Comment by blackandwhitetux** [comment]
Thanks!
