### ISSUE TITLE
Custom feeds collapsing does not stick when phone is locked and unlocked or app is exited

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/sync-for-reddit#172]
Steps to reproduce:

1) Collapse "custom feeds" in the subreddit list.

2) Return to posts feed. At this point, the collapsed state remains if you check the subreddit list.

3a) Lock device and unlock. The custom feed section is again uncollapsed.

3b) Exit the Sync app and return. Same result as in 3a.

Pixel 3a XL, Android 10, V20 beta 3.

**Comment by laurencedawson** [comment]
Fixed for the next release
