### ISSUE TITLE
Put link text in expanded comment links

### ISSUE THREAD

**Issue by drhodesmumby** [laurencedawson/sync-for-reddit#18]
Change expanded links in comments and posts to have both URL and link text shown similar to old versions of Sync. This makes it easier to see what any particular link is in reference to, particularly on long lists. An old example is attached.

![20200509_125300](https://user-images.githubusercontent.com/4113486/81473259-1dba8700-91f5-11ea-91e9-c0f7ac5e3ff3.png)

**Comment by laurencedawson** [comment]
In the latest beta I've largely replaced these older style links and replaced them with a new image preview and link text span.

I'm not completely sold on the title being in there so I'm going go ahead and close this. Cheers
