### ISSUE TITLE
BUG: Direct links to v.reddit videos don't load

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#180]
https://v.redd.it/2xfpbzrexi351?a=1594150987%2CYWNkOWY5MTE2NjAzMWFlODFiOGQzZWU0ZDljOGE4YzE5ZTY4YjE4MjY0ODY4ZjQyNmM5NGM1ZjdhZTEyN2Q2Nw%3D%3D&amp;v=1&amp;f=sd

This video is unable to load in Sync, but loads in browser fine

**Comment by laurencedawson** [comment]
Fixed for the next release.
