### ISSUE TITLE
[BUG]Single click on image background fails to close view

### ISSUE THREAD

**Issue by drew4237** [laurencedawson/sync-for-reddit#186]
**Describe the bug**
Clicking on the picture or video will close but clicking on the black background around doesn't close the view and return to list or comments. 

**To Reproduce**
1. Go to 'image'
2. Click on 'black border at top and bottom of image'
3. See error, in image view not closing. 

**Expected behavior**
I believe before the redesign this functioned. 

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: android 10
 - Browser Chrome
 - Version latest beta 4

**Comment by laurencedawson** [comment]
Clicking either the image or black area around seems to be working for me.
