### ISSUE TITLE
[BUG] Opening "Saved" from the bottom Sync menu results in lowercase '' in "saved' being shown in the Profile view top left chip. 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#187]
**Describe the bug**
Just the lowercase 's' in the chip

**To Reproduce**
1. Tap Sync button
2. Tap Saved
3. See top left chip

**Screenshots**
![Screenshot_20200608-020124_1](https://user-images.githubusercontent.com/55349349/84032112-71ff8500-a9b4-11ea-9c7f-60523405d00e.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release.
