### ISSUE TITLE
[BUG] Options in settings menu do not consistently reflect base font size

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#188]
**Describe the bug**
Main settings are consistent. 
But going inside the main settings, the font is inconsistent for few of them

In "General" and "Images", for example, the font is fixed. Not tied to base font size.  

But few items in, for example, "Data Options" and "Messaging" are tied to base font size. That too, only some of the options

![Screenshot_20200608-182001](https://user-images.githubusercontent.com/55349349/84032526-1aade480-a9b5-11ea-950c-4350f2841502.jpg)
![Screenshot_20200608-182034](https://user-images.githubusercontent.com/55349349/84032533-1d103e80-a9b5-11ea-9994-5f874b9ea64b.jpg)
![Screenshot_20200608-182038](https://user-images.githubusercontent.com/55349349/84032541-1f729880-a9b5-11ea-9d3a-43851dee1978.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release.
