### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stager** [laurencedawson/sync-for-reddit#189]
**Describe the bug**
Bottom navigation disappear when I use gesture navigation on my phone

**To Reproduce**
you just have to see the screenshot

**Expected behavior**
The bottom navigation should work in both gesture types

**Screenshots**
http://imgur.com/gallery/K0ZwDGi

**Smartphone (please complete the following information):**
 - Device: [Motorola One]
 - OS: [Android 10]
 - Browser [Firefox]
 - Version [vv20 (nightly alpha)]

**Additional context**
1 - As you could see in the screenshot, it works only if I use the 3 button navigation
2 - My settings are right, the bottom navigation is enabled

**Comment by laurencedawson** [comment]
You can disable the hiding of this in the settings under general. Closing as this isn't a bug.
