### ISSUE TITLE
[BUG] Selftext cutoff

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#190]
**Describe the bug**
First line of selftext sometimes gets cutoff

**To Reproduce**
Couldn't find a pattern. Happens on random posts

![Screenshot_20200608-210738_1](https://user-images.githubusercontent.com/55349349/84052293-ff9b9e80-a9cd-11ea-940d-5f97f5a58e0a.jpg)

**Smartphone:**
 - Device: OnePlus 7
 - OS: Oxygen OS 10.3.2

**Comment by laurencedawson** [comment]
This has since been fixed.
