### ISSUE TITLE
[BUG] Issue hiding read posts

### ISSUE THREAD

**Issue by McSullivan** [laurencedawson/sync-for-reddit#191]
**Describe the bug**
There's an issue hiding read posts when all visible posts have already been read. It successfully hides the posts, but doesn't load more automatically, and since it's not possible to scroll, you can't trigger the event that fetches more posts at the end of the recyclerview.

**To Reproduce**
1. Make sure all visible posts are read.
2. Click on the Sync logo in the bottom navigation bar.
3. Click on the "Hide read" option.

**Expected behavior**
Hides all visible posts and loads more.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 10
 - Version 20 (beta 3)

**Comment by laurencedawson** [comment]
Added a fix for this.

**Comment by laurencedawson** [comment]
Added a fix for this.
