### ISSUE TITLE
[BUG] Swipe to zoom on peek no longer working

### ISSUE THREAD

**Issue by cychow** [laurencedawson/sync-for-reddit#192]
**Describe the bug**
When peeking posts, holding and swiping up or down no longer zooms the content

**To Reproduce**
1. Peek any peekable post
2. Swipe up/down

**Expected behavior**
Content should zoom in or out with one finger held and swiping up/down.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10 (QQ3A.200605.002)
 - Browser N/A
 - Version: Sync Dev vv20 (nightly alpha)

**Additional context**
This feature was removed in the v19.1 beta and was re-added at some point afterwards.
https://www.reddit.com/r/redditsync/comments/fcufsl/sync_for_reddit_v191_beta_is_now_going_live_on/fjdt68y/

**Comment by thereddestdog** [comment]
I'm still on V3, but I can't even zoom in on any animated image, even with two fingers

**Comment by andysteakfries** [comment]
> I'm still on V3, but I can't even zoom in on any animated image, even with two fingers

This was disabled by default because of some odd distortion when you enable zooming in on videos. Search the settings for "zoom" to turn it back on.

**Comment by laurencedawson** [comment]
I don't plan to add this back as we've completely switched to a new image manage.
