### ISSUE TITLE
[BUG] Home page is not retained per user account

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#193]
**Describe the bug**
Unable to set home as Frontpage in one account and All on another account

**To Reproduce**
1. Account 1, home is set as All
2. Change to Account 2, set home page as Frontpage
3. Change back to Account 1, home page is now Frontpage

**Expected behavior**
Please remember home page on a per account basis

**Screenshots**
n/a

**Smartphone (please complete the following information):**
Android Dev version

**Comment by laurencedawson** [comment]
Unable to reproduce this. Closing but please let me know if you still have this issue.
