### ISSUE TITLE
Please allow removal of Popular and Random in Subreddit menu

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#194]
**Describe the solution you'd like**
I would like to tap on a 3-button menu and be able to hide from list

Popular has this option, but then I get a message saying you cannot unsubscribe from Popular

**Additional context**
I never use these features and they are taking up valuable real estate :)

**Comment by laurencedawson** [comment]
You can now hide the entire section and fav items
