### ISSUE TITLE
[BUG]No way to go back to a sub after searching for a keyword in the sub

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#195]
**Describe the bug**
Searching a keyword, for instance, "beta" in r/redditsync will bring few posts as the result. 

Going back from those results takes user to the front-page. It should be taking user back to r/redditsync

**To Reproduce**
As described above

**Smartphone :**
 - Device: OnePlus 7
 - OS: OxygenOS 10.3.2

**Comment by laurencedawson** [comment]
This has since been addressed
