### ISSUE TITLE
[BUG] Issue with adding post to Saved on the "Post options"

### ISSUE THREAD

**Issue by Keinta15** [laurencedawson/sync-for-reddit#196]
**Describe the bug**
Can't add post to the saved section while using the three-dots (Post options). Tested adding the save button on the view customization and that works.

**To Reproduce**
1. Go to any post
2. Click on Post options (three dots)
3. Press the save option
4. Nothing happens 

**Expected behavior**
Expected the post to be added to Saved section.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: OxygenOS 10.3.4
 - Version V20 (beta 4)

**Comment by alcatrazblaze** [comment]
Has already been reported

**Comment by laurencedawson** [comment]
This has since been fixed,
