### ISSUE TITLE
[BUG] "Collapse all comments" does not collapse comments without replies with "Collapse parent" is enabled

### ISSUE THREAD

**Issue by ofth** [laurencedawson/sync-for-reddit#197]
App version: v20 (beta 4)

Steps to reproduce:  
1. Enable the "Collapse parent" setting.
2. Open in the app a reddit comment page that contains comments without children.
3. Press the collapse all button.

Expected behavior:
* All comment threads, including threads with no replies, should be collapsed.

Actual behavior:
* Only comment threads that have children comments are collapsed.

**Comment by laurencedawson** [comment]
This is by design. They have no replies.
