### ISSUE TITLE
[Feature request] Use Material motion library when opening and closing cards

### ISSUE THREAD

**Issue by jonasnaimark** [laurencedawson/sync-for-reddit#198]
The MD2 update looks great! It would be a nice improvement to use the Material motion library that recently launched: https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md

Specifically, when navigating between a card and a comments page, it could use this pattern:
https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#container-transform

How the transition should look:

![Reddit Sync mp4](https://user-images.githubusercontent.com/4028486/83928234-d9fb6480-a743-11ea-869a-f31b093f3836.gif)

**Comment by skff-err** [comment]
this would be **terrific**

**Comment by laurencedawson** [comment]
As beautiful as this is. The design has changed quite a bit since this.
