### ISSUE TITLE
Full width image previews in posts, or a way to move the thumbnail to the left

### ISSUE THREAD

**Issue by maltasoron** [laurencedawson/sync-for-reddit#199]
Posts with images used to have a full width image preview, like this: https://i.imgur.com/oHLO91g.jpg
(Maybe this was only in the full width view; I can't remember.) In the beta, there's only a small thumbnail on the right.
I was quite fond of the full width preview, because I liked having a preview and because I navigate using my left thumb. I can't reach the thumbnail now.

If possible, I would like to have the fill width preview back.
Otherwise, I would like to have a way to move the thumbnail to the left, so I can reach it with my left thumb.

Thanks for your time!

**Comment by laurencedawson** [comment]
The full width preview has since been added back.

**Comment by maltasoron** [comment]
Awesome, thank you very much! I'm using the full size previews now, so I don't even have to click :)
