### ISSUE TITLE
Add option to move the voting chip to right side of post

### ISSUE THREAD

**Issue by drhodesmumby** [laurencedawson/sync-for-reddit#20]
It would be nice to have the option to move the voting chip to the right hand side of the post next to the overflow menu as in the below screenshot (personally I would like this as it would be significantly more comfortable on larger screens).

![Screenshot_20200521-183619](https://user-images.githubusercontent.com/4113486/82715597-c653f680-9c8b-11ea-9565-a2da989b103c.jpg)

**Comment by laurencedawson** [comment]
Added for the next release.
