### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#200]
**Describe the bug**
New comment count shows up when you click on the post itself but not on the main page. 

**To Reproduce**
1. Go to a post that has comments
2. Click on post.
3. Go back and wait until new comments get added 
4. Refresh the page. New comment count won't show up until you click the post. 

**Expected behavior**
A new comment count shows up in the comment pill after a page refresh. It should also show up when the post gets clicked 

**Screenshots**
![Screenshot_20200608-174644_Sync Pro](https://user-images.githubusercontent.com/20840348/84088665-a40fe780-a9b2-11ea-8a5c-01e4fec2b9eb.jpg)
![Screenshot_20200608-174646_Sync Pro](https://user-images.githubusercontent.com/20840348/84088873-2ac4c480-a9b3-11ea-88b6-5fd1cd499b50.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10, One UI 2
 - Version Beta 4

**Comment by laurencedawson** [comment]
This has since been fixed.
