### ISSUE TITLE
[BUG] Can't unsubscribe via sub's sidebar

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-reddit#201]
**Describe the bug**
The unsubscribe function via the sidebar doesn't work. Pressing the "joined" button changes its state to "join+" on click, but nothing actually happens.

Unsubscribing through the sub list (bottom or side navigation) works fine.

**To Reproduce**
1. Go to any sub
2. Click on top right ... and select 'view sidebar'
3. Click the "joined" button, watch it change to "join+"
4. Restart sync, sub is still showing on frontpage. Also in sub list.

**Expected behavior**
Proper unsubscribe

**Screenshots**
Self explanatory

**Smartphone (please complete the following information):**

    Sync version: v20 (beta 4)    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Push enabled: false    
    
    Device: OnePlus7Pro    
    Model: OnePlus GM1910    
    Android: 10

**Comment by laurencedawson** [comment]
This has since been fixed
