### ISSUE TITLE
[BUG] Unreadable browser menu

### ISSUE THREAD

**Issue by davidgro** [laurencedawson/sync-for-reddit#202]
The menu for the browser isn't readable. Sync is in Dark mode.

***Scenario* (steps to reproduce)**
1. Open an article (not media or text post, but a link) in the internal browser.
2. Try refreshing the page from the menu.
3. See unreadable menu. 

Result(s)
https://i.imgur.com/0wCtIHF.png

Device information

Sync version: 20 (betas 2-4 so far)    
Sync flavor: free    
Removed ads: true    

View type: Small cards    
Push enabled: false    

Device: elsa    
Model: LGE LG-US996  (LG V20)  
Android: 8.0.0

**Comment by laurencedawson** [comment]
This has since been fixed
