### ISSUE TITLE
[BUG] Opening inbox via notification resets browsing position

### ISSUE THREAD

**Issue by ofth** [laurencedawson/sync-for-reddit#203]
App version: v20 (beta 4)

Steps to reproduce:
1. Navigate to a subreddit or comment page
2. Receive a reddit message (e.g. comment reply, direct message, username mention, etc.)
3. Wait for reddit sync message notification
4. Open the notification to access app inbox
5. Press back button to exit out of app inbox

Expected behavior:
* Return to previously navigated-to page (as in pre-MD2 reddit sync)

Actual behavior:
* App browsing position reset to front page

**Comment by laurencedawson** [comment]
Your position in posts will be saved, just hit home
