### ISSUE TITLE
[BUG] search function gone

### ISSUE THREAD

**Issue by mil88** [laurencedawson/sync-for-reddit#204]
**Describe the bug**
Beta 4 search function disappeared after  disabled the bottom navigation bar, but enabled the left sidebar.

**To Reproduce**
1. Go to 'open a thread'
2. Click on 'the name of the sub at the top of the screen.'
3. See error

**Expected behavior**
A search function in the subreddit should appear

**Screenshots**
![Screenshot_20200608-201409_Sync](https://user-images.githubusercontent.com/66656206/84099427-d297bd80-a9c6-11ea-982c-b8a76028c5b1.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: 9
 - Browser: chrome

**Comment by laurencedawson** [comment]
This has since been fixed with the bottom navigation button
