### ISSUE TITLE
Pin the sorting pills at the top so they are easily accessible

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#205]
**Is your feature request related to a problem? Please describe.**
I am always frustrated that I have to scroll all the way back to the top to access the sorting pill or the side bar pill. The same experience is seen in the comments section when you want to add a new comment or sort the comments after scrolling down for a while. 

**Describe the solution you'd like**
Sorting option pill, sidebar pill, comment sorting pill, and adding new comment input field should be stickied to the top when the user scrolls so they can quickly change the sort or add a new comment or access the sidebar rather than scrolling all the way to the top.  

**Describe alternatives you've considered**
Maybe change the contents of the sync button depending on the context.

**Comment by laurencedawson** [comment]
These have since been added to the sync menu for easy access
