### ISSUE TITLE
[BUG] Videos in imgur albums play before they are shown on the screen

### ISSUE THREAD

**Issue by BUYT-1** [laurencedawson/sync-for-reddit#206]
**Description**
Videos in imgur albums play as soon as they load, not once they appear on the screen. They also don't pause when you swipe to see another page, and when that page is also a video, you have 2 videos playing simultaneously.

**To Reproduce**
1. Open [this post](https://www.reddit.com/r/2020PoliceBrutality/comments/gy6xx8) in Sync.
2. Open the album in the post. (warning: 4th album page is graphic)
3. Video on the second page will automatically start playing in the background.
4. After you swipe to the right to go to the second page, the video in the third page will start playing in the background.

**Expected behavior**
Videos should only start playing when they are shown on screen and pause when they are not.

**Smartphone:**
 - Device: Xiaomi Redmi 5 Plus
 - OS: Android 7.1.2

**Additional context**
- Sync version: v20 beta 4

**Comment by laurencedawson** [comment]
Fixed. Cheers
