### ISSUE TITLE
[BUG] Scrollbar Resizing and Jittering

### ISSUE THREAD

**Issue by jolo283** [laurencedawson/sync-for-reddit#207]
**Describe the bug**
The scrollbar randomly resizes and jitters when scrolling.

**To Reproduce**
1. Enable scrollbar on posts/comments.
2. Scroll down.

**Expected behavior**
The scrollbar should stay properly sized and smoothly move with the user scrolling.

**Screenshots**
I've attached gifs of this happening with both [posts](https://gfycat.com/nastyscratchybittern) and [comments](https://gfycat.com/difficultsecondhandgroundbeetle). Notice the behavior of scrollbars in both gifs. The gifs are from Beta 3, but the issue persists on Beta 4.

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android 10
 - Version: Sync v20 (Beta 4)

**Comment by laurencedawson** [comment]
This is exactly the same as how it used to look and a restriction of using views with different sizes. Not much I can do here.
