### ISSUE TITLE
[BUG] Collapsing a long comment can move the next comment off-screen

### ISSUE THREAD

**Issue by jolo283** [laurencedawson/sync-for-reddit#208]
**Describe the bug**
When scrolling down on a long comment and collapsing it to move to the next comment, the next comment is moved off-screen to where the previous comment begins.

**To Reproduce**
1. Find a long comment.
2. Scroll down on the comment and collapse it.

**Expected behavior**
The next comment should be at the top of the screen, not moved off-screen.

**Screenshots**
I've included two gifs. [Gif 1](https://gfycat.com/accomplishedimperturbableasianconstablebutterfly) shows the behavior on Sync. [Gif 2](https://gfycat.com/lightwiltedandalusianhorse) shows the behavior on Boost. Notice in Gif 1 how the comment right below the first one is shifted up and off-screen when the longer comment is collapsed. The gifs are from Beta 3, but the issue persists on Beta 4.

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android 10
 - Version: Sync v20 (Beta 4)

**Comment by laurencedawson** [comment]
Fixed for the next release
