### ISSUE TITLE
[BUG] Navigating back from search within subreddit brings us to Frontpage instead of the subreddit

### ISSUE THREAD

**Issue by jolo283** [laurencedawson/sync-for-reddit#209]
**Describe the bug**
Navigating back from a search within a subreddit brings us back to the Frontpage, not the subreddit we were searching.

**To Reproduce**
1. Go to a subreddit.
2. Search for a term within the subreddit.
3. Navigate back (via Android back or app back button).
4. You will be returned to the Frontpage.

**Expected behavior**
Going back (i.e. closing the search) should return you to the subreddit you were searching, not the Frontpage. Going back from the subreddit should only then return you to the Frontpage.

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android 10
 - Version: Sync v20 (Beta 4)

**Comment by alcatrazblaze** [comment]
Already reported

**Comment by laurencedawson** [comment]
Fixed for the current version.
