### ISSUE TITLE
In the "Sort by Top" menu, a back button would be really niceto go back to the main sort menu

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#210]
Suggestion on r/redditsync

https://www.reddit.com/r/redditsync/comments/gylgo5/_/

**Describe the solution you'd like**
After you select sort by top or controversial, you get a second menu where you can select the age of the posts you want to see.

I think it would be really nice if this menu had a back button to go back to the previous menu. For example if I accidentally tap "controversial" but I actually wanted "top". I drew the red arrow where I think an arrow that's the back button would fit well.

.

**Additional context**
https://i.imgur.com/rTv7T3a.png

**Comment by laurencedawson** [comment]
Added "..." to the list to go up (beta 30).
