### ISSUE TITLE
[BUG] Creating Multi-reddit initially redirects you to the subreddit you named the multi-reddit after

### ISSUE THREAD

**Issue by ShaneMitch** [laurencedawson/sync-for-reddit#211]
**Describe the bug**
Created a multi-reddit within sync and initially when going into the subreddit menu and scrolling to my multi's it sends me to the subreddit that I named the multi-reddit. In my case I made a multi of all the Call of Duty subs I wanted and named it "COD". When clicking this in the multi-reddit menu it sends me to reddit.com/r/COD instead of my multi. When I close the app and re-open this issue is fixed and clicking that then sends me to the multi I created.

**To Reproduce**
1. Go to various sub-reddits and add to new multi
2. Click subs from the menu bar
3. Scroll down to the newly created multi under the custom feeds header (I noticed it had an "r" icon instead of an "m")
4. Click the new multi 
5. This initially sends you the subreddit named after the multi you created until closing the app and re-opening.

**Expected behavior**
Clicking the multi would take me to the feed of the subreddits within the multi

**Screenshots**
NA

**Smartphone (please complete the following information):**
Sync version: v20 (beta4)
Sync flavor: pro

View type: Small cards
Push enabled: false

Device: charlotte
Model: HUAWEI P20 Pro
Android: 9

**Additional context**

**Comment by laurencedawson** [comment]
Fixed for the next release.
