### ISSUE TITLE
Labels in bottom nav get cut off on curved screens.

### ISSUE THREAD

**Issue by koinupapi** [laurencedawson/sync-for-reddit#220]
Hey there LJ. So this isn't really a bug, that's why I'm using just a blank canvas for this issue.

It seems that for users with curved screens, the messages label is super close or starting to get cut off by the curve.

The user requested perhaps an option with only icons and no labels. Just wanted to bring it to your attention. :)

Here's the link to the reddit post. :)

https://www.reddit.com/r/redditsync/comments/gzkmyj/_/

**Comment by laurencedawson** [comment]
Added an option to disable these.
