### ISSUE TITLE
Swipe to Reply on comment

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#221]
**Is your feature request related to a problem? Please describe.**
No problem, just a better way to achieve already existing function

**Describe the solution you'd like**
Swipe on a comment from right to left for reply action.  

This swipe is opposite to that of the already existing full width swipe to go back. So shouldn't interfere with that.  
Also, the swipe would be from anywhere on the screen, not from the edges, so shouldn't mess with Android Q gestures

**Additional Context**. 
Replying to a comment is one of the most used activity while going through a post.  
Swiping to comment is easy and more intuitive that the current method. 

Would be great if it is possible

**Comment by laurencedawson** [comment]
Added!
