### ISSUE TITLE
[BUG] Settings text doesnt wrap, gets cut off

### ISSUE THREAD

**Issue by benjo456** [laurencedawson/sync-for-reddit#227]
**Describe the bug**
Some settings options cannot be read as the text is cut off. 

For example, the bottom of the Posts settings page reads "Long press cards to open comments in the  - - " 

**To Reproduce**
1. Go to Settings
2. Click on Posts
3. Scroll down to Bottom

**Expected behavior**
Text wraps to next line

**Smartphone (please complete the following information):**
 - Device: Oneplus 6T
 - OS: Android 10

**Comment by laurencedawson** [comment]
Fixed for the next release.
