### ISSUE TITLE
[BUG] search result text is unreadable in light mode

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#231]
**Describe the bug**
When searching in app settings while having light mode turned on the search results' text is unreadable (as it is white and the background is white too)

**To Reproduce**
1. Go to 'Dark mode'
2. Check 'Light mode'
3. Go back to app settings overview
4. type something into 'Search settings'

**Expected behavior**
the text of the results should be visible

**Screenshots**
[search results](https://i.imgur.com/1zfQdyC.jpg)

**Smartphone:**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen 10.0.6
 - Browser DuckDuckGo 5.55.1
 - Version vv20 (beta 4)

**Additional context**
works fine in dark mode

**Comment by laurencedawson** [comment]
Fixed for the next release.
