### ISSUE TITLE
[BUG] Add comment button is always grey

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#232]
**Describe the bug**
The Add comment button is always grey, should probably only be gray in dark mode

**To Reproduce**
1. Go to 'Dark mode'
2. Check 'light mode'
3. Go to the comment section of a post

**Expected behavior**
Background of the Add comment button should be white

**Screenshots**
[error in light mode](https://i.imgur.com/rIwcL37.jpg)
[fine in dark mode](https://i.imgur.com/AXHFNlW.jpg)

**Smartphone (please complete the following information):**
- Device: OnePlus 7 Pro
- OS: Android 10, Oxygen 10.0.6
- Browser DuckDuckGo 5.55.1
- Version vv20 (beta 4)

**Additional context**
-

**Comment by laurencedawson** [comment]
This has since been fixed
