### ISSUE TITLE
[BUG] search icon is cut off at the top

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#233]
**Describe the bug**
the magnifying glass icon in the search settings bar is cut off at the top

**To Reproduce**
1. Go to 'app settings'

**Expected behavior**
icon not being cut off

**Screenshots**
[pic](https://i.imgur.com/haLVGrf.jpg)

**Smartphone (please complete the following information):**
- Device: OnePlus 7 Pro
- OS: Android 10, Oxygen 10.0.6
- Browser DuckDuckGo 5.55.1
- Version vv20 (beta 4)

**Additional context**
none

**Comment by laurencedawson** [comment]
Added a fix for the next release.
