### ISSUE TITLE
[BUG] Pressing back button in any subreddits search results page goes back to the Frontpage instead of that particular subreddit home

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#235]
Video (Old design & md2 beta 4) - https://imgur.com/gallery/aSNh2bi

I don't know whether this is a bug or it's intentional in the redesign, if it is then please add that old action again. It's annoying to find and select the subreddits again from the drawer. Thank you so much.

**Device information**

    Sync version: v20 (beta 4)    
    Sync flavor: dev    
    
    View type: Dynamic cards    
    Push enabled: false    
    
    Device: tissot_sprout    
    Model: Xiaomi Mi A1    
    Android: 9

**Comment by laurencedawson** [comment]
Fixed for beta 6
