### ISSUE TITLE
[BUG] old.reddit links open in browser if they have an age verification check

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#237]
**Describe the bug**
A Attempting to open an old.reddit link will open the app in the browser, if the page has an age verification check

**To Reproduce**
1. Go to https://old.reddit.com/over18?dest=https%3A%2F%2Fold.reddit.com%2Fr%2Fboobs
2. Be brought to browser, instead of opening page in app

**Expected behavior**
Page should be opened in app

**Smartphone (please complete the following information):**
 - Device: [Pixel 2XL]
 - OS: [Android 11 Public Beta 1 ]
 - Browser [chrome custom tabs]
 - Version [20 Beta 4]

**Comment by laurencedawson** [comment]
Fixed ya filthy animal.
