### ISSUE TITLE
[BUG] Dynamic Cards fail for some posts

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#238]
**Describe the bug**
Dynamic cards not working for some media posts. Behave as fixed height cards
I checked, my default view for all subs is dynamic cards. So that's not causing this issue.

**To Reproduce**
Couldn't find a pattern. But here are some example posts. Save them and see the post from your saved section.  

https://www.reddit.com/r/BikiniBottomTwitter/comments/h0hhie/_/

https://www.reddit.com/r/wholesomememes/comments/gyegp0/_/

https://www.reddit.com/r/memes/comments/gz5avz/_/

**Expected behavior**
Should see the dynamic cards view

**Screenshots**
https://imgur.com/aHYjUoH

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 10

**Comment by laurencedawson** [comment]
Closing as dynamic cards will be removed in the next release.
