### ISSUE TITLE
SUGGESTION/REQUEST: Option to mark posts as read once they have been voted on, even without opening said post

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#239]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An option to mark voted posts as read, even if post hasn't been opened

**Describe alternatives you've considered**
None

**Additional context**
Requested by a user in Discord

**Comment by laurencedawson** [comment]
Not sure I agree with this one and I think I'll close it for now.
