### ISSUE TITLE
[BUG] Clicking a notification doesn't open the app

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#243]
**Describe the bug**
When clicking on a notification from Sync it doesn not open the app, it just closes the Notification Shade

**To Reproduce**
1. Have a notification e.g. about a new comment reply
2. Click on the notification in the notification shade
3. Nothing happens

**Expected behavior**
The app should open up and either show the Messages tab with the unread notification or just go straight to that comment reply.

**Screenshots**
[Video](https://streamable.com/63qxke)

**Smartphone (please complete the following information):**
- Device: OnePlus 7 Pro
- OS: Android 10, Oxygen 10.0.6
- Browser: DuckDuckGo 5.55.1
- Version: vv20 (beta 4)

**Additional context**
None

**Comment by hmzuleta** [comment]
I'm pretty sure this only happens when you have multiple message notifications, from my experience.

**Comment by NickPfeiffer** [comment]
@hmzuleta Yes, you are right. It should open the Messages overview when clicking on the notification itself, when you have multiple message/reply notifications.
If you expand the notification and click one specific message/notification the app opens up.

**Comment by hmzuleta** [comment]
Yup, agreed @NickPfeiffer

**Comment by laurencedawson** [comment]
Fixed for the next release.
