### ISSUE TITLE
[BUG] Video glitch and app lockup on Android 11 Beta

### ISSUE THREAD

**Issue by Cwoo0** [laurencedawson/sync-for-reddit#244]
Only started happening after the latest Android 11 Beta. Previous Developer Preview was fine.

Steps to reproduce

Scroll down to a post that has an autoplay video. Let the video start playing. 

Click post and go to comments. 

Go back to main page.

Video will now be looping a small segment.

Scroll down.

When the video goes off screen the app locks up for about two seconds then continues as normal.  

**Device information**

    Sync version: v20 (beta 4)    
    Sync flavor: dev    
    
    View type: Full height cards    
    Push enabled: false    
    
    Device: crosshatch    
    Model: Google Pixel 3 XL    
    Android: 11

**Comment by laurencedawson** [comment]
I've seen similar complaints from other apps, think it might be an Android 11 issue. Hopefully.
