### ISSUE TITLE
[BUG]Back action while side navigation drawer is open affects the sub/window open. And not the drawer

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#245]
**Describe the bug**
Clicking back while drawer is open doesn't affect drawer, but the window behind it

**To Reproduce**
1. Open a sub, example r/redditsync
2. Open side navigation drawer
3. Click back
4. The drawer doesn't close. But behind the drawer, r/redditsync goes away to bring default sub

**Expected behavior**
Drawer should close and r/redditsync should stay

**Smartphone:**
 - Device: OnePlus 10
 - OS: Android 10

**Comment by laurencedawson** [comment]
Fixed for the next release.
