### ISSUE TITLE
[BUG] Can't change flair on subreddits

### ISSUE THREAD

**Issue by thezelenyy** [laurencedawson/sync-for-reddit#247]
**Describe the bug**
When I go to change subreddits a white box with white text appears with an incomplete list of flairs to choose from

**To Reproduce**
1. Go to any subreddit with flairs
2. Click on flairs
3. See error 

**Expected behavior**
A full and complete list of all the flairs a subreddit has. 

**Screenshots**
![Screenshot_20200613-155140](https://user-images.githubusercontent.com/66877104/84571862-18b99c00-ad8e-11ea-9d02-e1cde7ea6468.png)

**Smartphone (please complete the following information):**
 - Device: [Motorola G7 Power]
 - OS: [Android]

**Additional context**
I'm using dark mode and this has been a problem before the new UI update

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
