### ISSUE TITLE
SUGGESTION/REQUEST: Ability to share full size image when sharing post preview

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#248]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Ability to share full size image when sharing a post preview (it only shares a fixed-height preview)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by laurencedawson** [comment]
Actually yeah, I think the full sized image should be shared here. Added for the next release.
