### ISSUE TITLE
Some Redd.it videos download with mismatched filetype/extension

### ISSUE THREAD

**Issue by drhodesmumby** [laurencedawson/sync-for-reddit#25]
I'm not sure what triggers this currently (only one I've seen it on so far but I also don't download many videos, playing around with the URL hasn't revealed anything to me either) but on the below example the MP4 is downloaded but the extension is .gif. The video plays correctly in app and the image debugging log correctly detects it as an MP4 following initial parsing as a GIF.

Example post link: https://www.reddit.com/r/PixelArt/comments/gnyuki/_/
Video URL on post: https://preview.redd.it/b1i5gewax4051.gif?format=mp4&s=e5c03b88912f6fa4c1cc3c632d708311d9be9f27

Image debug log:
![Screenshot_20200523-164017_Sync Pro](https://user-images.githubusercontent.com/4113486/82734635-20000380-9d14-11ea-8584-11d8ff49c40d.png)

**Comment by laurencedawson** [comment]
Fixed for the next release.
