### ISSUE TITLE
[BUG] Imgur album doesn't open/returns error

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#250]
**Describe the bug**
Opening this album in the app just returns an error instead of opening it (works fine through the browser)

**To Reproduce**
1. Go to https://www.reddit.com/r/dankmemes/comments/h8w89u/_/futfq32?context=1000
2. Click on the link (https://m.imgur.com/gallery/NGsQAkh)
3. See error

**Expected behavior**
Album should open in the apps image view

**Screenshots**
[Error message](http://imgur.com/a/6ZgMjk3)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen OS 10.0.6GMA
 - Browser: DuckDuckGo
 - Sync for reddit version: vv20 Beta 4

**Additional context**
None

**Comment by laurencedawson** [comment]
URL is pre imgur API and sadly isn't supported.

**Comment by geominorai** [comment]
Can the URL not be re-written to https://imgur.com/NGsQAkh or https://i.imgur.com/NGsQAkh.png (or https://i.imgur.com/NGsQAkh.jpg since file extension did not matter) before parsing?
