### ISSUE TITLE
Add "Hide" to post preview context menu

### ISSUE THREAD

**Issue by JacobDB** [laurencedawson/sync-for-reddit#251]
**Is your feature request related to a problem? Please describe.**
It's annoying that I have to open a post to hide it. It took me quite a while to figure out where this option went.

**Describe the solution you'd like**
"Hide" should be added to the post preview context menu.

**Describe alternatives you've considered**
Opening the post to hide is a viable option, although annoying. I could also add the "hide" button to the post preview, but that moves the vote buttons further left, and I'd prefer them to be right aligned.

**Additional context**
![missing option to hide](https://user-images.githubusercontent.com/1123997/84797681-b811a580-afbf-11ea-83d2-52447cc6d08e.png)

**Comment by laurencedawson** [comment]
Actually if swipe to hide is enabled the option isn't shown here.

Disable swipe to hide if you want it to just appear here.

**Comment by JacobDB** [comment]
Just verified that I do have swipe to hide disabled, but it still doesn't appear here. Tried enabling it then disabling it just in case that was the issue, but that doesn't seem to be the case.
