### ISSUE TITLE
[BUG] Tapping the gesture bar when bottom nav is up goes to content behind it

### ISSUE THREAD

**Issue by eriktrinh** [laurencedawson/sync-for-reddit#253]
**Describe the bug**
Accidently tapping the gesture bar when trying to interact with the bottom nav will interpret the action as tapping the content behind the bottom nav bar.

**To Reproduce**
1. Have the bottom nav bar up while viewing a subreddit or profile
2. Tap on the gesture bar
3. It follows the content behind the bottom nav

**Expected behavior**
It should ignore the tap and do nothing.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/15272902/84830229-127a2880-aff7-11ea-8ee7-d2c4997123d3.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: 10
 - Browser: Chrome
 - Version: 20 beta 4

**Comment by laurencedawson** [comment]
Fixed for the next release.
