### ISSUE TITLE
[Bug] It always takes like 3-4 taps to open content from comments

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#255]
The thumbnail always consistently takes around 3 taps in order to successfully open the content into fullscreen when the comments is in view. Regardless of content type.

**Comment by laurencedawson** [comment]
Can't reproduce this. Let me know if you sill have the issue when beta 5 goes live,

**Comment by skff-err** [comment]
> Can't reproduce this. Let me know if you sill have the issue when beta 5 goes live,

it's working great now.
