### ISSUE TITLE
SUGGESTION : enter link in the search box and display all the posts that have that link listed after hitting search

### ISSUE THREAD

**Issue by devanshux** [laurencedawson/sync-for-reddit#257]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
when you search normally, you would enter the link in the search box and after hitting search sync would display all the post having the link regardless of the subs so that you can read all the

**Describe alternatives you've considered**
https://play.google.com/store/apps/details?id=chaitanya.im.searchforreddit
this app does the exact thing i am asking

**Additional context**

**Comment by laurencedawson** [comment]
Neat idea. Added for the next release
