### ISSUE TITLE
Bottomsheets should match background colour to bottom nav bar

### ISSUE THREAD

**Issue by drhodesmumby** [laurencedawson/sync-for-reddit#26]
RecklessDwark raised this - as bottom nav bar follows the Content background colour from Theme customisation it can result in the slide-up bottomsheets having a mismatched background colour, which is inconsistent with Google apps (Google News cited).

Bottomsheet:
![20200523_164913](https://user-images.githubusercontent.com/4113486/82734828-5be79880-9d15-11ea-9d3a-cebc9d7fbe70.png)

Navbar:
![20200523_164901](https://user-images.githubusercontent.com/4113486/82734831-5d18c580-9d15-11ea-8744-c424d750cf4b.png)

**Comment by laurencedawson** [comment]
Fixed for the next release.
