### ISSUE TITLE
[BUG] Deleting a favourite-d multi doesn't remove it from favourites section

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#262]
**To Reproduce**
1. Make a dummy custom feed with couple of subs
2. Favourite it
3. Delete it
4. Check favourite section

**Expected behavior**
Shouldn't appear in Favourites section

**Smartphone:**
 - Device: OnePlus 7
 - OS: Android 10

**Comment by laurencedawson** [comment]
Added for the next release.
