### ISSUE TITLE
[BUG] Overflow menu in subreddit sidebar has pire black background, and text is difficult to see

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#263]
**Describe the bug**
When opening the overflow menu in a subs sidebar bottomsheet, the background is pure black.

**To Reproduce**
1. Go to any subreddit sidebar
2. Click on the 3-dot overflow menu
3. See error

**Expected behavior**
Overflow menu respecting app theme
**Screenshots**
https://cdn.discordapp.com/attachments/685912289202798712/725721702453215232/20-06-25-22-38-12.mp4

**Smartphone (please complete the following information):**
Multiple phones

**Additional context**

**Comment by laurencedawson** [comment]
Fixed fixed fixed
