### ISSUE TITLE
[BUG] Opening redgif link in external browser opens v.redd.it link instead (beta 4)

### ISSUE THREAD

**Issue by Moleculor** [laurencedawson/sync-for-reddit#264]
Maybe something about my settings is screwy? But when I attempt to open a redgif link in an external browser (FIREFOX), it opens as a v.redd.it link.

Example (ALL OF THIS IS NSFW)

https://www.reddit.com/r/dirtysmall/comments/gzmf6y

Open that in browser rather than in app and it takes you to

https://v.redd.it/nyn8ztnlrv351/DASHPlaylist.mpd

Despite actually being

https://www.redgifs.com/watch/cautiousagitatedaquaticleech

Sync version: v20 (beta 4)    
Sync flavor: pro    

View type: Full height cards    
Push enabled: false    

Device: judyp    
Model: LGE LM-V350    
Android: 9

From: https://github.com/laurencedawson/reddit-sync-development/issues/2039

**Comment by laurencedawson** [comment]
This has since been fixed.
