### ISSUE TITLE
[BUG] New comment count only shows up when you click on a post

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#267]
**Describe the bug**
If you refresh the front page or a subreddit, new comment count doesnt show up in the pill until you click on a post and then refresh. 

**To Reproduce**
1. Go to any post and read a few comments. 
2. Exit the app
3. Re launch the app and find the post you visited. New comment count won't be shown. 
4. Click on the post and pull down to refresh. New comment count shows up in the comment pill.

**Expected behavior**
New comment count should show up on the front page, and subreddits.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by laurencedawson** [comment]
This has since been fixed,
