### ISSUE TITLE
[BUG] No "Select text..." window when long pressing text post

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#268]
**Describe the bug**
Long pressing a self post does not show the "Select text" popup.

**To Reproduce**
1. Go to any subreddit.
2. Open a self post (only text).
3. Long press the self post body.
4. No window to select the text is shown.

**Expected behavior**
Based on the v19 version, a popup or window should be shown with the "Select text..." title and a scrollable non-editable TextView with the post's text.
Example self post: https://www.reddit.com/r/redditsync/comments/hfma9t/sync_for_reddit_v20_beta_5/

**Screenshots**
Expected pop up window (taken using v19): https://i.imgur.com/5fkIm7q.jpg

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+ SM-G955F
 - OS: Android 9
 - Version 20 beta 5 Pro
 - View type: Fixed height cards    
 - Push enabled: false

**Comment by laurencedawson** [comment]
Make sure you have "long press selftext to select text" enabled (Settings > Posts)

**Comment by geominorai** [comment]
@laurencedawson This does not work for me either even with that setting enabled (Galaxy S9+, Android 10).

I would also appreciate an alternative like https://github.com/laurencedawson/reddit-sync-development/issues/1367

**Comment by hmzuleta** [comment]
> Make sure you have "long press selftext to select text" enabled (Settings > Posts)

I do have it enabled. I have the same issue as @geominorai.
![Screenshot_20200626-232443_Sync](https://user-images.githubusercontent.com/3502252/85914566-b25c6100-b804-11ea-8942-42fc5e5733ad.jpg)

**Comment by geominorai** [comment]
I think you accidentally closed the issue.

**Comment by hmzuleta** [comment]
But still present in beta 7.

**Comment by laurencedawson** [comment]
Fixed for the ext release.
