### ISSUE TITLE
[BUG] Gifs hosted on giphy don't have previews

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#269]
**Describe the bug**
It seems like gifs hosted on Giphy (media.giphy.com, for example) do not generate a preview/thumbnail

**To Reproduce**
1. Go to any subreddit.
2. Find a gif hosted on giphy.com

**Expected behavior**
Based on the v19 version, there should be a thumbnail on the post preview for the gif.
Example post: https://old.reddit.com/r/Wellthatsucks/comments/hb6c3h/they_might_need_a_new_phone/

**Screenshots**
Example post screenshot v19: https://i.imgur.com/Q7BTH6A.jpg
Example post screenshot v20: https://i.imgur.com/AapfJLz.jpg

**Smartphone:**
 - Device: Samsung Galaxy S8+ SM-G955F
 - OS: Android 9
 - Version 20 beta 5 Pro
 - View type: Fixed height cards    
 - Push enabled: false

**Comment by hmzuleta** [comment]
Bug still present in beta 7.

**Comment by laurencedawson** [comment]
Working fine here. Still having the issue?

**Comment by hmzuleta** [comment]
Hi, I still do, apparently. This is on beta 11: http://imgur.com/a/cdHC0M6

**Comment by laurencedawson** [comment]
Fixed for the next release.
