### ISSUE TITLE
[BUG] Persistent "No messages returned, retry" snackbar

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#271]
**Describe the bug**
It feels to me like whenever I reach the bottom of a post, I can't swipe right to dismiss the comments activity.

**To Reproduce**
1. Open the Messages window
2. Load the "Inbox unread" messages, while having no unread messages.
3. hit the back button and the snack-bar that says "No messages returned, retry" is kept on top of any activity, regardless if switched, and has no timeout on it. It is only removed by hitting the retry button, and is not affected by the Swipe down to update gesture either.

**Expected behavior**
The snackbar should go away when changing the foreground Activity.

**Screenshots**
Video example: https://i.imgur.com/WGufJdz.mp4

**Smartphone:**
 - Device: Samsung Galaxy S8+ SM-G955F
 - OS: Android 9
 - Version 20 beta 5 Pro
 - View type: Fixed height cards    
 - Push enabled: false

**Comment by laurencedawson** [comment]
Fixed for the net release
