### ISSUE TITLE
[SUGGESTION] Long press search icon to force keyboard, single tap for no keyboard

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#272]
**Is your feature request related to a problem? Please describe.**
If I only want to reopen something I have searched earlier, the keyboard is brought up to focus, so I must hide it before being able to access the search item.

**Describe the solution you'd like**
Maybe I just want to open the search dialog to open something I've searched for before, so I must hit the back button because my keyboard automatically goes up. The behavior I've seen in Instagram, for example, is that if you hit the Search button, the keyboard stays hidden. If you hold down the search button, however, it forces the keyboard to come up.

**Comment by laurencedawson** [comment]
Going to close this one as I'm happy with how it is now. Cheers.
