### ISSUE TITLE
[BUG] Border radius on OC label partially missing

### ISSUE THREAD

**Issue by xandervedder** [laurencedawson/sync-for-reddit#273]
Very small "bug".

**Describe the bug**
Border radius (top-left and top-right) of the OC label are missing in the card view.

**To Reproduce**
1. Go to any post with the OC label.
2. See the missing border radius.

**Expected behavior**
As a user I should see the correct border radius.

**Screenshots**
Card view:
![Screenshot_20200626-130217](https://user-images.githubusercontent.com/34238405/85850811-d3de2e00-b7ad-11ea-988c-26f9cbcd708b.jpg)

This "issue" is not present in the comment view: 
![Screenshot_20200626-130735](https://user-images.githubusercontent.com/34238405/85850990-27507c00-b7ae-11ea-97d1-dfd19bbe98f2.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10
 - Browser: FireFox
 - Version: Sync for reddit vv20 (beta 5)

Edit:
This seems to be happening only in the small cards view.

**Comment by xandervedder** [comment]
Now that I've had a second look at it, it looks like the title is cutting into the label.

**Comment by laurencedawson** [comment]
Fixed for the next release.
