### ISSUE TITLE
[BUG] Auto-hiding bottom bar doesn't wkrk unless both the auto-hide toolbar and bottom nav are activated.

### ISSUE THREAD

**Issue by koinupapi** [laurencedawson/sync-for-reddit#274]
**Describe the bug**
Auto-hiding bottom bar doesn't wkrk unless both the auto-hide toolbar and bottom nav are activated.

**To Reproduce**
1. Go to settings>General and click on "auto-hide bottom nav".
2. Return to posts page and scroll down. You'll see that it doesn't auto-hide the bottom nav bar.
3. Navigate to Settings > General, turn off auto-hide bottom nav and turn on auto-hide toolbar.
4. Return to posts page and scroll down. You'll see that it does indeed hide.
5. Navigate back to settings>general and activate both auto-hide toolbar and bottom nav.
6. Return to posts page and you'll see that now the bottom nav auto-hides.

**Expected behavior**
Bottom nav should auto-hide even when only the auto-hide bottom nav is selected, and isn't dependent on "auto-hide toolbar" being active.

**Screenshots**
No screenshots, but here is a link to a video I recorded of the bug.
https://mega.nz/file/ac4BHZwC#_UrzAUxuKn3Nd1fWGa1JkRmLwGO65qPTGRarAQUh5d8

**Smartphone (please complete the following information):**
 - Device: [LG Stylo 5]
 - OS: [Android 9]
 - Browser [Chrome]
 - Version [v 20 Alpha 6]

**Comment by laurencedawson** [comment]
Fixed for the next release. Thanks for the detailed changelog!
