### ISSUE TITLE
[SUGGESTION] Comment navigation bar concept, with collapse comments and reply button

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#275]
**Is your feature request related to a problem? Please describe.**
This behavior is not a problem, but it's the way it used to be back in v19, so I got used to it.

**Describe the solution you'd like**
I'd love to have a couple of new buttons in the comment navbar: the contract all comments button (left), and the reply OP button (right).
Current layout, v20 beta 6: https://i.imgur.com/N0qL9ya.jpg
Old layout, v19: https://i.imgur.com/EBk56Df.jpg
Proposed layout, v20 beta 7 (?): https://i.imgur.com/0iQsweE.png

**Comment by hmzuleta** [comment]
Made a new version, because the collapse comments icon used above doesn't have a counterpart in the [MD icon list](https://material.io/resources/icons):

* Proposed layout 2, collapse comments new icon: https://i.imgur.com/8sOXALm.png
* Proposed layout 2, expand comments: https://i.imgur.com/RYmKpFd.png

**Comment by devanshux** [comment]
i really like this. good job! i hope he considers it

**Comment by hmzuleta** [comment]
Bump :(

**Comment by laurencedawson** [comment]
@hmzuleta this has been added for v22!
