### ISSUE TITLE
[BUG] Saved v.redd.it videos missing time index

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#276]
**Describe the bug**
The v.redd.it videos downloaded or shared (direct) are missing a time index and some video players (e.g. on PC) cannot seek through it.  Desktop apps built on Chromium-based frameworks like Electron (e.g. Discord for PC) cannot play the video shared from Sync.

**To Reproduce**
1. Go to a v.redd.it video
2. Click on download
3. Transfer the video onto PC
4. Open in media player, e.g. Windows Media Player
5. Try to seek

**Expected behavior**
Video of any length should allow user to seek to any timestamp.
Video should be playable on Chrome and Chromium-based apps.

**Screenshots**
Video cannot seek or restarts to 0:00.
Video cannot play on Chrome or Chromium-based apps.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: V20 beta 6 (Pro)

**Additional context**
My main gripe is when I try sharing a Reddit video to Discord, only those on the Discord mobile app can watch hit but anyone on the PC app (Chromium-based) cannot.  Though strangely, the video plays and seeks fine when opened in Firefox.

**Comment by laurencedawson** [comment]
Unfortunately this is a limitation of the method used to download and combine video + audio on mobile.
