### ISSUE TITLE
[BUG] comment navbar auto hide setting is always on

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#277]
**Describe the bug**
"The comment navigation bar now has its own auto hide setting”. This setting appears to always be on.

**To Reproduce**
1. Go to Settings/Comments
2. Turn off the "Auto hide comment navigation bar" option
3. Open any post with 5+ comments.
4. Scroll down and notice the comment navbar is hidden on scroll.

**Expected behavior**
The comment navbar should respect the selected setting and stay visible at all times.

**Screenshots**
Video of the scenario: http://imgur.com/a/L8KXnQ1

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+ 
 - OS: Android 9
 - Version 20 beta 6

**Comment by laurencedawson** [comment]
Fixed for the next release
