### ISSUE TITLE
Allow the title bar to expand as I type

### ISSUE THREAD

**Issue by ghost** [laurencedawson/sync-for-reddit#279]
As it is now when I create a post and write in the title bar it stays as it is and it won't expand as I type more content into it. It becomes hard to know what's been type beyond what the default screen space allows and I have to scroll horizontally to view it, this is really hard when the title is really long and sometimes it just triggers the long press action menu as I swipe. 

![Screenshot_20200629_141553](https://user-images.githubusercontent.com/42088907/85993179-716f7280-b9e5-11ea-80aa-7b8c32be189c.jpg)

**Comment by laurencedawson** [comment]
Added for the next release
