### ISSUE TITLE
[BUG] Rotating video changes state of mute.

### ISSUE THREAD

**Issue by pqee** [laurencedawson/sync-for-reddit#280]
**Describe the bug**
Status of mute is reset when rotating video even though video continues.

**To Reproduce**
1. Go to video with sound (other than Youtube)
2. Unmute video and play
3. Rotate phone
4. State of the mute button will revert to the setting you have set under App Settings > Images > Video / GIF Playback > Mute when opening.

**Expected behavior**
Video continues to play and mute state stays the same as before the rotate.  Eg. If sound was on before then it should still be on after rotating. If sound was muted before then it should still be off after rotating. Instead it's reloading the mute state from App Settings.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Browser: Stock Chrome

- Sync version: v20 (beta 6)    
- Sync flavor: free    
- Removed ads: true 

**Additional context**

**Comment by geominorai** [comment]
This so happens if the app loses focus, like when opening Android's recent apps list, but going back to Sync not only remutes the video (while incorrectly showing the unmuted icon), it also restarts the video from the beginning.

**Comment by NickPfeiffer** [comment]
Same goes for just unmuting a video in the feed and then tapping on it to open it in fullscreen

**Comment by laurencedawson** [comment]
Fixed for the next release
