### ISSUE TITLE
EXTREMELY IMPORTANT REQUEST: Make Sync button on navbar a centred FAB

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#282]
Yeah, if you could just go ahead, and uhhh make the Sync button on the bottom navbar a sexy FAB, that'd be greaaat. Thanks.

![image](https://user-images.githubusercontent.com/31053171/86184497-58101880-bb02-11ea-9b04-640240c4596a.png)

**Comment by laurencedawson** [comment]
Hmmmmm closing for now. I think the outline icon is the better option!
