### ISSUE TITLE
[BUG] Tapping any link in-app that leads tk a specific subreddit triggers the "Random Subreddit" action (Beta 7)

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#283]
**Describe the bug**
Title

**To Reproduce**
1. Go to any "r/subreddit" link in-app
2. Click on it
3. Be brought to linked sub for a split second
4. "Random sub" action triggers
5. Be brought to different subreddit

**Expected behavior**
To be brought to the linked subreddit

**Screenshots**
https://cdn.discordapp.com/attachments/685912289202798712/727725918306435143/screen-20200630-232242.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11 Beta 1.5
 - Version: Sync Dev (Beta 7, Nightly)

**Comment by laurencedawson** [comment]
Fixed for beta 8
