### ISSUE TITLE
[BUG] Missing audio toggle for non-Reddit hosted videos in feed previews

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#284]
**Describe the bug**
The audio toggle icon on the feed currently only shows for Reddit-hosted videos but not for Imgur or Gfycat video that also have audio (and can play audio when opened).  Consequently, we also cannot tell if these video have audio without actually opening it.

(But sometimes Reddit-hosted videos are also missing the icon until it starts auto-playing the video in the preview.)

**To Reproduce**
1. Open a sub with Imgur or Gfycat videos with sound.

**Expected behavior**
The audio toggle icon should be shown on the feed consistent with Reddit-hosted videos.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser Firefox Beta
 - Version: v20 beta 6 (Pro)

**Comment by laurencedawson** [comment]
This is unfortunately a limitation of the reddit API.
