### ISSUE TITLE
Separate users and subs in recent searched & visited list

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#285]
**Is your feature request related to a problem? Please describe.**
Subs and users with icons are currently in the same list and indistinguishable.

**Describe the solution you'd like**
Add a separate list for recently searched/visited users

**Describe alternatives you've considered**
Indicator for whether the item is a user or sub, e.g. keeping the _r/_ or _u/_ or even a small _r_ or _u_ overlayed on the top-right corner of the sub/user icon.

**Comment by laurencedawson** [comment]
Added for the next release.
