### ISSUE TITLE
[BUG] Rotating video changes state of pause

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#287]
**Describe the bug**
Changing the phone orientation between portrait and landscape mode unpauses paused videos.

**To Reproduce**
1. Open a video.
1. Pause the video.
2. Rotate the screen.

**Expected behavior**
The video should have remained paused in the last position of the video it was in.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v20 beta 6 (Pro)

**Comment by NickPfeiffer** [comment]
Same goes for just unmuting a video in the feed and then tapping on it to open it in fullscreen

**Comment by laurencedawson** [comment]
Fixed for the next release
