### ISSUE TITLE
[BUG] Seeking video changes state of pause

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#288]
**Describe the bug**
Moving the video seek slider unpauses paused videos.  The play/pause button is also broken following this until after one more press.

**To Reproduce**
1. Open a video.
1. Pause the video.
2. Click somewhere on the seek bar.

**Expected behavior**
The video should have remained paused but in the new position of the video.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v20 beta 6 (Pro)

**Comment by laurencedawson** [comment]
Fixed for the next release.
