### ISSUE TITLE
[BUG] Google image/video search not working

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#289]
**Describe the bug**
The image search feature leads to a plain Google search main page with no search terms.

**To Reproduce**
1. Open an image or video from a sub
2. Expand the context menu (three vertical dots).
3. Click on the magnifying glass search icon.

**Expected behavior**
Some kind of reverse image search should have opened.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v20 beta 6 (Pro)

**Comment by laurencedawson** [comment]
Only works with chrome I'm afraid.
