### ISSUE TITLE
BUG: Opening animation flash/flicker returning from previous Alpha Build

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#29]
https://cdn.discordapp.com/attachments/685912289202798712/713492804428496926/2020_05_22_16_43_512.mp4

Upon app opening, main feed screen flashes for a moment, before opening animation is complete. First found in Alpha 10, later fixed, returned in Alpha 18

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/16
