### ISSUE TITLE
Option to not auto-focus search text field on search page

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#290]
**Is your feature request related to a problem? Please describe.**
Currently opening the Search tab automatically steals focus onto the text field and thus opening the keyboard, which covers up the lower part of the screen.  This interrupts opening the page just to look up history every single time.

The focus is also re-stolen every time we drag to scroll the _recent search & visited_ list back to the top (but not enough to trigger closing the whole pull-up menu) if we have a long search or view history.

**Describe the solution you'd like**
1. Add an option for whether or not to auto focus to the text field when opening the tab.
2. Not re-steal focus when scrolling to the top of the list.

**Describe alternatives you've considered**
Or just not steal focus at all.  We expect the keyboard to pop up when we click on a text field, not suddenly appear by itself unprovoked every time.

**Comment by hmzuleta** [comment]
Hey @geominorai, @laurencedawson closes a similar suggestion I opened: https://github.com/laurencedawson/sync-for-reddit/issues/272

He says he's happy with the way it is. :(
I would like to to he behave like Instagram's search button: single tap = the search window is shown with precious searches, long press = keyboard pops up.

**Comment by laurencedawson** [comment]
Added this as an option (there will be a little three dots menu at the top of the search section)
