### ISSUE TITLE
[BUG] Externally launched activities don't go back to their launcher, rather within Sync itself

### ISSUE THREAD

**Issue by efraimbart** [laurencedawson/sync-for-reddit#291]
**Describe the bug**
Opening an external link into Sync breaks you out of the flow and "traps" you in Sync

**To Reproduce**
1. Go to Google
2. Search for anything within Reddit
3. Click on a result
4. Attempt to navigate back, via back button or dragging back

**Expected behavior**
Sync should allow you to navigate backwards to the intent launcher as it does in the stable version

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 10

**Comment by laurencedawson** [comment]
Cant replicate this.

**Comment by efraimbart** [comment]
@laurencedawson Replication video https://streamable.com/w3t3nb

**Comment by laurencedawson** [comment]
I actually am going to close this as this is the desired behaviour.

**Comment by efraimbart** [comment]
That's not how it worked before the beta, it also doesn't always work this way currently, plus I personally strongly prefer it not this way.
