### ISSUE TITLE
[BUG] YouTube video playback pause is inconsistent when pulling down the notification shade.

### ISSUE THREAD

**Issue by koinupapi** [laurencedawson/sync-for-reddit#292]
**Describe the bug**
when you're watching a YT video in the sync app, it seems to be coded to pause when the notifications shade is brought down, but it seems to be highly inconsistent with the timing of it. Sometimes, it pauses immediately when I pull it down. Sometimes, it takes 2 seconds to pause.

**To Reproduce**
1. begin streaming a YT video in the sync app.
2. Bring down your notification shade
3. Video will pause randomly between immediately after bring the shade down, or up to 2 seconds after (in my testing it never went longer than 2 seconds.)
4. Okay the video again, and repeat step 2 to see if it is inconsistent with you as well.

**Expected behavior**
if the video is supposed to pause when not in focus, maybe make the timing of the pause a little more consistent?

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [LG Stylo 5]
 - OS: [Android 9]
 - Browser [Chrome]
 - Version [83.0.4103.106]

**Additional context**
It isn't really an app breaking issue, but seems to be a bug nonetheless :)

Sidenote: while trying to record a video of it to show you, it was always consistent with pausing at 1 second. So, maybe my phone just sucks? IDK.

**Comment by laurencedawson** [comment]
Unfortunately I have no control over the youtube player.
