### ISSUE TITLE
[BUG] Sidebar Quick Action doesn't do anything

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#293]
**Describe the bug**
The new Quick Action for Show Sidebar doesn't do anything, as opposed to the button on the bottom sheet that pops up after long pressing the Posts icon (house, left side bottom posts navbar). This happens at any subreddit that is not the main subreddit, e.g. /r/All.

**To Reproduce**
1. Go to any subreddit's main page.
2. Click on the Quick Actions' Sidebar button.

**Expected behavior**
The sidebar for the current subreddit should be shown.

**Screenshots**
Video example: https://imgur.com/a/joNBOow

**Smartphone:**
 - Device: Samsung Galaxy S8+ SM-G955F
 - OS: Android 9
 - Version 20 beta 7
 - View type: Fixed height cards    
 - Push enabled: false

**Comment by laurencedawson** [comment]
Fixed for the next release
