### ISSUE TITLE
[BUG] Search sub button misaligned and oversized

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#295]
**Describe the bug**
Search buttons are oversized and do not respect base font size setting to the extent the text on the buttons do not fit in one line and cause the buttons to misalign.

**To Reproduce**
1. Open a sub
2. Click Search

**Expected behavior**
Textbox and buttons should be aligned and not take too much space relative to the text box and recent list.
Buttons should also follow base font size.

**Screenshots**
![Image](https://i.imgur.com/p6ek2ti.jpg)

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: V20 beta 7 (Pro)

**Comment by laurencedawson** [comment]
Fixed for the next release.
