### ISSUE TITLE
[BUG] Opening Subreddit from a post opens a random subreddit

### ISSUE THREAD

**Issue by dabcus** [laurencedawson/sync-for-reddit#296]
**Steps to reproduce** 
1. Click on the three dots of a post on your frontpage
2. Select the button which correspond to the subreddit of the post
3. You will get sent to a different subreddit

**Expected behavior** 
You will get sent to the corresponding subreddit of the post 

Device: Huawei P30 Pro
Version: v20 (beta 7)

**Comment by fessmm** [comment]
Just tested, can confirm

**Comment by fessmm** [comment]
![Polish_20200702_111810719](https://user-images.githubusercontent.com/19999039/86340816-c6192480-bc55-11ea-945c-e174e4650820.png)
Also happens when you click here

**Comment by dabcus** [comment]
Also happens when you click a subreddit in a comment
