### ISSUE TITLE
[BUG] Recents doesn't save on exiting of the app. Even though cache is cleared every other day

### ISSUE THREAD

**Issue by oathzed** [laurencedawson/sync-for-reddit#297]
**Describe the bug**
Recents doesn't save on closing of the app, it does work for RecklessDwark though. He's using same phone and OS

**To Reproduce**
1. Go to posts and look at one
2. Click on recents in the bottom nav, see it's been added
3. Exit app
4. Open app and look at recents, it's gone

**Expected behavior**

The recents will be kept until the cache is cleared

**Smartphone (please complete the following information):**
 - Device: pixel 2
 - OS: Android 11 beta 1.5
 - Browser chrome
 - Version 83.0

**Comment by laurencedawson** [comment]
Intentional and the way its always been.
