### ISSUE TITLE
[Feature Request] Clicking on the "Posts" button should refresh subreddit

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#298]
When you're viewing a subreddit and you use the "Posts" button in the bottom bar to return to your default sub, it should refresh the default sub. I find myself using this button frequently and always need to refresh the default sub upon return.

**Comment by RecklessDwark** [comment]
Tapping the posts button is reserved for bringing a user to the top of a subreddit, and returning a user to their default sub. You can access refresh from the quick action menu

**Comment by Nxt3** [comment]
Yes, bit upon bringing you back to the default sub, it should refresh too. Only in that instance. 'cause after returning to the default after a while in the app, the content on your default is usually out of date anyways.

**Comment by devanshux** [comment]
> 
> 
> Yes, bit upon bringing you back to the default sub, it should refresh too. Only in that instance. 'cause after returning to the default after a while in the app, the content on your default is usually out of date anyways.

i disagree. its nice how it is. i like how it keeps track of where i was

**Comment by laurencedawson** [comment]
I think this might get a little confusing.
