### ISSUE TITLE
Watched threads get deleted when clearing cache/updating app

### ISSUE THREAD

**Issue by rvictorr** [laurencedawson/sync-for-reddit#3]
The list of watched threads is stored in cache and thus gets deleted when the cache is wiped and sometimes when Sync is updated.

Scenario (steps to reproduce)

1. Update Sync or wipe cache

Result(s)

User>Watching list is empty

**Comment by laurencedawson** [comment]
Added a rule to not clear the list when updating.

**Comment by rvictorr** [comment]
Reopening this, the watched list still gets deleted when clearing the cache. Is this intended behavior?
