### ISSUE TITLE
[BUG] [Beta] 'Hide Post' missing from Post Options context menu / popup

### ISSUE THREAD

**Issue by StrangelyTyped** [laurencedawson/sync-for-reddit#300]
**Describe the bug**
Previous versions included a 'hide post' option in the dropdown/overflow menu in the corner of each post in the subreddit view. The beta version appears to be missing this option.

![Screenshot_20200704-141715](https://user-images.githubusercontent.com/16519546/86513380-a7f02780-be01-11ea-84bf-47f6c7f77e18.jpg)
![Screenshot_20200704-141928](https://user-images.githubusercontent.com/16519546/86513381-a888be00-be01-11ea-90d2-34527c125d58.jpg)

**Comment by RecklessDwark** [comment]
This is intended, if you have the hide post button (the "X" button) enabled, then hiding posts from the overflow menu doesn't appear. If you disable the hide post button, the option will then appear in the overflow menu

**Comment by StrangelyTyped** [comment]
I do not have that button enabled. I just tried enabling and disabling it and the option still is not listed in the menu

**Comment by StrangelyTyped** [comment]
To add: it's not present in the subreddit view (including all/frontpage etc), but is in the menu in the post view regardless of whether the button is enabled or not (as the save/share options also seem to be)

**Comment by RecklessDwark** [comment]
Can't reproduce, what flavor (Pro, Free, Dev) are you using, and what beta version

**Comment by RecklessDwark** [comment]
![Screenshot_20200704-101050](https://user-images.githubusercontent.com/65828824/86514198-a95c2880-bdde-11ea-85ec-cba4ca7019fa.png)
Working for my on Dev (Beta 8)

**Comment by StrangelyTyped** [comment]
Free (with pro IAP), v20 Beta 8. I've cleared storage, checked it both logged in and logged out, rolled back to v19 then forward to v20b8 again, it's just not there.

![Screenshot_20200704-151620](https://user-images.githubusercontent.com/16519546/86514437-08836280-be0a-11ea-8794-77d54735000d.jpg)

**Comment by laurencedawson** [comment]
If you have swipe to hide enabled it wont be shown in that menu.

Disable swipe to hide and it will be there.

**Comment by StrangelyTyped** [comment]
I do not have that feature enabled. I tried enabling and disabling it but the option is still absent
