### ISSUE TITLE
[Feature request] Add "ignore anonymous profile" for account toggle button

### ISSUE THREAD

**Issue by oathzed** [laurencedawson/sync-for-reddit#302]
When pressing the account toggle button from the sync icon, it would be nice to just be able to switch fast through the two accounts I have, instead of going through to anonymous aswell.

**Comment by scottjfer** [comment]
I wish you could disable the anonymous account, I swear I keep accidentally hitting it when I want to switch user accounts!

**Comment by askeeve** [comment]
Just commenting to add interest to this request.  The button has a lot of potential and is an awesome idea but having to toggle through signed out kills its utility for me.

**Comment by laurencedawson** [comment]
This is now the default behavior for the next release.
