### ISSUE TITLE
[BUG] Search sort resets upon search term change

### ISSUE THREAD

**Issue by Ali60351** [laurencedawson/sync-for-reddit#305]
**Describe the bug**
Search sort reverts to `Relevance` every time Search Term is changed.

**To Reproduce**

1. Go to any subreddit
2. Select Search and then search for something within the said subreddit
3. The result will be search based upon your search term with Search sorting set to `Relevance`.
4. Change the sorting to `New > All`.
5. The touch the title on the top to change your search term.
6. After hitting search in the previous step the search term updates but it also causes the search sorting to revert to `Relevance`.

**Expected behavior**
The search sorting to remain the selected sorting instead of reverting to `Relevance` on every search term change.

**Screenshots**

![Screenshot_20200713-004234](https://user-images.githubusercontent.com/11636916/87255310-248aa200-c4a3-11ea-8646-2bd573543961.jpg)

![Screenshot_20200713-004258](https://user-images.githubusercontent.com/11636916/87255318-3b30f900-c4a3-11ea-897b-3128f87d6d36.jpg)

![Screenshot_20200713-004310](https://user-images.githubusercontent.com/11636916/87255335-63b8f300-c4a3-11ea-864a-09f2e8a38b74.jpg)

![Screenshot_20200713-004330](https://user-images.githubusercontent.com/11636916/87255352-716e7880-c4a3-11ea-9010-c81a3c0f1e37.jpg)

![Screenshot_20200713-004547](https://user-images.githubusercontent.com/11636916/87255366-877c3900-c4a3-11ea-8ea0-d28183eb0ffc.jpg)

![Screenshot_20200713-004557](https://user-images.githubusercontent.com/11636916/87255386-bf837c00-c4a3-11ea-88c0-a2383d60d253.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: OxygenOS 10.3.4 - Android 10
 - Browser: Chrome (Stock), Opera Beta, Firefox Nightly, Firefox Beta. No browser set as default.
 - Version: v20 (beta 8)

**Additional context**

On a separate note I'd like to request an option to set default search sorting if possible.

**Comment by Ali60351** [comment]
@laurencedawson Can I get an update regarding this issue please?

**Comment by laurencedawson** [comment]
It's on the issue tracker but low priority for now.

**Comment by laurencedawson** [comment]
@Ali60351 done! Only took 2 years...
