### ISSUE TITLE
[BUG] Inconsistent icons for image bottom sheet

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#306]
**Describe the bug**
The Share and Comments icons on the image bottom sheet are not consistent with the ones used for posts.

**To Reproduce**
1. Open an image full screen
2. Swipe up the bottom sheet
3. Compare icons with the post's icons.

**Expected behavior**
Icons from the bottom sheet should be the same from the post's icons.

**Screenshots**
Post icons: https://i.imgur.com/Le9Z4qh.jpg
Image bottom sheet icons: https://i.imgur.com/5RfHiIr.jpg

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+
 - OS: Android 9
 - Version 20 beta 9

**Additional context**
It's a really minor thing ;)

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers!
