### ISSUE TITLE
[BUG] GIFV load as image if link ends in "jpg"

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#307]
**Describe the bug**
For some reason, some IMGUR gifs have a ".jpg" in the end of the link, even if they are a GIFV, causing the app to load that as a static image

**To Reproduce**
1. Go to https://www.reddit.com/r/DestinyTheGame/comments/hqww2l
2. Click on "Gifv Version thanks to Kyle"
4. See error (loads as static image

**Expected behavior**
Load a GIFV (animated image)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - OS: Android 10, July '20 security update
 - Version v20 beta 8

**Comment by laurencedawson** [comment]
Fixed
