### ISSUE TITLE
[BUG] domain mishmash in parenthesis

### ISSUE THREAD

**Issue by moviuro** [laurencedawson/sync-for-reddit#308]
**Describe the bug**
A link to https://blog.netbsd.org has the following text in parenthesis: (blogbsd.org)

**To Reproduce**
1. Go to 'https://www.reddit.com/r/BSD/comments/hsaba4/gsoc_reports_benchmarking_netbsd_first_evaluation/'

**Expected behavior**
Correct domain in parenthesis

**Screenshots**
https://i.imgur.com/NAZbBOD.jpg

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: Android 10
 - Browser N/A
 - Version v20 beta 9

**Additional context**
It's probably a very bad idea to manipulate the domain, other than removing an extraneous `^www.`

**Comment by laurencedawson** [comment]
This was due to trying to clean the url to minimize whats been shown. Fixed the logic for the next release.
