### ISSUE TITLE
[BUG] New comments count in post view are being shown for posts I'm seeing for the very first time

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#309]
**Describe the bug**
Posts I've never seen shouldn't display"new" comments count

**Screenshots**

**Smartphone:**
 - Device: OnePlus 7
 - OS: Android 10
 
 [Sync Beta 11]

![Screenshot_20200719-012110.jpg](https://user-images.githubusercontent.com/55349349/87860890-b2accf80-c95e-11ea-9d84-53d975fb5d09.jpg)

**Comment by laurencedawson** [comment]
Pretty sure is only happening when the posts have been loaded into sync before. Could be the case that you saw them in other lists but never actually scrolled down to them?

**Comment by Fuhrmann** [comment]
Happening here too. But only with posts that I've already scrolled. Even if I did not opened the post, the new comment count appears.

**Comment by Fuhrmann** [comment]
There is something going on.

Here in the first screenshot you can see the comment count:

![Screenshot_20200727-115443.png](https://user-images.githubusercontent.com/1160365/88563532-15a60280-d000-11ea-89e4-147766550de4.png)

Then, after I reload the page, it's gone:

![Screenshot_20200727-115456.png](https://user-images.githubusercontent.com/1160365/88563558-1dfe3d80-d000-11ea-8289-1df153afd6c3.png)

**Comment by Fuhrmann** [comment]
The comment count should disappear after I reload the page? I though it would disappear after I open the post.

**Comment by Fuhrmann** [comment]
Here is what it looks like:

https://imgur.com/a/kNI42XZ

**Comment by laurencedawson** [comment]
The only way this is happening is when sync has previoualy loaded the post (you might not have viewed it but if its loaded into the cache it will use the data).

Closing as not really an issue.
