### ISSUE TITLE
Provide some haptic feedback when dragging down through alphabet sidebar on subreddit bottomsheet

### ISSUE THREAD

**Issue by drhodesmumby** [laurencedawson/sync-for-reddit#31]
Requested by EightBitBoot, when scrolling through the subreddit bottomsheet by dragging down the alphabet sidebar, haptic feedback would be provided.

![Screenshot_20200523-145916](https://user-images.githubusercontent.com/4113486/82740940-4db17080-9d45-11ea-9752-46c1cc68a815.jpg)

**Comment by laurencedawson** [comment]
I've enabled haptic but it doesn't seem to play nice on my device, needs testing but I'll close for now.
