### ISSUE TITLE
[UX Feedback] Seperate the buttons for Upvote and Downvote

### ISSUE THREAD

**Issue by ShatteredPixel** [laurencedawson/sync-for-reddit#310]
I know what you'll say. Please at least listen to me. Thank you! 

Merging the Upvote and Downvote buttons is I think is not a very good UX decision. Because no app does this and for that matter any website, I have never seen anything like this before! See Facebook, YouTube, or any website that features like and dislike buttons or even Reddit's official website and apps. No one had them merged, don't you think there's a reason for this? 

Upvote and Downvote buttons are a _very_ central part of the Reddit as a whole, I don't think any sort experiment should be done on them. They are _not at all_ like YouTube or Facebook's like and dislike buttons or any websites'. Reddit is entirely based on different concept when its Upvote and Downvote buttons are considered, I think. Sync for Reddit merges both Upvote and Downvote buttons and in doing so it goes one step further and makes the both buttons for Upvote and Downvote same coloured and to be really frank it feels so very weird. Why would someone make them same colour, for example; imagine if YouTube or Facebook merged both of their like and dislike buttons and made them same coloured (I don't even wanna imagine it 😅)! 

If this lands in the stable channel, not only any new users to Reddit itself be confused but for once any Reddit user who is using Reddit for a while.

I know you're making it like this to be consistent with the design language of the app. But I think if the User Experience (UX) is sacrificed in doing so; then I think, it's not worth it. As UI & UX should go hand-in-hand, and one should always compliment another. And as a developer of such a stunningly beautifully designed Android app you must have already known it. I don't think I need to tell anymore about it.   

Thanks for listening to me. :)

**Comment by ShatteredPixel** [comment]
Unsubscribing from this issue because I don't think anybody will listen to me here.

Thank you! :)

**Comment by laurencedawson** [comment]
@ShatteredPixel there is an option to disable this.

Enable classic card in the settings.
