### ISSUE TITLE
[BUG] Comments don't animate in when posts have few comments

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#312]
When opening posts with few comments (usually below 10), the comments won't animate in at all.

**Comment by laurencedawson** [comment]
Unable to reproduce this. Any chance of a screen recording?

**Comment by Nxt3** [comment]
https://photos.app.goo.gl/g2pDjAiE14fGUEe86

Sure thing

**Comment by laurencedawson** [comment]
Unable to reproduce. CLosing for now,

**Comment by Nxt3** [comment]
[This is still happening on v20 (beta 28)](https://photos.app.goo.gl/apHAjCWqamLk3ZXL9).

These are my card settings if that helps:

![Screenshot_20210118-201905.png](https://user-images.githubusercontent.com/2940826/104979783-1cbc3500-59d3-11eb-8ac2-e505e3022ced.png)

![Screenshot_20210118-201914.png](https://user-images.githubusercontent.com/2940826/104979795-2180e900-59d3-11eb-8521-03db757c6390.png)
