### ISSUE TITLE
[BUG] App crashes when you long press Search in Messages

### ISSUE THREAD

**Issue by Kiteu** [laurencedawson/sync-for-reddit#314]
**Description**
When you open messages on bottom navigation and hold search (on bottom navigation too) app will crash.

**Scenario (steps to reproduce)**
1. Open messages;
2. Hold search.

**Result(s)**
App crashes.

**Device information**

Sync version: v20 (beta 11)    
Sync flavor: free    
Removed ads: false    

View type: Dynamic cards    
Push enabled: true    

Device: HWBKK-Q    
Model: HUAWEI BKK-L21    
Android: 8.1.0

**Comment by laurencedawson** [comment]
Fixed for the next release.
