### ISSUE TITLE
[BUG] While browsing subreddits pages after page 1 don't load

### ISSUE THREAD

**Issue by Kiteu** [laurencedawson/sync-for-reddit#315]
**Description**

When I scroll through subreddits and page ends it shows "No more posts were loaded" and shows empty pages when you try to load again.

**Scenario (steps to reproduce)**
1. Go to any subreddit;
2. Scroll to the end of the page 1.

**Expected behavior**
I expected all pages to load.

**Screenshot**
https://i.imgur.com/YVTCQML.jpg

**Device information**

Sync version: v20 (beta 11)    
Sync flavor: free    
Removed ads: false    

View type: Dynamic cards
Push enabled: true    

Device: HWBKK-Q    
Model: HUAWEI BKK-L21    
Android: 8.1.0

**Comment by laurencedawson** [comment]
Are you using a shit load of filters by any chance?

**Comment by Kiteu** [comment]
All filters are default

>
