### ISSUE TITLE
[BUG] Blurry preview in some images

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#316]
**Describe the bug**
There is a blur in the image preview using dynamic heigh cards with just a few posts (only 1 I've seen so far

**To Reproduce**
Steps to reproduce the behavior, using dynamic height cards
1. Go to /r/Dark
2. Search post titled "[No Spoilers/ Winden High School. But which year?"
3. See blurry preview, touch to open image in full

**Expected behavior**
Non blurry preview

**Screenshots**
Refer to screenshot: https://discordapp.com/channels/684912692485554230/684912692489748484/735229581459456135

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10, July 2020 update
 - Browser Chrome
 - Version 20 beta 9

**Comment by laurencedawson** [comment]
I've since increased the resolution of preview images.
