### ISSUE TITLE
[Feature request] Dim self text on read posts 

### ISSUE THREAD

**Issue by zachberger** [laurencedawson/sync-for-reddit#317]
**Is your feature request related to a problem? Please describe.**
Sync for Reddit already includes functionality to Dim titles, and images when the post is read. When using card view, the self text is in bright white. When scrolling quickly, I see bright white text and think there is an unread post and I stop my scrolling, only to find out its just a self text post I've already read.

**Describe the solution you'd like**
Self-text is dimmed, like the title, once a post is read.

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Additional context**
Attaching sample photo: 
![Screenshot_20200719-135834](https://user-images.githubusercontent.com/1634878/88105978-9a54d480-cb59-11ea-9b15-d27e544c945f.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release

**Comment by zachberger** [comment]
![Screenshot_20201119-185922](https://user-images.githubusercontent.com/1634878/99752580-72d72f80-2a99-11eb-9c4a-25d75ba44479.jpg)

Which release was this in? In beta 22 read self text appears to still be same brightness as unread self text.

    Sync version: v20 (beta 22)    
    Sync flavor: pro    
    
    View type: Full height cards    
    Push enabled: false    
    
    Device: OnePlus7T    
    Model: OnePlus HD1905    
    Android: 10
