### ISSUE TITLE
[BUG] Biometrics Lock Failure & Circumvention

### ISSUE THREAD

**Issue by Brownie18** [laurencedawson/sync-for-reddit#318]
**Describe the bug**
Sync Dev V20 Beta 11 - used Sync's Biometrics/Password required to open app setting, and has worked great until this Beta release. Biometrics work fine in all other instances across the phone. I've been unable to open the application since installing this beta release. Out of curiosity, I clicked on a reddit link and chose Sync to handle it. I was able to open it in the application, and get to both of my accounts just fine. I 

**To Reproduce Biometrics Failure**
1. Use biometrics to lock app (maybe it's a Samsung/Samsung Pass issue?)
2. reboot phone and try to login, hopefully the biometrics prompt occurs
3. ...failure to login? Go to step 4
4. Click on external reddit link, and use Sync to handle it (is sync holding login, but unable to use it on the prompt screen?)

**To Reproduce only Biometrics Circumvention**
1. have sync locked via its settings using biometrics
2. confirm biometrics are needed to open app
3. back out and click on external reddit link, and use Sync to handle it

**Expected behavior**
I expected:

1. The app to open when using biometrics or password, but it failed

2. The biometrics to reject me when using Sync to handle an external reddit link

**Screenshots**
Don't have any screenshots, but I do have a logcat txt file of the biometrics failing to login. 
[20200719_SyncLogcat.txt](https://github.com/laurencedawson/sync-for-reddit/files/4956880/20200719_SyncLogcat.txt)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 10
 - Browser N/A
 - Version Dev V20 Beta 11

**Additional context**
Will try to reproduce circumvention w/ logcat shortly

**Comment by Brownie18** [comment]
Additional Logcats attached. Circumvent_loginAttempt.txt was an attempt to actually use the fingerprint reader. Circumvention_noLogin was to confirm asking for fingerprint, backed out and opened link to get inside Sync
[Circumvent_loginAttempt.txt](https://github.com/laurencedawson/sync-for-reddit/files/4957089/Circumvent_loginAttempt.txt)
[circumvent_noLogin.txt](https://github.com/laurencedawson/sync-for-reddit/files/4957090/circumvent_noLogin.txt)

**Comment by laurencedawson** [comment]
Beta 12+ reverted the changes to the biometric library.

Sharing to sync will now use the biometric login from v19.
