### ISSUE TITLE
[BUG] Long pressing a link in a comment should show the whole link

### ISSUE THREAD

**Issue by qhnguyen27** [laurencedawson/sync-for-reddit#321]
**Describe the bug**
When long pressing a link in a comment, the pop-up that appears on the bottom doesn't show the whole link.

**To Reproduce**
1. Go to a comment containing a link
2. Long press on the link
3. See pop-up not showing the whole link

**Expected behavior**
The full link should be shown.

**Screenshots**
![Screenshot_20200722-003908_Sync](https://user-images.githubusercontent.com/26371054/88225427-787e4f00-cc38-11ea-8432-138a9e944a35.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Version: v20 (beta 11)

**Additional context**

> **Device information**

    Sync version: v20 (beta 11)    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Full height cards    
    Push enabled: false    
    
    Device: dreamqltecan    
    Model: samsung SM-G950W    
    Android: 9

**Comment by laurencedawson** [comment]
Agreed. Added for the next release.
