### ISSUE TITLE
[BUG, CRASH] Using sidebar shortcut through sync button crashes the app when in user profile

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#322]
Reproduction:

1. Go to user profile (any)
2. click sync button sidebar shortcut
3. crash

expected result:

Opens user profile sidebar

**Comment by skff-err** [comment]
it also shows this before crashing a few seconds later

![Screenshot_20200726-011655582.jpg](https://user-images.githubusercontent.com/66136655/88462501-573e8c80-cede-11ea-9214-3aedab87a84b.jpg)

**Comment by omaralsharif** [comment]
I'm getting the exact same issue, as can be seen in the screenshot below.

**BUILD:** Sync of Reddit v20 (beta 13)
**DEVICE:** Samsung SM-G960 on Android 10

![SCREENSHOT](https://user-images.githubusercontent.com/62202583/89718822-e3ff4500-d9ca-11ea-8f9e-de6d33951a6c.png)

**Comment by laurencedawson** [comment]
Fixed for the next release.
