### ISSUE TITLE
[BUG] Post titles occasionally have missing words

### ISSUE THREAD

**Issue by rafaeldamasceno** [laurencedawson/sync-for-reddit#323]
**Describe the bug**
Post titles occasionally have missing words using the small cards view. I'm not sure if the bug is limited to this view.

**To Reproduce**
1. Scroll down on any feed with the small cards view
1. Titles will sometimes not have a word at the end

**Expected behavior**
It's expected that the full title appears in the card view.

**Screenshots**
Occasionally, the last word of the post is missing.
![image](https://user-images.githubusercontent.com/6492427/87854226-6040c400-c908-11ea-91a5-d8ffc6a5bc86.png)
Opening the post and coming back or refreshing sometimes helps.
![image](https://user-images.githubusercontent.com/6492427/87854317-0c82aa80-c909-11ea-80de-30d8420e1068.png)
However, other times, no matter what you do, the word will always be missing.
![image](https://user-images.githubusercontent.com/6492427/87854256-9b42f780-c908-11ea-886a-824dbd3d1a75.png)
![image](https://user-images.githubusercontent.com/6492427/87854261-a0a04200-c908-11ea-8e5f-c8f9dca8ad03.png)

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: LineageOS 17.1
 - Browser: Chrome
 - Version: Sync for Reddit Pro v20 (beta 9)

**Additional context**
I've seen this bug for at least one year on the stable branch. I also think it was not limited to the title, but the line underneath it (with the flair or subreddit being missing).

**Comment by laurencedawson** [comment]
Not had this reported for some time. Going to close in the hope its fixed!

**Comment by rafaeldamasceno** [comment]
I was going to say the same, but then this happened yesterday on b27...

![Screenshot_20210117-022614_Sync_Pro](https://user-images.githubusercontent.com/6492427/104839791-6ade1500-58bb-11eb-91a0-7675d33a02f3.png)
![1610884665858](https://user-images.githubusercontent.com/6492427/104839799-792c3100-58bb-11eb-96e3-f26d7d2e6ce5.jpg)

**Comment by laurencedawson** [comment]
Goddamn...

**Comment by laurencedawson** [comment]
I think this has been fixed with v22
