### ISSUE TITLE
Include target sub(s) for search terms in search history

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#324]
**Is your feature request related to a problem? Please describe.**
Currently previous searches are listed in the Search tab as just "{query terms here}" without an indication of which sub it was made or whether it was search-all from the front page.  This can get very confusing quickly, not only because we forget, but also because searching the same term in multiple subs look like this:

![search_duplicate](https://user-images.githubusercontent.com/13911156/88511585-f1afd600-cf99-11ea-8896-ddba11cd9d3c.jpg)

Similarly, opening the search results for one of these will not indicate which sub(s) they are from -- just the individual posts that have the search term and their corresponding sub.  We have no way to tell whether the search was done on a single sub, multi-sub, or all subs.

**Describe the solution you'd like**
A smaller text on the right side of the search terms with the name of the originating sub/multi-sub/all would be nice for both the search history list and the search results page.

**Describe alternatives you've considered**
Not a fix for stacking the same search terms as in the picture, but the context menu (three dots) could have an item showing the originating sub(s) and selecting it opens the sub.

**Additional context**
Version: v20 beta 9 (Pro)

**Comment by laurencedawson** [comment]
Added for the next release
