### ISSUE TITLE
[BUG]Add comment button hidden by the "There is no comment in this post. REFRESH"

### ISSUE THREAD

**Issue by chemsed** [laurencedawson/sync-for-reddit#325]
I cannot be the first commenter on a post, because the message at the bottom of a post hide the "add comment" button. 

Could you put the "no comment" message below the "add comment" button? So I can finally comment "First"?

I have a Samsung Galaxy S10E on android 10 and I use the Samsung Internet browser 12.0.1.47

**Comment by laurencedawson** [comment]
This snackbar can be swiped away.
