### ISSUE TITLE
[BUG] Preview text cutoff

### ISSUE THREAD

**Issue by Horatius314** [laurencedawson/sync-for-reddit#327]
**Describe the bug**
Text cut off in preview

**To Reproduce**
Some subreddits have it, some don't, not sure what or why it is happening.

**Expected behavior**
Should show fully

**Screenshots**
![Screenshot_20200727-182843.jpg](https://user-images.githubusercontent.com/50734579/88567345-a64c0500-d037-11ea-9d99-c3cfb36dc991.jpg)
![Screenshot_20200727-182906.jpg](https://user-images.githubusercontent.com/50734579/88567358-a9df8c00-d037-11ea-920a-85a86953244b.jpg)

**Smartphone (please complete the following information):**
 Sync version: v20 (beta 9)    
    Sync flavor: pro    
    
    View type: Full height cards    
    Push enabled: false    
    
    Device: OnePlus6    
    Model: OnePlus ONEPLUS A6003    
    Android: 10

**Additional context**

**Comment by laurencedawson** [comment]
This has finally been fixed.
