### ISSUE TITLE
[BUG] Redgif videos won't download.

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#328]
**Describe the bug**
When you try to download a redgif, the app keeps on saying saving image in the notification panel. Doesn't download the gif.

**To Reproduce**
1. Go to https://www.redgifs.com/watch/spanishscaredcuckoo
2. Click on download
3. Some gifs say 'Invalid MIME type' or it just keeps on saying 'Saving image' in notification panel

**Expected behavior**
Redgif video to download

**Smartphone (please complete the following information):**
Sync version: v20 (beta 12)    
Sync flavor: dev    

View type: Dynamic cards    
Push enabled: false    

Device: star2qltesq    
Model: samsung SM-G965U    
Android: 10

**Comment by laurencedawson** [comment]
fixed for beta 13

**Comment by patel-jeel92** [comment]
Just tried beta 13. I get an IO Exception

**Comment by laurencedawson** [comment]
Try a few. Tested as working here
