### ISSUE TITLE
Add theme accent color to the "Joined" pill on reddit sidebar

### ISSUE THREAD

**Issue by oathzed** [laurencedawson/sync-for-reddit#329]
**Is your feature request related to a problem? Please describe.**
Currently it's just white, it should be the color of our theme accent when we've joined a sub

**Describe the solution you'd like**
Make the "joined" pill the color of our theme accent when we've joined the sub
![Screenshot_20200727-132642](https://user-images.githubusercontent.com/52545913/88591602-70942580-d011-11ea-88a6-394553939f08.png)

**Comment by laurencedawson** [comment]
https://github.com/laurencedawson/sync-for-reddit/issues/146

Duplicate
