### ISSUE TITLE
[BUG] Video preview cut off in full height view

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#330]
**Describe the bug**
The video preview is not full height although I use the full height cards view

**To Reproduce**
Well only reproducable in the overview of a sub or similar, but a post would be this one: 
https://www.reddit.com/r/Vanced/comments/hywygr/_/

**Expected behavior**
Also see the first line of text of the video in the preview

**Screenshots**
![Screenshot_20200728-010545__01.jpg](https://user-images.githubusercontent.com/60349846/88600968-cd262d80-d06f-11ea-958a-20b61ba4a300.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen OS 10.0.6
 - Browser DuckDuckGo
 - Version Beta 12

**Additional context**
The post is a mp4 video hosted on imgur

**Comment by laurencedawson** [comment]
Seeing this elsewhere? Is it autoplaying?

**Comment by NickPfeiffer** [comment]
I can't remember, but as text and pictures are often cut off too I guess it's a general problem (maybe only on Frontpage though)

**Comment by laurencedawson** [comment]
Can't reproduce this.
