### ISSUE TITLE
[FEATURE BUG] Animation bug when opening comment options or collapsing comments

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#332]
**Describe the bug**
The animation for when you collapse a parent comment and open the options for a given post are a big rough, with them overlapping the content below.

**To Reproduce**
1.Open any thread with comments with a chain of replies
2. Single click and hold and press on a comment with replies (for the two given things)
3. See animation with content overlapping the ones below it (set slower phone animations to better it)

**Expected behavior**
Content not overlap others

**Screenshots**
Refer to the following videos in the messages in the discord channel:
https://discordapp.com/channels/684912692485554230/684912692489748484/737809353150693516
https://discordapp.com/channels/684912692485554230/684912692489748484/737808265911730186

**Comment by scottjfer** [comment]
lj pls fix

**Comment by laurencedawson** [comment]
Fixed for b24
