### ISSUE TITLE
[BUG] Font is messed up 

### ISSUE THREAD

**Issue by Primeey** [laurencedawson/sync-for-reddit#333]
Often the text on comments will look like [this](https://i.imgur.com/LMKcH39.jpg) when I enter a thread and it only goes back to [normal](https://i.imgur.com/jXBPxOF.jpg) after I select 1 of the comments. Changing the typeface does nothing, the bug happens no matter what typeface I use. 

Sync version: v20 (beta 12)   
Sync flavor: pro    
    
View type: Small cards    
Push enabled: true    
    
Device: gta4xlwifi    
 Model: samsung SM-P610    
 Android: 10

**Comment by laurencedawson** [comment]
Looks like a line height issue.

Have you tried changing the option "comment body line space multiplier"?

**Comment by laurencedawson** [comment]
Can't replicate. Closing for now.
