### ISSUE TITLE
[GUI][Improvement][Beta] Tablet feedback

### ISSUE THREAD

**Issue by Eideen** [laurencedawson/sync-for-reddit#334]
I like to give some feedback on the layout on tablet.  
https://imgur.com/a/67mvyPW

1. image01  move quicktools to left or right  
When using Sync on tablet i prefer to only navigate with my thumbs, so to have it in centre, low it longest from my thumbs. Also move button.
1. image02 Android have drop down that is depended on draw down position
1. image03  The sort many and menu other minor menus are to large, and in centre.   
I like to see it moved to small compact manu's that show up at the same location as the button.  
Since there is a lot of space available i like to see the top3 sort option always show on tables with lots of space (Best, hot, top).
1. image04 Like .3 make smaller menu  
Add a option to select default. 
1. image05 account menu  
Reveres the order of icons, so the user icon don't move.
Make the menu smaller.
1. image06 Make the sidebar be on a side.  
To make it easier to navigate sidebar's make the sidebar appear on a side. 
1. image07 Subreddit layout   
There is inconsistency between Subreddit layout and user layout. 
1. image08 user layout  
Make the user layout more like subreddit  
Show a button for sidebar  
Make Overview/post/comment menu smaller 
Since there is a lot space show "add friend"  
1. image09 User sidebar  
There is a lot of space available, so show more buttons.  
1. image10 for som links that don't generate thumbnail, there is a lot of empty space.  
Maybe hide the icon.

Others:

1. When option posts, and returning to overview, other videos does not resume.
1. When "soft opening" a text post, i would like to see flowing soft close button.
1. when view subreddit or user or friend, i like there to be a button to show as gallery similar to in post.
1. There is missing a button for "friend" in the hamburger menu.

**Comment by laurencedawson** [comment]
With the next update I think these have all been addressed.
