### ISSUE TITLE
[features request] highlighting content, reveres hide

### ISSUE THREAD

**Issue by Eideen** [laurencedawson/sync-for-reddit#335]
Currently in the app you can hide certain content based on user, keyword, domain, flair and subreddits. I like it tho be possible to do the reverse by highlight post that have certain user, keyword, domain, flair and subreddits. I know users can be highlighted via friend, but this will also add them to the friends subreddits, and some users posts a lot. 

I sometimes modest should be used like change the background of Metadata for a post, like is done for friends.

**Comment by laurencedawson** [comment]
You can kinda do this with content filters already but I dont plan to expand this futher. Thanks for the feedback though.
