### ISSUE TITLE
[Bug] Unable to backup to microsd card

### ISSUE THREAD

**Issue by Arkcade** [laurencedawson/sync-for-reddit#337]
When trying to backup setting to a microsd card it gives an error whenever trying to backup.
![Screenshot_20200731-123846_Sync](https://user-images.githubusercontent.com/19383165/88988188-3df96e00-d32c-11ea-80fa-97cae9834185.jpg)

Sync version: v20 (beta 13)
    Sync flavor: free
    Removed ads: true

    View type: Full height cards
    Push enabled: false

    Device: jackpot2lte
    Model: samsung SM-A730F
    Android: 9

**Comment by laurencedawson** [comment]
The latest update fixes.
