### ISSUE TITLE
Show preview on links from post/comments

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#338]
**Is your feature request related to a problem? Please describe.**
When using the show links from a comment/post, it doesn't show any previews (for YouTube, for example), only a "play" icon.
See message: https://discordapp.com/channels/684912692485554230/685907412146061339/741326303277613056

**Describe the solution you'd like**
Show a small preview instead of the icon, like Apollo: See message: https://discordapp.com/channels/684912692485554230/685907412146061339/741325708655067136

**Additional context**
Asked by user jhoan on discord

**Comment by scottjfer** [comment]
Would really like this feature!

**Comment by laurencedawson** [comment]
Done
