### ISSUE TITLE
Cache Subreddit Wiki's

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#340]
I frequent a few subreddit's wiki pages which are quite large, and Sync hangs while loading them with no loading indicator. Every time I revisit the wiki, it has to download everything again. Caching the wiki would be helpful.

**Describe the solution you'd like**
Load wiki quickly from memory, and only reload after a while or after a wiki update or something

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by laurencedawson** [comment]
Added for the next release.
