### ISSUE TITLE
[BUG] Download album text is unreadable in light mode

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#341]
**Describe the bug**
When trying to download an album (e.g. imgur album) the popup text is white in light mode, same as the popup so you can't read it.
(Fine in dark mode)

**To Reproduce**
1. Go to https://www.reddit.com/r/Props/comments/i45ks6/this_early_2000s_military_spec_laptop_would_make/
2. Click on the image
3. Tap the download icon in the top right 

**Expected behavior**
Text should be readable/be black or grey

**Screenshots**
[Problem in light mode](https://i.imgur.com/W0AxnMs.jpg)
[No problem in dark mode](https://i.imgur.com/c8Q6Vfv.jpg)

**Smartphone:**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen OS 10.0.7
 - Browser DuckDuckGo
 - Version Beta 13

**Additional context**
-

**Comment by laurencedawson** [comment]
This has since been fixed
