### ISSUE TITLE
[BUG] mod options for comments/posts not visible if you became mod after first login - new authorization required

### ISSUE THREAD

**Issue by MaximeDelwaulle** [laurencedawson/sync-for-reddit#343]
**Describe the bug**
The icon to moderate a post/comment is not shown if you become mod after first logging into the app (it seems).

**To Reproduce**
1. Be logged into sync and go to a test subreddit you do not moderate with this account
2. Look at the comments/posts in it: the moderator icon under each (the shield next to downvote/upvote/save) is not there - rightfully!
3. Be given the moderator role for this subreddit
4. Go to sub, see comments etc.: no shield! (not good) even in the modqueue, there is no option to remove/approve/ban. You also can't do things like distinguish your comment. 
5. Logout, login again (maybe you have to change your password - that's an extra step I had done)
6. Go to sub, view comments etc.: magic, it works!

**Expected behavior**
I would expect to see the mod tools immediately after I become mod for this sub, instead of having to re-login. 

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Browser: chrome
 - Version 19.0.4

**Additional context**
I'm opening the issue cuz I saw it happen exactly like that - though for me, there were months of app usage between the several points. Things might have changed. But I never saw the mod options on comments/posts. And now, having reset my password and thus having to re-login, I saw the magical mod tools ;)

**Comment by laurencedawson** [comment]
Closing and re-opening the app should fix this as its refreshed on launch.
