### ISSUE TITLE
[FEATURE BUG] Touch target for profile icon is small

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#344]
**Describe the bug**
Not a bug per se. The touch target for the profile icon is a bit too small (I guess it's just the circle itself), and end up touching the top bar (and thus, going to the top of the screen) when that's not the intended behavior

**To Reproduce**
1. Scroll down anywhere
2. Click on the profile icon kinda fast (like you'd do when you're normally using the app)
3. Ends up going to the top

**Expected behavior**
Bigger touch target for profile icon (expand the touch target so it is a bigger square, makes it easier on the fingers

**Screenshots**
https://discordapp.com/channels/684912692485554230/684912692489748484/742575108014604340

**Additional context**

**Comment by scottjfer** [comment]
LJ pls

**Comment by laurencedawson** [comment]
Added for b24
