### ISSUE TITLE
[FEATURE REQUEST] Option to disable visit count per subreddit /disable list in launcher menu

### ISSUE THREAD

**Issue by omaralsharif** [laurencedawson/sync-for-reddit#345]
**REASON:** It's a bit of a privacy concern if I allowed someone to access my phone with the possibility that they may see my most viewed subreddits (if they're nsfw). This can even be done without opening the app by long pressing the app's icon in a launcher.

**IDEAL SOLUTION:** An option to disable the visit count for specific subreddits, so they don't show up in the "most visited". This maintains the feature of accessing commonly viewed subreddits while also allowing 

**ALTERNATIVE SOLUTION:** An option to disable visit count completely, or disable subreddit list in launcher menu, since "most visited" subreddits can already be disabled.

**ADDITIONAL CONTEXT:**
Sync Dev v20 (beta 13)

**Comment by laurencedawson** [comment]
Uncheck:

Settings > General > Show top visited subs icon shortcuts.
