### ISSUE TITLE
[BUG] While loading new pages old hidden posts are displayed again

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#346]
**Describe the bug**
Sometimes when a new page (maybe also happens when new posts are loaded, but I think they are always loaded pagewise?) is being loaded old posts you already scrolled pasted (marking them as read) and have hidden are being loaded again and the app even jumps up a bit.

**To Reproduce**
1. Read through some posts
2. Use "Hide read"
3. Scroll further until new pages are being loaded
4. See error (sometimes, not always, maybe only occurs after a lot of pages?)

**Expected behavior**
The new posts of the next page are being loaded and old & hidden posts are not displayed again.

**Screenrecording**
https://streamable.com/ay88qj

**Smartphone**
 - Device: OnePlus 7 Pro
- OS: Android 10, Oxygen OS 10.0.7
- Browser DuckDuckGo
- Version Beta 13

**Additional context**
None

**Comment by laurencedawson** [comment]
This has since been fixed
