### ISSUE TITLE
Add more image reverse search engines

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#347]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to find an image in a higher resolution, because the google reverse search does not show the image resolution. TinEye does that

**Describe the solution you'd like**
an option to set the default image reverse search engine in the settings
long pressing the reverse search image (the magnifying class) will bring up a bottom sheet or popup to choose the others for this time

**Describe alternatives you've considered**
tapping the image URL to copy it to clipboard, open browser, open the reverse search engine and paste the URL and search

**Additional context**
Some reverse image search engines: TinEye, Yandex, bing, karmadecay, baidu.
(Maybe if you ever want to add image editing to the app you could use imgops.com which also has these engines and a few more, plus online image editing tools)
The image debug sheet also needs redesigned icons (some like the share one just need to be replaced with the new one)

**Comment by laurencedawson** [comment]
Until these open up APIs I'll keep this closed.
