### ISSUE TITLE
[BUG] Sharing from imgur puts title in URL field

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#348]
**Describe the bug**
When using the Share option from imgur and choose to share via reddit sync it will put the imgur post's title and URL into the URL field in reddit sync

**To Reproduce**
1. Tap 'share' on an imgur post
2. choose 'Sync' in share sheet
3. See error

**Expected behavior**
the data should be parsed and only the URL would be in the URL field and the Title in the Title field
Now you need to cut the title and paste it into the Title field

**Screenshots**
[Step 1 and 2](https://ibb.co/BqtKDQ2) | [Step 3 Error](https://ibb.co/BfCyqcj)
(I wanted to include a screen recording but after 2 hours of trying to blur a part of the share sheet and exporting a vertical video I give up Openshot and Shotcut are crap. I really need to get into FFmpeg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen OS 10.0.7
 - Browser: DuckDuckGo
- Version: Beta 13

**Additional context**
None

**Comment by laurencedawson** [comment]
Not a sync bug. Theyre not splitting the title and url.
