### ISSUE TITLE
[BUG] Posts button sometimes fails to return user to default sub/feed

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#350]
**Describe the bug**
Occasionally the "Posts" button in the bottom nav bar will fail to return the user to their default subreddit/feed. It has proven to be difficult to reliably reproduce, but when the bug is "active", the button functions this way until the app is force-closed.

**To Reproduce**
1. After scrolling to the top of a subreddit or feed, press the "Posts" button.

**Expected behavior**
Tapping "Posts" when at the top of a sub usually returns the user to their default.

**Screenshots**
https://imgur.com/gallery/j5awVxG

**Smartphone:**

    Sync version: v20 (beta 13)    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Fixed height cards    
    Push enabled: false    
    
    Device: coral    
    Model: Google Pixel 4 XL    
    Android: 11
    Browser: Chrome

**Comment by andysteakfries** [comment]
Seems to be related to viewing profile page.

**Comment by laurencedawson** [comment]
Can'#t reproduce this. Closing for now.

**Comment by andysteakfries** [comment]
Seems like the issue was resolved when you implemented other changes to the function of the Posts button.
