### ISSUE TITLE
[BUG] Reddit gallery downloads preview-quality images instead of original

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#351]
**Describe the bug**
Reddit galleries currently show and download the preview images from the _preview.redd.it_ domain instead of the original image off the _i.redd.it_ domain.

**To Reproduce**
1. Open a Reddit image gallery post 
2. Expand context menu for a single image
3. Observe image link is the  _preview.redd.it_ domain
4. Click on download (alternatively, bulk download all gallery images together)

**Expected behavior**
The higher quality original image should be downloaded instead of the preview.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v20 beta 13 (Pro)

**Comment by laurencedawson** [comment]
The full sized image is currently used. Just because it's on that domain doesn't mean it's a downsized version (check the query params to confirm).
