### ISSUE TITLE
[BUG] Underscore appended when sharing link to comments

### ISSUE THREAD

**Issue by jeffreymcclain** [laurencedawson/sync-for-reddit#353]
**Describe the bug**
When sharing the comments section of a post, there is an underscore appended after it.

**To Reproduce**
1. Click on a post to open the comments section.
2. Click "Share"
3. Choose "Comments"
4. Notice that the preview of the link to be shared has an underscore in it.

**Expected behavior**
When sharing post comments, there should not be an underscore appended.

**Example**
https://www.reddit.com/r/funny/comments/ibfe2t/_/

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Browser: Internal Sync browser
 - Version: 19.0.4

**Additional context**
I tested this on a few random posts on /r/Funny and /r/Android

**Comment by laurencedawson** [comment]
Fixed for the next release.
