### ISSUE TITLE
[BUG] Invisible back button in image viewer top left

### ISSUE THREAD

**Issue by timocapa** [laurencedawson/sync-for-reddit#354]
**Describe the bug**
Title

**To Reproduce**
1. Open any image or video
2. Top left has an invisible back button you can tap

**Expected behavior**
No back button

**Screenshots**
![Screenshot_20200825-172419](https://user-images.githubusercontent.com/22844613/91193996-106bce80-e6f8-11ea-8573-083bd07cb3fe.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 10 (custom ROM, AOSPA)
 - Browser: -
 - Version: version v20 (beta 16)

**Additional context**
-

**Comment by laurencedawson** [comment]
Fixed for the next release.
