### ISSUE TITLE
[BUG] Video in previous feed keeps playing after opening a different sub

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#355]
**Describe the bug**
Videos playing in a sub's feed keep playing in a loop in the background even when a different sub is opened.
Normally this it not noticeable unless the video has audio and is unmuted in the preview, but it may cause performance issues.

**To Reproduce**
1. On the front page feed, or open the feed for a sub with a video that has audio
2. Unmute the video in the preview
3. Without scrolling away, open a different sub (from Search or Subs tabs)

**Expected behavior**
Audio from the video should have stopped playing when the feed for the new sub opens.

**Smartphone:**
- Device: Samsung Galaxy S9+
- OS: Android 10
- Browser: Firefox Beta
- Version: v20 beta 16 (Pro)

**Comment by laurencedawson** [comment]
This has since been fixed.
