### ISSUE TITLE
[BUG] Chip buttons overlap on small screens/low density settings

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#358]
**Describe the bug**
Chip buttons (upvote/downvote, comments, buttons on profile view) overlap one another when on small screens and/or low density settings for the device

**To Reproduce**
1. Increase density/size of stuff in the device settings
2. Open anything in the app, open a profile

**Expected behavior**
Not overlapping

**Screenshots**
To be added

**Comment by laurencedawson** [comment]
Think I've got all these now
