### ISSUE TITLE
Popup windows use system background color instead of being theme-dependent

### ISSUE THREAD

**Issue by gkhang2806** [laurencedawson/sync-for-reddit#36]
This can be seen if you view a table. The text is white since it's dark theme, but it takes the background from my system (light theme). Running MIUI on Redmi K20 Pro.

![IMG_20200524_170548](https://user-images.githubusercontent.com/43963745/82751676-1db8aa80-9de3-11ea-9a9a-0db98125741d.jpg)

Similar (but not sure if related) thing happens if I search for options in dark theme.

![IMG_20200524_171754](https://user-images.githubusercontent.com/43963745/82751696-37f28880-9de3-11ea-8d08-e8bfa212fec2.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next beta.
