### ISSUE TITLE
[BUG] Downloaded/shared videos only play for a couple of seconds before freezing

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#360]
**Describe the bug**
When sharing a video downloaded from the app to apps like Discord and Facebook Messenger, the video freezes after a couple of seconds. Audio might still keep playing, video is def freezed

**To Reproduce**
1. Download any video using the app
2. Share the video to Discord or Facebook Messenger
3. Watch behavior

**Expected behavior**
Video plays ok

**Comment by laurencedawson** [comment]
This is down to the v.redd.it video being downloaded and muxed locally.

If your device is having issues with the video downloaded by sync I'd recommend trying 

https://play.google.com/store/apps/details?id=com.tegnatiek.veddit&hl=en_GB
