### ISSUE TITLE
[BUG] Thestreamable.com links treated as streamable (video) link

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#361]
**Describe the bug**
thestreamable.com links (a website) treated as a video (streamable), and opens a media UI, instead of the browser

**To Reproduce**
1. Go to https://www.reddit.com/r/cordcutters/comments/ilxy2i/pbs_launches_live_local_streaming_of_pbs_stations/
2. Click on the link
3. See error

**Expected behavior**
Open the browser

**Screenshots**
https://i.imgur.com/vUDH2Xn.png

**Smartphone (please complete the following information):**
Sync version: v20 (beta 16)    
Sync flavor: dev    

Device: bonito    
Model: Google Pixel 3a XL    
Android: 1

**Additional context**
Reported here: https://www.reddit.com/r/redditsync/comments/ilyj76/bug_thestreamablecom_links_treated_as_steamable/

**Comment by laurencedawson** [comment]
Fixed for the next release.
