### ISSUE TITLE
[Feature request]Add 'scroll to top and hide' into FAB Action

### ISSUE THREAD

**Issue by Aphirodite** [laurencedawson/sync-for-reddit#362]
**Is your feature request related to a problem? Please describe.**
When 'mark as read on scroll' and 'hide read on reddit' are checked and choose FAB as 'hide'，
every time you scroll to the middle and want to click FAB to hide those read posts,for example,scroll from top to page 2 and want to click FAB to hide page 1-2.After your click,page 1-2 will be slide upwards and hidden,the new page 1（which was the original page 3）,will be slided upwards to top and marked as read in one second,and the screen will stopped at the new page 2（which was the original page 4）,If you want to glance over the new page 1 which obviously you haven't read yet,you need to scroll back to top and start to browse the new page 1,whick is already been marked as read.
To avoid this, when i want to hide those read posts,i need to scroll to top(or double tap the top) and click hide.

**Describe the solution you'd like**
Add 'scroll to top then hide' into FAB Action.In this way，we can scroll down,click FAB to hide, instead of scroll down, scroll to top when want to hide,click FAB to hide.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by laurencedawson** [comment]
Clicking "hide all" now scrolls to the top first
