### ISSUE TITLE
[BUG] Zooming in on photos in albums stops working after 2 photos

### ISSUE THREAD

**Issue by Anders51** [laurencedawson/sync-for-reddit#364]
**Describe the bug**
After opening an album with 3 or more images and zooming in on 2 different images, trying to zoom in on another image will not work

**To Reproduce**
1. Open any image album with 3 or more images
2. zoom in on one of the images
3. swipe to the next image and zoom in again
4. swipe again to a third image
5. you will not be able to zoom in anymore

**Expected behavior**
I should be able to zoom in on all the images on an album

**Smartphone (please complete the following information):**
 - OnePlus 6T
 - Android 10, OxygenOS 10.3.5
 - Sync Pro, v20 (beta 18)

**Comment by scottjfer** [comment]
I've definitely experienced this intermittently before, so you aren't alone!

**Comment by laurencedawson** [comment]
Can't repeat. Closing for now.
