### ISSUE TITLE
[Request] selectively Hide NSFW posts from a sub

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#365]
What I have in mind is that this feature would allow users to browse subs without having NSFW posts show up at all if NSFW toggle for the sub is set to OFF

This applies to subs that makes it to Frontpage and while in the Subreddit with the toggle for NSFW: OFF

it'd make sense to me for the toggle to be in the subreddit sidebar and post's long press action popup

**Comment by skff-err** [comment]
![image](https://user-images.githubusercontent.com/66136655/98903985-a8a57280-24f3-11eb-8b70-cb6db58ff60f.png)

**Comment by laurencedawson** [comment]
I'm afraid I wont be expanding on the nsfw options due to restrictions.
