### ISSUE TITLE
[BUG] Suggested Sort isn't followed when loading additional comments

### ISSUE THREAD

**Issue by AlexRaubach** [laurencedawson/sync-for-reddit#367]
**Describe the bug**
When viewing a large thread with a suggested sort set to new, any additional comments loaded (via view more or expanding a thread) are loaded as if the comment sort was still on the default 'hot'. If you explicitly sort by new, everything works as expected. 

**To Reproduce**
1. Go to any large thread with a suggested sort, for example a large /r/nfl [game thread](https://www.reddit.com/r/nfl/comments/iuv8ra/game_thread_cincinnati_bengals_at_cleveland_browns/)
2. Scroll to the bottom of the thread
3. Click on View More
4. Observe that the new comments are no longer in chronological order and are instead ordered by points

**Expected behavior**
When a thread is sorted by new via suggested sort, it should behave the same as if the sort was set manually to new.

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus
 - OS: Android 10
 - Version 19.0.4

**Comment by laurencedawson** [comment]
Fixed
