### ISSUE TITLE
[BUG] Pressing "Mark as read" on a notification doesn't clear the notification

### ISSUE THREAD

**Issue by ThoCor** [laurencedawson/sync-for-reddit#369]
**Description**

When I receive notifications for comment replies, there's an option "mark as read". When I press that I'd expect the notification to not only be marked as read abut also be cleared from the Android notification list. It gets cleared for a couple of seconds but then a new notification with the same content pops up. I cannot interact with that notification (nothing happens when I press it). I have to swipe it away manually.

**Scenario**

1. Receive notification, press on "mark as read" in the notification shade
2. Notification disappears (and the comment/reply is indeed marked as read)
3. Notification re-appears after a couple of seconds.

**Results**

This new notification is not only unnecessary but it also cannot be interacted with. It can only be swiped away. Pressing that notification does nothing.

**Device Info**

* Device Model: Pixel 3a XL
* Android Version: 10 and 11
* sync version: all of the v20 betas

**Comment by hmzuleta** [comment]
I think this has been fixed since. Can you retest?

**Comment by laurencedawson** [comment]
Unable to reproduce. Working here.
