### ISSUE TITLE
Option to allow comments to span fullscreen in tablet mode

### ISSUE THREAD

**Issue by Oknehc-nurub** [laurencedawson/sync-for-reddit#374]
**Is your feature request related to a problem? Please describe.**
When using sync on my Galaxy Z Fold 2 in landscape mode, the post show up fine but when entering comments the comments only show up in the middle 2/3rd of the screen leaving a lot of blank room on the left and right side 

**Describe the solution you'd like**
Perhaps an options in the setting to span full screen comments when in tablet mode.

**Describe alternatives you've considered**
An option to allow dual pane view so that extra room can be utilized to show posts and comments at the same time. So the post can be on the right, 3rd and the comments on the left 2/3rds

**Additional context**
There was a post i put on reddit with pictures: https://www.reddit.com/r/redditsync/comments/iv60x3/weird_comment_layout_on_fold_2_in_landscape_any/

**Comment by laurencedawson** [comment]
Added
