### ISSUE TITLE
[BUG] New comment and new post header styles are not consistent

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#375]
**Expected behavior**
Both headers should be the same (the new Comment header seems to be the newer style, so that one should be favored). Font family and size, and the submit icon are different.

Submit a new post
![Screenshot_20200921-052043_Sync Pro](https://user-images.githubusercontent.com/3502252/93756525-dabce700-fbca-11ea-98ce-f51b61cebab6.jpg)
--
Submit a new comment
![Screenshot_20200921-052101_Sync Pro](https://user-images.githubusercontent.com/3502252/93756539-dee90480-fbca-11ea-9f13-ec81fda91fa8.jpg)

**Device information**

    Sync version: v20 (beta 19)    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Push enabled: false    
    
    Device: dream2lte    
    Model: samsung SM-G955F    
    Android: 9

**Comment by hmzuleta** [comment]
Still present in beta 23

**Comment by laurencedawson** [comment]
Corrected for b25.
