### ISSUE TITLE
[BUG] Background images/words is visible in the status bar space when I open settings page

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#376]
I've enabled transparent status bar https://www.imgur.com/a/A1D8M1n 

**Device information**

    Sync version: v20 (beta 20)    
    Sync flavor: dev    
    
    View type: Dynamic cards    
    Push enabled: true    
    
    Device: tissot_sprout    
    Model: Xiaomi Mi A1    
    Android: 9

**Comment by devanshux** [comment]
what you have enabled is its intended behavior. theres no bug

**Comment by RecklessDwark** [comment]
> what you have enabled is its intended behavior. theres no bug

This is not the intended behaviour, the previous page is being "saved" to the status bar. This is a bug

**Comment by devanshux** [comment]
> > what you have enabled is its intended behavior. theres no bug
> 
> This is not the intended behaviour, the previous page is being "saved" to the status bar. This is a bug

Oh i am sorry. Didn't pay attention to that. You are correct

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers guys
