### ISSUE TITLE
[BUG] Settings section headings color doesn't match the user theme

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#379]
Colors are in default blue, but my highlight color is yellow.

https://www.imgur.com/a/xfdCBH3

**Device information**

    Sync version: v20 (beta 21)    
    Sync flavor: dev    
    
    View type: Dynamic cards    
    Push enabled: true    
    
    Device: tissot_sprout    
    Model: Xiaomi Mi A1    
    Android: 9

**Comment by laurencedawson** [comment]
These are updated after your theme is applied
