### ISSUE TITLE
Long press "Posts" to return to default (without scrolling to top)

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#380]
**Is your feature request related to a problem? Please describe.**
Current long-press bottom sheet on Posts button has a lot of utility, but it's all been replicated by the Sync button.

Returning to the default sub/feed using Posts from an arbitrary position in the app requires tap-wait-tap (since you need to wait for the scroll-up animation to finish before the second tap will register). (also, this works inconsistently - https://github.com/laurencedawson/sync-for-reddit/issues/350)

Returning to Frontpage or All via the Subs bottom sheet requires a tap-swipe(s)-tap (since Favorites were moved above Defaults in the Subs sheet).

**Describe the solution you'd like**
Long-press the home button returns the user to and refreshes their default sub/feed. The scroll-to-top function and the restore position button seem really popular and should probably stay the same.

**Describe alternatives you've considered**
Option to reorganize the Subs bottom sheet to move Defaults above Favorites would restore a faster way to return to Frontpage or All.

**Comment by laurencedawson** [comment]
Agreed. Changed this for the next release
