### ISSUE TITLE
[BUG] 'Search All' doesn't work in a specific sub. It only searches the term inside that sub, not whole reddit

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#381]
Search all only works in frontage/popular/all, not inside a specific subreddit

**Device information**

    Sync version: v20 (beta 21)    
    Sync flavor: dev    
    
    View type: Dynamic cards    
    Push enabled: true    
    
    Device: tissot_sprout    
    Model: Xiaomi Mi A1    
    Android: 9

**Comment by johnnyw94** [comment]
Another bug report ihttps://www.reddit.com/r/redditsync/comments/j9etu0

**Comment by laurencedawson** [comment]
Fixed for the next release
