### ISSUE TITLE
[BUG] Thumbnails eventually stop loading

### ISSUE THREAD

**Issue by pasci199601815** [laurencedawson/sync-for-reddit#382]
**Describe the bug**

Thumbnails stop loading after a while when scrolling through Image heavy subs like me_irl

**To Reproduce**
1. Open /r/me_irl with sorting method "hot"
2. scroll for a while (threads can also be opened and closed)
3. Thumbnails eventually stop loading

(happens in 4G and WiFi)

**Expected behavior**
thumbnails should continue to load

**Screenshots**

![Screenshot_20201013-120659](https://user-images.githubusercontent.com/38651087/95847805-76b2bc00-0d4d-11eb-975f-62b80665911f.jpg)

Screenshot of image preloading:

![Screenshot_20201013-121335](https://user-images.githubusercontent.com/38651087/95847970-b24d8600-0d4d-11eb-91dd-b850c11e364d.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: OxygenOS 11 Open Beta 2
 - Browser Stock (Chrome)
 - Version: Sync (V20 Beta 21)
Chrome: Version 86.0.4240.75

Using dynamic cards

**Comment by hmzuleta** [comment]
Can confirm on Galaxy S8+, Android 9, v20 beta 23.
Given that it happened after scrolling a lot, could it be related to the caching of images?

**Comment by timdorr** [comment]
Same here. I have for Force Stop the app to get them to start loading again. It's like a background task queue is overloaded and doesn't get cancelled when switching views, instead continuing to download things that are out of view.

**Comment by laurencedawson** [comment]
Any way to make this reliably happen?

**Comment by pasci199601815** [comment]
> Any way to make this reliably happen?

actually i found one now:

Force stop app

Go to a image heavy subreddit, i prefer me_irl

Sort by top all 

Begin scrolling

At around the mark where Posts have ~60k upvotes, Thumbnails Stop loading, even for other subreddits then until u force stop again

**Comment by laurencedawson** [comment]
Are you using dynamic cards?

**Comment by pasci199601815** [comment]
yes

**Comment by laurencedawson** [comment]
Does it still happen if you don't use Dynamic cards?

**Comment by pasci199601815** [comment]
Just tried it with fixed height cards and it didnt happen

**Comment by Nxt3** [comment]
I also use Dynamic Cards and run into this issue.

Another user posted here with the same: https://www.reddit.com/r/redditsync/comments/ku081n

**Comment by laurencedawson** [comment]
This was caused by dynamic cards and has since been removed,

**Comment by Nxt3** [comment]
You removed Dynamic Cards? Or removed the defect?

**Comment by timdorr** [comment]
Looks like Dynamic Cards was removed :(
