### ISSUE TITLE
[BUG] Custom icon disappears from home screen favorites bar

### ISSUE THREAD

**Issue by biobak64** [laurencedawson/sync-for-reddit#387]
I have changed the Sync icon from Default to Fancy, and when I add the app with the new icon to the favorites bar on the home screen, it will only stay there for a few minutes and disappear when I'm using another app. I often add it again and come back to a gap between the other apps.

1. Go to Settings > General
2. Click on "Icon"
3. Choose "Fancy"
4. Add icon to home screen favorites bar

Expected behavior: The icon should just stay there and not disappear eventually

 - Device: Nokia 7 Plus
 - OS: Android 10 (Sep. 1 security update)
 - Version: v20 beta 21

Additional context : 
Launcher is Quickstep 10.0010.07

**Comment by laurencedawson** [comment]
Does this happen if you use the default icon?

**Comment by biobak64** [comment]
No, it only happens with the non-default icons.

**Comment by laurencedawson** [comment]
Sadly there's not much I can do on this front apart from recommend only using the default icon.
