### ISSUE TITLE
[BUG] Check for Messages "On launch" doesn't indicate a message has been received

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#390]
**Describe the bug**
When "Check for new messages on launch" is set, there's no indication without going to the Messages tab that a new notification is received.

Side note that I'd love the option or something so that it checks for new messages every time you return "home" to the default sub you have set. 

**To Reproduce**
![Screenshot_20201108-113950.png](https://user-images.githubusercontent.com/2940826/98472198-21849180-21b7-11eb-8f74-b1d43b38b64c.png)

**Expected behavior**
Toast or some indication I've received a message or have a notification.

**Smartphone (please complete the following information):**
 - Pixel 5
 - Pixel 4 XL

**Comment by laurencedawson** [comment]
Fixed for beta 24.
