### ISSUE TITLE
Swipe pictures from a album directly from the front screen (if no other swipe related features are on)

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#392]
Be able to swipe between pictures from an album directly from the feed page, considering no other swipe features are enabled.

 Disable either feature from the settings (disabled state) if conflicting feature is on, and warn the user about that

https://www.reddit.com/r/redditsync/comments/jugk9t

**Comment by laurencedawson** [comment]
Closing and merging with this:

https://github.com/laurencedawson/sync-for-reddit/issues/765
