### ISSUE TITLE
[BUG] fix "Report Hides to Reddit" terminology

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#393]
The "report hides to reddit" terminology gives the idea that the post was reported, as in something is wrong with it, or that you don't want to see content like that (like in a Facebook or Twitter context would)

The feature actually syncs with desktop reddit of posts that are hidden

Terminology could be changed to "Sync hidden posts to reddit"

https://www.reddit.com/r/redditsync/comments/ju6pd6

**Comment by laurencedawson** [comment]
Changed!
