### ISSUE TITLE
[BUG] About sheet no longer shows member count

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#396]
The About sheet (previously Sidebar) no longer shows the member count. It used to be right below the subreddit name.

**Device information**

    Sync version: v20 (beta 22)    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Push enabled: false    
    
    Device: dream2lte    
    Model: samsung SM-G955F    
    Android: 9

**Comment by laurencedawson** [comment]
Fixed.
