### ISSUE TITLE
[SUGGESTION] Add drop shadow to image view buttons

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#397]
The image view has a download and options button, which are white. If the image or video has a white background, the buttons are no longer visible.

Video (buttons are on the bottom right corner): https://imgur.com/a/sy6cekr

If these buttons had a dark border or drop shadow, it would improve the visibility of those buttons.

**Comment by hmzuleta** [comment]
Same thing happens to the buttons in the video preview when using dynamic cards:

![Screenshot_20201203-160836_Sync Pro](https://user-images.githubusercontent.com/3502252/101088937-65827080-3582-11eb-91a8-0c6f184f5c89.jpg)

**Comment by laurencedawson** [comment]
Closing this as I intend to fully redesign the image viewer after v20 goes to production.

**Comment by laurencedawson** [comment]
(and the current buttons at the bottom will be replaced)
