### ISSUE TITLE
[FEATUREBUG] Don't reload comments that have already loaded if the comments are scrolled to the top

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#398]
Make it so Sync doesn't reload comments if you navigate away and back into them immediately if the comments are scrolled to the top (even if you have a bunch of collapsed parents)

I was in the middle of reading that!!!

![image](https://user-images.githubusercontent.com/31053171/99738704-1c69f100-2a99-11eb-881a-96be53077ba2.png)

**Comment by laurencedawson** [comment]
Oh actually this already exists:

Settings > Data options > cache comments
