### ISSUE TITLE
[BUG] Subreddit's total users count/users online is not visible

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#399]
**Describe the bug**
Subreddit's total users count/users online is not visible

**To Reproduce**
1. Go to 'any subreddit'
2. Click on 'About'

**Screenshots**
https://i.imgur.com/IUe2Iev.jpg

**Device information**

    Sync version: v20 (beta 22)    
    Sync flavor: dev    
    
    View type: Dynamic cards    
    Push enabled: false    
    
    Device: tissot_sprout    
    Model: Xiaomi Mi A1    
    Android: 9

**Comment by laurencedawson** [comment]
Fixed for the next release
