### ISSUE TITLE
[BUG] Add a .nomedia to "shared" folder (and option to auto clear it)

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#410]
Usually apps save their own copy of a shared image/video, so sync saving it is usually not needed. 

I understand that Android 11 needs to save the file to share it, but I usually don't want the file saved if I'm just sharing it, so a .nomedia to the folder would be nice

Also, an option to auto clear the folder would be nice as well (an option because I'm sure that if it's not used selectable, it's going to piss some people's weirdly specific useflow)

**Comment by laurencedawson** [comment]
Added for b24. Not sure about auto clearing so I've left that out for now.
