### ISSUE TITLE
[BUG] [Cosmetic] Residual "sidebar" references

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#411]
**Describe the bug**
Since v20b23, the "Sidebar" quick action was renamed to "About", and its logo was changed. However, the 3 dot menu from posts still shows the now-legacy "View sidebar" option in the bottom sheet.

**To Reproduce**
1. Go to any subreddit.
2. Click on any post
3. Open the 3-dot menu bottom sheet, called "Comment actions".
4. See "View sidebar" list item, with the old logo.

**Expected behavior**
It should be consistent with the "About" quick action.

**Screenshots**
--
"About" quick action:
![Screenshot_20201123-111543_Sync Pro](https://user-images.githubusercontent.com/3502252/99986631-6bf03b80-2d7d-11eb-9b84-8f50b0838241.jpg)
--
Inconsistent label and icon:
![20201123_111822](https://user-images.githubusercontent.com/3502252/99986845-b83b7b80-2d7d-11eb-9fce-1ad7bcf07411.jpg)

**Smartphone:**
 - Device: Samsung Galaxy S8+
 - OS: Android 9, OneUI 1.0
 - Version 20, beta 23

**Comment by laurencedawson** [comment]
Fixed.
