### ISSUE TITLE
[Feature Request] Add the ability to Follow users

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [laurencedawson/sync-for-reddit#414]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to follow or subscribe to users from their profile page. 

**Describe the solution you'd like**

There should be an option in the bottom sheet or better, the user's page to quickly follow, as I do this often. 

**Describe alternatives you've considered**

Using the official client

**Comment by gXxshock** [comment]
Looks like it will be [implemented eventually](https://github.com/laurencedawson/sync-for-reddit/issues/826)

**Comment by laurencedawson** [comment]
Added for the next release.
