### ISSUE TITLE
[Feature Request] Remove non-error snackbars

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [laurencedawson/sync-for-reddit#415]
The snackbars, like "No more posts were loaded" are generally used for errors, but these are sitting in the way for too long and it prevents interacting with the content below. It also comes back repeatedly on the same page. Rather than a notification, can there just be text at the bottom of the feed that says "no more posts"? Also, retry doesn't seem to be a frequently used thing in places where there aren't going to be frequent changes at the bottom of a scrollable. For example, a new post won't come up in the view if I hit retry since I'm at the bottom of the screen. This I would expect to be maybe in a pull to refresh. Just my 2 cents. Thanks!

**Comment by laurencedawson** [comment]
The only case where I see this being a problem is on comment pages.

**Comment by ThinkDigitalSoftware** [comment]
And on the user's posts page when you get to the bottom. I've never needed to hit retry because it's not an action that was failing.

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by ThinkDigitalSoftware** [comment]
You're awesome. Thanks!
