### ISSUE TITLE
[BUG] Selftext preview is contracted after voting or saving it

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#416]
**Describe the bug**
When the selftext preview is expanded, voting or saving it will contract it, pushing the selftext post up and making it confusing for the end user. The user must then scroll up to continue reading the preview.

**To Reproduce**
1. Go to Settings/View customization.
2. Enable "Show selftext previews".
3. Go to r/redditsync and find a long selftext post. 
4. Expand the selftext post.
5. Click the upvote button.

**Expected behavior**
The post vote should be updated and the selftext preview should be kept expanded.

**Video**
https://imgur.com/a/HkQ6mdw

**Smartphone:**
 - Device: Samsung Galaxy S8+
 - OS: Android 9, OneUI 1.0
 - Version 20, beta 23

**Comment by laurencedawson** [comment]
Fixed for the next release.
