### ISSUE TITLE
[BUG] Subreddit Drawer lags on open

### ISSUE THREAD

**Issue by koinupapi** [laurencedawson/sync-for-reddit#418]
**Describe the bug**
The subreddit Drawer lags when you click to open it for sometimes up to half a second. I don't know if it's always been like this, but i don't think so because it just became so jarring when I updated to beta 23 (maybe it was 24) when you changed the animation for the subreddit Drawer. I included a video in case you can't reproduce because I do realize that i have a "budget" phone, and that might be the issue, although it didn't lag like this before the update.

**To Reproduce**
1. Open Sync.
2. Click on subreddits button on bottom nav.
3. Watch the lag for the drawer to open.

**Expected behavior**
Subreddit Drawer should open faster than it does.

**Screenshots**
https://drive.google.com/file/d/1B-KlCV5ZreBQKMRta2H2LZcA7z5Yp9iO/view?usp=drivesdk

**Smartphone (please complete the following information):**
 - Device: LG Stylo 6
 - OS: Android 10

**Comment by laurencedawson** [comment]
Fixed for the next release.
