### ISSUE TITLE
Add Picture-in-picture Mode

### ISSUE THREAD

**Issue by fessmm** [laurencedawson/sync-for-reddit#419]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Watching longer videos in the background when browsing Sync or something else on the phone

**Describe alternatives you've considered**
There is no alternative

**Additional context**
https://developer.android.com/guide/topics/ui/picture-in-picture for implementation

**Comment by felimenta970** [comment]
Just to add to this: This is something nice, but can't be adde to YouTube links, as that would piss off Google quite a bit

**Comment by pwd-github** [comment]
> Just to add to this: This is something nice, but can't be adde to YouTube links, as that would piss off Google quite a bit

YouTube already has picture in picture mode at the OS level, this would just be for video that plays via Sync
