### ISSUE TITLE
[BUG]  More post doesn't load after hiding pages of posts

### ISSUE THREAD

**Issue by EmmEffTee** [laurencedawson/sync-for-reddit#420]
**BUG: More post doesn't load after hiding pages of posts**
Bug description: More posts doesn't load after hiding read posts from the initial loaded posts. 

**To Reproduce**
1. Read through a lot of posts (or mark as read when scrolling) 
2. Make sure no unread posts are loaded, or the next page of posts are not loaded yet
3. Hide read posts 
4. Left with only unread posts if there is any, or just blank post page, with no indication if the next page of posts are loading (or even loading).

**Expected behavior**
Expected that new posts are to be loaded after the initial hide read posts, with some kind of indication they are loading.

**Screenshots**
Video link to reproduce bug: https://youtu.be/_exS2BXEh-g

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO X3 NFC (M2007J20CG; surya)
 - OS: Android: 10
 - Sync version: v20 (beta 23)    
 - Sync flavor: free    
 - Removed ads: true    

**Additional context**
Have reported this in the subreddit before in v20 (beta 21) here: https://old.reddit.com/r/redditsync/comments/jaw3o4/bug_if_there_was_no_unread_posts_loaded_hiding/ 

Bug still present in latest Android v20 beta24.

**Comment by EmmEffTee** [comment]
After being diligent enough to search in Closed Issues, I found this: https://github.com/laurencedawson/sync-for-reddit/issues/191

But it's still not fixed for me.

**Comment by laurencedawson** [comment]
Fixed for the next release
