### ISSUE TITLE
[REQUEST] Mute/unmute button on post previews for other video hosts

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#427]
Right now, the video previews that autoplay in dynamic and full height cards can only be muted/unmuted when the video is hosted on v.reddit (button right next to the play/pause button). Could this same feature be implemented for gfycat, imgur, redgifs, etc?

Thanks!

**Comment by laurencedawson** [comment]
Unfortunately not. Sync replies on the video thats cached by reddit in orfder to autoplay.
