### ISSUE TITLE
[BUG] "Open in browser" button in gallery doesn't open in browser, just open another instance of the image in app

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#428]
**Describe the bug**
The "open in browser" button while viewing media doesn't actually open the media in browser, it just opens another instance of Sync's media viewer

**Comment by laurencedawson** [comment]
You likely have sync set to open the links...

**Comment by felimenta970** [comment]
Yeah, but when I press a button that forces the app to open in browser (because it says so), it should

**Comment by scottjfer** [comment]
> Yeah, but when I press a button that forces the app to open in browser (because it says so), it should

this ^^^^

**Comment by laurencedawson** [comment]
Fixed for the next release.
