### ISSUE TITLE
[ENHANCEMENT] Transparent statusbar icons should change based on background content

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#433]
If the setting for "Transparent statusbar", the color of the icons should change between white or black depending on the content behind it. Not sure if something like this exists but would def be a cool thing to have.

(see below, the black status bar icons on the dark background):

![Screenshot_20201129-155944.png](https://user-images.githubusercontent.com/2940826/100553653-fb558d00-325c-11eb-85e3-0f2960dd6ebc.png)

**Comment by laurencedawson** [comment]
I wish. Not a feature Android offers sadly.
