### ISSUE TITLE
[REQUEST] Post preview improvements

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#435]
Suggested improvements for post previews (Share > Post preview)  
  
**Solution(s):**
Removing unnecessary buttons in post preview (mod tools, hide, save, three dots); vote and comment counts should remain. Subreddit name is missing.  

**Additional context** 
https://cdn.discordapp.com/attachments/684912692489748484/783035308164775996/1606760552642.jpg (Post preview from Sync 20 beta 25)

**Comment by laurencedawson** [comment]
Added for the next beta
