### ISSUE TITLE
[FEATURE] Add ability to customize comment indent lines' colour (limit to 2-3 choices)

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#439]
Would be really nice to have a 3rd option to the comment indent lines. Right now we just have rainbow, and grey. A third option where you pick 2 colours, ideally based on accent colours, would be amazing!

Example, if my accent colour was blue, I could have my comment indent lines be blue and grey alternating, would look sick :D

**Comment by laurencedawson** [comment]
Closing this ticket as we've expanded in the duplicated one...

https://github.com/laurencedawson/sync-for-reddit/issues/617
