### ISSUE TITLE
Bring back the sidebar! You know you wanna...

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#444]
Do it do it do it do it

Yay 444

**Comment by koffiato** [comment]
You should be able to enable it in somewhere within settings mate. It's there on beta, no need to worry. And you can mark this issue as closed.

**Comment by scottjfer** [comment]
> You should be able to enable it in somewhere within settings mate. It's there on beta, no need to worry. And you can mark this issue as closed.

Haha, sorry for confusing you, I meant the right subreddit sidebar 😁

**Comment by laurencedawson** [comment]
So long
