### ISSUE TITLE
Redesign image upload view

### ISSUE THREAD

**Issue by AlexVasiluta** [laurencedawson/sync-for-reddit#446]
**Is your feature request related to a problem? Please describe.**
Since the dev started the redesign, he has interacted very little with the editor. Now, I do not have a big problem with the current design (the dev can update it if they'd like), except for the image upload dialog.

That specific dialog is extremely counter intuitive. When you press it, you are met with two buttons: a camera one and a picture one. Figuring out what they mean requires concentrating on the image upload process instead of the image to upload!

**Describe the solution you'd like**
I would like to see a redesign of the image upload modal, and maybe the editor as a whole to adhere to MD.

**Describe alternatives you've considered**
First of all, I think the modal can be transformed into a bottom drawer with 2 options" "Camera" and "Gallery". From there, each one has its old functionality.

**Comment by laurencedawson** [comment]
Merging with this ticket:

https://github.com/laurencedawson/sync-for-reddit/issues/1135
