### ISSUE TITLE
Surface Duo/Dual screen/foldable support.

### ISSUE THREAD

**Issue by fahdriyami** [laurencedawson/sync-for-reddit#447]
**Is your feature request related to a problem? Please describe.**
Currently, when spanning Sync across both screens on the Surface Duo, the content doesn't not take the hinge into consideration. So content and UI elements are blocked by it.

**Describe the solution you'd like**
Make the app hinge-aware. Display the list of content on the left screen, and the content itself + comments on the right screen.

**Describe alternatives you've considered**
The only alternative is using the app on a single screen. Which loses out on a lot of potential.

**Additional context**

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/385

Closing, cheers
