### ISSUE TITLE
[FEATURE] Replace check boxes with toggle switches in Settings menu

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#448]
Check boxes are _so_ 2012 dontchaknow

Old:

![Screenshot_20201204-105421](https://user-images.githubusercontent.com/31053171/101185137-7f25c580-361f-11eb-9805-b52a92c7c985.png)

New:
![Screenshot_20201204-105404](https://user-images.githubusercontent.com/31053171/101185180-8b118780-361f-11eb-9bbb-44b49b36b6c4.png)

LJ pls

**Comment by laurencedawson** [comment]
Done
