### ISSUE TITLE
[BUG] All visible posts are marked as read when data saving or dark mode are toggled

### ISSUE THREAD

**Issue by PizzaFlavoured** [laurencedawson/sync-for-reddit#449]
**Describe the bug**
When _Mark as read on scroll_ is enabled, toggling on/off either Dark Mode or Data Saving via the quick actions menu marks all posts visible at the time as read.

**To Reproduce**
1. Enable _Mark as read on scroll_
2. Go to any subreddit with unread posts
3. Toggle either _Dark mode_ or _Data saving_ On or Off
4. All visible unread posts are now marked as read

**Expected behavior**
Posts shouldn't be marked as read without scrolling through or viewing them

**Smartphone (please complete the following information):**
 - Device: ASUS_Z01R_1        
 - OS: Android 10
 - Browser: Firefox
 - Version: v20 (beta 26)

**Comment by laurencedawson** [comment]
Added a fix for the next release.
