### ISSUE TITLE
Separete "read posts" color from "secondary color"

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#452]
"Currently if we want usernames to be green for example (for better separation of comments), all the read posts are green too. They could just be dark grey while unread posts are all thick white by default. The beta version is amazing so far except for few lil things here and there."

As seen in: 
https://www.reddit.com/r/redditsync/comments/k8865v/let_the_read_posts_be_dark_grey_by_default_and/

**Comment by laurencedawson** [comment]
DOnt intend to add this.
