### ISSUE TITLE
[BUG] Unable to create flair on r/collegebasketball

### ISSUE THREAD

**Issue by Murabitos** [laurencedawson/sync-for-reddit#455]
![Screenshot_20201211-233516_Sync Pro](https://user-images.githubusercontent.com/1791523/101976353-15528080-3c0a-11eb-92e4-53dfd71c790e.png)
The instructions for adding a flair on this subreddit don't work while using sync.

![Screenshot_20201211-233614_Sync Pro](https://user-images.githubusercontent.com/1791523/101976361-27342380-3c0a-11eb-9dbf-d0bf757346c2.png)
This pops up instead of the message box with a send option that is supposed to.

**Comment by laurencedawson** [comment]
I'm afraid this only works on the reddit desktop version (and the old version at that).
