### ISSUE TITLE
[REQUEST] Transparent system navbar for 3-button navigation (v20)

### ISSUE THREAD

**Issue by 10catsinspace** [laurencedawson/sync-for-reddit#456]
The v20 beta is fantastic overall and using it has been a joy. I have the status bar set to transparent, but there is no way to set the android system nav bar to transparent when using 3 button navigation.

Could we get this as an option? It's present in other apps such as Google's Messages. It increases immersion and decreases the chance of burn in on OLED displays.

Also, in apps such as Messages the navbar & status bar aren't 100% transparent, but rather slightly "dimmed". This is a good compromise between immersion and usability. Could that be incorporated as an option?

Thank you!

**Comment by laurencedawson** [comment]
I don't intend to add this as I've already added support for gesture nav fullscreen. Cheers
