### ISSUE TITLE
Primary color support for checkboxes wherever they are + small fixes

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#463]
Checkboxes (such as, in the Sync button, subreddit, search, etc) deserves a primary color for whenever it is activated

Example here: https://cdn.discordapp.com/attachments/684912692489748484/790682898243125328/Screenshot_20201221-175126.png

Also, on that screenshot, fix the padding and/or margin. Too much space in right, too little in the left, as well as the space between text and checkbox (such as "Toggle account", for example; might be fixed with the padding adjustments already)

**Comment by laurencedawson** [comment]
Unfortunately they're controlled by the theme accent color and can't be changed dynamically...
