### ISSUE TITLE
[BUG] Improve error message text with messaging

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#464]
As seen here: https://www.reddit.com/r/redditsync/comments/ki411x
-------
"Device information

Sync version: v20 (beta 26)    
Sync flavor: pro    

View type: Compact    
Push enabled: false    

Device: HWALP    
Model: HUAWEI ALP-L29    
Android: 10

Sending a message to moderators, had post title as the subject. Tried sending the message and got this toast pop up error message.

Spent a while cutting down the message to be less than 100 words (maybe modmail is limited to stop hate rants against them), got it down to below 100, still got the error. 

Eventually guessed that "this is too long: 100" refers to the message subject and (presumably?) 100 characters.

Please could the pop up say "subject is too long: max 100 characters" and similar for similar situations? To avoid confusions and misplaced effort."

**Comment by laurencedawson** [comment]
This is the error returned from reddit. Not a bug from sync.
