### ISSUE TITLE
[BUG] Long spoilers aren't scrollable

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#469]
**Describe the bug**
Long enough spoiler tags aren't scrollable.

Possible alternative: 
Make the spoiler window, a bottom card (like most other app components)

Reported here (with example): https://www.reddit.com/r/redditsync/comments/kr8mjs/beta_long_spoilers_arent_scrollable/

**Comment by laurencedawson** [comment]
Fixed
