### ISSUE TITLE
[BUG] libredd.it link posts crash Sync

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#470]
Description

Clicking on a link to libredd.it crashes Sync.

Scenario (steps to reproduce)

Save this post because your app might crash.

Click on this post's link: https://www.reddit.com/r/selfhosted/comments/kp6ioj

Result(s)

Sync instantly crashes.

```
Device Info

Sync version: v20 (beta 26)    
Sync flavor: pro    

View type: Dynamic cards    
Push enabled: false    

Device: d1q    
Model: samsung SM-N970U1    
Android: 10
```

Reported here: https://www.reddit.com/r/redditsync/comments/kr9x44/bug_libreddit_link_posts_crash_sync/

**Comment by laurencedawson** [comment]
Fixed.
