### ISSUE TITLE
[BUG] Internal Browser doesn't follow theming from app/system for websites

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#473]
Opening links with a dark theme in the internal browser doesn't load the dark theme, but the default (usually light) theme.

Refer to this

https://developer.android.com/guide/webapps/dark-theme

**Comment by laurencedawson** [comment]
Cant reproduce.

**Comment by felimenta970** [comment]
https://felimenta970.github.io/felipepimenta/

This website changes theme according to system theme. If open in sync, it will always be light theme, no matter the app and/or system theme
