### ISSUE TITLE
[BUG] Biometric locks Sync out on devices that don't have biometric hardware.

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-reddit#474]
**Describe the bug**
If you enable the biometric option on a device which does not have the hardware, Sync will refuse to open as it will keep trying to use the nonexistent biometric hardware, failing with an authentication error.

**To Reproduce**
1. Enable the biometric login option in Security on a device which doesn't have biometric support.
2. Close Sync.
3. The app will now be permanently locked out due to an Authentication error.

**Expected behavior**
The biometric checkboxes should not be able to be toggled on devices which do not support biometric security.

**Screenshots**
![image](https://user-images.githubusercontent.com/28932047/103725751-3e65f700-4fa5-11eb-8924-0069fe91bef1.png)

**Smartphone (please complete the following information):**
 - Device: Lenovo Smart Tab M8
 - OS: Android 10
 - Browser Chrome
 - Version v20 (beta 26)

**Comment by laurencedawson** [comment]
Added a check for this for b28.
