### ISSUE TITLE
Filter keyword per subreddit

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#475]
"I'm trying to filter out all the obituaries on r/movies and r/television but I don't necessarily want to filter out every instance of "passes away" on reddit. If there was an option to only filter keywords on specific subreddits, that would be really useful."

Requested here: https://www.reddit.com/r/redditsync/comments/kt5tif

**Comment by laurencedawson** [comment]
Closing as I don't intend to add this. Would be a nightmare
