### ISSUE TITLE
[BUG] downloaded gifs are broken/all downloads have the prefix .jpg added to file name

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#476]
**Describe the bug**
Downloading an video as gif doesn't work. The downloaded file can't be played (neither Google Photos nor OnePlus Gallery)

**To Reproduce**
1. Try downloading this [post](https://i.imgur.com/7yZKgT0.mp4) as GIF
2. Try opening that file

**Expected behavior**
I get a playable 7yZKgT0.gif file

**Screenshots**
[Screen Capture](https://streamable.com/z675it)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10, Oxygen OS 10.0.10
 - Browser DuckDuckGo/Chrome
 - Version v20 beta 26

**Additional context**
None

**Comment by laurencedawson** [comment]
Looks like imgur have stopped serving both up. RIP. Removed the option from sync.
