### ISSUE TITLE
[BUG] App crash when accessing mod tools via account switcher

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#482]
The app crashes when accessing mod tools via account switcher.

1. Tap account switcher on top right of the screen.
2. Click on "Moderator"
3. App crashes

Expected behavior is moderator activity would launch.

 - Device: Nokia 6.1 Plus
 - OS: Android 10
 - Version: 20 beta 27

**Comment by laurencedawson** [comment]
Fixed (removed from the app switcher so fixed in a way...)
