### ISSUE TITLE
[BUG] Profile pictures won't display in comments opened in "View more"

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#483]
Profile pictures won't display in comments opened in "View more" 

1. Enable "Show profile pictures" in Settings > Comment view customization
2. Visit a thread with a lot of comments. [Example here.](https://www.reddit.com/r/Android/comments/34ui7l) 
3. Tap "View more"

Expected behavior is profile pictures should be displayed.

[Screenshot.](https://i.imgur.com/aA72cu8.png)  
  
 - Device: Nokia 6.1 Plus
 - OS: Android 10
 - Version: 20 beta 27

**Comment by laurencedawson** [comment]
Fixed.
