### ISSUE TITLE
[BUG] Comment bosy relative size change increases the line space multiplyer and doesn't affect the body size 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#484]
**To Reproduce**
1. Go to Settings
2. Click on Comment View Customisation 
3. Change comment body relative size
4. See error is preview 

**Expected behavior**
Should change size

**Smartphone:**
 - Device: OnePlus 7
 - OS: OxygenOS 10.3.7

**Comment by laurencedawson** [comment]
Fixed
