### ISSUE TITLE
[BUG] Post Flair is sometimes too big, causes empty space in post header 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#485]
**Describe the bug**
Due to the tall flair, an empty space is created between the title and the descriptive text

**To Reproduce**
1. Go to https://www.reddit.com/r/harrypotter/comments/kxi49k

Or 

https://www.reddit.com/r/ActualPublicFreakouts/comments/kxjgrd

**Expected behavior**
The flair should be shrunk down 

**Screenshots**
![Screenshot_20210115-164820~(1).jpg](https://user-images.githubusercontent.com/55349349/104724326-94c9f700-5756-11eb-9e9d-5e9415eb5a96.jpg)

![Screenshot_20210115-121100~(1).jpg](https://user-images.githubusercontent.com/55349349/104724337-998eab00-5756-11eb-834f-b3b495ce4dae.jpg)

**Comment by laurencedawson** [comment]
Fixed.
