### ISSUE TITLE
Request: the ability to jump directly to the subreddit a crossposted post was submitted from

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#486]
**Is your feature request related to a problem? Please describe.**
As of now, we have to select view cross post to view the post directly, and then have to select the go to subreddit

https://i.imgur.com/0tLr43G.png

https://i.imgur.com/T3RPOZX.png

**Describe the solution you'd like**
For crossposts, add in a link the the original subreddit along with the current shortcuts to the /u/, /r/, and Explore Domain

**Comment by laurencedawson** [comment]
Added for the next eelease
