### ISSUE TITLE
Change file data backup name (something to indicate it is sync's)

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#488]
"In the latest release, it's just a `.txt` file with the date and time as name. It easily gets lost. Please change the name as it was earlier (at least indicate that it's sync's backup)."

Maybe include a "sync_" in the start of the file name

Reported here:
https://www.reddit.com/r/redditsync/comments/ky3pto

**Comment by laurencedawson** [comment]
done
