### ISSUE TITLE
[BUG] Thin white lines appear around some images in full height cards

### ISSUE THREAD

**Issue by csttsn** [laurencedawson/sync-for-reddit#489]
**Describe the bug**
Thin white lines appear around some images in full height cards.

**To Reproduce**
1. Enable full-height cards
2. Enable full-width cards
3. Browse some subreddit with lots of pictures (r/museum, for example)

**Expected behavior**
Images should occupy full width.

**Screenshots**
https://external-preview.redd.it/GQzDOGeqGCCBadaAUe4hDZKHxQv5j9sefmbtQxKfWQ0.jpg?auto=webp&s=6fa7dac2b27f5dcf07c9db9e01c2aaacbe1d6676

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers

**Comment by csttsn** [comment]
Not sure why it was reopened, because it is fixed in beta 38 (both for cards and slides).

**Comment by csttsn** [comment]
> Not sure why it was reopened, because it is fixed in beta 38 (both for cards and slides).
Update: I reinstalled Sync before updating to V20, and the issue indeed persists. Very strange!

**Comment by laurencedawson** [comment]
Fixed again for the next release. Sorry about the hold up on this one!

**Comment by csttsn** [comment]
> Fixed again for the next release. Sorry about the hold up on this one!

Thank you very much!
