### ISSUE TITLE
Feature request: Toggles for content filters

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#49]
User-created content filters for keywords, domains, or subreddits exactly how it is now, but with an on/off switch.

**Comment by laurencedawson** [comment]
How would this look, per filter toggle?

**Comment by andysteakfries** [comment]
![20200601_sync-filter-example](https://user-images.githubusercontent.com/65996472/83460479-61329a80-a41b-11ea-8a30-ec83a1f64db4.png)

Yeah, nothing more than adding a toggle in addition to being able to remove it entirely. Obligatory MS Paint mockup is provided.

**Comment by laurencedawson** [comment]
Review some older issues and I think I'm going to close this one. I don't really see the benefit as you can quickly add or remove them anyways,
