### ISSUE TITLE
[BUG] Settings toggle buttons have disabled state when off

### ISSUE THREAD

**Issue by rvictorr** [laurencedawson/sync-for-reddit#490]
**Describe the bug**
The toggle buttons in settings use the disabled state when off.

**To Reproduce**
1. Go to settings

**Expected behavior**
Toggle buttons should use the off state, not the disabled one.

**Screenshots**
![Screenshot_20210116-134839](https://user-images.githubusercontent.com/4266327/104811346-7110ba80-5803-11eb-8025-ea4e894b32c0.png)
![Screenshot_20210116-134843](https://user-images.githubusercontent.com/4266327/104811348-72da7e00-5803-11eb-8e3c-b87290d7b515.png)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 5 II
 - OS: Android 10
 - Version v20 beta 27

**Comment by laurencedawson** [comment]
Updated for the next release. Cheers

**Comment by rvictorr** [comment]
Still happening in dark mode

![Screenshot_20210305-200455](https://user-images.githubusercontent.com/4266327/110155391-38966180-7dee-11eb-8ca0-688674f6a15a.png)

**Comment by laurencedawson** [comment]
It's really not.

Go to general and try toggling autohide toolbar when pin chip bar is
disabled. You'll be able to observe that when not selected the switch has
two tones. When it's disabled it only has one tone.

**Comment by rvictorr** [comment]
Oops my bad, you're right. However I still think the difference between off and disabled isn't obvious enough:
![Screenshot_20210305-235509](https://user-images.githubusercontent.com/4266327/110177967-74d9ba00-7e0e-11eb-8298-8cb33d697eac.png)
![Screenshot_20210305-235519](https://user-images.githubusercontent.com/4266327/110177973-760ae700-7e0e-11eb-9d61-00530574e662.png)

**Comment by laurencedawson** [comment]
It's all based on themes. Some work slightly better than others!

**Comment by rvictorr** [comment]
Fair enough! What do you think about also dimming the labels of disabled items?
