### ISSUE TITLE
[BUG] Some videos are saved and shared with wrong extensions/mime types

### ISSUE THREAD

**Issue by oakkitten** [laurencedawson/sync-for-reddit#492]
Some videos are saved and shared with wrong extensions/mime types

**Steps to reproduce the behavior**
1. Go to https://redd.it/kykjef
2. Note that the url has `r5tn1m42npb61.gif?format=mp4`
2. Try to save or share media
3. Observe that it's saved as `r5tn1m42npb61.jpg.gif` (and doesn't work) or shared as a gif (and also doesn't work)
4. Rename the extension to `mp4` and observe that it works

**Expected behavior**
The mime type and/or extension is correct

**Screenshots**

**Smartphone**
 - Device: Xiaomi Mi A2
 - OS: Android 11
 - Browser: Firefox Nightly
 - Version: Free v20 (beta 26)

**Comment by laurencedawson** [comment]
Fixed in beta 27. Cheers

**Comment by oakkitten** [comment]
just got beta 28 and while the file is now saved as `r5tn1m42npb61.gif` instead of `r5tn1m42npb61.jpg.gif` it's still unusable as it's really not a gif but a mp4. sharing also doesn't work so it has the same issue.
