### ISSUE TITLE
[BUG] Invalid HTML closing tags disappear 

### ISSUE THREAD

**Issue by yttrian** [laurencedawson/sync-for-reddit#493]
**Describe the bug**
While valid HTML tags like `font` and `span` no longer render, invalid tags like `marquee` render the opening tag but not the closing tag. 

**To Reproduce**
1. Write a comment with an invalid tag 
2. Observe the closing tag not showing 

**Expected behavior**
I'm not sure. The Reddit website shows HTML tags, valid or invalid. The latest update still keeps valid tags hidden, but they no longer affect the color of text. I would assume it would make more sense to show all tags valid or invalid to match the behavior of the website and expectations of users trying to share HTML. 

**Screenshots**
![Screenshot_20210116-225021](https://user-images.githubusercontent.com/5406616/104830510-cd98c780-584d-11eb-9b01-ff7820f9dfde.png)
![Screenshot_20210116-225333](https://user-images.githubusercontent.com/5406616/104830511-ce315e00-584d-11eb-901b-76b94c605f50.png)
![Screenshot_20210116-225353](https://user-images.githubusercontent.com/5406616/104830512-ce315e00-584d-11eb-9fa9-47294822a2b2.png)

**Smartphone (please complete the following information):**
Sync version: v20 (beta 27)    
Sync flavor: pro    
View type: Cards    
Push enabled: false    
Device: def    
Model: motorola motorola one hyper    
Android: 10

**Additional context**
(sorry)

**Comment by laurencedawson** [comment]
This has since been fixed
