### ISSUE TITLE
[BUG] Loading a theme overwrites the sticky text color

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#494]
**Describe the bug**

**To Reproduce**
1. Go to Settings/Theme customization
2. Create a theme and click save, with any name.
3. Click on the color palette button on the top bar, and select your recently created theme. 
4. See error: the text color for Sticky Text gets overwritten with dark green.

Video: http://imgur.com/a/3v9ycBl

**Expected behavior**
All colors should be loaded as they were saved.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 10, One UI 2.5
 - Version 20b27

**Additional context**
Didn't happen on v20b26

**Comment by hmzuleta** [comment]
Still happens on beta 28

**Comment by hmzuleta** [comment]
Still happens on beta 31

**Comment by laurencedawson** [comment]
Sticky text color is now part of the export json (as of beta 35)
