### ISSUE TITLE
[BUG] Typeface selection list doesn't get updated

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#496]
**Describe the bug**
When selecting a new typeface while customizing the post view, the preview is indeed changed, but the selected typeface will still reference the previous one. The list is only updated when you go back to the Settings activity and reload the Post View Customization activity.

**To Reproduce**
Video: https://imgur.com/a/WTHFvob

**Expected behavior**
Updating the typeface and clicking on the typeface option list again should show the proper selected typeface, not the previous one. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 10, One UI 2.5
 - Version 20b27

**Additional information:**
Happens for all typeface selectors

**Comment by hmzuleta** [comment]
Still happens on beta 28

**Comment by laurencedawson** [comment]
Fixed
