### ISSUE TITLE
[BUG] Videos stop playing for the last second when autoplay is on

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#497]
**Describe the bug**
When scrolling down a subreddit while having full height or dynamic height (RIP) cards, and Autoplay (Settings/Data options/Autoplay) on, videos will play automatically but, once they reach the end, the seekbar will continue going for a second or two, while the video is stopped. This behavior does not occur when watching the video on the media viewer (after tapping on the video).

**To Reproduce**
1. Enable full height cards and Autoplay
2. Scroll on any sub until a video comes up
3. Watch the video
4. Notice how the seekbar keeps going for the last couple of seconds but the video is completely stopped.

**Expected behavior**
The video's seekbar should not keep going once the video is done playing, it should loop back immediately.

**Video**
https://imgur.com/a/xvN8Dwr

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 10 One UI 2.5
 - Version 20b27

**Additional context**
I noticed it since v20b26. It seems to happen on videos hosted on Reddit and Imgur, so I would assume it's a general but with the video Autoplay feature.

**Comment by hmzuleta** [comment]
Can confirm it happens in beta 28.

**Comment by laurencedawson** [comment]
Cannot reproduce. Keep in mind that the previews there are different to the files shown in the image viewer and can be trimmed etc.
