### ISSUE TITLE
[BUG] [Cosmetic] Inconsistent padding/spacing in post flairs

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#498]
**Describe the bug**
Very minor bug on v20b27. It seems like there is a space at the end of the flairs' text, so it looks strange.
Maybe a space at the beginning would make it look symmetrical and padded.

![Screenshot_20210117-084225_Sync Pro](https://user-images.githubusercontent.com/3502252/104844810-49236480-58a0-11eb-9e26-040287d7d8d3.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 10 One UI 2.5
 - Version 20b27

**Comment by hmzuleta** [comment]
The extra space at the end does not appear for awards:
![Screenshot_20210117-084700_Sync Pro](https://user-images.githubusercontent.com/3502252/104844901-b1724600-58a0-11eb-86fe-b06cdd82ad44.png)

**Comment by hmzuleta** [comment]
Doesn't happen for user flair either:
![Screenshot_20210118-234110_Sync Pro](https://user-images.githubusercontent.com/3502252/104988661-ad504080-59e6-11eb-810a-3b06dd1863bb.png)

**Comment by laurencedawson** [comment]
This has since been fixed
