### ISSUE TITLE
[BUG] Creating multireddit with single character name shows generic error message

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#499]
**Describe the bug**
If you try to create a multirreddit whose name consists of only one character, a vague error message is shown "Failed to create multireddit". However, it is caused by the length of the name, which needs to be 2 or more characters long.

Video: https://gfycat.com/entirewickedeft
Photo:
![Screenshot_20210118-233646_Sync Pro](https://user-images.githubusercontent.com/3502252/104988469-1d11fb80-59e6-11eb-91a2-b90585e9d906.png)

**Expected behavior**
A more descriptive error message would be better, or add length validation to the multirreddit name field.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 10 One UI 2.5
 - Version 20b27

**Comment by laurencedawson** [comment]
Updated this to a bottomsheet and added better error messages.

Thanks
