### ISSUE TITLE
[BUG] Read on scroll causing stutter

### ISSUE THREAD

**Issue by auterak** [laurencedawson/sync-for-reddit#500]
**Description**
Turning read on scroll on causes stutter-like behavior when scrolling. The issue is most apparent when using more compact views, such as list, compact or smaller cards, but it is still present using other views. 

**To Reproduce**
1. Turn on read on scroll
2. Scroll through unread posts

**Expected behavior**
Scrolling should be smooth

**Screenshots**
I've tried to capture it via screen recorder, so I hope this will suffice - [https://streamable.com/j5xmqf](https://streamable.com/j5xmqf)

**Smartphone:**
 - Device: Xiaomi Mi 9 Lite
 - OS: Android 10 (MIUI 12.0.5)
 - Browser: Firefox
 - Version: v20 (beta 27)

**Comment by auterak** [comment]
This is still present in beta 32

**Comment by laurencedawson** [comment]
Few big updates for beta 35 to fix this.
