### ISSUE TITLE
Option to change the look and feel for flairs/type listed under posts

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#501]
**Is your feature request related to a problem? Please describe.**
An option to change the look and feel of the type of a post or a flair that's listed under a post such as (Media, Daily Discussion, Sunday Support, etc) would help so it stands out in a custom theme. 

**Describe the solution you'd like**
A theme option to control the look. Optional feature would be to change them into tiny chips.

**Describe alternatives you've considered**
Instead of providing option, they could use the accent color that's set. 

**Additional context**
Screenshot for what I am talking about. 
![Screenshot_20210117-121710_Sync Pro~2](https://user-images.githubusercontent.com/20840348/104852218-39674880-58bf-11eb-8713-526b9310db94.jpg)

**Comment by laurencedawson** [comment]
This has been implemented for b29
