### ISSUE TITLE
Option to hide or use the new comment bar that was in previous betas

### ISSUE THREAD

**Issue by patel-jeel92** [laurencedawson/sync-for-reddit#504]
**Is your feature request related to a problem? Please describe.**
Frustrated that the new comment bar was removed. It was really convenient to write a new comment or sort really quickly using that bar. 

**Describe the solution you'd like**
An option to either hide it or show it so people can toggle it based on their preference

**Comment by scottjfer** [comment]
I believe this is coming back in a future iteration, but don't hold me to it!

**Comment by laurencedawson** [comment]
Added back!
