### ISSUE TITLE
[BUG] With "show post author" disabled, users tags and the divider dot will still show.

### ISSUE THREAD

**Issue by PrebbLord** [laurencedawson/sync-for-reddit#505]
**Describe the bug**
When "show post author" setting is turned off, the user's flair will still be displayed. In addition, if no flair is displayed, there is a divider dot at the beginning of the description when there shouldn't be.

**To Reproduce**
1. Turn off "show post author" in post options
2. View frontpage

**Expected behavior**
Dot in front shouldn't appear when username is hidden.
User flair shouldn't appear when username is hidden.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/7637583/104858927-6aab4b80-5987-11eb-8ba7-dbcbf5381565.jpg)

![Untitled2-1](https://user-images.githubusercontent.com/7637583/104858935-726af000-5987-11eb-95c8-3129163015ce.jpg)

**Smartphone:**
 - Device: Galaxy Note 9
 - OS: 10

**Comment by laurencedawson** [comment]
This has since been fixed
