### ISSUE TITLE
[BUG] Sharing video directly from Sync to Telegram will send it as a file and not a video.

### ISSUE THREAD

**Issue by PrebbLord** [laurencedawson/sync-for-reddit#507]
**Describe the bug**
When using the direct share in app for videos/MP4s, when sharing that to telegram and possibly other apps, it won't display as a video but as a file, forcing the user to open it externally. Saving the video in sync then sharing it from the notification, it functions as expected and will display as a video, not a file.

**To Reproduce**
1. Find a video post
2. Open video
3. On share menu, select 'direct'
4. Send to telegram
5. Cry

**Smartphone:**
 - Device: Galaxy Note 9
 - OS: Android 10

**Additional**
I tried with some other apps and it does work as expected but I don't have many messaging apps to test on. So if this is a telegram exclusive issue or not, I'm not entirely sure but it does show that the behaviour of share from in app and from the download notification are different.

**Comment by laurencedawson** [comment]
Alright after a few hours I cracked this one.

So most other apps will go ahead and find the file and load up to show a preview before sending to someone.

Telegram expects the video to be in a public directory saved using the MediaStore API.

So the only alternative I can think of at this point is to save the file to "Movies" and then share with Telegram...

**Comment by PrebbLord** [comment]
Ahhh, thanks for looking into it! I guess telegram changed something on their end recently because it worked as expected a couple of months ago. I guess I just have to hope they change it back.

**Comment by laurencedawson** [comment]
Telegram has since changed this behaviour woo
