### ISSUE TITLE
[BUG] Cards do not show upvote percentage

### ISSUE THREAD

**Issue by yttrian** [laurencedawson/sync-for-reddit#508]
**Describe the bug**
When post view customization is set it cards, entering a post does not show the upvote percentage. It does show it for slides option. 

**To Reproduce**
1. Set post view customization to cards
2. Open the comments of a post

**Expected behavior**
Upvote percentage should show. 

**Screenshots**
![Screenshot_20210118-032739](https://user-images.githubusercontent.com/5406616/104890527-b2a58080-593d-11eb-84b1-2083750b50cf.png)
![Screenshot_20210118-032812](https://user-images.githubusercontent.com/5406616/104890529-b33e1700-593d-11eb-8f0c-a81b90359362.png)

**Smartphone (please complete the following information):**
Sync version: v20 (beta 27)
Sync flavor: pro
View type: Cards
Push enabled: false
Device: def
Model: motorola motorola one hyper
Android: 10

**Additional context**
None.

**Comment by laurencedawson** [comment]
Fixed. Cheers
