### ISSUE TITLE
[BUG] disabling "pin chipbar" still keeps the chipbar pinned

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#509]
https://user-images.githubusercontent.com/3417276/104930271-5f274700-59be-11eb-8709-967f94e45133.mp4

**Describe the bug**
Unpinning the chipbar in settings doesn't unpin the chipbar

**To Reproduce**
1. Disable pin chipbar
2. Scroll down
3. Chipbar still pinned

**Expected behavior**
The chipbar should hide on scroll

**Smartphone (please complete the following information):**
 Samsung galaxy note 9
 One UI 2.5 Android 10
 - Version beta 28

**Comment by scottjfer** [comment]
I am able to replicate this by having "pin chipbar" disabled but also disabling "autohide toolbar", which can be found above the chipbar settings. The hiding behaviour works as expected if "autohide toolbar" is enabled.

**Comment by laurencedawson** [comment]
This is actually the expected behaviour. I'll add logic to disable the option if autohide is not enabled.
