### ISSUE TITLE
BUG: Keyboard not appearing when pressing reply

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#51]
Alpha 18

User said:
 "OnePlus 6, Google keyboard. Alpha.  Sometimes I can't type.  I'll try to reply to a comment, keyboard up and phone vibrates registering the key, but nothing shows up in redditsync."

First recorded issue of this occuring, may be issue on users end (3rd party app issue, OEM skin issue)

No current way to replicate:
"It's also not 100% of the time, still trying to figure out triggers."

**Comment by laurencedawson** [comment]
This is likely a oneplus issue and now sync. Closing unless we have more reports.
