### ISSUE TITLE
Not everything is themed correctly[BUG]

### ISSUE THREAD

**Issue by fessmm** [laurencedawson/sync-for-reddit#514]
**Describe the bug**
Some hidden parts of the app are not correctly themed and therefore are hardcoded

**To Reproduce**
1. Go to Quick actions (Sync Symbol on the Bottom navigation)
2. Click on the 3 dots menu, also same with the Action visibility List
3. See error: Hardcoded color
4. https://imgur.com/a/5ABT7Mc
5. https://imgur.com/a/6D6B4ht

1. Go to left navigation menu
2. Click on the 3 dots
3. See error: Hardoced color for the 3 dots menu, section visibility and apps 
4. https://imgur.com/a/ImVpKYp
5. https://imgur.com/a/BoskSkA
6. https://imgur.com/a/3k0af5y

1. Go to search from botton navigation
2. Click on the 3 dots menu, also happens on the 3 dots menu of the recently searched subreddits
3. See error: Hardoced color
4. https://imgur.com/a/PN9nwr1
5. https://imgur.com/a/MUHIT6G

1. Go to the bottom navigation and open subreddits
2. Click on the 3 dots menu also for the 3 dots menu of the subreddits
3. See error: Hardoced color for both 3 dot menu and subreddit 3 dots menu
4. https://imgur.com/a/nnMUfvM
5. https://imgur.com/a/M3ALnsZ

**Expected behavior**
Follow the theme

**Screenshots**
Screenshots above

**Smartphone (please complete the following information):**
 - Device: [Oneplus6]
 - OS: [Android 11]
 - Version [Sync Beta 28]

**Comment by laurencedawson** [comment]
Not a bug. This was a decision to have one color for those in dark and one for light mode.

**Comment by fessmm** [comment]
> Not a bug. This was a decision to have one color for those in dark and one for light mode.
alright then close this issue if you want to leave it like that 👍

**Comment by laurencedawson** [comment]
Cheers
