### ISSUE TITLE
About in quick actions opens trending[BUG]

### ISSUE THREAD

**Issue by fessmm** [laurencedawson/sync-for-reddit#515]
**Describe the bug**

**To Reproduce**
1. Go to quick actions 
2. Click on about
3. See error: It opens Trending

**Expected behavior**
It should open the about section not the trending section

**Screenshots**
https://imgur.com/a/FJp3zEp
https://imgur.com/a/BOnvOYp

**Smartphone (please complete the following information):**
 - Device: [Oneplus6]
 - OS: [Android 11]
 - Version [Sync Beta 28]

**Comment by laurencedawson** [comment]
fixed
