### ISSUE TITLE
Slides view with a smaller media preview or thumbnail

### ISSUE THREAD

**Issue by Code027** [laurencedawson/sync-for-reddit#516]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
It would probably be good to see an option to make the image in the Slides view to also be placed in the right or left side of the view, similar to how it appears in the small cards.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by laurencedawson** [comment]
Slides is intended to use full images. I'd recommend using a different view mode. Cheers
