### ISSUE TITLE
[BUG] Version 28 - Account Picker menu breaks after navigating from Messages/Inbox

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#517]
1. Open Sync, tap Account Picker icon in top right to see Accounts.
2. Tap on Inbox/Messages on lower toolbar
3. Go back to Home page
4. Tap Account Picker icon, it acts as the old 3 dot menu and pulls up Quick Actions instead

**Comment by laurencedawson** [comment]
Fixed
