### ISSUE TITLE
BUG: App hierarchy inconsistencies

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#52]
User said: 
"I feel like navigation just doesn't work as intuitively in the alpha. For example, visiting a subreddit, then going to your profile from the toolbar and then clicking back from there takes you to the front page instead of the subreddit you were at. This is just hierarchically wrong, no?"

Steps to reproduce:
Visit subreddit>Tap profile icon>Tap "Profile">Back out of user profile page>User is brought back to Frontpage instead of subreddit they were currently in"

User also said:
"Also being on a subreddit, performing a search and then clicking back takes you to the front page instead of the subreddit you were at"

Steps to reproduce:
Visit subreddit>use search to search for term>be brought to search results page>back out of search page>user is brought to Frontpage instead of subreddit they were previously in

**Comment by laurencedawson** [comment]
These have since been addressed.
