### ISSUE TITLE
[BUG] Cannot upload PNG images.

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-reddit#520]
**Describe the bug**
When you try to upload an image, you can only pick JPG files, PNGs are greyed out.

**To Reproduce**
1. Create a post
2. Go to the image picker
3. Try to select a PNG

**Expected behavior**
The PNGs should be able to be picked just like the JPGs.

**Screenshots**
![Screenshot_20210119-140915.png](https://user-images.githubusercontent.com/28932047/105081918-d7dedf80-5a60-11eb-88ef-070e92dc94e1.png)
![Screenshot_20210119-141602.png](https://user-images.githubusercontent.com/28932047/105081954-e4fbce80-5a60-11eb-8488-cae309e1780c.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 11 (January 2021)
 - Browser Chrome Beta
 - Version Beta 28

**Comment by laurencedawson** [comment]
Fixed
