### ISSUE TITLE
[BUG] Sharing post preview text has extra padding

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#522]
Pictures speak a thousand words

~Wayne Gretzky 
![1611159452005](https://user-images.githubusercontent.com/31053171/105204684-74ad8580-5b12-11eb-9732-95b7bd20c88e.jpg)

**Comment by laurencedawson** [comment]
Fixed

**Comment by laurencedawson** [comment]
- Michael Scott
