### ISSUE TITLE
[BUG] Swiping a post to hide causes crashes

### ISSUE THREAD

**Issue by michaeldrouin** [laurencedawson/sync-for-reddit#526]
**Describe the bug**
when scrolling through posts on the frontpage while using the "slides" view, if you swallow to the left to hide posts the app crashes after a few hides in a row.

**To Reproduce**
1. open app
2. make sure your view setting for posts is set to "slides"
3. start swiping left on posts to hide them
4. boom

**Expected behavior**
the posts to get hidden and the app not too crash

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android 11
 - Browser: Firefox
 - Version 84.1.4
 - Sync Version: v20 Beta 28

**Comment by mivens** [comment]
See also bug report at [https://www.reddit.com/r/redditsync/comments/l2it5f](https://www.reddit.com/r/redditsync/comments/l2it5f)

**Logcat from that report:**

`FATAL EXCEPTION: main Process: com.laurencedawson.reddit_sync.pro, PID: 12463 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:-1).state:22 com.laurencedawson.reddit_sync.ui.views.recycler.PostsRecyclerView{546b0d5 VFED.V... ......ID 0,0-1080,2000 #7f0901d9 app:id/fragment_posts_vertical_recycler}, adapter:d4.f@2b860ea, layout:com.laurencedawson.reddit_sync.ui.util.recycler.CustomLinearLayoutManager@504bfdb, context:com.laurencedawson.reddit_sync.ui.activities.MainActivity@1dcf982 at androidx.recyclerview.widget.RecyclerView$w.H(RecyclerView.java:35) at androidx.recyclerview.widget.RecyclerView$w.p(RecyclerView.java:1) at androidx.recyclerview.widget.RecyclerView$w.o(RecyclerView.java:1) at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3) at androidx.recyclerview.widget.LinearLayoutManager.q2(LinearLayoutManager.java:1) at androidx.recyclerview.widget.LinearLayoutManager.W1(LinearLayoutManager.java:9) at androidx.recyclerview.widget.LinearLayoutManager.Y0(LinearLayoutManager.java:72) at androidx.recyclerview.widget.RecyclerView.E(RecyclerView.java:31) at androidx.recyclerview.widget.RecyclerView.D(RecyclerView.java:13) at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at androidx.coordinatorlayout.widget.CoordinatorLayout.M(CoordinatorLayout.java:18) at androidx.coordinatorlayout.widget.CoordinatorLayout.S(CoordinatorLayout.java:7) at com.google.android.material.appbar.ViewOffsetBehavior.F(ViewOffsetBehavior.java:1) at com.google.android.material.appbar.HeaderScrollingViewBehavior.F(HeaderScrollingViewBehavior.java:24) at com.google.android.material.appbar.ViewOffsetBehavior.l(ViewOffsetBehavior.java:1) at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.l(AppBarLayout.java:1) at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at com.google.android.material.appbar.HeaderScrollingViewBehavior.F(HeaderScrollingViewBehavior.java:22) at com.google.android.material.appbar.ViewOffsetBehavior.l(ViewOffsetBehavior.java:1) at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.l(AppBarLayout.java:1) at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at com.laurencedawson.reddit_sync.discord.OverlappingPanelsLayout.onLayout(OverlappingPanelsLayout.kt:1) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:22844) at android.view.ViewGroup.layout(ViewGroup.java:6389) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673) at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)`

**Comment by laurencedawson** [comment]
Fixed
