### ISSUE TITLE
[BUG] Themes get mixed up when you load a new theme and swipe back a few pages

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#527]
**Describe the bug**
Loading a new theme will initially seem fine. Going back a few pages by swiping will show this bug

**To Reproduce**
1. Open frontpage 
2. Click on a subname of a post to open that sub
3. From that sub, click on a username from a post to open a userprofile
4. Basically, open up 3-4 new pages over each other 
5. Open settings a load new theme
6. Swipe back to previous pages
7. Few pages at the start would have a mix of old and new theme

**Screenshots**
![Screenshot_20210122-202017.jpg](https://user-images.githubusercontent.com/55349349/105520177-5dcc8600-5d00-11eb-954a-2fbf1c5a41b2.jpg)

**Smartphone:**
 - Device: OnePlus 7
 - OS: Android 10

**Comment by laurencedawson** [comment]
This was fixed in v22 woo
