### ISSUE TITLE
[BUG] Swipe to Return reduces touch sensitivity on Samsung devices

### ISSUE THREAD

**Issue by razordynamics** [laurencedawson/sync-for-reddit#528]
**Describe the bug**
Touch sensitivity is reduced when Swipe to Return is enabled - it often takes more than one tap to save a post/mark as favorite or to tap an image post to open. Turning off Swipe to Return eliminates this issue - tapping on the same UI elements is responsive and takes a single tap. I am using a Galaxy S20 5G, beta 28 of Reddit Sync, on OneUI 3.0 (Android 11).

I have tested and reproduced the issue with Increased Sensitivity enabled and disabled (device Settings app --> Display --> Touch Sensitivity), no change. I have also disabled Samsung's Edge panel feature, no change. 

I have also enabled Show Taps and Pointer Locations under Developer Settings in the device Settings app and can confirm that I am indeed touching the display and that the device is registering the touch input, but the app is not. The issue also is not present with other Reddit apps, such as Boost or Relay.

Lastly, I am not using any screen protector.

This issue has occurred in the past with other Samsung devices and other users:
https://www.reddit.com/r/redditsync/comments/adek3h/touch_screen_taps_not_registering_every_time_in/
https://www.reddit.com/r/redditsync/comments/h9ht7t/comment_actions_tap_and_long_press_are_often/
https://www.reddit.com/r/redditsync/comments/azmn5z/bug_taps_not_registered_on_galaxy_s9/
https://www.reddit.com/r/redditsync/comments/i3v5dq/samsung_s20_single_touchtap_finnicky/
https://www.reddit.com/r/redditsync/comments/kwma6g/touch_sensitivity_on_samsung_galaxy_s20/

**To Reproduce**
On a Samsung device, enable Swipe to Return on Reddit Sync settings (General), and go into your post feed and try to save comments/posts and open image posts. About half the time you will have to tap more than once.

**Expected behavior**
Single tapping on the save button (the star icon) for a comment and post should save the comment or post. Single tapping on an image post in any post view should open the image.

**Screenshots**
Not really applicable.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 5G (Snapdragon version)
 - OS: OneUI 3.0 (Android 11)
 - Browser: Firefox
 - Version Reddit Sync beta 28

**Additional context**
This issue doesn't exist at all on other non-Samsung devices that I have tried: OnePlus 7 Pro, Pixel 4a 5G, Fire HD 10 (2019) tablet

**Comment by razordynamics** [comment]
Please do let me know if there's any additional data you need, such as logs, etc. Thank you in advance!

**Comment by laurencedawson** [comment]
I've swapped to the latest version of the google drag helper. Lets see if that helps in beta 29

**Comment by laurencedawson** [comment]
Looks like this has been fixed. Hurrah!
