### ISSUE TITLE
[BUG] Numbered lists not working properly if the you start list with a non - 1 bullet point

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#534]
**Describe the bug**
If you want to start a numbered list with '2', the comment will turn it to '1' when you submit the comment 

**To Reproduce**
Case A
1. Put a bullet point "2."
2. Write some text 
3. Put a bullet point "3."
4. Write some text 

**Expected behavior**
Comment should display - 
2. Test 1
3. Test 2

Comment shows - 
1. Test 1
2. Test 2

And if you put text between both these bullets, then both bullet point show "1."

**Screenshots**
![Screenshot_20210126-095327~(1).jpg](https://user-images.githubusercontent.com/55349349/105800658-43730080-5fbd-11eb-8b29-1e628d312f0f.jpg)

![Screenshot_20210126-095333~(1)__01.jpg](https://user-images.githubusercontent.com/55349349/105800666-48d04b00-5fbd-11eb-802a-c4f05dea4dd4.jpg)

**Comment by laurencedawson** [comment]
This is sadly an issue with the markdown parser Sync uses,

**Comment by laurencedawson** [comment]
The markdown processor sync uses scrubs this out and there's no easy way to get this back.

Marking as "wontfix" and closing.
