### ISSUE TITLE
Adding a Forward button to return to a page that was backed out from

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#536]
**Is your feature request related to a problem? Please describe.**
If you've accidentally backed out of a search or nested searches/subreddit entries by the back button, a forward button to re-enter that search or the page that was backed out from would be great

A clear and concise description of what the problem is.
When I search the postatch thread flair in r/soccer and scroll through in new(week), there are times where I accidentally press the back button or do the back gesture on my phone, and I'd be back on the front page within seconds, a way to go forward in pages/actions would be a nice addition

**Describe the solution you'd like**
I've thought of adding the forward button in the sync button drawer but it doesn't allow to go forward within a post, so a forward button with the post ellipses option would fix that I feel

**Describe alternatives you've considered**
An alternative is the already available search history but a post that I've been backed out of by accident would not be visible from there

**Additional context**
![20210128_200039](https://user-images.githubusercontent.com/3417276/106164562-88f12280-61a3-11eb-9856-61ed4226958f.png)

**Comment by laurencedawson** [comment]
I'd suggest looking at the recents tab as this allows pretty much exactly this but for comments.
