### ISSUE TITLE
[BUG] Text/images cut off on inside margins while spanned in landscape mode (surface duo) 

### ISSUE THREAD

**Issue by dadartz** [laurencedawson/sync-for-reddit#537]
When the app is set to two-panel span in landscape (to utilize the double screen of the surface duo) the inside margins of both screens are cut off resulting in cropped images and text. Essentially, the gap between the screens is not being taken into account.

**Comment by laurencedawson** [comment]
Screenshot?

**Comment by dadartz** [comment]
![IMG_20210128_151759](https://user-images.githubusercontent.com/4504713/106210634-0b65ec00-617c-11eb-8c4f-18e5df853a6c.jpg)
Hope this helps!

**Comment by laurencedawson** [comment]
Closing as this will be covered by:

https://github.com/laurencedawson/sync-for-reddit/issues/537
