### ISSUE TITLE
[BUG] After clicking on a flair in a multireddit, swiping back goes: flair→subreddit→multireddit

### ISSUE THREAD

**Issue by ovitters** [laurencedawson/sync-for-reddit#542]
**Describe the bug**

After clicking on a flair in a multireddit, each swipe back does the following: flair→subreddit→multireddit. I'd expect flair→multireddit.

**To Reproduce**
1. Go to a multireddit with a few subreddits in it
2. Click on the flair on a post (so it'll filter to that subreddits flair)
3. Swipe back
4. See that Sync now only shows one subreddit instead of going back to the multireddit

**Expected behavior**
I expect it to go back to the multireddit without needing to swipe back twice. 
Something like, clicking: multireddit→flair posts. Swiping back: flair posts→multireddit.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: Android 10
 - Version: Beta 28 (sync for reddit pro)

**Additional context**

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers
