### ISSUE TITLE
[BUG]Can't remove "Random NSFW" quick action tile if "Hide NSFW Posts" filter is toggled on in settings 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#543]
**Describe the bug**
If the "Hide NSFW Posts" filter is on, then the action visibility menu doesn't show "Random NSFW". So if someone had that quick action check marked earlier, they can't remove it now. 

The would have to toggle the Hide NSFW filter. And then hide the quick action tile. 

**To Reproduce**

1. Make sure "Hide NSFW Posts" filter is off
2. Add Random NSFW quick action tile to the sync menu
3. Turn on the filter in Step 1
4. Attempt to remove the "Random NSFW" quick action tile

**Expected behavior**
User cannot add the Random NSFW tile if the user has the "Hide NSFW Posts" filter on. That makes sense

But it should allow the user to remove the action tile irrespective of the filter setting

**Comment by laurencedawson** [comment]
I actually think this is incorrect. If the nsfw option is enabled the ability to show or hide should be hidden.

However if they previously enabled it and THEN disabled nsfw content the option should be hidden. I've added this fix for beta 31.
