### ISSUE TITLE
[BUG] Drawer Navigation is empty when user enables drawer navigation [Beta 30]

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#544]
**Describe the bug**
Drawer Navigation is empty when user enables drawer navigation. Restarting the app resolves this issue

**To Reproduce**
1. If drawer navigation is on, Turn off drawer navigation 
2. Relaunch app
3. Turn on drawer nagivation
4. Try using drawer navigation 
5. See empty drawer

**Expected behavior**
Drawer should not be empty

**Screenshots**
![Screenshot_20210203-153715.jpg](https://user-images.githubusercontent.com/55349349/106733891-6c883680-6638-11eb-86f2-604329073920.jpg)

**Comment by laurencedawson** [comment]
Fixed for beta 35
