### ISSUE TITLE
[BUG] Random NSFW is lowercase

### ISSUE THREAD

**Issue by PrebbLord** [laurencedawson/sync-for-reddit#545]
**Describe the bug**
In the sync menu, the Random NSFW button, NSFW is lowercase when it should be all caps.

**Comment by laurencedawson** [comment]
Fixed

**Comment by PrebbLord** [comment]
This didn't seem to make it through. It's still lowercase on my end.

**Comment by laurencedawson** [comment]
Finally fixed lol
