### ISSUE TITLE
[BUG] Gifs from preview.redd.it are not downloaded properly

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#546]
UPDATE: View last comment for solution.

**Describe the bug**
Gifs and videos downloaded through the app, which are hosted in preview.redd.it. seem to be corrupted or not downloaded properly.

**To Reproduce**
1. Open this post on the app. https://www.reddit.com/r/memes/comments/lc4hxu
2. Download the gif through the app. Direct link to gif is https://preview.redd.it/whqrcysu9df61.gif?format=mp4&s=d234c8abbe1afd8f4ad67d204831263dec41fc28
3. Try to open the gif on your device.

**Expected behavior**
Gif should be downloaded and playable the same as imgur, gfycat, and v.redd.it hosted videos.

**Screenshots**
https://1drv.ms/u/s!AvkRx3qLjzoyg6pvFPhPUNHfjoCb4g

https://1drv.ms/u/s!AvkRx3qLjzoyg6pxs0MmPdxK67ITTw

https://1drv.ms/u/s!AvkRx3qLjzoyg6px3YnJVtxpgPayjQ

Actual corrupted gif: https://1drv.ms/u/s!AvkRx3qLjzoyg6py8lxNfwAsOVgpnQ

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 11, One UI 3.0
 - v20 beta 30

**Additional context**
Happens since beta 28, maybe earlier.

**Comment by hmzuleta** [comment]
Trying to play back the file on Samsung's gallery app shows a still image with the first frame of the gif.
I downloaded it using Firefox, and the same behavior is there (wtf).

However, the u/savevideo bot generates the correct download link: https://redditsave.com/info?url=/r/memes/comments/lc4hxu/maybe_i_am_a_robot/

Hotlink to that gif download: https://redditsave.com/d/aHR0cHM6Ly9pLnJlZGQuaXQvd2hxcmN5c3U5ZGY2MS5naWY=

I noticed that the proper gif is 10MB, while the one Sync and Firefox are downloading is 253K. Sounds like they're trying to download the .mp4 instead of the gif, and some weird error happens.

**Comment by chargingtriceratops** [comment]
Yep its an MP4 file 

As you can see in the download URL - "?format=mp4"

[Similar issue reported nearly a year ago.](https://old.reddit.com/r/redditsync/comments/f4zkb9/bug_ireddit_download_problem/fhx5900/)

**Comment by hmzuleta** [comment]
@chargingtriceratops yes, but Sync is downloading as gif :(

**Comment by laurencedawson** [comment]
.gif and is actually an mp4. Great naming scheme there reddit

**Comment by laurencedawson** [comment]
Fixed for beta 35
