### ISSUE TITLE
Some way to view multireddit subs from quick actions

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#547]
Prior to beta 29/30, you used to be able to tap the "About" button to bring up a list of the subs in the multireddit. Some way to hit that "Manage" button at the bottom would be much appreciated.

![Screenshot_20210204-101221.png](https://user-images.githubusercontent.com/2940826/106913102-a8bba580-66d1-11eb-9b66-a833a6b67f3a.png)

**Comment by laurencedawson** [comment]
This has since been added with the "contextual chips"
