### ISSUE TITLE
BUG: When viewing a subreddit after searching, subreddit title reflects capitalization of search term

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#55]
Alpha 19

Steps to reproduce:
Search for subreddit (ex. "android")>Tap on search result> User is brought to subreddit, where subreddit name follows users capitalization

(So searching for "android" and then tapping "android" brings you to r/Android, but displays "android" at top of screen. But when searching with a capital "Android", subreddit displays "Android" as name)

**Comment by laurencedawson** [comment]
Sorry but I'm not following this one. Got a pic?

**Comment by RecklessDwark** [comment]
https://imgur.com/a/j1m6iVz


Tapping the top result (capitalized):
https://imgur.com/a/perhkfr

Tapping the bottom result (not capitalized):
https://imgur.com/a/zYA1Pwc

**Comment by laurencedawson** [comment]
Aha, hmm I'll have a think on this one what the correct behavior should be.

**Comment by laurencedawson** [comment]
Fixed for the next release.
