### ISSUE TITLE
Request - Add subreddit picture to the left of sub name

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#550]
I feel like the app is missing sub pictures next to the name... 
Regarding concerns about the top being too crowded, I propose that when viewing a subreddit, the profile picture is changed to a 3 dot menu (keeping the same functionality) but keep the profile pic when viewing the default sub (aka frontpage).

**Comment by bohrabhijeet** [comment]
Added in v22.
