### ISSUE TITLE
Feature - Replace "return position" banner with button like Discord has

### ISSUE THREAD

**Issue by scottjfer** [laurencedawson/sync-for-reddit#551]
I really like Discord's implementation of this!
Instead of a big, opposite coloured banner taking up the whole bottom of the screen:
![Screenshot_20210205-074725](https://user-images.githubusercontent.com/31053171/107036726-0f9b9600-6788-11eb-9728-0dfd708e8c82.png)

Do it like Discord (and other apps) and have a little arrow in the corner (that can be moved to left, right, or centre of screen for dexterity) to go back down instead:
![Screenshot_20210205-074625](https://user-images.githubusercontent.com/31053171/107036855-42458e80-6788-11eb-94ab-5b2031c9386f.png)

It's a lot more elegant IMO and it also improves accessibility at the same time!

**Comment by felimenta970** [comment]
Whatsapp, Telegram are two other apps with the same behavior

**Comment by laurencedawson** [comment]
Gotta disagree on this one.

The snackbar is a call to action and familiar design.

The skip to bottom icon shown here is more commonly used in messaging applications and not really for this use.
