### ISSUE TITLE
[BUG] Comment Media links redirect to the first link in the generated album 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#553]
**Describe the bug**
If there are multiple media links in the comments, they appear as an album now but all links redirect to the first link of the album

**To Reproduce**

1. Go to a post on subs like r/HighQualityGifs or r/PhotoshopBattles. 
Example - https://redd.it/lcrqck

2. Click on few comment links

**Expected behavior**
All links should open

**Comment by laurencedawson** [comment]
Since removed
