### ISSUE TITLE
(request) Changes to the post flair (modern)

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#558]
Would you consider reducing the padding of the post flair to something more moderate, like the accent background over the op or mod which usually hugs the name as close as possible. The post flairs seem to be a tad too large

Also would you consider switching the theming of the flair? Currently the background is the accent and the text is black (or white depending on accent color), would you instead consider making the flair instead have an outline with transparent background like how it was previously with the text being the accent colors (like it is in minimal post flairs), this would make the flairs a bit less strong, especially on amoled backgrounds

[An image for reference](https://i.imgur.com/zlMPEgH.jpg)

**Comment by laurencedawson** [comment]
I've actually expanded the themeing to use what reddit provides.

As for the padding I'm inclined to disagree, there is always the minimal option. Cheers.
