### ISSUE TITLE
Restore split-screen function to v20+

### ISSUE THREAD

**Issue by jaw709** [laurencedawson/sync-for-reddit#566]
I recently upgraded to the beta v28, now v31 and am sad to find the beloved split-screen ability to no longer an option. I inquired about it on the reddit, but was told it was removed, with no intention to necessarily return it.
  
Before we do away with this function, one that I certainly began using from day 1 years ago, I just want to get community input. If you haven't tried it, please do and comment your feelings.   
  
If you do use it, or did use it, please let it be known that this feature is desired to continue.

Thank you

**Comment by 9aaron** [comment]
Very sad to see this missing from v20. This was the #1 reason I chose Sync. It's so convenient to browse reddit quickly. I used it on phone.

**Comment by apopanda** [comment]
If this is the feature where there's a list of posts on the left, with the post on the right in horizontal, then ditto - would love to see it in v20 as well. It's really convenient to scroll in bed without having to view every post, and without having to click out of a post every time, which is incredibly uncomfortable when the buttons are right next to the base of your thumb.

**Comment by jaw709** [comment]
> If this is the feature where there's a list of posts on the left, with the post on the right in horizontal, then ditto - would love to see it in v20 as well. It's really convenient to scroll in bed without having to view every post, and without having to click out of a post every time, which is incredibly uncomfortable when the buttons are right next to the base of your thumb.



> 
> 
> If this is the feature where there's a list of posts on the left, with the post on the right in horizontal, then ditto - would love to see it in v20 as well. It's really convenient to scroll in bed without having to view every post, and without having to click out of a post every time, which is incredibly uncomfortable when the buttons are right next to the base of your thumb.

Exactly, if you have v19 (I think they reverted the upgrade) then check it out. It's basically what I like to call "Outlook mode" because it has the links (in compact/list mode) on the left, and the preview on the right. Super-efficient, and world-class experience. One of the devs Burton something said it was supposed to return in V20 but I couldn't find it :shrug:

**Comment by laurencedawson** [comment]
This has since been added back
