### ISSUE TITLE
BUG: NSFW "covers" aren't appearing properly

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#57]
Even with "Hide all NSFW previews" enabled, media can still be seen. Cover appears when going into recents menu and returning back to Sync however

**Comment by laurencedawson** [comment]
Not quite sure what you mean with this one.

**Comment by RecklessDwark** [comment]
Reported by user in Discord:

https://imgur.com/a/fnoWpgI

Red NSFW covers don't appear unless post is opened, and then closed. Or if app is closed and then re-opened (such as going into the recent apps menu, and then going into the app again)

**Comment by laurencedawson** [comment]
Aha I think this one was fixed already. Cheers
