### ISSUE TITLE
[Suggestion] show OP username on comment reply activity

### ISSUE THREAD

**Issue by hmzuleta** [laurencedawson/sync-for-reddit#572]
It would be cool to see the username of the OP whose comment you're replying to above the comment text, and underneath the "Comment" activity title. This can let you confirm who you're replying to, in case of a mistake, or make comments about their username.

**Comment by bohrabhijeet** [comment]
Created ticket https://github.com/laurencedawson/sync-for-reddit/issues/1343 with a concept for this.
