### ISSUE TITLE
[Suggestion] Haptic feedback intensity slider

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#573]
**Context**:

I recently changed to a new phone, a Samsung Galaxy A51 to be exact and for some reason the phone came with haptic feedback turned off by default. It also comes with a very weak vibration motor. This would mean that applications that supports haptic feedback would not vibrate. (Sync comment actions, Plus, a Telegram Client)

**Solution**:

it'd be great for the application to have a haptic feedback intensity slider maybe nested in settings/general that would override what the application thinks the vibration motor would do. The vibration intensity would be measured in _ms_ similar to how Gboard does it. 

**Alternatives**:

I've used this application called SetEdit to enable haptic feedback but it doesn't enable it universally

**Comment by Nxt3** [comment]
FYI there are settings in Android you can change to possibly increase the haptic feedback. Typically these settings are under Accessibility.

**Comment by skff-err** [comment]
> FYI there are settings in Android you can change to possibly increase the haptic feedback. Typically these settings are under Accessibility.

i have haptic feedback enabled, look at alternatives i have tried on the post, no matter the intensity, it does not apply universally across all apps

**Comment by laurencedawson** [comment]
Comment actions vibrating can now be enabled even if the system option is off.

I have no plans to add a slider for intensity though. Cheers.

**Comment by skff-err** [comment]
> Comment actions vibrating can now be enabled even if the system option is off.
> 
> I have no plans to add a slider for intensity though. Cheers.

yeah my vibration motor might be too weak to do the default vibration duration set in the app. Thanks for adding the feature for people who needs it though
