### ISSUE TITLE
[FEATURE]: Semi-transparent statusbar

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#574]
At one point, having a fully transparent statusbar was possible. It has since been removed due to issues with visibility of the statusbar icons. I think a good middle-ground for this would be a semi-transparent statusbar. Having an opaque statusbar all the time makes the screen feel smaller on devices with notches. Would be a nice addition.

**Comment by scottjfer** [comment]
+1 from me too

**Comment by laurencedawson** [comment]
Transparent has since been added back.
