### ISSUE TITLE
Quick Actions Button

### ISSUE THREAD

**Issue by JoeG-1003** [laurencedawson/sync-for-reddit#575]
**Is your feature request related to a problem? Please describe.**
I use a large phone with my left hand. 

**Describe the solution you'd like**
 I would like to be able to move the quick actions button to the left side of the screen so I can easily access the Quick Actions using only one hand. 

**Describe alternatives you've considered**
Use two hands. 

**Additional context**

**Comment by laurencedawson** [comment]
This has since been added to the bottom nav.
