### ISSUE TITLE
[BUG] Beta 31: Navigating to Frontpage from user profile prevents hiding posts

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#577]
**Describe the bug**
Navigating to the Frontpage from someone's user account page creates another Frontpage pane on top which prevents swiping to hide posts

**To Reproduce**
1. Open app to front page
2. Tap 3-dot menu on any post
3. Select /u/xxxxx to see user overview
4. Long press the Home button on the nav bar to go to Frontpage
5. Attempt to swipe to hide a post, can't be done

Issue is the creation of another layer that must be swiped away to back to original home page

**Expected behavior**
When long pressing the Home button, do not add a layer over top of original Frontpage

**Screenshots**
https://i.imgur.com/2lNZTKk.png

**Smartphone (please complete the following information):**
**Device information**

    Sync version: v20 (beta 32)    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: sunfish    
    Model: Google Pixel 4a    
    Android: 11

**Comment by laurencedawson** [comment]
Done

**Comment by laurencedawson** [comment]
Added for beta 35*
