### ISSUE TITLE
The ability to styling/sizing Sub Name Text

### ISSUE THREAD

**Issue by minanagehsalalma** [laurencedawson/sync-for-reddit#578]
we have options to size ( title - sticky title - description - self text ) fonts .... everything but the subreddit name on the top of the posts ... which for example i want to make it in bold font with a bigger text size as i prefer to know which sub is the post from before reading/seeing or scrolling past it.
 
 for example : how it's 
 
![image](https://user-images.githubusercontent.com/20546638/107809857-6e5aa400-6d74-11eb-9d79-c5f8b2f5243e.png)

vs how it should be

![image](https://user-images.githubusercontent.com/20546638/107809768-4c612180-6d74-11eb-8486-21182494ace0.png)

**Comment by laurencedawson** [comment]
This has since changed.
