### ISSUE TITLE
Feature Request: Reimplement Random NSFW Dice button on main screen when browsing random NSFW subreddits.

### ISSUE THREAD

**Issue by tpfxlrtm** [laurencedawson/sync-for-reddit#580]
**Is your feature request related to a problem? Please describe.**
Not related to a problem in the app. Problem in the fap.

**Describe the solution you'd like**
The old app, only when opening a random nsfw subreddit, displayed a dice button at the top so you're always 1 tap away from a new random nsfw. Screenshot Included.
![dice](https://user-images.githubusercontent.com/52160655/108084083-a68a0d00-7028-11eb-8ebe-48b9f54df047.jpg)
The dice being on the main screen matters because my other hand is busy. ( ͡° ͜ʖ ͡°) It's a great way to discover new subreddits and I wish it would come back. I can't ditch the old app because of this.

**Describe alternatives you've considered**
I've considered moving the "random nsfw" button into quick actions in the drawer, but being able to browse multiple subs a second with the 1 tap of the dice button is unparalleled in terms of UX.

**Additional context**
I believe the dice existed for random sfw as well, although I'm only concerned about the nsfw. Even though this is a feature that previously existed, I understand screen real estate is valuable, and this feature might have fallen out in favor of a newer design scheme(which looks greats btw, kudos!). I'd like to argue however, that displaying the dice **only** when user clicks on "random nsfw" is appropriate and helpful as the user has conveyed that is the exact functionality they intend on using by clicking "random nsfw" in the first place.

Thank you for all the hard work!

**Comment by laurencedawson** [comment]
On beta 38 long pressing the sync button acts as a shortcut to the first quick action you have.
