### ISSUE TITLE
[BUG] 2 in 1 bug report > flair emoji size and locked comment icon

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#583]
**Describe the bug**
From beta 33 to beta 34, the size of the emoji flairs in subs such as r/soccer decreased, like by a lot and makes it harder to see, would you consider re-increasing the size?
Beta 33
![Screenshot_20210219-112635_Sync Pro](https://user-images.githubusercontent.com/3417276/108556488-81d7b300-7310-11eb-8ab1-52485447663e.jpg)

Beta 34
![Screenshot_20210220-001246_Sync Pro](https://user-images.githubusercontent.com/3417276/108556509-8a2fee00-7310-11eb-8aeb-e381467353cf.jpg)

Note: the stickied locked comment is referring to the DD of Feb 19, 2021, the stickied ones in the DD's after are not locked
*Bug 2*
Also the stickied comment in the DD is a locked comment, but there is no indication of it being locked by a lock icon or such

**To Reproduce**
Enter daily discussion, stickied comment is locked in reddit.com desktop > indication not seen in reddit sync

**Expected behavior**
A lock icon to indicate locked comments

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android 10 one ui 2.5
 - Browser: bowser
 - Version beta 33/34

Also is it just me or does the double width comment indents not do anything? Both on and off they look the same in size

**Comment by laurencedawson** [comment]
Increased the first.

Created a new issue for your second point (more of a request than a bug)

https://github.com/laurencedawson/sync-for-reddit/issues/584
