### ISSUE TITLE
[BUG] All new comments loaded when tapping "load more" are uncollapsed, even if "collapse all threads by default" is on

### ISSUE THREAD

**Issue by biobak64** [laurencedawson/sync-for-reddit#585]
**Describe the bug**
If you have the "Collapse all threads by default" option enabled, the first batch of loaded comments will be collapsed, but if you press "load more" at the bottom of a post, all the comments loaded from there on in the post will NOT be collapsed.

**To Reproduce**
1. Enable "Collapse all threads by default"
2. Go to a post with a lot of comments, click "load more"
3. Comments loaded will not be collapsed

**Smartphone**
 - Device: Nokia 7 Plus
 - OS: Android 10
 - Version: v20 beta 34

**Comment by laurencedawson** [comment]
This doesnt apply to load more
