### ISSUE TITLE
[BUG] Hyperlinks doesn't link properly if the link contains a close bracket ")"

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#586]
**Reproduction**:

1. Make sure hyperlink goes like this "[name] (**linky.com/zelda_(video_game)**)"
2. The browser will open "**linky.com/zelda_(video_game**" instead, no close brackets

**Expected behavior**:

it would open up in any internet browser with the close bracket still in the URL, opening with no 404s

**Examples**:
[Link to a Reddit comment containing the issue, open with Sync](https://www.reddit.com/r/spaceporn/comments/lqj77d/_/gogqmv8)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51 SM-A515F
 - OS: Android 10, January Security Patch, OneUI 2.5
 - Browser: bug appears on both, Internal Browser and Microsoft Edge
 - Version: V20 Beta 34

**Comment by laurencedawson** [comment]
Does the same on desktop. Issue is invalid markdown
