### ISSUE TITLE
[BUG] Hide option no longer in post bottomsheet?

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#589]
So, in the post bottomsheet, there used to be a hide option until a few betas ago, it has now since disappeared

Beta 34
![Screenshot_20210224-103229_Sync Pro](https://user-images.githubusercontent.com/3417276/108958213-1719d500-768c-11eb-955f-dfa85769d2a8.jpg)

(Not sure if removed on purpose)

**Comment by laurencedawson** [comment]
If you have swipe to hide enabled its not shown there.

**Comment by GetPsyched6** [comment]
> If you have swipe to hide enabled its not shown there.


But I have it disabled :(

**Comment by laurencedawson** [comment]
Which view type?

**Comment by GetPsyched6** [comment]
> Which view type?

A bit late but Slides

**Comment by laurencedawson** [comment]
I'm going to just make this available all the time to save on confusion.
