### ISSUE TITLE
[BUG] Default Post Sort Order does not update properly when changed

### ISSUE THREAD

**Issue by rg-burton** [laurencedawson/sync-for-reddit#590]
**Describe the bug**
Changing the Default Post Sort Order does not change the sort order unless you switch to Anonymous account (or maybe any other account?) or Force Close the App.

**To Reproduce**
Steps to Reproduce
1. Using a logged in account.
2. Open Settings>Post Options>Default post sort.
3. Change to a different sort option.
4. Back out of settings and notice that the sort order does not change.
5. Switch to Anonymous account and notice that the sort order does change then.
6. Switch back to logged in account and the new sort order is updated there as well.

**Expected behavior**
Expected the Sort order to updated in the app without having to switch accounts or Force stop the app.

**Smartphone**
Samsung Galaxy Note 20 Ultra
Android 11
Sync Dev v20 Beta 36  (also happening on beta 35)

**Additional context**
Also reported on Reddit here  https://www.reddit.com/r/redditsync/comments/lrpoas/changing_default_post_sort_in_settings_post/

**Comment by laurencedawson** [comment]
Fixed for the next release
