### ISSUE TITLE
[BUG] links to intent://images.app.goo.gl do not open

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [laurencedawson/sync-for-reddit#591]
**Describe the bug**
When tapping on a link that is intent://images.app.goo.gl it brings up an error page with net::ERR_UNKNOWN_URL_SCHEME 

**To Reproduce**
1. Tap a link with that URL scheme while in the app
Example

https://www.reddit.com/r/redditsync/comments/lrqjkz/_/gonbtpc

**Expected behavior**
The image or web page should open

**Screenshots**
Attached

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10e
 - OS: android 11
 - Browser: seems to be the built in sync web viewer
 - Version: 20 beta 34

**Additional context**
![Screenshot_20210225-060649_Sync](https://user-images.githubusercontent.com/26926284/109145535-995bd500-7730-11eb-82ad-f71eed542902.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release
