### ISSUE TITLE
[BUG] Menu button invisible when viewing white image

### ISSUE THREAD

**Issue by LouisMT** [laurencedawson/sync-for-reddit#593]
**Describe the bug**
When viewing an image with a white background, the menu button in the bottom right becomes invisible. I wanted to share an image but couldn't find the button, but assumed it had moved in a beta release. When viewing another image I saw that the button was just invisible on a white background. 

When viewing an album, same goes for the current image/total image counter in the bottom left. 

**To Reproduce**
1. Go to 'https://www.reddit.com/r/Images/comments/lpvc1o'
2. Zoom so a white part of the image is in the bottom right corner 

Note: I originally opened a screenshot which opened full screen for me and was white in the bottom right corner. So I didn't have to zoom in. But I couldn't find the image I was viewing anymore. 

**Expected behavior**
Maybe add a little shadow to the button?

**Screenshots**
![Screenshot_20210226-174852](https://user-images.githubusercontent.com/1782761/109330307-d375c580-785b-11eb-8da1-6c8af621ba28.jpg)
![Screenshot_20210226-174912](https://user-images.githubusercontent.com/1782761/109330325-d8d31000-785b-11eb-9814-eee87863f808.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro
 - OS: Android 10
 - Browser Chrome
 - Version 20 (beta 35)

**Additional context**
None

**Comment by laurencedawson** [comment]
Closing as the image viewer is due a refresh after v20 (and other issues are discussing this).

Cheers
