### ISSUE TITLE
[BUG] Can't open posts on Beta 35

### ISSUE THREAD

**Issue by LiveLM** [laurencedawson/sync-for-reddit#597]
**Describe the bug**
After the v20 beta 35 update, trying to open a post immediately closes the app.
Already tried reinstalling the app, and clearing the data, issue is still present. Issue is not present on Beta 34.

**To Reproduce**
1. Install beta 35
2. Open app
3. Click on any post
4. App closes.

**Expected behavior**
Post opens correctly

**Screenshots**
Video of the issue: https://streamable.com/028j7y

**Smartphone (please complete the following information):**
 - Device: Motorola G4 Play
 - OS: Android 10 (LineageOS 17.1)
 - Version: Sync v20 Beta 35

**Comment by thilakm-git** [comment]
Unfortunately, experiencing the absolute exact same when on v35 or v36. This does not occur on v34 or lower.

**Comment by thilakm-git** [comment]
Experiencing the exact same issue with beta 35 and upwards. Do not experience it with beta 34.

**Smartphone (please complete the following information):**
Device: OnePlus7Pro
OS: Android 10 (LineageOS4microg 17.1)
Version: Sync v20 beta 36

**Comment by laurencedawson** [comment]
Any reason why your installs would fail license checks

**Comment by laurencedawson** [comment]
This is due to the licensing checks failing, my guess is you guys are sideloading or not using google play serivces?

**Comment by LiveLM** [comment]
> not using google play serivces?  
  
That is my case, my device uses MicroG instead of the Google Play Services.  
I'm surprised to hear that there are license checks on the free version of the app. Are these here to stay, or are they present only during the Beta period?

**Comment by thilakm-git** [comment]
Same, I've been using MicroG instead of Google Play Services for quite some time now. Would love to know the answer to @LiveLM question to better understand my options in the future.

**Comment by laurencedawson** [comment]
I don't plan on supporting alternative app stores I'm afraid.
