### ISSUE TITLE
[BUG] changing suggested (new) sort to top or best or others does not change the name of the sort shown

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#598]
**Describe the bug**
For all(?) threads with suggested sort new, changing to another sort like best or top doesn't actually change the name of the sort shown in the comments

**To Reproduce**
A link to a thread that does this https://www.reddit.com/r/Gunners/comments/lz2jcj

Changing the suggested sort to best/top doesn't change the name shown in comments, not only that but changing back from best/top to suggested doesn't actually change the sort to suggested, it stays with best/top

Note the time of comments in the pictures below, while opening a suggested new sort post, it is written new as per beta 26 and the sort is new, in pic number 2, I had changed sort to best > which gives me best sorted comments such as from 22 minutes ago but the name of the sort shown is still new

(1)

![Screenshot_20210306-184627_Sync Pro](https://user-images.githubusercontent.com/3417276/110210871-25969680-7ead-11eb-9280-b3f5eb92d5f1.jpg)

(2)

![Screenshot_20210306-184639_Sync Pro](https://user-images.githubusercontent.com/3417276/110210874-2a5b4a80-7ead-11eb-8420-36efa9fabf68.jpg)

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers
