### ISSUE TITLE
[BUG] long pressing Posts when currently in messages bugs out the header and nav bar

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#599]
**Describe the bug**
Long pressing Posts when not currently in that part of the app. The header and content window changes to default feed, but the navbar still shows the Inbox icon highlighted. 
Navigating using the Subs menu to a different feed, the header continues to display the name of default feed.
Similar bugs occur when long pressing Inbox when I'm a different part of the app.
There's also some frame rate drops that may be related to this bug.

**To Reproduce**
1. Tap "inbox"
2. Long press "Posts" (nav bar should now be bugged)
3. Tap "Subs" (header should now be bugged)

**Expected behavior**
Normal stuff happening

**Screenshots**
![Screenshot_20210306-103557](https://user-images.githubusercontent.com/65996472/110217578-aa5fc100-7e69-11eb-80a7-ae28f912b246.png)

**Smartphone (please complete the following information):**
    Sync version: v20 (beta 36)    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 11

**Comment by laurencedawson** [comment]
This has since been completely replaced.
