### ISSUE TITLE
[BUG] with auto dark mode enabled, some posts are appearing in the wrong theme

### ISSUE THREAD

**Issue by andysteakfries** [laurencedawson/sync-for-reddit#600]
**Describe the bug**
With auto dark mode enabled, some cards are appearing in the wrong theme. These may be cards for posts that were cached prior to the auto dark/light mode switch?

**To Reproduce**
1. Enable auto dark mode in both Android and Sync
2. Load a subreddit or feed
3. Wait for the sun to rise/set
4. Refresh the sub or feed

**Expected behavior**
All cards displayed in the active theme.

**Screenshots**
![Screenshot_20210307-131333](https://user-images.githubusercontent.com/65996472/110255298-d05b9300-7f47-11eb-83da-a8b81bb4420f.png)

**Smartphone (please complete the following information):**

    Sync version: v20 (beta 36)    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 11

**Comment by laurencedawson** [comment]
This has since been fixed
