### ISSUE TITLE
[BUG] Searches with "&" return 404 error

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#607]

**Comment by laurencedawson** [comment]
Can't reproduce this

**Comment by thereddestdog** [comment]
> Can't reproduce this

More info here: https://www.reddit.com/r/redditsync/comments/md2cat/bug_cant_make_a_search_with_the_symbol/

**Comment by laurencedawson** [comment]
@thereddestdog are you saying the issue still is still repeatable? Steps to reproduce?

**Comment by thereddestdog** [comment]
Yeah just tried it: https://i.imgur.com/ZfJvxXu.png

I just opened the app to Frontpage, tapped search icon, typed in h&m, and searched all: https://i.imgur.com/dGZWSmB.png

**Comment by laurencedawson** [comment]
Fixed for the next release.
