### ISSUE TITLE
[BUG] Home button doesn't do anything when viewing a user profile

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#609]
Tapping and long pressing the Home button does nothing here:

https://i.imgur.com/Kflrcgn.png

I believe a tap should bring you back to your home reddit, but in the position last remembered. A long press should bring you back to your home page, but back to the top

**Comment by laurencedawson** [comment]
After experimenting with a few we arrived on the current implementation to avoid confusion. Cheers.
