### ISSUE TITLE
Not count an ad to the image count in galleries

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#610]
Apparently, ads in a gallery count as part of the gallery in the picture counter (at the bottom of the screen)

The suggestion made was to not count them (they are fine to be there, in the gallery, just not count as part of it)

**Comment by felimenta970** [comment]
[Issue #1326 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/1326)
**[Enhancement] Don't include ads in total photo count for albums**

_https://www.reddit.com/r/redditsync/comments/4wi2o5/can_you_make_it_so_ads_arent_included_in_the/_

**Comment by laurencedawson** [comment]
These have since been removed.
