### ISSUE TITLE
[BUG] Referencing #589, hide option is not visible in post bottomsheet while swipe to hide disabled

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#615]
**Describe the bug**
Referencing Bug #589 

The hide option in the post bottomsheet is still not visible even with swipe to hide disabled, just thought I'd reiterate my issue with more context 😅

**Screenshots**

Post Settings

![Screenshot_20210402-003003_Sync Pro](https://user-images.githubusercontent.com/3417276/113350913-2fe06f00-934b-11eb-8d03-55ae7f1fd9b5.jpg)

Bottomsheet

![Screenshot_20210402-003014_Sync Pro](https://user-images.githubusercontent.com/3417276/113350942-3969d700-934b-11eb-9d5e-a39e6f1536da.jpg)

**Smartphone (please complete the following information):**
 - Note9
 - Beta 36

**Comment by GetPsyched6** [comment]
Slides

**Comment by laurencedawson** [comment]
Fixed
