### ISSUE TITLE
Bottom sheet sizing issue

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-reddit#636]
While in landscape mode or splitscreen (with sync on the bottom occupying only half or a third of the screen it works fine if it's sized to two thirds) the bottom sheet doesn't go to the edge of the screen but just stays in the middle with massive gaps at the side

![Screenshot_20210415-052641.png](https://user-images.githubusercontent.com/78653137/114814291-6a162b80-9da3-11eb-803a-86650cc4518a.png)

![Screenshot_20210415-052632.png](https://user-images.githubusercontent.com/78653137/114814309-7601ed80-9da3-11eb-9d71-6a32118f04a9.png)

![Screenshot_20210415-053106.png](https://user-images.githubusercontent.com/78653137/114814329-7ef2bf00-9da3-11eb-9660-7220d76f1211.png)

**Comment by laurencedawson** [comment]
This has since been fixed. Please open again if I'm wrong.
