### ISSUE TITLE
Hamburger sizing issue

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-reddit#637]
when in splitscreen with sync taking up half or a third of the screen or with splitscreen landscape the hamburger menu is slimmer than it should be causing text to be cut off

![Screenshot_20210415-053713.png](https://user-images.githubusercontent.com/78653137/114814821-8797c500-9da4-11eb-9798-8e42b028a351.png)

![Screenshot_20210415-053400.png](https://user-images.githubusercontent.com/78653137/114814839-90889680-9da4-11eb-8a6a-e408646478b0.png)

**Comment by laurencedawson** [comment]
This has since been fixed
