### ISSUE TITLE
[BUG] Crash when opening link to flair search

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#645]
Clicking this link crashes Sync:

```
/r/mechmarket/search?q=flair:%22Interest%20Check%22&restrict_sr=on&sort=new&t=all
```

It can be found in /r/MechMarket's sidebar.

**Device information**

    Sync version: v20    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: redfin    
    Model: Google Pixel 5    
    Android: 11

**Comment by laurencedawson** [comment]
Fixed for the next release.
