### ISSUE TITLE
[BUG] Record Recently searched and Visited continues to track when turned off.

### ISSUE THREAD

**Issue by rg-burton** [laurencedawson/sync-for-reddit#646]
**Describe the bug**
In Settings>History the Record recently searched and visited option continues to add subs to the most visited even when the setting is turned off.

**To Reproduce**
1. Open Settings > History and Turn off Record recently searched and visited.
2. Clear History Settings>History>Clear All
3. Exit App.

4. Reopen app
5. Notice that the Most Visited subs is empty.
6. Browse to a different sub.
7. Now notice that the Most Visited Sub is populating again.

**Expected behavior**
When Track recently searched and visited is turn off, it should not continue to populate the Most Viewed Subs.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra
 - OS: Android 11
 - Browser Microsoft Edge
 - Version V20 beta 39

**Additional context**

**Comment by laurencedawson** [comment]
I've been trying to replicate this and I think it's been fixed with v22. Cheers
