### ISSUE TITLE
[BUG] Repeatable crash when long-holding Sync logo on bottom navbar when there are no quick actions.

### ISSUE THREAD

**Issue by BliiiTzzzzzz** [laurencedawson/sync-for-reddit#648]
**Describe the bug**
On the bottom navigation bar, the Sync logo, when held, should do the first most selected Quick action (I believe?). However, if there are no quick actions (ie Sync logo > Action visibility > All deselected), holding down the Sync logo (eg accidentally) will cause the application to crash every time.

**To Reproduce**
1. Deselect all Quick actions by going to Sync logo > Action visibility > All deselected.
2. Hold down the Sync logo.
3. Experience immediate crash with no haptic feedback.

**Expected behavior**
Nothing, I assume, but definitely not a crash. Perhaps a message should appear about no Quick actions being selected?

**Video**
https://streamable.com/qyeeaf

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro.
 - OS: Android 10 (Oxygen OS 10.5.14.IN11BA).
 - Browser: Firefox v87.0.0-rc.1.
 - Version: v20.0.1.

**Additional context**
Also occurs when the bottom navbar is disabled, so when you just have a Sync logo in the bottom right.

**Comment by laurencedawson** [comment]
Fixed for the next release.
