### ISSUE TITLE
[BUG] Some images are slightly blurred in Post/Comment view

### ISSUE THREAD

**Issue by Fanolian** [laurencedawson/sync-for-reddit#652]
**Describe the bug**
In v20, direct images shown in Post or Comment view are sometimes slightly blurred compared to the original image opened in Sync for Reddit. The blur occurs on the whole image but it is more obvious on computer text in the image, e.g. memes or comics, even if it is a PNG image.

**To Reproduce**
1. Use v20 or v20.0.1.
2. Visit https://www.reddit.com/r/comics.
3. Scroll down until you find an image with blurred text.
4. Tap on the affected image to view it as a standalone.

**Expected behavior**
The text should be crisp and clear to read in preview

**Screenshots**
In Comment view:
![Screenshot_20210418-015334](https://user-images.githubusercontent.com/771216/115383666-b67cc380-a208-11eb-8223-d75b8e29cb23.png)

In standalone view:
![Screenshot_20210418-015426](https://user-images.githubusercontent.com/771216/115383743-cb595700-a208-11eb-80cb-b1fb711217f6.png)

Here's another example from reddit user CSab6482: https://imgur.com/a/I6TObM3

**Smartphone (please complete the following information):**
 - Device: Pixel 4a (non-5G)
 - OS: Android 11 2021 April update
 - Browser: Firefox Nightly
 - Version: 20 or 20.0.1

**Sync for reddit settings
 - data saving mode: `Never`
 - Image preloading: all set to `Always`
 - Post view mode: Slides, Cards
 - Full height: Yes
 - Full width: doesn't matter

**Additional context**
There is a notice in v19 when I switch to full-height card view. I don't see it when enabling full height/width in v20, Slides or Cards view. I don't know if this is related to my issue.
![Screenshot_20210418-011103](https://user-images.githubusercontent.com/771216/115384079-2db25780-a209-11eb-82a9-11494958d93a.png)

This issue was originally reported at the since-deleted reddit post:
https://www.reddit.com/r/redditsync/comments/mt9xac/v20_some_images_are_slightly_blurred_in/

#316 is a similiar case (I think... I don't have a discord account to read the screenshot). I did not use v20 until it officially released so I don't know if the issue persisted in previous betas.

**Comment by laurencedawson** [comment]
This has since been fixed for v22
