### ISSUE TITLE
[FEATURE REQUEST] [AGGREGATOR] Tablet/folding phones/dual screen/landscape devices support and features

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#653]
Issues related to this:

#334 [GUI][Improvement][Beta] Tablet feedback
#374 Option to allow comments to span fullscreen in tablet mode
#385 Folding/dual screen devices support (official API)

**Comment by felimenta970** [comment]
Issue [#2116 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/2116):
**Split screen on Android tablets**

_Please restore split screen view when browsing on Android tablets. This was where the posts were on the left and the comments for a particular post were on the right and the two could be scrolled independtely._

_Thanks!_

**Comment by felimenta970** [comment]
[Issue #1787 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/1787)
**[Bug] No tablet mode on chromebook with android apps**

_Description_

_Using the Samsung Chromebook Pro, tablet mode doesn't engage, even when the app is full screen and in a wide mode_

_Scenario (steps to reproduce)_

_Open sync on a chromebook with android app support, note the lack of tablet mode
Screenshot_

**Comment by felimenta970** [comment]
[Issue #1472 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/1472)
**[Enhancement] Dual pane mode for card views**

_Request thread: https://www.reddit.com/r/redditsync/comments/51y3m4/request_bring_back_dual_pane_mode_for_full_height/_

**Comment by felimenta970** [comment]
[Issue #295 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/295)
**The dedicated comments page uses space poorly on 10-inch Tablets**

**Comment by Sebianoti** [comment]
**[Bug] Drawer takes up the whole screen on tablets**
_v22.3.3_

**Comment by Sebianoti** [comment]
**[Bug] settings page is portrait only**
_v22.3.3_

**Comment by snargledorf** [comment]
> Issue [#2116 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/2116):
> **Split screen on Android tablets**
> 
> _Please restore split screen view when browsing on Android tablets. This was where the posts were on the left and the comments for a particular post were on the right and the two could be scrolled independtely._
> 
> _Thanks!_

Simulated example on the Surface Duo 2.

![Screenshot_20220303-170201.png](https://user-images.githubusercontent.com/1033711/156660326-7a9a1951-efc1-4453-9a1f-77e9878f4a87.png)

**Comment by laurencedawson** [comment]
Closing as all these points have been addressed!
