### ISSUE TITLE
[BUG] Weird flair bug

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#662]
Reported here: https://www.reddit.com/r/redditsync/comments/mwgspn

Thread here: https://www.reddit.com/r/Amd/comments/mw32oe/sapphire_launches_the_ultimate_peakperformance/

**Comment by felimenta970** [comment]
[Issue #2063 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/2063)

_Reddit wiki allows embedding images using markdown code ![Alt text](%%image_name%%). Image name can be converted to the corresponding image url by reading data.images array in https://www.reddit.com/r/<subreddit>/about/stylesheet/.json and finding an item with the matching name._

_Example:_

_StarlinkUT image at https://www.reddit.com/r/Starlink/wiki/index#wiki_-_what_kind_of_antenna_does_it_use.3F_
_URLs of images: https://www.reddit.com/r/Starlink/about/stylesheet/.json_
_I know it's an obscure feature but it would be nice to support._

**Comment by laurencedawson** [comment]
Tested and this is no longer an issue. Closing.
