### ISSUE TITLE
[FEATURE REQUEST] Option to change the default view of profiles

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#664]
[Issue #2033 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/2033)
**Option to change the default view of profiles**

_It would be nice to be able to change the default view to comments or submitted so you don't have to change it every time you go to a profile_

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/612
