### ISSUE TITLE
[FEATURE REQUEST] Auto-detect inconsistency between theme colors and the theme type

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#678]
[Issue #1874 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/1874)
**[Enhancement] Auto-detect inconsistencies between the theme and the section where it is being loaded/configured**

_Right now the app is quite strict regarding the differentiation between a "Dark theme" and a "Light theme". But there's absolutely nothing in place preventing the user from loading a light theme in the dark section, or vice-versa. And if the user mixes that up, they end up with weird and unexpected results, like illegible text, or UI sections/elements that don't show properly._

_This seems to catch many users by surprise, which is further aggravated by the fact that the drop-downs or "spinners" or what's-their-name on the toolbar seem to be pretty undiscoverable (judging by the amount of posts on the sub where users ask questions regarding this, or the "hidden" section on the profile, or the different sections on the view customization, or basically any screen that has a drop-down on the toolbar to switch among different sections/options)._

_It would be helpful if he app detected these inconsistencies somehow, maybe testing the contrast between the text color for the current theme section (dark/light) and the background color of the theme being configured/loaded, and alerting the user if the theme is being defined in the wrong section._

**Comment by laurencedawson** [comment]
This has been fixed by switching the theming manager.
