### ISSUE TITLE
[FEATURE REQUEST] NSFW only filter

### ISSUE THREAD

**Issue by apopanda** [laurencedawson/sync-for-reddit#680]
**Is your feature request related to a problem? Please describe.**
Some days you don't want to look at cute kittens, and prefer to look at gore or naked people. A NSFW only filter would be great for that occasion. We can call it "naughty mode" or something. 

**Describe the solution you'd like**
An option that filters out any SFW post and creates a feed containing only NSFW material. Inserted into the "filters" tab, alongside the "Hide NSFW posts", can only be turned on if Hide NSFW is off. 

**Describe alternatives you've considered**
The only possible one would be a seperate account that only subscribes to NSFW subreddits, but it's problematic. Some subs are also not marked NSFW only, with content ranging from cutsey pics to outright porn. IIRC there are reddit clients on PC with that option already. Haven't checked other mobile clients though.

**Comment by bohrabhijeet** [comment]
Relevant request:
https://www.reddit.com/r/redditsync/comments/v6ji0e
> In the previous design, we were able to quickly filter out NSFW posts as the filter toggle was in the 3 dot drop down. Now, we have to go to the quick action "Filters", which jumps to the settings page, and we need to toggle it there. It would be great if it is maybe a quick action option that we can enable like the other actions, and we can toggle in the quick actions.

**Comment by laurencedawson** [comment]
Out of scope for sync.
