### ISSUE TITLE
[BUG] App shows way to reply to removed comment or blocked/archived thread

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#682]
[Issue #1851 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/1851)
**[Bug] Don't pretend to allow submitting replies to removed comments**

_I am able to hit reply on removed comments, type a comment in, and hit submit. I even get a toast saying "Submitting". Obviously this doesn't work, but it looks like it does, and if I didn't know any better or check my post history, I'd think it actually posted, because it never errors out._

_As an edge test case, when this is fixed, make sure a comment that's been removed but is in a sub you moderate can still be replied to (since those are "removed" but you can actually still see them)._

**Comment by laurencedawson** [comment]
This has since been fixed
