### ISSUE TITLE
[BUG] "Create multi/add to multi" button is shown even if user is logged off

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#684]
[Issue #1841 from old Reddit](https://github.com/laurencedawson/reddit-sync-development/issues/1841)
**[Feature Request] Hide "New Multireddit" Option If User Is Not Logged In**

_Since the user must be logged in to create a multireddit, the option to create one should be hidden from the user if they are not logged in. This can potentially cause confusion as the app will just show a toast saying "Failed to create multireddit"._

**Comment by laurencedawson** [comment]
This has since been fixed.
