### ISSUE TITLE
[FEATURE REQUEST] Use reddit's obfuscated (blurred) media previews for NSFW posts

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#688]
[Issue #1807 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/1807)
**[Request] Use reddit's obfuscated (blurred) media previews for NSFW posts **

_You get requests for blurring images for NSFW posts (as opposed to show the solid red mask) pretty frequently. AFAIK, these requests have been always ruled out based on performance reasons (applying a blur mask is an expensive process)._
 
_In the [latest thread about the subject](https://www.reddit.com/r/redditsync/comments/70qqmf/request_please_add_option_to_blur_nsfw_content/), `/u/NuScorpii` pointed out that blurring works just fine for _spoiler_ threads. I thought that in that case the blurred media preview was provided by reddit, and later confirmed my suspicion._

_But it turns out that **reddit seems to provide the obfuscated media preview por NSFW posts too**. For example [this thread](https://www.reddit.com/r/ImGoingToHellForThis/comments/70uctb/wow_reddit/) provides this obfuscated preview variant:_

**Comment by laurencedawson** [comment]
Closing as I dont intend to add this.
