### ISSUE TITLE
[FEATURE REQUEST] Disabling fingerprint lock should prompt for verification

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#689]
[Issue #1796 from old Github](https://github.com/laurencedawson/reddit-sync-development/issues/1796)
**[feature request] disabling fingerprint lock should prompt for verification.**

_Currently fingerprint lock can be disabled freely, defeating it's supposed security purpose. This does mainly effect people using a single settings profile for all accounts._

_To enhance this function a fingerprint challenge could be presented to the user when trying to disable the fingerprint lock setting._

_Reddit thread: https://www.reddit.com/r/redditsync/comments/6puca0/fingerprint_account_switch/_

**Comment by laurencedawson** [comment]
Pass on this one, if they're on your device and in the app already its game over.
