### ISSUE TITLE
Navigation bar buttons are white-on-white

### ISSUE THREAD

**Issue by zamuz** [laurencedawson/sync-for-reddit#7]
On my Galaxy S9+, and possibly other Samsung phones running One UI 2.0, when the navigation bar is white the buttons are also white.

![Screenshot_20200331-224125_Sync Pro](https://user-images.githubusercontent.com/731751/78090667-be1cc080-7398-11ea-904c-95884056d8df.jpg)

**Comment by laurencedawson** [comment]
Fixed for alpha 5.
