### ISSUE TITLE
[FEATURE REQUEST] Highlight all comments by a user

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#706]
[Issue #1585 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/1585)
**[Feature Request] Being able to highlight all comments by a user through the 3-dot menu**

_Being able to highlight all comments by a user in a post through the 3-dot menu in the comment actions. It would be very useful if a relevant person makes several comments on a post that is not OP._

**Comment by laurencedawson** [comment]
Kinda works like painting in ultra. No plans to add this.
