### ISSUE TITLE
[FEATURE REQUEST] Support for alt text on links

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#713]
[Issue #830 from old GitHub](https://github.com/laurencedawson/reddit-sync-development/issues/830)
**Support for alt text on links**

_Some subreddits, including Japanese learning subs, use alt-text so much that the subs are practically unusable without it. In the case of Japanese learning subs, they use it to show the readings of complex Kanji (Chinese characters) with a much easier phonetic alphabet._

_It would be great if there was some way to long press a link and select "View Alt Text" or something like that._

**Comment by laurencedawson** [comment]
Closing this one as I've not had this requested since.
