### ISSUE TITLE
[BUG] Swipe mode not working correctly when viewing profile (v19)

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#718]
https://www.reddit.com/r/redditsync/comments/ngikdy/change_view_for_profile_comments/

As commented, does not happen in v20 due to Swipe being just a mode fro now, but needs to be considered for when/if Swipe becomes a view in the future

**Comment by laurencedawson** [comment]
Closing as this is a v19 issue
