### ISSUE TITLE
[BUG] Remove plus.google.com from "Bypass external domains" default list

### ISSUE THREAD

**Issue by jeffreymcclain** [laurencedawson/sync-for-reddit#721]
**Describe the bug**
Google shutdown plus.google.com (Google+) back in 2019, so there is no longer a functional reason to have that as one of the default domains included in the bypass list.

**Expected behavior**
The URL should be removed from the default "bypass external domains" list when the app is first installed.
You could also remove the URL from existing users' bypass lists if desired, although that is probably excessive since it's not like there is a downside to having a non-functional URL in the bypass list beyond having an extra redundant entry.

**Additional context**
I tested on both the stable and dev Sync for Reddit app, and plus.google.com seems to be a default entry on both. I'm assuming it would apply to the v20 beta as well, since that is the version of the dev app.

**Comment by laurencedawson** [comment]
Good shout lol. Removed
