### ISSUE TITLE
[BUG] App crash/lockup when attempting to open video in fullscreen while in swipe mode

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#722]
**Describe the bug**
App lockup/crash when attempting to view videos in full screen when in swipe mode

**To Reproduce**
1. Go to swipe mode
2. Click on video to open fullscreen
3. App either locks up, crashes, or behaves normally

**Expected behavior**
Video opens in fullscreen without issue

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Browser: Not applicable
 - Version: 20.0.3

**Additional context**
https://www.reddit.com/r/redditsync/comments/ntapfx/_/h0rl4wu

**Comment by laurencedawson** [comment]
Swipe mode has been completely rewritten and I'm now unable to reproduce this issue. Cheers.

p.s. come back!
