### ISSUE TITLE
[BUG] Unable to select directory for saving files or backups

### ISSUE THREAD

**Issue by TheNikomo** [laurencedawson/sync-for-reddit#723]
**Description**
When asked to select a download or backup directory, application errors out with "You must select a directory to continue".

**Reproduction**
1. Be stupid enough to buy another Xiaomi phone
2. Open application
3. Either open media from a post or go to the backup section of settings
4. Try to save media, or attempt to change backup directory/backup/restore from backup
5. When asked to select a directory, attempt to select a directory
6. Error "You must select a directory to continue" is displayed

**Expected behavior**
Be able to select folder that is used for downloads or backups.

**Result(s)**
Unable to save or load backups, or save media, due to this bug.

**Screen capture**
Screen capture of bug: https://streamable.com/suq480

**Device Info**
* Device Model - Xiaomi Redmi Note 10 Pro
* Android 11, MIUI Global 12.5.1 Stable. Screenshot of About Phone:
![Screenshot_2021-06-16-18-38-17-113_com android settings](https://user-images.githubusercontent.com/1451669/122280335-c3105600-cef1-11eb-9c9b-09aece121140.jpg)
* Happens on both Sync Dev (Everything else -> App info indicates v20), and the beta version of Sync Pro (v20.0.3)

**Additional context**
On my second phone (being replaced), this bug does not happen. Screenshot of About Phone: 
![Screenshot_2021-06-16-18-59-07-154_com android settings](https://user-images.githubusercontent.com/1451669/122280417-d7ece980-cef1-11eb-8cc9-9422f7c7d17e.jpg)

Current hypothesis is that this is caused by Android 11 + MIUI.

**Comment by TheNikomo** [comment]
I don't know if it'll do any good, but I captured a logcat, and I stripped out most of what happened before application launch, based on timestamps.
[logcat.txt](https://github.com/laurencedawson/sync-for-reddit/files/6665428/logcat.txt)

**Comment by laurencedawson** [comment]
Still having this issue?

**Comment by Leolebleis** [comment]
It's still happening to me as well, with a Poco F3, MIUI 12.5.8, android 11, and sync v22.3.24

**Comment by Vritrahan** [comment]
Can confirm it's still happening with a Xiaomi 11T Pro, MIUI 13.0.1, Android 12 and Sync v22. I reverted back to Sync v19.0.13 a few days back, and I don't face this issue now. Happy to help with more details if required.

**Comment by 3ddy** [comment]
Still the same. Mi9 SE, MIUI 12.5.1, Android 11, sync v22.4.4

**Comment by laurencedawson** [comment]
Fixed for the next release!
