### ISSUE TITLE
Increase the number of most visited subs to 20 (or allow customizable amount)

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#725]
I'm used to keeping my front page clean from clutter and only sub to 2 subreddits, so instead I rely on the most visited feature to gain quick access to my .... Most visited subs :)

The issue is the current amount of most visible subs right now, (around 15 I think) is really limiting and at this point I need to visit a sub atleast 40 times to crack even the bottom of this list, reducing the convenience of this feature.

I would love a bump up to the number of possible most visited subs to 25 or maybe even allow us to choose any number.

**Additional context**

I had made a post about this in r/RedditSync and that's where the idea of a customizable amount came from

// Reddit sync V20

**Comment by laurencedawson** [comment]
Added for the next release!
