### ISSUE TITLE
[BUG] Ads despite purchased IAP

### ISSUE THREAD

**Issue by K0bin** [laurencedawson/sync-for-reddit#728]
**Describe the bug**
I am getting ads despite having purchased the "Remove ads" IAP. Restarting the app (by clearing it in recents) didn't fix it.

**To Reproduce**
Scroll through the app. Unfortunately I don't know when they show up exactly. Might be limited to the front page but I'm not sure about that.

**Expected behavior**
No ads

**Screenshots**
[https://i.imgur.com/Oz4PQEW.jpg](https://i.imgur.com/Oz4PQEW.jpg)

**Smartphone (please complete the following information):**
    Sync version: v20.0.4    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Slides    
    Push enabled: true    
    
    Device: OnePlus8T    
    Model: OnePlus KB2003    
    Android: 11

I really love Sync, especially v20.

**Comment by laurencedawson** [comment]
Closing this as it was quite a while ago.

Please make a new issue if you're still experiencing issues.
