### ISSUE TITLE
[Feature Request] Ability to add flairs when creating a post

### ISSUE THREAD

**Issue by CaptainJack42** [laurencedawson/sync-for-reddit#729]
**Describe the solution you'd like**
It would be cool to be able to add a flair to a post before posting it, some subreddits I'm in don't allow posting without a flair so I can't post there from the sync app.

**Describe alternatives you've considered**
My current alternative is having the stock Reddit app installed as well and posting from there, but ultimately sync just feels way better.

**Comment by anonymous-user** [comment]
This is already possible in version 20. You can opt-in to the beta test if you want it.

**Comment by laurencedawson** [comment]
As @anonymous-user mentioned this is already possible with the beta. Cheers
