### ISSUE TITLE
BUG: old card style upvote/downvote animation shows the post is both upvoted and downvoted instead only one thing is performed on alpha 20

### ISSUE THREAD

**Issue by devanshupipalia** [laurencedawson/sync-for-reddit#73]
steps to reproduce:
1. upvote the post
2. downvote the same post
3. both arrorws are colored and you dont the know the post is upvoted/downvoted not
![Screenshot_20200530-105713](https://user-images.githubusercontent.com/26577124/83320408-dd36b200-a264-11ea-8675-bc975a319005.jpg)

**Comment by RecklessDwark** [comment]
Already been previously reported

**Comment by laurencedawson** [comment]
Fixed for the next alpha.
