### ISSUE TITLE
Update to Material Design 3

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#731]
Material Design 3 is so hot right now. Time to start work on the next chapter of Sync.

I'm going to start cataloguing good examples of MD3:

![image](https://user-images.githubusercontent.com/534059/147492562-adf691b8-fcd0-46dd-b0e7-c45614b869f2.png)

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/147492562-adf691b8-fcd0-46dd-b0e7-c45614b869f2.png)

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/147492810-fff64303-8dd0-4d64-8e93-df7390a6fa6e.png)

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/147498741-bef77950-8522-429a-91b5-7bf63f43ad13.png)

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/147510341-68526f4b-b30d-4b03-9f81-883cf768c709.png)

**Comment by starscar12** [comment]
Adding this concept to further narrow down the designs/implementation.  
  
https://www.reddit.com/r/redditsync/comments/ql1bex

**Comment by laurencedawson** [comment]
Doneeee

**Comment by THARADO** [comment]
> Material Design 3 is so hot right now. Time to start work on the next chapter of Sync.
> 
> 
> I'm going to start cataloguing good examples of MD3:
> 
> ![image](https://user-images.githubusercontent.com/534059/147492562-adf691b8-fcd0-46dd-b0e7-c45614b869f2.png)

5e890abaa4c01a8f812cef8eb44d40b54ce43e66
