### ISSUE TITLE
Video getting pinned on top when scrolling through comments 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#734]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The video section should not move up when user a rolls through the comments. It should stay pinned. 

**Additional context**
Reference can be taken from the official app.

**Comment by laurencedawson** [comment]
https://github.com/laurencedawson/sync-for-reddit/issues/377

Duplicate.
