### ISSUE TITLE
[BUG] Urls with escaped symbols don't open

### ISSUE THREAD

**Issue by MrMikeJJ** [laurencedawson/sync-for-reddit#737]
**Describe the bug**
Urls with escaped symbols do not work. Sorry I don't have any handy, will update if I find one. An example I can remember was a YouTube link with an underscore in it. It displayed as foo\_bar 
Removing the \ allows it to work.

**To Reproduce**
Click a link with a \ and symbol following it. 

**Expected behavior**
The link to open. It was a while ago when I saw this issue, but i believe that a browser opened it after copy pasting the link into it. 

**Smartphone (please complete the following information):**
 - Device: Samsung S7 Edge
 - OS: Android 8
 - Browser: the browser built into sync. Also have Firefox and the Samsung browser installed. 
 - Version 20.0.3

**Comment by laurencedawson** [comment]
Example link?

**Comment by MrMikeJJ** [comment]
This comment has an example broken link. A few comments down, someone has deleted the \ to make a working link. 

https://www.reddit.com/r/CombatFootage/comments/t9dh2i/_/hztkp2g

thanks
Mike

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/160294656-b561ecb6-cfdb-4540-850a-738198c015df.png)

Added a little bottomsheet to handle this.
