### ISSUE TITLE
Update the Report comment/post action

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#738]
Currently just a blank field to submit, where now most subreddits have multiple choice selections and then maybe a blank field to type into

**Comment by DefinitelyNotSpicy** [comment]
This would be very helpful for moderators, too. The quality of reports improves when people can see the rules before reporting. 

And the API specifically seems to support it with the `rule_reason` parameter https://www.reddit.com/dev/api/oauth#POST_api_report
