### ISSUE TITLE
[BUG] HDR videos do not play 

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#744]
https://www.reddit.com/r/AppleWatch/comments/t3yb6o/the_black_unity_solo_loop_glows_beautifully_under/

**Comment by Sam97MT** [comment]
How can I help provide logs or test?

**Comment by Sam97MT** [comment]
![Screenshot_20220324-092754_Netflix](https://user-images.githubusercontent.com/102254414/159927290-91907085-6d5a-43f1-ab9d-578e0abea53a.png)

**Comment by Sam97MT** [comment]
So far I have attempted to delete the app, wipe cache, reinstall the app. That didn't help.

I have tried to disable high refresh. That didn't help. 

This samsung doesn't allow me to change resolution and I havent figured out how to call the exoplayer outside of the Reddit sync app for extra testing.

**Comment by Sam97MT** [comment]
https://v.redd.it/ajwq1e71vbp81

This shouldn't be HDR.

**Comment by laurencedawson** [comment]
Fixed for the next release.
