### ISSUE TITLE
[BUG] Horizontal line overlaps code formatting

### ISSUE THREAD

**Issue by Piggered** [laurencedawson/sync-for-reddit#745]
**Describe the bug**
A horizontal line followed by code formatted using an indentation of 4 spaces causes the horizontal line to overlap on the first line of the code.

**To Reproduce**
1. Submit a selftext post or comment with a horizontal line (`---`), followed by code formatted using the four-space indentation markdown.
[Example post](https://www.reddit.com/r/u_Piggered/comments/t8f1gg)

**Expected behavior**
The formatted code should display under the horizontal line.

**Screenshots**
![Screenshot](https://i.piggered.me/u/lbwl1.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Browser: N/A (Firefox)
 - Version: 22.3.6 (and 20.0.3)

**Additional context**
N/A

**Comment by laurencedawson** [comment]
Fixed for the next release.
