### ISSUE TITLE
[BUG] Video does not remember position when switching between apps

### ISSUE THREAD

**Issue by fessmm** [laurencedawson/sync-for-reddit#746]
**Describe the bug**
Open any video, stop in the middle, change app, change back to sync, video starts from the beginning instead of the last stopped position

**To Reproduce**
1. Open any video
2. Click on pause somewhere in the middle
3. Open another app
4. Open sync again

**Expected behavior**
Stopped position should be remembered 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 12L Beta 3
 - Version [e.g. v22.3.7-12]

**Additional context**
No

**Comment by laurencedawson** [comment]
Video position is remembered when rotating. Pausing and resuming. 

If you let the app go into deep sleep it isn't remembered but no intention of adding this either. Cheers

**Comment by fessmm** [comment]
the app is not going into deep sleep, im just switching between 2 apps. why should the app reset the video when i just want to pause it for a sec and come back to sync again to resume the video?

**Comment by laurencedawson** [comment]
I'll reopen but this probably won't get looked at again for some time. Cheers

**Comment by laurencedawson** [comment]
Fixed for the next release.
