### ISSUE TITLE
[BUG] Spoiler Text in selftext previews not hidden 

### ISSUE THREAD

**Issue by GetPsyched6** [laurencedawson/sync-for-reddit#747]
**Describe the bug**
In selftext previews, if there is spoiler text in that selftext, the preview does not spoiler it (the solid rectangles) and instead leaves it completely visible. 

**To Reproduce**
1. Any post with spoiler text in the body that will show up in selftext preview

**Expected behavior**
Spoiler text should show up in the preview as well

**Screenshots**

**Before Opening**
![IMG_20220307_223623.jpg](https://user-images.githubusercontent.com/3417276/157096646-99886c76-e2a0-415a-9657-c50b0e00f6ac.jpg)

**After Opening**
![IMG_20220307_223635.jpg](https://user-images.githubusercontent.com/3417276/157096667-5ff71421-da4e-43d8-b0e7-34cb6c9ee03c.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 10S
 - OS: Android 11
 - Browser Chrome
 - Version V22.3.6

**Comment by laurencedawson** [comment]
Fixed for the next release.
