### ISSUE TITLE
Click on "Posts" to return to default subreddit

### ISSUE THREAD

**Issue by rvictorr** [laurencedawson/sync-for-reddit#758]
**Is your feature request related to a problem? Please describe.**
Returning to the default subreddit can currently only be done by going back through the interface.

**Describe the solution you'd like**
Like in v20, clicking on "Posts" on the bottom bar should return to the default subreddit if the user is already at the top of the page.

**Comment by bohrabhijeet** [comment]
Long-pressing Home in v22 returns to default sub/feed and refreshes the page.
