### ISSUE TITLE
[BUG] Going to messages on Foldable display in tablet mode locks the app in messages. 

### ISSUE THREAD

**Issue by SuperfightingRobit** [laurencedawson/sync-for-reddit#759]
**Describe the bug**

**To Reproduce**
1. Open sync using foldable display phone
2. Unfold phone to tablet mode 
3. Go to messages (may require there not to be new messages)
4. Fold phone back to phone mode

**Expected behavior**
User input should allow users to exit messages, but user input no longer takes user out of messages to frontpage or specific subreddits

**Screenshots**

***Device information**

    Sync version: v22.3.15    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: q2q    
    Model: samsung SM-F926U1    
    Android: 12

**Additional context**

**Comment by laurencedawson** [comment]
Fixed for the next release
