### ISSUE TITLE
BUG: overriding individual subreddit sort mode to "comments" causes app to crash

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/sync-for-reddit#76]
Steps to replicate:

1. Pull up subreddit bottomsheet menu

2. Select three-dot menu for a subreddit (e.g., /r/changelog)

3. Select "Update sort" --> "override sort" and select "Comments"

4. Navigate to this same subreddit via the subreddit menu and the app crashes.

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
