### ISSUE TITLE
[BUG] Card views are broken in tablet/big screen device

### ISSUE THREAD

**Issue by erbold-bu** [laurencedawson/sync-for-reddit#760]
**Describe the bug**
All the card views take only half of the screen width and don't show multiple columns even if multiple columns are configured.

**To Reproduce**
1. Choose any of the card views (cards, small, smaller)
2. Make sure column is configured more than one
3. Go to frontpage or any subreddit

**Expected behavior**
- [ ] Card view should take all the screen width
- [ ] Card view should show multiple columns of post

**Screenshots**
![image](https://user-images.githubusercontent.com/66581972/158735336-f329e641-9550-4570-bb02-a9485378b036.png)

**Smartphone (please complete the following information):**
 - Device: lenovo chromebook duet
 - OS: ChromeOS 100, Android 9
 - 22.3.15

**Comment by laurencedawson** [comment]
Settings > Tablet > disable multi column view.
