### ISSUE TITLE
[Request] Add expanded comment links for links

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/sync-for-reddit#767]
**Describe the bug**
The "expanded comment links" feature does not work for most links, except for imgur and YouTube.

**To Reproduce**
1. Go to any comment with external links that are not imgur or YouTube, e.g., https://www.reddit.com/r/movies/comments/tg9y5t/amazon_closes_mgm_acquisition_in_85_billion_deal/i10ul5l/
2. Expanded hitbox for link is not present.
3. 
**Smartphone :**
 - Device: Pixel 3a
 - OS: Android 12
 - Version 22.3.15

**Comment by laurencedawson** [comment]
Thanks. This was removed with the new markdown re-write but I plan to add it back in before v22.

**Comment by laurencedawson** [comment]
Added back in!
