### ISSUE TITLE
Add onboarding for v22

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#772]

**Comment by laurencedawson** [comment]
Ideas:

- View type
- Select flair display type
- Select award display type

**Comment by felimenta970** [comment]
Explain the press and hold Explore to open recents directly;

Onboarding with choosing FAB option

**Comment by laurencedawson** [comment]
Material docs:

https://material.io/design/communication/onboarding.html#top-user-benefits-model

**Comment by laurencedawson** [comment]
Added for the next release.
