### ISSUE TITLE
[BUG] Full height images in comments 

### ISSUE THREAD

**Issue by aaronstc1** [laurencedawson/sync-for-reddit#775]
**Describe the bug**
Full height images do not appear in comments when enabled unless also enabled in the view type. Happens in Slides, cards and small cards. Works fine for compact and smaller cards.

**To Reproduce**
1. Disable full height cards or image previews in view type
2. Enable full height cards under comments
3. Go to comments of an image post
4. Image not full height. Will either be cropped or thumbnail depending on viewtype.

**Expected behavior**
Expect to see the full height image in the comments.

**Comment by woojin-ra** [comment]
I am currently using a Samsung Tab S8+ and would love this bug to be fixed soon. It would be so much more convenient if the inline media auto played when pressing onto the post.

**Comment by laurencedawson** [comment]
Fixed for the next release.
