### ISSUE TITLE
[BUG] Check for new messages is turned off, but app still checks for new messages and shows a notification

### ISSUE THREAD

**Issue by mendhak** [laurencedawson/sync-for-reddit#798]
**Describe the bug**

In settings, I've got messages turned off (periodically check for new messages), so I'm expecting no notifications. 
But I'm still getting notifications for messages on receiving comment replies. 

**To Reproduce**
1. Go to Settings > Messaging
2. Turn off "Periodically check for new messages (notifications)
3. Go to messages and mark some messages as unread, or get someone to reply to your comment
4. Wait a bit eventually the app shows a notification with a reply, and a badge at the bottom with a new message. 

**Expected behavior**
App should not check for messages, notification should not appear, envelope/badge should not get updated. 

**Screenshots**

![image](https://user-images.githubusercontent.com/746276/159002926-5f76ebfa-3378-4565-8f37-d823034e8a36.png)
![image](https://user-images.githubusercontent.com/746276/159002934-2354dc6a-c7ec-4d2f-82cf-4913ec5dc537.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3A XL
 - OS: Android 11, 12
 - Browser: Firefox Android
 - Version: 20.0.5

**Additional context**

**Comment by laurencedawson** [comment]
Please update to v22. If the issue persists please let me know.

**Comment by mendhak** [comment]
Hi there, it's still happening in v22.3.24.  Could this issue be reopened please

![image](https://user-images.githubusercontent.com/746276/160256298-cde7b6a5-98dc-41cf-8fb2-2b7647a06ac4.png)

![image](https://user-images.githubusercontent.com/746276/160256336-af1e4685-955d-4a31-a3d9-5fc3977982c3.png)

![image](https://user-images.githubusercontent.com/746276/160256356-c228cc86-8462-4355-9c80-193c34872dda.png)

Version is v22.3.24

**Comment by laurencedawson** [comment]
Apart from checking as the app starts, does it check again?

**Comment by mendhak** [comment]
Ah good observation!  
From what I can see, it's only checking during app start.    
Once the app is open and being used, no checking.  I left it open overnight to be sure.   
When I exit and swipe away the recent app, then reopen, it checks again.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by mendhak** [comment]
Many thanks, it seems to be behaving as expected now!
