### ISSUE TITLE
[BUG] Copy to Clipboard toast missing icon 

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#805]
On newer versions of Android, when an app copies to clipboard it displays a toast. It seems Reddit Sync doesn't have this icon!

[Screenshot_20220318-163733.png](https://user-images.githubusercontent.com/2940826/159080113-393f2268-26e9-4c96-b2f6-920fdfc54a12.png)

**Comment by laurencedawson** [comment]
Sadly this is an Android bug and has been fixed in the A13 developer previews.

**Comment by Nxt3** [comment]
Classic Android 🙃
