### ISSUE TITLE
[BUG] Gesture bar background isn't transparent still in multiple places

### ISSUE THREAD

**Issue by Jnss98b** [laurencedawson/sync-for-reddit#806]
**Describe the bug**
In many places within the app (mostly popup sheets and navigation drawer) the gesture bar background is either opaque or just straight up black

**Expected behavior**
The gesture bar background should be transparent like the rest of the main app

**Screenshots**

When typing a message
![Screenshot_20220318-163604_Sync Dev](https://user-images.githubusercontent.com/24306400/159080827-e42eec98-caf2-4427-8e42-a4052f06b5e0.png)

Explore sheet
![Screenshot_20220318-163629_Sync Dev](https://user-images.githubusercontent.com/24306400/159080831-9db3e0f8-57a7-4803-82fd-fb0dc2e11eb3.png)

Navigation drawer
![Screenshot_20220318-163551_Sync Dev](https://user-images.githubusercontent.com/24306400/159080832-dc5b060b-4341-42f8-bb01-30ac63ebc6d7.png)

When zooming in media
![Screenshot_20220318-163838_Sync Dev](https://user-images.githubusercontent.com/24306400/159080833-44e8c456-3d19-485e-b145-1153caae5285.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 12 February patch
 - Version 22.3.17

**Comment by laurencedawson** [comment]
Keeping this open but this is actually the desired behavior for bottomsheets in sync.

**Comment by Jnss98b** [comment]
@laurencedawson Why would that be desired behavior? Shouldn't it look immersive every where else, not just in the main view? Also I hope you'll still try to fix those instances of black gesture bar background

**Comment by laurencedawson** [comment]
The navigation drawer was done like this so we don't have to add additional padding above the search box. No plans to change this.

**Comment by laurencedawson** [comment]
Full screen images will be addressed in the media player milestone.

**Comment by laurencedawson** [comment]
Just changed the editor to use the correct color behind the bottom bar.

**Comment by laurencedawson** [comment]
Created a new more specific request ticket:

https://github.com/laurencedawson/sync-for-reddit/issues/924
