### ISSUE TITLE
[BUG] opening v.reddit videos on browser directs you to a website to download a .mpd file

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#807]
**Describe the bug**
opening v.reddit videos via "open in browser" button opens v.reddit

**To Reproduce**
1. Go to post containing v.reddit video
2. Click on post options
3. Click 'open in browser'
4. opens v.reddit and prompts you to download dashplaylist.mpd which is useless

**Expected behavior**
opens reddit site or redditmedia where video is playable 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51 4G (a51nsxx)
 - OS: Android 11, OneUI 3.1
 - Samsung Internet (16.2.1.56)
 - Sync Dev (22.3.18-16)

**Comment by laurencedawson** [comment]
I'm sharing what's returned in the API. I'd suggest sharing the post comments instead.
