### ISSUE TITLE
[BUG] cards load incorrectly when switching subreddits

### ISSUE THREAD

**Issue by Sebianoti** [laurencedawson/sync-for-reddit#813]
**Describe the bug**
cards load incorrectly when switching subreddits, it would appear as if you scrolled down already, scrolling up corrects the view.

**To Reproduce**
1. Scroll down on any subreddit
2. Switch to another subreddit
3. See the bug

**Expected behavior**
Cards would load correctly

**Screenshots**
![Screenshot_20220320-002830_Sync_Dev](https://user-images.githubusercontent.com/96957054/159143008-deee9a99-9fc4-4e70-8442-20aec6b6d9eb.png)

https://user-images.githubusercontent.com/96957054/159143017-664e2d37-e847-450e-afbf-07af16492551.mp4

**Device:**
 - Device: Samsung Galaxy Tab S8 Ultra
 - OS: Android 12
 - Version v22.3.19

**Comment by laurencedawson** [comment]
Think I've fixed this. Please keep an eye out and if not make a new issue. Thanks

**Comment by Sebianoti** [comment]
It's not fixed, just updated the app and checked.

**Comment by laurencedawson** [comment]
I haven't pushed like yet lol

**Comment by Sebianoti** [comment]
Oops, will check after the update lol
