### ISSUE TITLE
[BUG] creating Hyperlinks prompts password managers to ask to save inputted text as password

### ISSUE THREAD

**Issue by skff-err** [laurencedawson/sync-for-reddit#814]
**Describe the bug**
creating hyperlinks prompts password management apps to ask for "password" whihc is just normal text inputted into a popup to be saved

**To Reproduce**
1. Go to comments
2. Create new comment
3. Upload image
4. Input image name
5. Post comment
6. Leave comment section
7. Wait
8. BitWarden pops up asking me whether to save information about that image link as login info

**Expected behavior**
BitWarden should not pop up (see notes to see information saved by bitwarden)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51 4G (a51nsxx)
 - OS: Android 11, OneUI 3.1
 - Samsung Internet (16.2.1.56)
 - Sync Dev (22.3.18-16)

**Notes**
- May also happen on "Insert Link" feature

- Information saved on bitwarden:
Type: Login
Name: com.laurencedawson.reddit_sync.dev
Username: [Link Name]
Password: [URL]
TOTP: -none-
URI: androidapp://com.laurencedawson.reddit_sync.dev

**Comment by laurencedawson** [comment]
Added a fix for this in the next release.

Please make another issue if the issue persists. Thanks
