### ISSUE TITLE
Option for 'Highlight new comments' to highlight the whole comment, like the old version

### ISSUE THREAD

**Issue by TimberAngry** [laurencedawson/sync-for-reddit#819]
Request for option to have 'Highlight new comments' to highlight the whole comment, like the old version.

The blue dot is not a sufficient highlight for me, I can't see it when scrolling fast, and I can't see it when covered by my thumb. Old Sync used to highlight the whole comment.

Thanks for your time.

**Comment by laurencedawson** [comment]
Pencilling in for the v22 prod release milestone,

**Comment by laurencedawson** [comment]
Done
