### ISSUE TITLE
[BUG] Sync in-line images not working properly

### ISSUE THREAD

**Issue by Vinzette** [laurencedawson/sync-for-reddit#821]
Sync isn't loading the 2nd image in the linked post - https://www.reddit.com/r/CrackWatch/comments/tisun1/open_source_crackwatch_alternative/

Also including screenshots of Sync App behaviour vs Reddit Webpage - https://imgur.com/a/5yFMANm

**Comment by laurencedawson** [comment]
Annoyingly the selftext has since been deleted. 

Please let me know if you see this again.
