### ISSUE TITLE
Remember post sorting per subreddit

### ISSUE THREAD

**Issue by monogon** [laurencedawson/sync-for-reddit#824]
I'd like the post sorting to remember what sorting I prefer _per_ subreddit.

For instance, right now I have "What's Hot" as default post sort in settings. If I go to r/android, then I go to another subreddit or quit the app and go again to r/Android, the sorting option is back on "What's Hot".

But I'd prefer it to remember that on r/android I prefer "New", and on r/redditsync and most others I prefer "What's Hot" for example.

**Comment by laurencedawson** [comment]
You can add per subs sorts from the subreddit picker
