### ISSUE TITLE
Autoplay videos in comment view

### ISSUE THREAD

**Issue by Indreya** [laurencedawson/sync-for-reddit#825]
Videos used to auto play in the comment view in v20 but it is missing in v22. For reference I linked gif belo**w.

Reference**
![no19ZknS8o](https://user-images.githubusercontent.com/26198011/159248110-bf100e67-c4f7-410d-a58b-6936a8b1cb74.gif)

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/775
