### ISSUE TITLE
Improve Inline gallery view

### ISSUE THREAD

**Issue by Indreya** [laurencedawson/sync-for-reddit#828]
When multiple image posts are made, the images are cropped in the post view. It would be nice if the first image was made fully visible.
And maybe we could swipe through the images without clicking and opening the image. Now we have to click and open the image and then swipe through them

**Comparison of V22 and V20**

![Untitled](https://user-images.githubusercontent.com/26198011/159265533-8c943f15-c163-4142-a61a-7141b6fa14eb.png)
.

**Comment by laurencedawson** [comment]
This has since been fixed.
