### ISSUE TITLE
FAB doesn't appear if there are no posts 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-reddit#829]
**Describe the solution you'd like**
FAB shouldn't be tied to posts loading

Issue -
![Screenshot_20220321-192535_Sync Dev.png](https://user-images.githubusercontent.com/55349349/159277948-2ad624d5-96f6-4682-a039-0efde1988559.png)

![Screenshot_20220321-192826_Sync Dev.png](https://user-images.githubusercontent.com/55349349/159277993-8b47e104-8cbf-4c45-b94b-dc19f4d2345d.png)

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/823
