### ISSUE TITLE
[BUG] Supported URLs containing special characters not opening in Sync

### ISSUE THREAD

**Issue by anarii** [laurencedawson/sync-for-reddit#839]
**Describe the bug**
When opening supported URLs containing special characters (e.g. Nordic ÄÖÅ), Sync link handler does not recognize the URL and the URL will not open in Sync.

**To Reproduce**

1. Open any Android app
2. Click on supported, e.g. reddit.com, URL containing special characters
3. The URL opens in browser, not in Sync. The issue can also be reproduced in e.g. long pressing the URL in any app and Sync link handler will not show up as option in the menu at all.

**Expected behavior**

Sync link handler recognizes the supported URL correctly and opens it in Sync.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S20 FE
 - OS: Android 11
 - Browser: Any
 - Version: 22.3.20 (beta)

**Comment by laurencedawson** [comment]
Example? Cheers

**Comment by anarii** [comment]
Couple of examples:

https://www.reddit.com/r/Suomi/comments/tdc639/venäjän_hyökkäys_ukrainaan_megaketju/
https://www.reddit.com/r/sweden/comments/tijjzk/ukrainakriget_megatråd_v/

**Comment by bohrabhijeet** [comment]
> Also tried to open them on Android 12 with Sync beta v22.3.24 and it behaves similarly (opening in browser).
I'm on Sync v22.06.02 at the moment. These two links open just fine. Can you check again, please?

**Comment by laurencedawson** [comment]
Added support for diacritics.
