### ISSUE TITLE
[BUG] Searching in drawer keeps actions and search result under the bottom most part (e.g under Top or Subscribtions items) )

### ISSUE THREAD

**Issue by itami12354** [laurencedawson/sync-for-reddit#843]
Searching in drawer keeps search result and actions under Top or Subscription items

**To Reproduce**
1. Go to Left Drawer
2. Click on Search and put something
3. Scroll down to bottom most part
4. See the search result still stacked under Top or Subscribtion (depends if you have Top or Subscription as your bottom most item)

**Expected behavior**
Search results are not showed

**Screenshots**
![1](https://user-images.githubusercontent.com/67090166/159384116-d78d71ae-dded-4bec-8c35-5bba0b6d5a65.jpg)
![2](https://user-images.githubusercontent.com/67090166/159384121-908bbe19-ec2b-4fc9-83e4-c7e2d9e7ca85.jpg)

**Smartphone (please complete the following information):**
 - Device: Oppo A93
 - OS: Android 11 (ColorOs 11)
 - Browser : Brave/Chrome
 - Version v22.3.20 (Pro)

**Comment by laurencedawson** [comment]
Fixed for the next release.
