### ISSUE TITLE
[BUG] Tablet Mode Status Bar Transparency Not Consistent

### ISSUE THREAD

**Issue by ichisaur** [laurencedawson/sync-for-reddit#846]
**Describe the bug**
In tablet UI, with transparency unchecked, the status bar may change colors corresponding to the scroll location of the different panes. This can create situations where the clock text in the status bar is written over two different colors. 

**To Reproduce**
1. Enable tablet UI
2. Enable Dual Pane
3. Disable Transparent Status
4. Make sure AMOLED Dark Mode is not enabled
5. Have either pane scrolled to top, while scrolling other pane. Issue is most apparent when scrolling to and from the very top, when the header shrinks

**Expected behavior**
Status bar to remain solid, with color consistent with side bar. 

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab S7 + 
 - OS: Android 12
 - Version: 22.3.20

**Additional context**
This may be intentional behavior. My device, however, places a clock centered in the status bar. The split between panes causes a color shift in the status bar where the clock would be. 
![Screenshot_20220321-231441_Sync](https://user-images.githubusercontent.com/16300780/159419420-3b1ce5f3-f191-4448-86c2-a2dbadee4b82.jpg)

**Comment by laurencedawson** [comment]
This is intentional.

Both of the panels will independently alter their section of the status bar to show the scroll status.
