### ISSUE TITLE
[BUG] Full Height Cards does not create Full Height Cards

### ISSUE THREAD

**Issue by ichisaur** [laurencedawson/sync-for-reddit#847]
**Describe the bug**
The Full Height option does not work for the Cards view type. Cards remain at a seemingly fixed height regardless of the option setting. 

**To Reproduce**
1. Enabled Cards View Type
2. Enable Full Height Cards
3. See error

**Expected behavior**
Expected behavior is similar to the Full Height Image Preview option under the Slides view type. Images and cards should expand in height to their full height when option is enabled. 

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab S7+ with Tablet UI Enabled, Galaxy Z Flip 3
 - OS: Android 12
 - Version: 22.3.20

**Comment by DailytheNoob** [comment]
Looks like changing the Title font size doesn't do anything either.

Sync version: v22.3.20    
    Sync flavor: pro    
    
    View type: Cards    
    Push enabled: false    
    
    Device: timelm    
    Model: LGE LM-V600    
    Android: 11

**Comment by joaofsa2000** [comment]
What I've found is if you also enable full width card it then shows the full height correctly, don't know if it's a bug or intended

**Comment by LKJones83** [comment]
> What I've found is if you also enable full width card it then shows the full height correctly, don't know if it's a bug or intended

I see the same behavior.

**Comment by ichisaur** [comment]
Fixed in latest beta
