### ISSUE TITLE
[BUG] Images displaying under status bar in image viewer

### ISSUE THREAD

**Issue by Code027** [laurencedawson/sync-for-reddit#849]
**Describe the bug**
Status bar is transparent on image viewer and goes over images. Mostly observed from tall images and zooming in which may disrupt viewing.

**To Reproduce**
1. Select a post preferably with a tall image.
2. Open the image in image viewer.
3. See error

**Expected behavior**
Status bar should be solid black and does not go over the image, similar to v20.

**Screenshots**
v20 image viewer
![Screenshot_20220322_153252](https://user-images.githubusercontent.com/29376476/159468666-bb8d2d3a-6fee-4d16-9442-4a52e834d1cf.jpg)

v22 image viewer
![Screenshot_20220322_153220](https://user-images.githubusercontent.com/29376476/159468688-1f1b921d-5511-4365-8e57-ec6bf0bb9654.jpg)

**Smartphone (please complete the following information):**
 - Device: vivo 1906
 - OS: Android 11
 - Browser: Brave
 - Version: 22.3.21

**Additional context**

**Comment by laurencedawson** [comment]
Fixed for the next release.
