### ISSUE TITLE
BUG: When changing view type, if audio is playing in-app, user cannot diasble audio.

### ISSUE THREAD

**Issue by RecklessDwark** [laurencedawson/sync-for-reddit#85]
Steps to reproduce:

Scroll through main feed, enable audio on a video that is playing> change card view type to full height (if in dynamic) or dynamic (if in full height)> Feed will load into chosen view type, however audio from video that was playing cannot be stopped

Only way to fix is to force close app

https://streamable.com/5idipt

**Comment by laurencedawson** [comment]
Fixed yo
