### ISSUE TITLE
[Tablet] Improve reachability of drawers

### ISSUE THREAD

**Issue by snah-dev** [laurencedawson/sync-for-reddit#850]
**Is your feature request related to a problem? Please describe.**
When holding the tablet on landscape mode by the sides and clicking on the explore button, the drawer shows up in the center so the user will have to reach the center. 

This also affects other types of drawers that show up in the center such as the action drawer.

**Describe the solution you'd like**
Move the drawer to the left side or near the explore button

**Additional context**
![Screenshot_20220322-190610_Sync Pro](https://user-images.githubusercontent.com/58427306/159469715-1c1e07cb-641c-47c7-b708-70902feb5f82.png)

**Comment by laurencedawson** [comment]
Added for the next release.
