### ISSUE TITLE
[BUG] Lack of spacing between username and score in comments

### ISSUE THREAD

**Issue by fushinari** [laurencedawson/sync-for-reddit#853]
**Describe the bug**
On each comment's header, there isn't enough space between the username and the score. It could make use of the for dot separator that's used elsewhere in the interface.

**To Reproduce**
1. Open any post with comments
2. Look at any comment's header

**Expected behavior**
There should be some form of separation between the username and comment score, either in the form of sufficient padding or a visual indicator like the dot between comment score and time of comment.

**Screenshots**
![Screenshot_20220322-172558_Sync Pro~2.png](https://user-images.githubusercontent.com/28823274/159479380-e30d16f7-9871-496d-999d-be7021c02c7a.png)

**Smartphone (please complete the following information):**
 - Device: Mi A3
 - OS: Android 12
 - Version: 22.3.1

**Comment by laurencedawson** [comment]
Settings > Comments > "delimit scores with a bullet point"
