### ISSUE TITLE
Provide resolution information for images (again)

### ISSUE THREAD

**Issue by Moleculor** [laurencedawson/sync-for-reddit#854]
**Is your feature request related to a problem? Please describe.**
Certain subreddits require a minimum resolution of images posted, and lacking that information means that those subreddits can not be properly moderated. 

Not a problem I'm actually facing, but a potential one. The one I'm actually facing is that I like to send links to my computer for high resolution images, but if I don't know the resolution, I... don't know the resolution. 

Prior versions of Sync showed the resolution of the image in the 'pull-up' thing showing the URL of the image. (First in debug, then later without debug since there was room available.) 

v22 does not.

**Describe the solution you'd like**
Show the resolution of images in the info provided, without debug mode turned on, in the pull-up info section for images being displayed.

**Comment by thereddestdog** [comment]
OK to close #854 : https://github.com/laurencedawson/sync-for-reddit/issues/991

**Comment by laurencedawson** [comment]
Thanks!
