### ISSUE TITLE
[BUG] Autoplayed video pauses momentarily when swiping up/down and lifting the finger off the screen

### ISSUE THREAD

**Issue by Fanolian** [laurencedawson/sync-for-reddit#863]
**Describe the bug**
Autoplayed video pauses momentarily when swiping up/down and lifting the finger off the screen. 

**Screencast**
https://i.imgur.com/djswdMQ.mp4 (12MB)

**To Reproduce**

0. (Optional) Clear app data/storage/cache
1. Enable gif/video autoplay in Settings > Data Options
2. Change subreddit view to `Cards` or `Slides`
3. Visit a subreddit that has a video, e.g. https://www.reddit.com/r/Unexpected/
4. Scroll down so a video autoplays
5. Swipe up/down a little bit (so the video doesn't leave the autoplay region) and quickly lift the finger so it is still sliding due to inertia.
6. Observe the video during the sliding.

**Expected behavior**
The video keeps playing when sliding.

**Additional context**
The video plays properly if I swipe up/down but do not lift my finger.
The video timer pauses when the bug occurs.

**Device information**

    Sync version: v22.3.21 and v22.3.20
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: sunfish    
    Model: Google Pixel 4a    
    Android: 12 (SP2A.220305.012)

    Browser: Firefox Nightly

Edit: Forgot to mention, v20 did not have this issue. v22.3.20 was the first v22 I used.

**Comment by laurencedawson** [comment]
This was actually intentional :)
