### ISSUE TITLE
[BUG] Red overlay present in subreddit view

### ISSUE THREAD

**Issue by dahern** [laurencedawson/sync-for-reddit#865]
**Describe the bug**
A pink/red square overlay is visible when viewing Subreddits after turning on AMOLED in dark mode, impacts light mode also. Does not impact Post view.

**To Reproduce**
1. Go to 'Dark Mode' settings page while already in dark mode
2. Activate 'AMOLED'
3. Return to subreddit view

**Expected behavior**
No overlay present

**Screenshots**
[Image](https://i.imgur.com/M1t35P9_d.webp) 

**Smartphone:**
 - Browser [Chrome]
 - Version [99.0.4844.73]
 - Device model: LYA-L29
 - Android Version: Android 10 (Android Q)
 - Device name: Huawei Mate 20 Pro
 - Sync Version: V22.3.20 beta

**Additional Information:**
Resetting dark mode setting page settings did not resolve the issue

**Comment by laurencedawson** [comment]
Settings > Developer options > disable "show autoplay video region"

**Comment by dahern** [comment]
Issue resolved, thank you
