### ISSUE TITLE
[BUG] Redd.it short links missing

### ISSUE THREAD

**Issue by antwonw** [laurencedawson/sync-for-reddit#866]
**Describe the bug**
`redd.it` short links are missing in v22.

**To Reproduce**
1. Go to a post
2. Click on the share icon
3. Click on `comment`
4. Shared link is Reddit original long URL

**Expected behavior**
A `redd.it` short URL

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G
 - OS: Android 12
 - Browser Chrome
 - Version 22

**Additional context**
Video showing differences:

x265
https://user-images.githubusercontent.com/519934/159564522-8f08e13c-5568-4caa-b6b8-7b7bb20f128d.mp4

x264
https://user-images.githubusercontent.com/519934/159564853-a0e69df5-a6b5-47de-9415-2c681abeb82b.mp4

**Comment by laurencedawson** [comment]
This was intentional due to sharing issues with other apps.
