### ISSUE TITLE
[BUG] Not possible to return from external link when incognito custom tabs is active

### ISSUE THREAD

**Issue by mschleeweiss** [laurencedawson/sync-for-reddit#867]
I have activated the incognito custom tabs feature. With this feature active I can no longer return to the app (either by pressing X or by tapping the back button) after opening an external link (there should be plenty of examples on r/all). 

If I press nav back a few times I will see the toast "Press once more to close the app" (or something like that) but nothing happens. I have to manually close the app.

Maybe it's possible to return from inline links (I was opening this repo from the app and could return to the app using the back button, but not with the X button). 

I am on v 22.3.22

This does not happen when incognito is not active, so it seems like it's related to this new feature. I have set the necessary flags to enabled.

**Comment by mschleeweiss** [comment]
Interestingly enough, if I rotate the device after pressing X or back once then I am back in the app, so maybe this is juts a rendering problem?

**Comment by laurencedawson** [comment]
Not a sync issue I'm afraid. There is also a disclaimer when enabling this feature as it's known to be buggy!
