### ISSUE TITLE
[BUG] Gifs and videos don't autoplay while full height on the right

### ISSUE THREAD

**Issue by woojin444** [laurencedawson/sync-for-reddit#871]
There is an option in the app that allows videos to autoplay if they're full height. This works in the main page but doesn't work when you go into a post that contains gifs/vids.

I have enabled the option to autoplay content if the view option is full height. This works on the left side but not on the right side. You can see that the right side has the "gif" button in the middle.

To Reproduce Steps to reproduce the behavior:
1. Enable option to auto play videos if full height
2. Set comment option to display content at full height
3. Enable tablet mod
4. Go into a gif or a video post

Expected behavior A clear and concise description of what you expected to happen.
Both the content on the left and the right side should auto play.

Screenshots If applicable, add screenshots to help explain your problem.
https://i.imgur.com/29FR3ho.jpg

Smartphone (please complete the following information):

Sync version: v22.3.21    
Sync flavor: pro    

View type: Slides    
Push enabled: false    

Device: gts8pwifi    
Model: samsung SM-X800    
Android: 12

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/825
