### ISSUE TITLE
[BUG] Scroll fails if initiated from the video controls on Slides view 

### ISSUE THREAD

**Issue by Tiagoliranl** [laurencedawson/sync-for-reddit#873]
See link: https://gfycat.com/perfumeddaringkatydid

Device information

Sync version: v22.3.21    
Sync flavor: pro    

View type: Slides    
Push enabled: false    

Device: alioth    
Model: Xiaomi M2012K11AG    
Android: 11

**Comment by laurencedawson** [comment]
Fixed for the next release.
