### ISSUE TITLE
[BUG] Improper theming for "Ban user" activity in light mode

### ISSUE THREAD

**Issue by starscar12** [laurencedawson/sync-for-reddit#874]
Improper theming for "Ban user" activity in light mode. Status bar and Send icons are unreadable.

1. Make you you have sufficient permissions as a mod to ban a user
2. Go to a subreddit where you moderate
3. Tap mod icon in a post and choose "Ban user"

Status bar and Send icons should have enough contrast to make them prominent.

Screenshot
https://media.discordapp.net/attachments/799399306775887926/956161312994512946/Screenshot_20220323-195244_Sync_Dev.png

 - Device: Samsung Galaxy A32 4G
 - OS: Android 11 (One UI 3.1)
 - Version: Sync Dev 22.3.22-15

**Comment by laurencedawson** [comment]
Fixed for the next release.
