### ISSUE TITLE
[BUG] Tagging a user changes nav bar position

### ISSUE THREAD

**Issue by vibrunazo** [laurencedawson/sync-for-reddit#876]
**Describe the bug**
While viewing a comment thread. Tagging a user will change the position of the nav bar (the on on the bottom with up, down and reply buttons) from the bottom of the screen to the middle of the screen.

**To Reproduce**
1. Go to any comment thread
2. Tag any user on the thread
3. Nav bar is now on the middle of the screen
4. Workaround: You can get it back into the original position by: exiting the thread; scrolling far up and down to hide the nav bar; tabbing out of reddit sync into another app then back

**Expected behavior**
Tagging a user should not change the position of the nav bar.

**Screenshots**

Before tagging a user:
![Screenshot_20220323-103702_Sync Pro](https://user-images.githubusercontent.com/446087/159713273-f3cdb878-b755-4054-b66f-73f5b857ad65.jpg)

After tagging a user:
![Screenshot_20220323-103715_Sync Pro](https://user-images.githubusercontent.com/446087/159713481-84db5b85-6ba7-42be-94a4-91bacfd7e08c.jpg)

**Smartphone (please complete the following information):**

- Sync version: v22.3.21    
-  Sync flavor: pro    
- View type: Compact    
- Push enabled: false       
- Device: r8s    
- Model: samsung SM-G780F    
- Android: 12

**Comment by laurencedawson** [comment]
Fixed for the next release.
