### ISSUE TITLE
[BUG] Discord drawer behaves unexpectedly

### ISSUE THREAD

**Issue by AlexVasiluta** [laurencedawson/sync-for-reddit#878]
**Describe the bug**
The experimental discord drawer, when quickly closed while it is opened, swipes the entire main viewport to the left. This exact same behavior also happens on the official discord app, but that app also includes a drawer on the right (which sync does not feature), so it makes proper use of that space.

**To Reproduce**
1. Enable experimental discord drawer;
2. Open it very quickly;
3. While it is opening, swipe in the other direction very quickly and let go. The viewport should now be empty  with the correct view clipped on the left.
I have made [a video](https://drive.google.com/file/d/1BfLXs8K8RP7s5T8bGeQNRnz8b7UG3x8w/view) with taps enabled in order to show how it is done. I have also included a few normal swipes that work as they should, in case it helps the debugging process. I found my method of reproducing to be 100% reliable.

**Expected behavior**
The drawer simply closes and returns the viewport back to normal.

**Smartphone (please complete the following information):**

Copied from the official app:
**Device information**

    Sync version: v22.3.21    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: true    
    
    Device: a50    
    Model: samsung SM-A505FN    
    Android: 11

**Additional context**
N/A

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers
