### ISSUE TITLE
[BUG] Multi-column autoplay broken since v22

### ISSUE THREAD

**Issue by darceidus** [laurencedawson/sync-for-reddit#879]
### Description

Gifs no longer autoplay in two-column (and probably more columns) mode since v22. This issue is already known by the author because it is mentioned in v22.3.17 patch notes that autoplay was rewritten and currently only works for single-column mode. See https://www.reddit.com/r/redditsync/comments/tgjo6z/v22317_dev_release_final_before_public_beta/. 

Creating this bug report so this issue is not forgotten. This feature was the only reason I used reddit sync. 

### Scenario (steps to reproduce)

1. In Change View > Customize View > Card options > Columns (portrait) set to 2.
2. Navigate to a subreddit or feed containing gifs.
3. See that gifs no longer autoplay.

### Device Info

Google Pixel XL
Android 10
Sync for reddit Free v22.3.22

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/789
