### ISSUE TITLE
[BUG] Large amount of whitespace on some posts causing readability issues in multi-column mode

### ISSUE THREAD

**Issue by darceidus** [laurencedawson/sync-for-reddit#880]
**Describe the bug**
When using multi-column mode, the post text and the post image are in separate "columns" and the post text cannot wrap under the image, causing the text to be so tall it is unreadable and a large amount of whitespace being present. There is a post about this issue from last year: https://www.reddit.com/r/redditsync/comments/mvg75f/bug_titlesthumbnails_not_displaying_properly_in_2/ but the bug has been present for many years. 

**To Reproduce**
1. In Change View > Customize View > Card options > Columns (portrait) set to 2.
2. Navigate to /r/baseball where this issue is common. It is common in other sports-related subreddits too. 

**Expected behavior**
The text should use the available whitespace under the image so it is readable, or, the image should be above the text and the text be below, so that the text can use the entire width, similar to other posts. See third screenshot.

**Screenshots**
![Screenshot_20220323-113419](https://user-images.githubusercontent.com/2941741/159750409-0a0e030f-21d9-4e84-a3da-ca2e36d0d957.png)
![2022-03-23_11-35](https://user-images.githubusercontent.com/2941741/159750359-d8ed1671-f3b2-42e5-98ad-d782ffc0ed57.png)
![2022-03-23_11-47](https://user-images.githubusercontent.com/2941741/159752585-7713d806-7864-4dd7-9a7c-123100dc0f4a.png)

**Smartphone:**
 - Device: Google Pixel XL
 - OS: Android 10
 - Version: Sync for reddit Free v22.3.22

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/176
