### ISSUE TITLE
[Request] Set default sort by subreddit/multireddit

### ISSUE THREAD

**Issue by haph88** [laurencedawson/sync-for-reddit#881]
**Is your feature request related to a problem? Please describe.**
There are some subreddits or multireddits that I visit where I always change the sort type on visiting. It would be helpful if I could save these so I don't have to change the sort every time I visit. This would override the default.

**Describe the solution you'd like**
An option to save the sorting style per subreddit or per multireddit that would override whatever the app default is set to.

**Describe alternatives you've considered**
This is different from the default. The default sort works as it should.

**Additional context**
This could allow users to have multireddits that always sort by new, or just show the top posts of the week.

**Comment by haph88** [comment]
I have found a way to to this already within the app. Is this something that could maybe be added to the "manage multireddit" tab?

**Comment by laurencedawson** [comment]
![image](https://user-images.githubusercontent.com/534059/160244402-76a1331c-6528-45db-8098-d07f5168b486.png)

![image](https://user-images.githubusercontent.com/534059/160244411-3a151ba1-6b72-4b77-93eb-436c52cf39af.png)

Hit the three dots next to a subreddit / multireddit (either from the drawer or explore).

And then select Update Sort to apply a per sub override,.
