### ISSUE TITLE
Flairs next to title where possible

### ISSUE THREAD

**Issue by Vexkriller** [laurencedawson/sync-for-reddit#882]
![Screenshot_20220323-184017](https://user-images.githubusercontent.com/102254245/159775044-e7c3a472-f223-40ce-9a9e-b38577fac914.png)

I understand its a fine line between the Material UI look and having too much "free space", but I think by putting the flair next to the title to save all the useless space it takes up would look nicer to the eye.

**Comment by laurencedawson** [comment]
Settings > Post options > Flair > "show minimal post flair" will achieve what you're asking for. No plans to expand on this further. Cheers.
