### ISSUE TITLE
[BUG] Exoplayer Exception When Playing Reddit Hosted Videos 

### ISSUE THREAD

**Issue by Sam97MT** [laurencedawson/sync-for-reddit#883]
For example: https://v.redd.it/lmc6un8h3zo81/DASHPlaylist.mpd

"Could not load video"

Error:

[https://i.imgur.com/rnEX3hu.png](https://i.imgur.com/rnEX3hu.png)

Edit 1:
Weird: it has no permissions and I can't grant more.

[https://i.imgur.com/n0jn3tJ.png](https://i.imgur.com/n0jn3tJ.png)

Edit 2:

Doesn't work for gifs or mp4 videos.

**Device information**

    Sync version: v22.3.22    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Slides    
    Push enabled: false    
    
    Device: o1q    
    Model: samsung SM-G991U    
    Android: 12

Edit 3:

This video works in the official reddit app

[https://i.imgur.com/cqRBsTh.png](https://i.imgur.com/cqRBsTh.png)

**Comment by Sam97MT** [comment]
> Duplicate:
> 
> #744
> 
> (its due to HDR videos)

Hi,
I don't think so.  Gifs don't play either. Nothing plays if it's hosted on reddit and uses the exoplayer.

**Comment by Sam97MT** [comment]
![Screenshot_20220402-201759_Sync](https://user-images.githubusercontent.com/102254414/161405865-53e858ae-3e42-4801-8aa5-503d80966704.png)


**Device information**

    Sync version: v22.3.31    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Slides    
    Push enabled: false    
    
    Device: o1q    
    Model: samsung SM-G991U    
    Android: 12

**Comment by laurencedawson** [comment]
Issue persists.

**Comment by Sam97MT** [comment]
> Issue persists.

Please tell me how I can help.

**Comment by ozancoskun** [comment]
I'm also seeing this issue but GIFs work fine for me.

**Comment by Sam97MT** [comment]
> I'm also seeing this issue but GIFs work fine for me.

Can you link me to a gift that works for you?

Can you post your device info using the Sync for Reddit app?

**Comment by laurencedawson** [comment]
Right so I've added two fixes here.

The first is switching over to a different way of streaming remote content.

The second is to allow disabling caching streaming content (Settings > Images > uncheck "cache streaming videos")

Hopefully these fixes will work for you and they'll be included in the next release.

Cheers
