### ISSUE TITLE
[BUG] Post self text font is not changing

### ISSUE THREAD

**Issue by jisanag** [laurencedawson/sync-for-reddit#886]
In the setting, post font is changed to system. So all post text should be in system font but it is static font and not changing as per option. Refer to screenshot. 

**Smartphone (please complete the following information):**
 - Device: oneplus 7t pro 
 - OS: Oxygen OS 10.3.8.HD01AA
 - Browser stock browser
 - Version latest beta 22

**Additional context**
![Screenshot_20220324-104144](https://user-images.githubusercontent.com/3917849/159847490-0c6b5712-6a54-4d01-a4d4-a0741af78a01.jpg)

**Comment by laurencedawson** [comment]
Which view type?

**Comment by jisanag** [comment]
Compact view

**Comment by laurencedawson** [comment]
Switch to slides and then you are able to customize this. Cheers
