### ISSUE TITLE
[BUG] Large unused space at top of screen.

### ISSUE THREAD

**Issue by LetoDK** [laurencedawson/sync-for-reddit#887]
**Describe the bug**
Large unused space at top of screen.
Maybe it's due to me using large font settings because of reduced eyesight.

![Screenshot_20220324-081954_Sync](https://user-images.githubusercontent.com/11471781/159864262-8c89a17b-71df-4896-a12d-a66356b0fae1.png)

**Expected behavior**
I expect no screen realestate going to waste.

**Screenshots**
![Screenshot_20220324-081954_Sync](https://user-images.githubusercontent.com/11471781/159864625-4ffdd252-a5b9-4844-a977-437d2657d516.png)

**Smartphone (please complete the following information):**
ONEPLUS A6013
18.1-20220127-NIGHTLY-fajita
11

**Comment by laurencedawson** [comment]
Not a bug:

https://www.reddit.com/r/redditsync/comments/tk02dp/v22_faq/i1wqmuz/
