### ISSUE TITLE
[BUG] Some images do not fully fit the width of the screen in slides/cards

### ISSUE THREAD

**Issue by csttsn** [laurencedawson/sync-for-reddit#888]
**Describe the bug**
Some images do not fully fit the width of the screen in cards and slides view. However, this issue disappears when viewing image in full-screen mode.

**To Reproduce**
1. For slides, enable "Preview full height" and "Preview full width"
2. Browse some sub with lots of pictures (r/museum, for example)

**Expected behavior**
 Images should occupy full width.

**Screenshots**
![121212](https://user-images.githubusercontent.com/46351005/159878793-d37cb542-3755-4f73-923e-3b56a6bd6f0e.png)

**Additional context**
Sync Pro v22.3.21

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/489
