### ISSUE TITLE
[REQUEST] Highlight comment owner in comment's thread

### ISSUE THREAD

**Issue by jnvillar** [laurencedawson/sync-for-reddit#891]
Lots of times I read a really interesting comment and some really cool and good questions/replies are made in the thread of the comment 

It would be nice to highlight the owner replies to this questions, in other words, highlight his comments inside the thread of his original comment

**Comment by laurencedawson** [comment]
The OP is shown with a little icon and colored.

**Comment by jnvillar** [comment]
> The OP is shown with a little icon and colored.

I don't mean the op of the post, I mean the **owner** of **each** **comment** in the post should be highlighted in his comment thread

**Comment by jnvillar** [comment]
Sorry to bother, but was this released ?
