### ISSUE TITLE
[BUG] Searching from Frontpage and pressing enter searches in /r/Frontpage

### ISSUE THREAD

**Issue by askeeve** [laurencedawson/sync-for-reddit#892]
**Describe the bug**
When searching from the Frontpage it is easy to accidentally restrict your search to only posts on the Frontpage which will typically return no results

**To Reproduce**
1. Go to Frontpage
2. Click on Search from More Actions or Search bar in Explore/Subreddits button.
3. Type a search query and press enter on the keyboard. 
4. See no results or much more restricted results than anticipated

**Expected behavior**
When searching from the context of a subreddit, you are presented with two buttons: Search All, and Search Subreddit. The latter being bolded to indicate its the default. If you type enter it selected the default button and restricts your search to the current subreddit.

When you do a search from the Frontpage, you only see one button: Search All, and it's bolded to indicate defaultness. If you don't click this button and execute your search by typing enter, the search is restricted to "in /r/Frontpage". This returns very few results if any and is probably never intended by the user. It should search All as if you'd clicked the only and default search button. 

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - OS: Android 12
 - Version V22.3.21 beta release

**Comment by laurencedawson** [comment]
Fixed for the next release.
