### ISSUE TITLE
[BUG] View Type: Cards does not auto play videos or gifs

### ISSUE THREAD

**Issue by LordFluffington** [laurencedawson/sync-for-reddit#893]
View Type: Card does not auto play videos or gifs

1. Go to Settings
2. Click on View Type and Select Cards
3. Go to page that has gifs or video 
4. See that they do not auto play no matter your position on the page

**Expected behavior**
Gifs and video to auto play when My view Type is Cards

 - Device: [ Xiaomi Pad 5 Pro]
 - OS: [Android 11] [MIUI 13.0.6]
 - Version [V22.3.21]

**Additional context**
Thank you good sir

**Comment by laurencedawson** [comment]
For cards are you using multiple columns?

**Comment by LordFluffington** [comment]
> For cards are you using multiple columns?

I am Indeed

2 columns portrait

4 columns landscape

**Comment by laurencedawson** [comment]
Already logged. 

https://github.com/laurencedawson/sync-for-reddit/issues/879

Cheers
