### ISSUE TITLE
[ request ] - optional left hand mode for submission button and bring back the old 'reddit more actions button'? 

### ISSUE THREAD

**Issue by yaochen** [laurencedawson/sync-for-reddit#894]
the submission button is right aligned, difficult for me to reach.

also, i saw that the more actions button has moved to the ... menu in the top right corner. can we have option to bring back the old button?

**Comment by laurencedawson** [comment]
Settings > Experimental > Actions

**Comment by yaochen** [comment]
that was fast. perfect. thanks!!
