### ISSUE TITLE
[BUG] Potential battery drain

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#895]
https://www.reddit.com/r/redditsync/comments/tm31es/high_battery_usage/

https://www.reddit.com/r/redditsync/comments/tm53un/massive_battery_usage_in_sync_for_reddit_22321/

**Comment by laurencedawson** [comment]
Added two small potential fixes for this. Keeping the issue open to see if they help at all.

**Comment by laurencedawson** [comment]
After switching ad provider, an animation issue and video player tweaks I think this has been resolved.

**Comment by benjo456** [comment]
Reopen please as have been experiencing for some time on Pixel 4a 5g. Separate issue opened too with screenshot
