### ISSUE TITLE
Add a way for self text padding to be in line with comments

### ISSUE THREAD

**Issue by Jotaro31** [laurencedawson/sync-for-reddit#898]
It appears that there is no option to maximize self text space, and it is always wrapped in a padded rounded corner box with additional padding for the text itself.
On narrow displays this cuts off a lot of screen real estate and does not match up with material (minimum) or sync classic comment options, and makes it a bit jarring to read long text posts.

If possible add a post option or change the style to left align at the same offset as the first comment level. (green line)

As mentioned in #897, a custom post view customization section might be the most ideal solution here but would require a lot of settings work.

![reddit_sync_self_text_alignment_example](https://user-images.githubusercontent.com/8150810/160005214-acf4d746-3fa4-4a95-9a3c-79d3badced6c.png)

**Comment by laurencedawson** [comment]
You can disable the border around selftext under Settings > View type > Slide and then scroll to the bottom
