### ISSUE TITLE
[BUG] Sliding Panel causes top toolbar to clash with notifications bar

### ISSUE THREAD

**Issue by willborum** [laurencedawson/sync-for-reddit#900]
**Sample description**
Enabling the experimental sliding drawer causes the top toolbar actions to be slightly higher than they normally would and conflicts with the notifications bar.

****Scenario** (steps to reproduce)**
1. Enable sliding panel style drawer
2. Navigate to a subreddit

**Result(s)**
In any view, top toolbar clashes with notifications.
https://i.imgur.com/qAGmPCn.jpeg

**Device information**

    Sync version: v22.3.21    
    Sync flavor: pro    
    
    View type: Slides and Cards
    Push enabled: false    
    
    Device: OnePlus7Pro    
    Model: OnePlus GM1915    
    Android: 10

**Comment by laurencedawson** [comment]
Fixed for the next release.
