### ISSUE TITLE
Tap to close image options interferes with video seek bar

### ISSUE THREAD

**Issue by Jotaro31** [laurencedawson/sync-for-reddit#902]
It is very easy to accidentally close a playing video when tapping the seek bar.
It appears the bar itself and the more info UI do not trigger tap to close, but there seems to be no grace zone above the seek bar itself so tapping slightly too high can lead to closing the player.

A solution would be to extend the safe zone overlay enough so minor misaligments when tapping the seek bar are still blocked from triggering tap to close.

**Comment by laurencedawson** [comment]
Added additional padding above this for the next release

![image](https://user-images.githubusercontent.com/534059/160242854-d2e81b69-1112-4db9-bd12-9ed034c79164.png)
