### ISSUE TITLE
[BUG] V22 beta - cannot play Dolby vision videos

### ISSUE THREAD

**Issue by dweitz** [laurencedawson/sync-for-reddit#906]
Not sure if this is a Pixel 6 issue, but reddit videos with Dolby vision fail to load
![Screenshot_20220324-233445](https://user-images.githubusercontent.com/595826/160049807-6d6a7651-30af-451a-83a2-f660ceaa5426.png)
https://www.reddit.com/r/greebles/comments/tmxsrf

**Device information**

    Sync version: v22.3.24    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: oriole    
    Model: Google Pixel 6    
    Android: 12

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/744
