### ISSUE TITLE
Please give us an option to change the order of the buttons (bottom navigation)

### ISSUE THREAD

**Issue by amnesia** [laurencedawson/sync-for-reddit#907]
I didn't like the three button layout, because the centered "explore" button. Having to stretch your thumb on a big phone is pretty annoying. Four buttons make navigating the app so much more comfortable. You just need to swap the two marked in the screenshot. I use "explore" (subreddit picker) all the time, while i press the other one maybe once a week. People have different preferences, though, so adding an option to customize the order would be amazing. 

For me, the order would be (from left to right): messages, sync/options, explore/subreddits, home

https://i.imgur.com/OnNRAs5.png

Also, thank you for this amazing update, I absolutely love it otherwise.

**Comment by laurencedawson** [comment]
I'm actually inclined to agree with this. I've made it the default for the next release.
