### ISSUE TITLE
Customizable colors for usernames?

### ISSUE THREAD

**Issue by phoenix-295** [laurencedawson/sync-for-reddit#908]
While scrolling through comments its hard to keep eyes on usernames as they are grey  
  
I would like to suggest to add an option to change them to some other color or add some light background to them so they are easily viewable.

I tried changing accent colors but they just change the colors of the tags that you have set for specific users

[Here](https://i.imgur.com/r7G3oz8.jpg) is an example of how username appears now, it would be eye catching if its changed to some different color rather than grey

**Comment by laurencedawson** [comment]
Added in sync ultra.
