### ISSUE TITLE
[BUG] Turning off Subreddit icons does not work

### ISSUE THREAD

**Issue by howdawg07** [laurencedawson/sync-for-reddit#912]
**Describe the bug**
Turning off Subreddit icons does not work

**To Reproduce**
1. Go to Settings
2. Click on General
3. Scroll down to Subreddit icons
4. See error - turning off Subreddit icons does not work

**Expected behavior**
It should turn off Subreddit icons

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: [Pixel 5]
 - OS: [Android 12]
 - Browser [Reddit Sync]
 - Version [22.3.24]

**Additional context**
-

**Comment by laurencedawson** [comment]
That icon relates to icons in the toolbar (I've added an extra summary description for the next release to clarify this).

I think you're wanting to disable the icons in posts? If so go to View type and disable it there
