### ISSUE TITLE
Return random/randnsfw to it's pre redesign behavior or give an option to do so

### ISSUE THREAD

**Issue by Fune3** [laurencedawson/sync-for-reddit#918]
Before the redesign, going to the random/randnsfw subreddit picked a random subreddit every time you refreshed the page. Currently if you go to either it picks out a random sub and doesn't change unless you open it again via explore.

**Comment by laurencedawson** [comment]
No plans to return to this behaviour.

However you can set "random" to be the first accessible action in more actions and then long press this to go to random over and over.
