### ISSUE TITLE
Access App via DNS Over HTTPS

### ISSUE THREAD

**Issue by ragasubekti** [laurencedawson/sync-for-reddit#920]
Some ISP has transparent DNS, and most of the times they block or slow down reddit by redirecting to their landing page.

While option for private DNS exist for system wide (Android 9+). Adding the feature to the app itself would be great.

**Comment by laurencedawson** [comment]
Isn't this something you'd configure the system and not the app to do?

**Comment by eim3** [comment]
I know tachiyomi does this, you can see how they did it here - https://github.com/tachiyomiorg/tachiyomi/issues/3377

**Comment by laurencedawson** [comment]
This has since been added to ultra. I'll move out of there for everyone for the next release.
