### ISSUE TITLE
Touch target for video seek bar is too small in v22 beta

### ISSUE THREAD

**Issue by Rionescu13** [laurencedawson/sync-for-reddit#921]
The touch target for the seek bar at the bottom of the built-in video player should be made vertically larger. About 50% of the time I try to tap the seek bar, I accidentally close the video as the app interprets my tap as being on the video instead of the seek bar. I've been a long-time user of Reddit Sync and this appears to be a new issue with the v22 redesign, which among many other things, slightly redesigned the video player and seemingly introduced this issue. It's not a bug per se, just a useability issue. Thank you!

**Comment by laurencedawson** [comment]
This has been increased already for the next release. Cheers
