### ISSUE TITLE
[BUG] cards load incorrectly when switching subreddits

### ISSUE THREAD

**Issue by Sebianoti** [laurencedawson/sync-for-reddit#925]
**Describe the bug**
cards load incorrectly when switching subreddits, it would appear as if you scrolled down already, scrolling up corrects the view.

**To Reproduce**

Scroll down on any subreddit
Switch to another subreddit
See the bug
Expected behavior
Cards would load correctly

![159143008-deee9a99-9fc4-4e70-8442-20aec6b6d9eb](https://user-images.githubusercontent.com/96957054/160258522-9c80682c-9bcf-4632-b217-073d1eb869a6.png)

https://user-images.githubusercontent.com/96957054/160258525-c28ba05f-7a17-4906-a97d-a107defa50d7.mp4

**Comment by laurencedawson** [comment]
Fixed for the next release.
