### ISSUE TITLE
[BUG] Internal browser doesn't have back or forward buttons.

### ISSUE THREAD

**Issue by askeeve** [laurencedawson/sync-for-reddit#926]
**Describe the bug**
The internal browser seems to have lost its history functions. Previously you could go back and forwards but now the back button just closes the browser. 

**To Reproduce**
1. Open a link in internal browser (not Chrome custom tab) 
2. Click on a link from within that page. 
3. Hit the back button. 
4. Browser closes. 

**Expected behavior**
I would expect the back button to go to the previous page and only close the browser if there's no more history to return to. I would also expect a "go forward" button in the browser's context menu. 

This behavior is attainable with Chrome custom tabs but using those means pages visited in Sync show up in your regular browsing history.

**Smartphone (please complete the following information):**
 - Device: Samsung S21U
 - OS: Android 12
 - Version V22.3.24 beta release

**Comment by laurencedawson** [comment]
This has been fixed for the next release.

https://github.com/laurencedawson/sync-for-reddit/issues/838

**Comment by askeeve** [comment]
Ah apologies, I searched before I submitted and I didn't see it. Thanks for fixing it!
