### ISSUE TITLE
[BUG] Wrong app icon in Toast for 'downloading'

### ISSUE THREAD

**Issue by ctrlbrk42** [laurencedawson/sync-for-reddit#927]
**Describe the bug**
Generic Android icon shown instead

**To Reproduce**
Share > Image (video)

**Screenshots**
![Screenshot_20220326-192727.png](https://user-images.githubusercontent.com/1001097/160261500-7809a68b-9dec-44ba-b1d3-f90462c9ade9.png)

**Device information**

    Sync version: v22.3.26    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: raven    
    Model: Google Pixel 6 Pro    
    Android: 12

**Comment by laurencedawson** [comment]
Unfortunately this is an Android bug. It's been fixed in 12L and 13 dev previews.

**Comment by ctrlbrk42** [comment]
> Unfortunately this is an Android bug. It's been fixed in 12L and 13 dev previews.

Hi LJ,

I'm on 12L QPM S3B1.220218.006 just to confirm it is not fixed in this build at least.
