### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by citking** [laurencedawson/sync-for-reddit#934]
**Describe the bug**

The reddit link at https://www.reddit.com/r/24hoursupport/comments/tpjzlw crashes Sync Pro

**To Reproduce**
1. Go to https://www.reddit.com/r/24hoursupport/comments/tpjzlw
2. After a brief moment, Sync Pro crashes

**Expected behavior**

No crashes

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Latest version of Android with March 2022 patches
 - Browser Sync Pro
 - Version Current version 

**Additional context**

Very easy to reproduce

**Comment by citking** [comment]
Based on some preliminary research it appears Sync Pro can't handle very wide images very well

**Comment by laurencedawson** [comment]
Fixed. The inline images are replaced with links if their height to width ratio is too small.
