### ISSUE TITLE
[BUG] Gif posts briefly flash thumbnail of a previously loaded gif

### ISSUE THREAD

**Issue by atgodfrey** [laurencedawson/sync-for-reddit#937]
Description

Sorry if this has already been posted but I can't find how to search within a subreddit.

When I'm scrolling my feed, if there are two gif posts in a row, the second will sometimes flash the thumbnail of the first before autoplaying the proper gif. This doesn't happen every time.

Device Info

Pixel 5
Android 11 
Sync Pro 22.3.24

**Comment by laurencedawson** [comment]
This has finally been fixed. Cheers.
