### ISSUE TITLE
Handle device rotation better when submitting a photo

### ISSUE THREAD

**Issue by dylanmtaylor** [laurencedawson/sync-for-reddit#942]
**Describe the bug**
When submitting a photo, if you rotate the device, it is lost. 

**To Reproduce**
1. Create a new image post with auto rotate enabled on the phone
2. Take a photo of anything
3. Rotate phone

**Expected behavior**
Photo is still there after rotation

**Screenshots**

https://user-images.githubusercontent.com/277927/160538181-953c3e23-87c3-4f2c-bc62-1563d8548697.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 12
 - Browser chrome
 - Version [e.g. 22] latest beta

**Comment by laurencedawson** [comment]
Reformatted issue and pencilled in for the following milestone:

https://github.com/laurencedawson/sync-for-reddit/milestone/7
