### ISSUE TITLE
[BUG] 'Best' missing from default post sorting options

### ISSUE THREAD

**Issue by freshgiammi** [laurencedawson/sync-for-reddit#946]
**Describe the bug**
Can't set 'Best' as default post sort, missing from options.

**To Reproduce**
1. Go to Settings
2. Click on Post Options -> Default post sort
3. All options are visible, but 'best' is missing from options

**Expected behavior**
'Best' should be along the other options for default post sorting.

**Screenshots**
![Screenshot_20220329-014430](https://user-images.githubusercontent.com/16855748/160592380-e4a59b0c-17d2-4f7e-a7a2-fa8e44ab5763.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: 12L
 - Version v22.3.24

**Comment by thereddestdog** [comment]
'Best' is only available on Frontpage and nowhere else

**Comment by thereddestdog** [comment]
In that case, you find Frontpage in the subreddit list and hit the 3-dot menu next to it to Update Sort and change to Best

**Comment by freshgiammi** [comment]
I know, but the default for Reddit is 'best', so the user should either have that sorting on app opening, or at least be able to customize the sorting on the default subreddit (frontpage in this case).
If this can be considered 'not a bug', it can still classify as an enhancement.

**Comment by laurencedawson** [comment]
This isn't a bug. Default for homepage can be overridden using the three dot menu as discussed here.

Default should apply to all subs and not just one. Closing.
