### ISSUE TITLE
[BUG] Sometimes when long-pressing Home, the feed will be behind the header

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#947]
Not sure how to replicate exactly

https://i.imgur.com/Bz4AhbX.jpg

**Device information**

    Sync version: v22.3.27    
    Sync flavor: dev    
    
    View type: Cards    
    Push enabled: false    
    
    Device: sunfish    
    Model: Google Pixel 4a    
    Android: 11

**Comment by laurencedawson** [comment]
Fixed.
