### ISSUE TITLE
[REQUEST] Can search results be shown in a different order

### ISSUE THREAD

**Issue by thereddestdog** [laurencedawson/sync-for-reddit#948]
When searching for a subreddit, the top results should always start with the beginning of the search string

Example when searching "car", askcarsales and AwesomeCarMods should be listed below results that actually start with car-

https://i.imgur.com/m4HUBPf.png

**Comment by laurencedawson** [comment]
Not a bug.

**Comment by laurencedawson** [comment]
Added to the backlog as v22 is feature complete.
