### ISSUE TITLE
 [Feature Request] Multi-column image gallery mode (with gif autoplay)

### ISSUE THREAD

**Issue by darceidus** [laurencedawson/sync-for-reddit#949]
Some reddit apps like Boost (and others), or reddit-y web apps like [scrolller.com](https://scrolller.com/), have a feature in which posts can be shown in multi-column mode with nothing but the images. This would be a great feature to add to Sync, especially once multi-column autoplay is working again. 

![Screenshot_20220323-111858](https://user-images.githubusercontent.com/2941741/160670913-f17b409f-3ae1-4163-945a-075988a0a181.png)
![Screenshot_20220323-112250](https://user-images.githubusercontent.com/2941741/160670908-773c1773-9ade-41a3-b556-fcc307af0b06.png)

**Comment by cococoot** [comment]
Yes. Asking for this as well.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/603
