### ISSUE TITLE
[BUG] Auto playing video pauses when scrolling

### ISSUE THREAD

**Issue by vascosimoes** [laurencedawson/sync-for-reddit#950]
**Description**

When auto play is enabled, the video pauses on momentum scrolling. If you are scrolling with the finger on the screen, the video plays normally, but if you give it some momentum, it pauses until the scroll stops. It's a bit jarring when using the app

[Example](https://imgur.com/a/P6p6sUT)

****Scenario****
** (steps to reproduce)**
1. Enable auto play
2. Find a video and wait for it to start playing
3. Scroll a bit so that when the finger is lifted, it scrolls for a while longer

**Result(s)**
The video pauses until the scroll ends

**Device information**

    Sync version: v22.3.28    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: t2s    
    Model: samsung SM-G996B    
    Android: 12

**Comment by laurencedawson** [comment]
This is intentional.

**Comment by vascosimoes** [comment]
Oh ok, thanks. Didn't happen on v21 though. That's why I reported as a bug. Any chance this could be toggled in settings?

**Comment by laurencedawson** [comment]
No plans to, if you fling I would expect the video to stop...
