### ISSUE TITLE
[BUG] Spelling error in a prompt while opening a link

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#959]
**Describe the bug**
Spelling error on a warning. It has "the" in the place of "that"

**To Reproduce**
By clicking on this link: 

https://www.reddit.com/r/Factoriohno/comments/trzdfr/_/i2ov4ir

**Expected behavior**
...shared a link "that" might not work...

**Screenshots**
![mfn0zMp.jpg](https://user-images.githubusercontent.com/34155181/160862933-15dc235b-0e58-4efd-9475-41883c1d1905.jpg)

**Smartphone (please complete the following information):**

Sync version: v22.3.28    
Sync flavor: pro    

View type: Cards    
Push enabled: false    

Device: whyred    
Model: Xiaomi Redmi Note 5    
Android: 9

**Comment by laurencedawson** [comment]
Fixed.
