### ISSUE TITLE
[BUG] Videos do not autoplay on Galaxy Tab S7

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#962]
**Spotted on:**
https://www.reddit.com/r/redditsync/comments/tsa8tl

**Description:**
I cannot get anything to autoplay on my tablet. I have tried with and without tablet mode.

**Scenario (steps to reproduce)**
Browsing Reddit with card view

**Result(s):**
Nothing autoplays, such as videos or gifs

**Device Info:**
Sync version: v22.3.28    
Sync flavor: pro    

View type: Cards    
Push enabled: false    

Device: gts7lwifi    
Model: samsung SM-T870    
Android: 12

**Screenshot:**
![Screenshot](https://user-images.githubusercontent.com/34155181/160896085-c7bbd9dd-403d-4283-9574-06b0e2d0051d.jpg)

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/789
