### ISSUE TITLE
[BUG] New comment count not visible in cards view 

### ISSUE THREAD

**Issue by AT302** [laurencedawson/sync-for-reddit#963]
New comment count (+XY) comments under post in cards view is not present. It's present in slides view only. 

1. In slides view - Go to  any rising post 
2. open comments. Close comment section. Wait for few minutes. 
3. Check comment count. There would be +XY new comment in post description. 
4. Now switch view to cards without opening comment section. New comment count is not visible in cards view 

**Expected behavior**
New comment count should be visible like +20 after regular comment count.

**Comment by laurencedawson** [comment]
Fixed for the next release.
