### ISSUE TITLE
[BUG] Wrong media type indicator icon for youtu.be URLs

### ISSUE THREAD

**Issue by dbarbuzzi** [laurencedawson/sync-for-reddit#964]
**Describe the bug**
For link submissions with URLs on the domain `youtu.be`, the media type indicator icon displayed in smaller cards view (possibly others) is the image icon, not the expected video icon.

**To Reproduce**
1. Using smaller cards view, view the 'smaller card' for a post of a `youtu.be` link
    * For example, open this URL in the app using its “explore domain” feature: https://old.reddit.com/domain/youtu.be/
 2. Look at the media type indicator icon next to the thumbnail

**Expected behavior**
The media type indicator icon should indicate that the URL leads to a video (e.g. same icon as links to URLs on `youtube.com` domain)

**Screenshots**
* https://i.imgur.com/kXGPVLL.png (5th post, from /r/Python)
* https://i.imgur.com/IAYVzm7.png (all posts, from /domain/youtu.be/)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 12 (Mar 2022 security update; build SP2A.220305.013.A3)
 - Browser: Firefox
 - Version: v22.3.28

**Additional context**
**Device information**

    Sync version: v22.3.28    
    Sync flavor: pro    
    
    View type: Smaller cards    
    Push enabled: false    
    
    Device: raven    
    Model: Google Pixel 6 Pro    
    Android: 12

**Comment by laurencedawson** [comment]
Fixed for the next release.
