### ISSUE TITLE
[BUG] Status bar isn't themed for the text editor

### ISSUE THREAD

**Issue by Jnss98b** [laurencedawson/sync-for-reddit#965]
**Describe the bug**
The status bar is black in the text editor regardless of theming option

**To Reproduce**
1. Create a new message or reply to a comment

**Expected behavior**
The status bar should be correctly themed like it is everywhere else within the app

**Screenshots**
![image](https://user-images.githubusercontent.com/24306400/160952886-bfc3f6e3-94c5-4413-9452-12be71e7c134.png)

![image](https://user-images.githubusercontent.com/24306400/160952862-eec5345d-a3f1-424d-8d06-7e74f528cc2c.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Version: v22.3.28

**Comment by laurencedawson** [comment]
Fixed for the next release.
