### ISSUE TITLE
Full height image album previews. 

### ISSUE THREAD

**Issue by Gaburun** [laurencedawson/sync-for-reddit#969]
**Is your feature request related to a problem? Please describe.**
It's a quite inconvenient to have to click the albums to see the full image and it looks inconsistent when all single images are full height. 

**Describe the solution you'd like**
Full height preview of the first image in the album when the option is enabled.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by geominorai** [comment]
Imgur images and by extension their albums do not show as full height yet as of v22.4.18-23.
