### ISSUE TITLE
[BUG] App Freezing While Scrolling Subreddit\Feed

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#970]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tsmpkr

**Description**
While scrolling through posts (both Frontpage and subreddits), the app can occassionally freeze up. Seems to occur while a video is displayed (before it actually plays) but is not consistant, the same video doesn't always cause the issue. While frozen, the app cannot be navigated or return to the home screen but can access the quick settings panel on my device. 

Might be very difficult to actually find the cause of the issue but making a post in case other users experience it. Have only encountered it with v22.3.28 and happens within a few minutes of use.

**Scenario (steps to reproduce)**
- Scroll through posts (either FrontPage or in a subreddit)

- Stop scrolling briefly while looking at a post with a video attached 

**Result(s)**
While the app is frozen, it cannot be navigated or return to the home screen but can access the quick settings panel on my device. 

**Device information**
```
Sync version: v22.3.28    
Sync flavor: free    
Removed ads: true    

View type: Slides    
Push enabled: false    

Device: judyln    
Model: LGE LM-G710    
Android: 10
```

**Comment by laurencedawson** [comment]
Added a fix for the next release.
