### ISSUE TITLE
[REQUEST] Hide preview in recents option

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#971]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tswnla

**Is your feature request related to a problem? Please describe.**
All but NSFW sub previews are visible in recents

**Describe the solution you'd like**
I know that there's already an option for hiding the preview in recents for NSFW subs - but it would be awesome if it's possible to permanently have it on. For example if I have people looking over my shoulder, I'd rather they not see my reddit username, profile, what I'm browsing, etc. Hope you'll consider it, thank you!

**Comment by laurencedawson** [comment]
No plans to add this.
