### ISSUE TITLE
[BUG] Image getting stuck behind cards in all

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#974]
**Spotten on**
https://www.reddit.com/r/redditsync/comments/ts8u92/

**Describe the bug**
Media stuck and visible b/w post dividers

**Smartphone (please complete the following information):**

Sync version: v22.3.28    
Sync flavor: pro    

View type: Slides    
Push enabled: false    

Device: x1q    
Model: samsung SM-G981U1    
Android: 12

**Additional context**
![axA25dK.jpg](https://user-images.githubusercontent.com/34155181/161143232-20db632d-bd80-4bbd-97c2-52719bc81240.jpg)

**Comment by jeffreymcclain** [comment]
A few other related posts from other users, for reference:

- https://www.reddit.com/r/redditsync/comments/tzv8ia/weird_text_behind_card_when_scrolling_slowly/
- https://www.reddit.com/r/redditsync/comments/u163ov/if_i_quickly_check_out_random_subreddits_after_a/

**Comment by laurencedawson** [comment]
Added a fix for this today. Fingers crossed.

**Comment by laurencedawson** [comment]
OK think I've finally nailed this. It will be in the next available update. Cheers
