### ISSUE TITLE
[BUG] Comment option exists for locked post

### ISSUE THREAD

**Issue by redfellow** [laurencedawson/sync-for-reddit#975]
**Describe the bug**
I'm able to comment on a comment in a locked post. This comment disappears upon submit. 

**Smartphone (please complete the following information):**
 - Device: OP9
 - OS: Android 12
 - Version 22.3.28

**Additional context**
Sometimes you just miss that a post is locked, sync could disable the comment and reply button.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by thereddestdog** [comment]
Hey @laurencedawson  Would this fix also work for trying to reply to any post in a sub you are banned from?

**Comment by laurencedawson** [comment]
The comment should fail to go through at that point no?

**Comment by thereddestdog** [comment]
@laurencedawson  Yeah but it just says Error Submitting. Just a thought

**Comment by laurencedawson** [comment]
Ahh. I'll add a check as a new feature.
