### ISSUE TITLE
[BUG] Children comments become visible by default after loading more comments

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#979]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ttsrwz

**Describe the bug**
I have all comments collapsed by default so I can open only the ones I choose. But after scrolling past the initial page (and loading more) it seems to ignore my preference of having all comments collapsed by default

Example post https://www.reddit.com/r/AskReddit/comments/tt87sl

**To Reproduce**
1. Collapse all comments
2. Scroll down to load more comments
3. Children comments appear

**Expected behavior**
All comments should stay collapsed

**Device information**
```
Sync version: v22.3.28    
Sync flavor: pro    

View type: Slides    
Push enabled: false    

Device: beyond2    
Model: samsung SM-G975F    
Android: 12
```

**Comment by laurencedawson** [comment]
Intended behaviour. "more" loads open expanded.
