### ISSUE TITLE
True Gallery View

### ISSUE THREAD

**Issue by cococoot** [laurencedawson/sync-for-reddit#980]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A gallery view...

**Describe alternatives you've considered**
None

**Additional context**

![Screenshot_20220401-161228_Gallery for reddit.jpg](https://user-images.githubusercontent.com/61015333/161335129-d90ff1d7-a360-4f6d-897d-bb217cad893c.jpg)

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/603
