### ISSUE TITLE
[BUG] Post submission failure/queue not fully working as expected

### ISSUE THREAD

**Issue by ctrlbrk42** [laurencedawson/sync-for-reddit#983]
When a post submission fails, a notification lets us know to "touch to retry".

However, it seems that if it fails again after that retry, it just disappears instead of staying queued or getting re-queued.

I experienced this multiple times right now when Reddit was returning 503 errors sporadically, and I ended up losing my post replies.

In the past, I know it does work as expected when the first retry is accepted by Reddit.

**Device information**

    Sync version: v22.3.28    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: raven    
    Model: Google Pixel 6 Pro    
    Android: 12

**Comment by laurencedawson** [comment]
I think in this case it sounds like it wasn't reported as failing. If the second retry fails (and I've just checked) sync is handling this correctly.
