### ISSUE TITLE
Better use of cache when sharing images/videos

### ISSUE THREAD

**Issue by ctrlbrk42** [laurencedawson/sync-for-reddit#984]
Timeline:
- Watch a funny video (completely)
- Share video via Sync > Share > Image
- Wait for Sync to re-download what I just watched

It should be cached. I don't have any limit established for my cache or file size.

It happens on every video share, so I think we just need an enhancement here to check cache first.

**Device information**

    Sync version: v22.3.28    
    Sync flavor: dev    
    
    View type: Slides    
    Push enabled: false    
    
    Device: raven    
    Model: Google Pixel 6 Pro    
    Android: 12

**Comment by laurencedawson** [comment]
Unfortunately the streaming video cache can't be used by the image downloader used for sharing. Closing sadly.
