### ISSUE TITLE
[BUG] Videos play after pausing and scrolling (with Autoplay enabled)

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#986]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tus9vm/

**To Reproduce**
- pause a video while browsing a sub
- scroll and it starts playing again
- no real pause option, just have to mute.

**Expected behavior**
Manually paused videos shouldn't resume playing on scrolling

**Comment by laurencedawson** [comment]
This has been fixed for the next release.4
