### ISSUE TITLE
[BUG] Cached videos re-download while sharing

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#987]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/tuty5u

**Describe the bug**
Why is it that I can watch an entire video, but when I click 'share' it has to download it again? Shouldn't it be in my cache? Happens every time.

**Smartphone (please complete the following information):**
```
Sync version: v22.3.28    
Sync flavor: dev    

View type: Slides    
Push enabled: false    

Device: raven    
Model: Google Pixel 6 Pro    
Android: 12
```

**Comment by ctrlbrk42** [comment]
That was me 😅 and you'll find it under #984

**Comment by bohrabhijeet** [comment]
> That was me 😅 and you'll find it under #984

Oh, thank you.
