### ISSUE TITLE
Option to show videos and images fully in the full post view

### ISSUE THREAD

**Issue by superluig164** [laurencedawson/sync-for-reddit#989]
When opening up the full post view by tapping on a post, I think it would be great to have the option to show the video or image fully instead of having to tap on the thumbnail.  This compliments my earlier suggestion of next/previous post buttons, since you could see the whole post and everything it has to offer plus the comments all at once without needing to tap anything.

**Comment by geominorai** [comment]
You can do this for images via
[Settings shortcut: Comments > Full height](sync-settings://26-media_preview_full)

But videos still have to be opened separately to play.  It would be convenient if video player can be embedded like in the feed though but still have the option to open fully.

It could be even more interesting if the video can continue playing while reading comments, similar to the YouTube app.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/775

https://github.com/laurencedawson/sync-for-reddit/issues/377
