### ISSUE TITLE
[BUG] Dropdown arrow next to moderator options in the drawer shows that it is still open after opening the page and going back to the homepage

### ISSUE THREAD

**Issue by Hupro** [laurencedawson/sync-for-reddit#993]
**Describe the bug**
When you open the moderator dropdown in the drawer and click on one of the options, and then go back to the main page the dropdown is closed but the arrow shows it as open

**To Reproduce**
1. Open the drawer
2. Click on moderator to open the dropdown
3. Click on one of the moderator dropdowns like modqueue
4. Press the back button to go back to the main page
5. Notice that the moderator dropdown menu is closed but the arrow still shows it as open

**Expected behavior**
When pressing back in step 4 the moderator dropdown should either still be open to match the arrow, or the arrow should show the dropdown as closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/102997944/161627314-c6fa9181-3782-42a8-8509-99e4d64f4044.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: A12.1
 - Version V22.3.28

**Comment by laurencedawson** [comment]
Fixed for the next release.
