### ISSUE TITLE
[BUG] Dead zone for tapping and holding into post options

### ISSUE THREAD

**Issue by atgodfrey** [laurencedawson/sync-for-reddit#994]
When touching a post (to link thru to the comments or media) some of the real estate won't recognize a tap. It is inconsistent, but there appears to be a clear area that is a dead zone. Outlined example below!

Edit: I worded this wrong. The tap to content works fine. It's the tap and hold (to access more post options) where I am experiencing dead zones.

This area won't allow tap and hold to post options:

![Screenshot_20220404-180723](https://user-images.githubusercontent.com/6992658/161661565-4d898172-7c3d-45fe-ae86-e867d813ac1f.png)

Android 11, Pixel 5, latest beta.

**Comment by laurencedawson** [comment]
Fixed for the next release.
