### ISSUE TITLE
[BUG] hitbox for subbreddit link too big

### ISSUE THREAD

**Issue by Vanjaman** [laurencedawson/sync-for-reddit#995]
**Describe the bug**
The hitbox for a subreddit link is a lot larfer than the link looks on the screen. Not sure if it's like that with all subreddit links, or obly this one. 

**To Reproduce**
1. Find subreddit link
2. Click to the right of it
3. ..? 
4. Profit

See attached video. 

**Expected behavior**
I expect the hitbox to be about as large as the link. Especially in this case where the link itself is pretty large and easy to press. 

**Screenshots**

https://user-images.githubusercontent.com/64230895/161646049-314db529-5314-4eb3-b61a-920c557d32a0.mp4

**Smartphone (please complete the following information):**
 - Device: OnePlus 7t pro
 - OS: Android
 - Browser Firefox
  - Version 22

**Additional context**

**Comment by laurencedawson** [comment]
Looked into this and it seems to be the way links are turned into clickable spans in Android.

Looked around and can't find a solution. Going to mark this as #wont-fix. 

Cheers
