### ISSUE TITLE
[BUG] High refresh screens with autoplay enabled sometimes locks to 60 Hz

### ISSUE THREAD

**Issue by Gepstra** [laurencedawson/sync-for-reddit#996]
**Describe the bug**
When having autoplay enabled on a phone with a high refresh rate screen it sometimes sometimes locks the framerate to 60 fps when scrolling past a video that starts to play. 

**To Reproduce**
1. Have autoplay enabled. (It also helps to have the refresh rate shown on screen from Android Developer Options.)
2. Scroll past a video and let it play.
3. See if it looks stuttery/laggy
4. See video below

**Expected behavior**
Either the phone stays locked at 90/120Hz when watching videos or after scrolling past the video the framerate goes back up instantly.

**Screenshots**

https://user-images.githubusercontent.com/32432776/161707553-1666d9d1-d816-4fb6-9965-bdca42ff09c9.mp4

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T 
 - OS: Android 11
 - Browser: n/a
 - Version 22.3.28

**Additional context**
You can't see the 120 fps in the video because it is recorded at 60 fps. You can see the frame counter however.

**Comment by laurencedawson** [comment]
This is a oneplus specific bug. You can get around it by enabling "fixed height video" under experimental in the settings.

**Comment by Gepstra** [comment]
Thanks, do you know what causes it? Maybe I can make a bug report on the OnePlus forums as well, not that they'd fix something but who knows.

**Comment by laurencedawson** [comment]
It looks like they have a whitelist of approved apps that can run at 120hz...

**Comment by laurencedawson** [comment]
Discussion over on /r/android after doing some digging:

https://www.reddit.com/r/Android/comments/twtsua/oneplus_devices_are_restricting_high_refresh_rate/
