### ISSUE TITLE
[BUG] Viewing my account comments crashes app

### ISSUE THREAD

**Issue by kei101895** [laurencedawson/sync-for-reddit#999]
Basically the title, when I try to view my account's comments, none of the comments show up, and if I try to do anything else from there, the app crashes

Scenario (steps to reproduce)

1. (May or may not be related?) Have two accounts on the app. The rest of these steps are performed on the "first" account
2. Open left side menu
3. Tap "Profile" to open dropdown list
4. Tap "Comments"

Result(s)

It moves to the expected screen, however none of my comments show up, and if I try to tap anything else from there, the app crashes.

This issue does NOT occur on my "second" account. I can view the comments there normally, following the same steps above

Device information

Sync version: 19.0.16    
Sync flavor: free    
Removed ads: false    

View type: List    
Player type: ExoPlayer    
Push enabled: false    

Device: sunfish    
Model: Google Pixel 4a    
Android: 12

**Comment by laurencedawson** [comment]
Just pushed an update that fixes this. Thanks
